### ISSUE TITLE
HDR Support

### ISSUE THREAD

**Issue by ggnull35** [rigaya/NVEnc#1]
Hello,

Does NVENC SDK 7.0 with Pascal GPUs support HDR encoding ?

Kind Regards,

**Comment by rigaya** [comment]
I think HDR encoding could be done using 10bit depth encoding plus bt.2020 colormatrix if you have a YUV HDR source.

**Comment by rigaya** [comment]
There are no parameters for generating HDR metadata (such as MaxCLL or MaxFALL) in NVENC SDK 7.0,
therefore it would be difficult to add support for it.
