### ISSUE TITLE
regarding the option --seek

### ISSUE THREAD

**Issue by adrianmak** [rigaya/NVEnc#101]
i have a video where there is an about 2 mins promotion advertisement before the content of the video.
i found a --seek option from online document

here is my command line
nvencc64 --seek 1:52 --cqp 22 --audio-copy input_video.mp4  -o output_video.mp4

However I found the audio of output video is not well. There is some sort of delay.

Will the --audio-copy option will all cut/trim the 1:52 before mux to the output video ?

**Comment by rigaya** [comment]
If you video is 30fps, please try using below (1:52 = 112 sec = 3360 frames).
```
--trim 3360:0
```
The last "0" means it will transcode to the end of the video. Please let me know if you still have audio delay.

**Comment by adrianmak** [comment]
I found that the source video is variable framerate

**Comment by rigaya** [comment]
Handling of vfr videos are improved on [NVEnc 4.30](https://github.com/rigaya/NVEnc/releases/tag/4.30), please try it adding option "--avsync vfr".
