### ISSUE TITLE
NVENC Psycho visual tuning function

### ISSUE THREAD

**Issue by NoLimits2018** [rigaya/NVEnc#102]
Hello Rigaya!

Is psycho visul tuning function exist on NVENC platform?

According to this video, even OBS software implemented this NVENC feature.

Watch this video from here:
https://youtu.be/-fi9o2NyPaY?t=142

Can you implement such option in Rigaya NVENC?

Thank you for your reply!

**Comment by rigaya** [comment]
I don't know much about OBS, but the latest version 22.02 [here](https://github.com/obsproject/obs-studio/releases) doesn't have that "psycho visul tuning" feature. Where can I download the OBS they are talking about in the video?

As far as I know, there is no such feature in current NVENC SDK 8.2, and [NVENC SDK 9.0](https://developer.nvidia.com/nvidia-video-codec-sdk) that should expose feature of Turing is not available now.

**Comment by rigaya** [comment]
"Psycho visual tuning" on OBS was out on OBS 23.0 RC, and is expressed "psycho_aq" on the code, so although I'm not sure of the details, it seems to be something around AQ.

You can use [--aq](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--aq), [--aq-temporal](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--aq-temporal), [--aq-strength](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--aq-strength-int) on NVEncC.

**Comment by NoLimits2018** [comment]
> 
> 
> "Psycho visual tuning" on OBS was out on OBS 23.0 RC, and is expressed "psycho_aq" on the code, so although I'm not sure of the details, it seems to be something around AQ.
> 
> You can use [--aq](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--aq), [--aq-temporal](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--aq-temporal), [--aq-strength](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--aq-strength-int) on NVEncC.

Hi Rigaya!

Just read the news here: 
https://www.videohelp.com/software/Open-Broadcaster-Software/version-history#changelog

"YouTube, Facebook, and more services are still in the works; more to come soon.
Service integration is currently only available on Windows for now, though Linux and Mac support is planned for a later date.
NVENC and Encoding Improvements (Windows)
A new implementation of NVENC has been added which has improved performance, reducing system and resource impact. To enable, go to Settings, Output Tab, and in Encoder select Hardware (NVENC) New. Note that the new implementation is not available on Windows 7 due to limitations in the operating system; the old implementation will be used instead in that case.

Added new features to the new NVENC implementation:

Psycho-visual Tuning: Enables encoder settings that optimize the use of bitrate for increased perceived visual quality, especially in situations with high motion, at the cost of increased GPU utilization. This increases subjective image quality. Qualitative measurements like PSNR may score lower but video may appear better to human viewers.
Look-ahead: Enables dynamic B-frames. If disabled, the encoder will always use the number of B-frames specified in the 'Max B-frames' setting. If enabled, it will increase visual quality by only using"

**Comment by rigaya** [comment]
I'll close this issue as the topic has been answered.
