### ISSUE TITLE
Default B-frames =3 & --bref-mode - not working with HEVC

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#104]
I tried the new HEVC features: B-frames=3 by default and "--bref-mode middle" or "--bref-mode each". But NVEnc 4.31 reported that: B-frames was changed to 0 and B Ref mode is unsupported.

Maybe I just don't understand how this should work?)

PS: By the way, the "--aq-strength" works perfectly smartly with HEVC, I didn't know that!) With --aq-strength=15 the size of the source file increases by about 20-25%, but it's worth it.

![ryjaya](https://user-images.githubusercontent.com/11748220/53256560-42523e00-36d9-11e9-9067-ce8141067873.png)

**Comment by rigaya** [comment]
Unfortunately, using B frames with HEVC requires new Turing Gen GPUs except TU117 chip. I don't know what TU117 exactly means, but it might be used on later GTX1650?

NVEnc will check functionality of the GPU on run-time, and if B frames are not supported (like on Pascal Gen GPUs) then it will disable the feature automatically (as you have mentioned).

**Comment by drSHLEFF** [comment]
Thanks, it seems it's time to upgrade: 9980XE + 2080 Ti 😁

**Comment by rigaya** [comment]
I'll close this issue now. Please reopen if you have any more related issues.
