### ISSUE TITLE
Add ability to specify video tag

### ISSUE THREAD

**Issue by danielpascal** [rigaya/NVEnc#105]
Please add the ability to manually specify the video tag on output, like in ffmpeg, to enhance the compatibility with some devices.

**For example**:
`ffmpeg -tag:v hvc1`

Thanks in advance.

**Comment by rigaya** [comment]
NVEnc 4.32 adds option ([--video-tag](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--video-tag-)) to specify the video tag on output. This is enabled when the internal muxer is enabled, and disabled for raw output.
```
NVEncC64.exe -i input.mp4 -o output.mp4 -c hevc --video-tag hvc1
```

**Comment by danielpascal** [comment]
@rigaya Great! ありがとうございます
