### ISSUE TITLE
SEI_rbsp_stop_one_bit    : Missing with version 4.32

### ISSUE THREAD

**Issue by pwacooijmans** [rigaya/NVEnc#107]
the SEI_rbsp_stop_one_bit is missing on version 4.32 is it possible to add it again please? We had an earlier discussion about this with 4.06 and 4.07 those 2 have the bit present, but 4.05 and before don't. It's an easy fix, so please fix it.

Kind Regards,

Pieter Cooijmans

**Comment by rigaya** [comment]
Actually I haven't changed the code around here, and doesn't seem to be missing according to MediaInfo.

x64\NVEncC64.exe -i Australia_8k_HDR_Down_Under_4k_HDR.webm -o F:\temp\test.265 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) --max-cll 1000,1 -c hevc

![image](https://user-images.githubusercontent.com/815947/53956035-df6f9680-411d-11e9-9671-96acf85e6fd3.png)

**Comment by pwacooijmans** [comment]
I used version 18.12 of mediainfo.dll to check this....and it shows the bit
is missing....so maybe you have an outdated version or my version is
corrupt....no clue.

Op do 7 mrt. 2019 13:14 schreef rigaya <notifications@github.com>:

**Comment by pwacooijmans** [comment]
https://drive.google.com/drive/folders/1tEdXAUgs5zoyy2LNM4N7H02Wh-wraGwl?usp=sharing
here you have a link of the 2 programs I tested it with.

Many thanks for your continued support.

Kind Regards,

Pieter Cooijmans

Op do 7 mrt. 2019 om 13:18 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
https://drive.google.com/drive/folders/1_hE55gIqvMX5a5VuhA0BG4HF-XTjNXqX?usp=sharing
here you see the old test samples with version 4.05 and 4.06 of nvenc 64
bit to show the difference....same issue with 4.32.

Op do 7 mrt. 2019 om 13:25 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
and here you have some newer samples made with 4.07
https://drive.google.com/drive/folders/16I0JHWxabP7suokpuIau6khVd4e7DCzq?usp=sharing
they all work fine and do not show the error of the missing bit.

Op do 7 mrt. 2019 om 13:40 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by rigaya** [comment]
I've checked the change log, and figured out that I've made a fix with this in #93, and that seems to change the output from 4.07. There was a issue that the values were not stored correctly for some values. I've rechecked the code, but the fix made for 4.07 is still active in 4.32, and is adding "0x80" to the end of the SEI unit as we've discussed before.

HEVC raw output of 4.32 should **not** show "SEI_rbsp_stop_one_bit: missing" even for MediaInfo 18.12 and have correct values in the bitstream. The problem might be with the mkv/mp4 output. For mkv/mp4 output, the app is internally passing the same bitstream to libavformat but somehow shows "SEI_rbsp_stop_one_bit: missing" (#75), and I've not yet found out what this means.

**Comment by pwacooijmans** [comment]
Well I can't help you further then, I hope you will find the fix for it
cause it's making ignore your product due to the error and it's a very very
handy tool which saves insane amounts of time for millions of people. I was
just interested in the NVencC64 api 9.0 to check what improvements had been
made. Further more I would really like to see a fix for the --weightp
option with hevc since it gives a warning that it may be unstable on some
systems....so not risking that either.

Many Thanks for your quick responses and good luck.

Kind Regards,

Pieter Cooijmans

Op do 7 mrt. 2019 om 14:41 schreef rigaya <notifications@github.com>:

**Comment by pwacooijmans** [comment]
It seems like you found the bug since the issue no longer is there with
version 1.7.0.0 stable build which is great to see. :)

Thx a lot for all your hard work, really appreciated.


Op do 7 mrt. 2019 om 15:14 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
Issue has been fixed.
