### ISSUE TITLE
What is the aim (should be in or out) for the next stable build of NVEnc?

### ISSUE THREAD

**Issue by pwacooijmans** [rigaya/NVEnc#108]
Dear Rigaya,

Could you enlighten us a bit about what will be in and what will be outside the next upcoming stable release of NVEnc?

Many Thanks in advance,

Kind Regards,

Pieter Cooijmans

**Comment by rigaya** [comment]
I just work on this app mainly on weekends, so there is no such fixed aims here...

Adding support for Turing (and NVENC SDK 9.0) is finished with NVEnc 4.31, which was my biggest concern recently.

Maybe?
- Moving on to CUDA 10.1 for x64, while using current CUDA 8.0 for x86.
- Adding 3rd deinterlacer.

**Comment by rigaya** [comment]
3rd deinterlacer "--vpp-nnedi" has been added on NVEnc 4.34.

**Comment by rigaya** [comment]
I'll close this issue, as this topic has been answered.
