### ISSUE TITLE
CUDA 10.1 - nppc64_101.dll nppi64_101.dll needed

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#110]
--vpp-resize super
failed with error message that nppc64_101.dll nppi64_101.dll not found.

We only have the old ones nppc64_80.dll nppi64_80.dll
Maybe there are more issues because there are  many changes in the new API.

**Comment by fzold** [comment]
NVEncC (x64) 4.33 (r1034) by rigaya, Mar 18 2019 12:45:25 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (17763)
CPU            Intel Core i7-7700HQ @ 2.80GHz [TB: 3.78GHz] (4C/8T)
GPU            #0: GeForce GTX 1050 (640 cores, 1493 MHz)[PCIe3x16][419.35]
NVENC / CUDA   NVENC API 9.0, CUDA 10.1, schedule mode: auto

**Comment by PhoO3nX** [comment]
@rigaya i can confirm in the lastest build 4.33
nppc64_101.dll (nppc64_10.dll (from CUDA library) is asked for all npp x64 filters (lanczos, nn, cbic, npp_linear)

And in <4.32 the library asked is
npp64_80_dll and all npp x64 filters work perfectly

So i must keep the 4.32 for the moment. Thank you so much for your great job

**Comment by rigaya** [comment]
Thanks for your report, the dll check in NVEncC 4.33 was wrong, dll name was actually not nppc64_101.dll, and was nppc64_10.dll, nppif64_10.dll & nppig64.dll. I have fixed this in NVEncC 4.34, and have put an archieve containing these dlls [here](https://drive.google.com/folderview?id=0BzA4dIFteM2dS1ZUT1FjTnF3Q0E&usp=sharing)(npp64_10_dll.zip).

**Comment by PhoO3nX** [comment]
> Thanks for your report, the dll check in NVEncC 4.33 was wrong, dll name was actually not nppc64_101.dll, and was nppc64_10.dll, nppif64_10.dll & nppig64.dll. I have fixed this in NVEncC 4.34, and have put an archieve containing these dlls [here](https://drive.google.com/folderview?id=0BzA4dIFteM2dS1ZUT1FjTnF3Q0E&usp=sharing)(npp64_10_dll.zip).

Great job mate :)

**Comment by fzold** [comment]
Works. Many thanks!
