### ISSUE TITLE
4.34 crashes always no matter what

### ISSUE THREAD

**Issue by techok** [rigaya/NVEnc#111]
Hello, i installed new version as always and when i want to encode it crashes with some error without any reference. I put the new npp dll's where the nvenc files. Should i place the npp anywhere else? 4.33 works fine.

**Comment by fzold** [comment]
Check your NVIDIA drivers.

**Comment by techok** [comment]
> Check your NVIDIA drivers.

I got latest.

**Comment by rigaya** [comment]
Npp dlls should be place at the directory where NVEncC64.exe is.

What option(s) are you using? I've currently found potential bug in vpp-nnedi which might cause crush.

**Comment by techok** [comment]
not much options, currently encoding for hdr in hevc of course, using staxrip...

--codec hevc --output-res 3840x2160 --vbv-bufsize 160000 --vbrhq 65000 --mv-precision q-pel --ref 5 --output-buf 128  --lookahead 32 --max-bitrate 120000 --qp-init 20:23:25 --lookahead 32 --gop-len auto -b 0 --aq --aq-strength 7 

add to this the HDR metadata / mastering display info

The 4.33 works perfect but 4.34 immediately crashes, using all the same.
The --output-res 3840x2160 use spline64 nvidia upscaler

**Comment by rigaya** [comment]
Thanks for letting me know the options, but 4.34 (and 4.33) works fine on my environment.

I rechecked the code diff between 4.33 and 4.34, but is only changing the check of npp libraries, which shouldn't affect your options as spline36 does not depend to npp library.

Could you get some logs when you add "--log-level debug --log log.txt" or does it crash immediately?

**Comment by hydra3333** [comment]
Hello.

> Npp dlls should be placed at the directory where NVEncC64.exe is.
> 
> What option(s) are you using? I've currently found potential bug in vpp-nnedi which might cause crash.

Well, I am getting an abort with Error -1073741819
This commandline
```
"C:\SOFTWARE\NVEncC\NVEncC64.exe" --avhw --input "G:\HDTV\TEST.mp4" --interlace TFF 
--output "G:\HDTV\TEST.deint.aac.nvencc.mp4" --output-thread 1 
--videoformat PAL --cuda-schedule auto 
--codec h264 --preset quality --vbr-quality 18 --lookahead 32 --gop-len 24 --bframes 3 --ref 3
 --aq --aq-temporal --aq-strength 0 --mv-precision q-pel --cabac --level 4.1 
 --vpp-nnedi field=auto,nns=128,quality=slow,prescreen=none,prec=fp32 
 --audio-codec aac --audio-bitrate 384 --audio-samplerate 48000 
 --audio-filter loudnorm=I=-16:TP=0.0:LRA=11:measured_I=-23.37:measured_LRA=1.20:measured_TP=-10.33:measured_thresh=-33.63:offset=-0.25:linear=true:print_format=summary 
 --log-level info
```

results in no output .mp4.
No error message is given, just an exit status of -1073741819

When run within a .bat, it just exits with no text evident. Log attached.
When run within a DOS command window it shows more info, but interestingly no error message.

Suggestions welcome.
[TEST.mp4.log.txt](https://github.com/rigaya/NVEnc/files/3000124/TEST.mp4.log.txt)

**Comment by hydra3333** [comment]
Oh, sorry, just ran it without the nnedi stuff and got the same abort result. 
Will play a tad further unless you have suggestions.

**Comment by rigaya** [comment]
_> edit: ah, removing the loudnorm stuff gets rid of the error :(_
Now fixed with [NVEnc 4.35](https://github.com/rigaya/NVEnc/releases/tag/4.35).

**Comment by techok** [comment]
> Thanks for letting me know the options, but 4.34 (and 4.33) works fine on my environment.
> 
> I rechecked the code diff between 4.33 and 4.34, but is only changing the check of npp libraries, which shouldn't affect your options as spline36 does not depend to npp library.
> 
> Could you get some logs when you add "--log-level debug --log log.txt" or does it crash immediately?

Sorry for the late reply. I had no log as @hydra3333 explained. Just an instant abort message. Will try the 4.35 asap then. Thanks!

**Comment by techok** [comment]
> _> edit: ah, removing the loudnorm stuff gets rid of the error :(_
> Now fixed with [NVEnc 4.35](https://github.com/rigaya/NVEnc/releases/tag/4.35).

It now works with 4.35. 

Is there any particular reason the GTX 2060 can't encode B Frames and only the RTX is able to do it? Would be nice to know if it actually works better or there's no much difference. I would swap for an RTX card if it's worth it.

**Comment by hydra3333** [comment]
> _> edit: ah, removing the loudnorm stuff gets rid of the error :(_
> Now fixed with [NVEnc 4.35](https://github.com/rigaya/NVEnc/releases/tag/4.35).

Thanks !

**Comment by rigaya** [comment]
> Is there any particular reason the GTX 2060 can't encode B Frames and only the RTX is able to do it?

SS below is what is shown on the NVENC SDK 9.0.20. It's not only RTX series that supports HEVC B frames, and Turing Gen GTXs should also support HEVC B frames. Pascal Gen GTXs will not.

Therefore Turing Gen GPUs (RTX2080Ti, RTX2080, RTX2070, RTX2060, GTX1660Ti, GTX1660) supports HEVC B frames. However Pascal Gen GPUs like GTX1080, GTX1070, ... don't.

![image](https://user-images.githubusercontent.com/815947/54923054-c738ad80-4f4c-11e9-9cf9-60d88549efce.png)

**Comment by techok** [comment]
Thanks a lot! Will then get some GTX 1660 for the matter. Asked if quality is worth as this is not really like CPU x265 where there is a lot more of commands not yet implemented here. Maybe adding B Frames to NVEnc is not a huge difference , though will try anyway.

**Comment by rigaya** [comment]
I'll close this issue, as the main subject of this issue has been fixed.
