### ISSUE TITLE
is there a way to deinterlace 1080i (25fps) to 1080p50 (double framerate) ?

### ISSUE THREAD

**Issue by hydra3333** [rigaya/NVEnc#112]
Is there a way to deinterlace 1080i25 (25fps, 50 fields/sec) to 1080p50 (50fps which is double framerate) ?

Had a quick try with nnedi but got 1080p25 output ...

**Comment by rigaya** [comment]
It'll be going to be supported by "--vpp-nnedi field=bob" in the future.

Actually it's already implemented so you can try it, but I have not tested it yet so it might be unstable or buggy.

**Comment by hydra3333** [comment]
OK thanks I will try it.  

Plain bob, though, ye olde worlde non-smart bob ?  Any chance of a 21st century filter or even yadif or something ? :)

https://en.wikipedia.org/wiki/Deinterlacing

> Line doubling takes the lines of each interlaced field (consisting of only even or odd lines) and doubles them, filling the entire frame. This results in the video having a frame rate identical to the field rate, but each frame having half the vertical resolution, or resolution equal to that of each field that the frame was made from. Line doubling prevents combing artifacts but causes a **noticeable reduction in picture quality** since each frame displayed is doubled and really only at the original half field resolution. This is noticeable mostly on stationary objects since they appear to bob up and down. These techniques are **also called bob deinterlacing** and linear deinterlacing for this reason. Line doubling retains horizontal and temporal resolution at the expense of vertical resolution and bobbing artifacts on stationary and slower moving objects. A variant of this method discards one field out of each frame, halving temporal resolution

**Comment by hydra3333** [comment]
:) lets say it is "glacial" :)  Thanks anyway.

**Comment by rigaya** [comment]
I've added --vpp-yadif in NVEnc 4.37.

**Comment by hydra3333** [comment]
I notice that nvenc's yadif seems to have different parameters to ffmpeg'sd yadif and yadif_cuda https://ffmpeg.org/ffmpeg-filters.html#yadif-1  (in meaning and less of them). eg the "mode"seems very different https://github.com/rigaya/NVEnc/commit/83f1822d2d490bec3d9db22f50f2555a68d5e606?short_path=9eb73f7#diff-9eb73f7ccf43aaa4778d43f7e38c4fe5

Would you please be able to clarify ?

**Comment by rigaya** [comment]
Please refer to the table below.

| ffmpeg |  |  | NVEncC |
|:---|:---|:---|:---|
| deint | mode | parity | mode |
| interlaced | send_frame | tff | tff |
| interlaced  | send_frame | bff | bff |
|  interlaced | send_frame  | auto | auto |
|   interlaced   | send_field   | tff | bob_tff | 
|   interlaced  | send_field     | bff | bob_bff | 
|interlaced | send_field    | auto | bob |
|  interlaced | send_frame_nospatial |  | not implemented |
| interlaced  | send_field_nospatial | | not implemented |
| all            |                               | | not implemented |

**Comment by hydra3333** [comment]
Ah, OK, thanks !

So per https://ffmpeg.org/ffmpeg-filters.html#yadif-1
mode: The interlacing mode to adopt. It accepts one of the following values:
0, send_frame, Output one frame for each frame.
1, send_field, Output one frame for each field.

then all of the NCENC "bob" modes means double-framerate deinterlacing using YADIF.

Just checking :) ... I suppose this isn't a CUDA based yadif like YADIF_CUDA https://ffmpeg.org/ffmpeg-filters.html#yadif_005fcuda ... or is it ?

**Comment by rigaya** [comment]
It should be the same algorithm with different implementation.
