### ISSUE TITLE
Feature Request: Ability to "burn-in" subtitles.

### ISSUE THREAD

**Issue by bigdwg71** [rigaya/NVEnc#115]
Some of the movies I am ripping have non-english subtitles and rather than invoking a transcoder (PGS subtitles) when I want to enable non-english subtitles. It would be great to have the ability to feed a PGS subtitle into NVENCC64 and have it encode it directly into the video. FFMPEG has the functionality. Thanks for the consideration.

**Comment by pwacooijmans** [comment]
This feature is something I am looking for as well, since Suptitle project stopped for avisynth there is no real alternative, especially for 4k HDR.

**Comment by rigaya** [comment]
As ffmpeg(libavcodec) has a PGS decoder, I think I can use this to get PGS data decoded into bitmap data, which I can handle. The first challenge will be to figure out how to do the "burn-in" on GPU, then next might be the 4K PGS stuff.

**Comment by rigaya** [comment]
I've added basical implementation for burning in subtitles in NVEnc 4.39. ([--vpp-subburn](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-subburn-param1value1param2value2), only simple burn-in feature)

**Comment by bigdwg71** [comment]
@rigaya I finally tested the --vpp-subburn but it didn't work for me. I'm wondering if my crop has something to do with it? Like could I be cropping off the location of the subtitles?

C:\Users\Chris\Documents\Ripper\NVEncC64.exe --avhw --vbrhq 10284 --codec h265 --output-depth 8 --level 4.1 --profile high --tier high --lookahead 32 --gop-len 24 --bframes 5 --qp-init 1 --vbr-quality 22 --aq --max-bitrate 30000 --key-on-chapter --mv-precision Q-pel --crop 0,140,0,140 --vpp-subburn 3 -i "d:\MakeMKV\Captain America - The Winter Soldier.mkv" -o "d:\MakeMKV\Captain America - The Winter Soldier.h265"

NVEncC (x64) 4.40 (r1097) by rigaya, May 21 2019 13:23:13 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (17763)
CPU            Intel Core i7-9700K @ 3.60GHz [TB: 5.00GHz] (8C/8T)
GPU            #0: GeForce RTX 2070 (2304 cores, 1830 MHz)[PCIe3x16][430.64]
NVENC / CUDA   NVENC API 9.0, CUDA 10.2, schedule mode: auto
Input Buffers  CUDA, 46 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
Vpp Filters    crop: 0,140,0,140/cspconv(nv12 -> yv12)
               subburn: track #3
               cspconv(yv12 -> nv12)
Output Info    H.265/HEVC main @ Level unknown
               1920x800p 1:1 23.976fps (24000/1001fps)
Encoder Preset default
Rate Control   VBRHQ
Bitrate        10284 kbps (Max: 30000 kbps)
Target Quality 22.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     24 frames
B frames       5 frames [ref mode: disabled]
Ref frames     3 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:Q-pel

**Comment by rigaya** [comment]
Current implementation does not take crop in consideration, so that might be the cause.

I'll add offset by crop in the next release.

**Comment by bigdwg71** [comment]
@rigaya Thank again!

After I posted I did test without cropping and still didn't see the subtitles where/when I expected them. Although, admittedly, I didn't scan the whole movie to see if they just ended up in the wrong timestamps... I can look more closely tonight.

**Comment by rigaya** [comment]
Now [NVEnc 4.41](https://github.com/rigaya/NVEnc/releases/tag/4.41) will consider crop value and try to avoid the subtitle getting out of range of the frame, please let me know if it works or issue continues (in that case, I might need a sample...)

I've currently checked this feature for PGS(in mkv)/SUP(external)/ASS(external).

**Comment by bigdwg71** [comment]
@rigaya Had a chance to test 4.41 today but the same result, no subtitles at the appropriate time:

NVEncC64.exe --avhw --vbrhq 10284 --codec h265 --output-depth 8 --level 4.1 --profile high --tier high --lookahead 32 --gop-len 24 --bframes 5 --qp-init 1 --vbr-quality 21 --aq --max-bitrate 30000 --key-on-chapter --mv-precision Q-pel --crop 0,140,0,140 --vpp-subburn track=3 -i "d:\MakeMKV\Captain America - The Winter Soldier.mkv" -o "d:\MakeMKV\Captain America - The Winter Soldier.h265"

Starting transcode...

NVEncC (x64) 4.41 (r1112) by rigaya, May 25 2019 02:27:30 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (17763)
CPU            Intel Core i7-9700K @ 3.60GHz [TB: 5.00GHz] (8C/8T)
GPU            #0: GeForce RTX 2070 (2304 cores, 1830 MHz)[PCIe3x16][430.64]
NVENC / CUDA   NVENC API 9.0, CUDA 10.2, schedule mode: auto
Input Buffers  CUDA, 46 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
Vpp Filters    crop: 0,140,0,140/cspconv(nv12 -> yv12)
               subburn: track #3
               cspconv(yv12 -> nv12)
Output Info    H.265/HEVC main @ Level unknown
               1920x800p 1:1 23.976fps (24000/1001fps)
Encoder Preset default
Rate Control   VBRHQ
Bitrate        10284 kbps (Max: 30000 kbps)
Target Quality 21.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     24 frames
B frames       5 frames [ref mode: disabled]
Ref frames     3 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:Q-pel


encoded 195506 frames, 377.06 fps, 7533.49 kbps, 7323.00 MB
encode time 0:08:38, CPU: 6.5%, GPU: 6.8%, VE: 96.9%, GPUClock: 1948MHz, VEClock: 1800MHz
frame type IDR   8686
frame type I     8686,  total size   976.88 MB
frame type P    73918,  total size  4320.06 MB
frame type B   112902,  total size  2026.06 MB
Transcode finished.

I scanned through the movie best i could, but I didn't see any, so I don't think they are there even at the incorrect time. Is there a log or something I can flag to send to you for this?

**Comment by rigaya** [comment]
I've been testing some another samples but subtitles are in the correct place.

1. Would you please show what the MediaInfo reports about your input file?

2. Would you mind trying more simple options like below, it's difficult to say what is wrong there with all those options, it's better to check with options close to default.

NVEncC64.exe -i "d:\MakeMKV\Captain America - The Winter Soldier.mkv" -o "d:\MakeMKV\Captain America - The Winter Soldier - test.mkv" --vpp-subburn 1

**Comment by bigdwg71** [comment]
Thanks, @rigaya!

Below is the MediaInfo output of the source file. It is a MKV generated using MakeMKV from the blu-ray of the movie, so its as original as I can make it... "Text #3" is the foreign language subtitle I am trying to burn-in.

I will test the limited option encode you mentioned above and get back to you. Thanks again.


MediaInfo Output:

General
Unique ID                                : 98870692628380773645592749102327571400 (0x4A61CD8162EE204CB3F412BE193EA3C8)
Complete name                            : D:\MakeMKV\Captain America - The Winter Soldier.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 33.2 GiB
Duration                                 : 2 h 15 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 35.0 Mb/s
Movie name                               : MARVEL'S CAPTAIN AMERICA: THE WINTER SOLDIER - BLU-RAY
Encoded date                             : UTC 2019-05-13 16:50:18
Writing application                      : MakeMKV v1.14.3 win(x64-release)
Writing library                          : libmakemkv v1.14.3 (1.3.5/1.4.7) win(x64-release)
Cover                                    : Yes
Attachments                              : cover.jpg

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 2 h 15 min
Bit rate mode                            : Variable
Bit rate                                 : 28.6 Mb/s
Maximum bit rate                         : 32.7 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.575
Stream size                              : 27.1 GiB (82%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 2 h 15 min
Bit rate mode                            : Variable
Bit rate                                 : 4 767 kb/s
Channel(s)                               : 8 channels
Channel layout                           : C L R LFE Lb Rb Lss Rss
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 4.52 GiB (14%)
Title                                    : Surround 7.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Audio #2
ID                                       : 3
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 2 h 15 min
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 1.43 GiB (4%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #1
ID                                       : 4
ID in the original source medium         : 4608 (0x1200)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 8 min
Bit rate                                 : 34.4 kb/s
Count of elements                        : 3300
Stream size                              : 31.7 MiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #2
ID                                       : 6
ID in the original source medium         : 4611 (0x1203)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 15 min
Bit rate                                 : 81.0 kb/s
Count of elements                        : 5439
Stream size                              : 78.6 MiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #3
ID                                       : 8
ID in the original source medium         : 4614 (0x1206)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 1 h 12 min
Bit rate                                 : 628 b/s
Count of elements                        : 56
Stream size                              : 333 KiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Menu
00:00:00.000                             : en:Chapter 01
00:03:28.666                             : en:Chapter 02
00:13:31.727                             : en:Chapter 03
00:17:57.868                             : en:Chapter 04
00:22:25.302                             : en:Chapter 05
00:33:20.415                             : en:Chapter 06
00:41:27.276                             : en:Chapter 07
00:51:37.302                             : en:Chapter 08
00:58:23.958                             : en:Chapter 09
01:07:40.347                             : en:Chapter 10
01:16:22.202                             : en:Chapter 11
01:24:43.078                             : en:Chapter 12
01:32:17.698                             : en:Chapter 13
01:37:06.612                             : en:Chapter 14
01:49:13.088                             : en:Chapter 15
01:55:03.730                             : en:Chapter 16
02:01:11.055                             : en:Chapter 17
02:06:22.241                             : en:Chapter 18

**Comment by bigdwg71** [comment]
@rigaya, just tested the simple command:

NVEncC64.exe -i "d:\MakeMKV\Captain America - The Winter Soldier.mkv" -o "e:\Captain America - The Winter Soldier - test.mkv" --vpp-subburn 3

Still don't see subtitles where i would expect them. I also tried to burn in track 1 which is a complete subtitle for the entire movie, but i don't see them in the resulting file either. So I guess it must be something in the source PGS format?

I can try and strip out this PGS to send to you if you think it will help.

**Comment by rigaya** [comment]
@bigdwg71, thank you very much for the information of the input file and the tests. Your input file format seems to be very similar to the one I've tested, so I'm not being able to come up of the reason why it is not burned.

Stripped out PGS shall be helpful to figure out what is wrong with my implementation.
```
ffmpeg -i input.mkv -map 0:3 -c:s copy "03.sup"
```

**Comment by bigdwg71** [comment]
@rigaya here is the 3rd subtitle track, which is the 0:5 from ffmpeg...
[05.zip](https://github.com/rigaya/NVEnc/files/3238406/05.zip)

**Comment by rigaya** [comment]
Thanks you, I was able to reproduce the issue. I'll check what is wrong with my implementation.

**Comment by rigaya** [comment]
I have tried fixing the issue in [NVEnc 4.42](https://github.com/rigaya/NVEnc/releases/tag/4.42), would you please try again?

It seems to be the timestamp issue, the timestamp seems not to start from 0.  In [NVEnc 4.42](https://github.com/rigaya/NVEnc/releases/tag/4.42), I have added code to get the timestamp of the first video frame and adjust the timestamp of the subtitle.

As it requires information from the video, it now only works with --vpp-subburn **track=n** mode. For example...

NVEncC64.exe -i "d:\MakeMKV\Captain America - The Winter Soldier.mkv" -o "e:\Captain America - The Winter Soldier - test.mkv" --vpp-subburn track=3

**Comment by bigdwg71** [comment]
@rigaya I was so excited to try this, hence I tried it right away, unfortunately, I see the same issue. No subtitles... I tried the simple encode command and used the full subtitles track to ensure I wouldn't miss it, but I do not see them anywhere.

NVEncC64.exe -i "d:\MakeMKV\HD\Captain America - The Winter Soldier.mkv" -o e:\cap.mkv --vpp-subburn track=1
NVEncC (x64) 4.42 (r1126) by rigaya, Jun  5 2019 15:01:47 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (17763)
CPU            Intel Core i7-9700K @ 3.60GHz [TB: 5.00GHz] (8C/8T)
GPU            #0: GeForce RTX 2070 (2304 cores, 1830 MHz)[PCIe3x16][430.86]
NVENC / CUDA   NVENC API 9.0, CUDA 10.2, schedule mode: auto
Input Buffers  CUDA, 16 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
Vpp Filters    cspconv(nv12 -> yv12)
               subburn: track #1
               cspconv(yv12 -> nv12)
Output Info    H.264/AVC high @ Level auto
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: h264 => matroska
Encoder Preset default
Rate Control   CQP  I:20  P:23  B:25
Lookahead      off
GOP length     240 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, LTR: off
AQ             off
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto


encoded 195505 frames, 484.21 fps, 2920.73 kbps, 2839.11 MB
encode time 0:06:43, CPU: 4.0%, GPU: 8.2%, VE: 77.0%, GPUClock: 1917MHz, VEClock: 1782MHz
frame type IDR    815
frame type I      815,  avgQP  20.00,  total size    52.44 MB
frame type P    48876,  avgQP  23.00,  total size  1051.86 MB
frame type B   145814,  avgQP  25.00,  total size  1734.81 MB

**Comment by rigaya** [comment]
Hmm, I've been testing your sup file, but it is burnt in...

NVEncC64.exe -i "sample input" -o test.mkv --vpp-subburn 05.sup

The first sub is at around 424 sec and it's like below,...
![image](https://user-images.githubusercontent.com/815947/58995352-da120d00-882e-11e9-9945-88bbfb5a4d64.png)

I can see others like... (around 446sec)
![image](https://user-images.githubusercontent.com/815947/58995465-47be3900-882f-11e9-8904-50d013e4f473.png)

**Comment by bigdwg71** [comment]
@rigaya , ok, so you gave me the idea to use the .sup file I created for you earlier and that WORKED! So inputting from a sup file seems to work, but defining the subtitle track from the original does not. Does the sup file use a different formatting than you might be pulling directly from the source mkv file? let me know if there is any data you need from me.

**Comment by rigaya** [comment]
Thanks for trying with the sup file. I've tried another fix, would you try the attached test build?
[NVEncC64_test_build.zip](https://github.com/rigaya/NVEnc/files/3269625/NVEncC64_test_build.zip)

**Comment by bigdwg71** [comment]
@rigaya, thanks for this. I'm traveling this week, but will be able to test this weekend and let you know. I really appreciate all your effort with this.

**Comment by pwacooijmans** [comment]
So do I from both of you :)

Op di 11 jun. 2019 04:55 schreef Chris Ward <notifications@github.com>:

**Comment by bigdwg71** [comment]
@rigaya This worked! So it looks like you have a good fix there. Sorry it took so long to test, but glad it's working! Thanks again.

**Comment by rigaya** [comment]
@bigdwg71 I'm glad to hear that it worked! Thanks for the information and the testings.

I'll add this modification in the next release.

**Comment by bigdwg71** [comment]
@rigaya , so sorry to ping you back on this, but I found an issue with the burn-in feature when using it with 4k. It looks like some sort of scaling issue with the resolution. The placement is wrong and size is much smaller than expected. I am providing a screenshot of the issue. This image contains the burned-in subtitle and the PGS subtitle overlaid to show you both the sizing and positioning issue. Thanks again!

![sub-size-placement](https://user-images.githubusercontent.com/26982284/60027993-8a27a880-966c-11e9-862e-30b73b30a8aa.jpg)

**Comment by fmohican** [comment]
@rigaya it's possible to add burnt-in for ASS/SSA subtitles?

**Comment by rigaya** [comment]
@bigdwg71 I'm wondering why this is caused and how it could be resolved, as bpp-subburn burns into the position and the size which the PGS decoder has suggested...

@fmohican Yes, ASS/SSA subtitles could be burnt-in by vpp-subburn.

**Comment by rigaya** [comment]
@bigdwg71 Although I haven't tested with 4K sample, I've added scaling feature to [--vpp-subburn](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-subburn-param1value1param2value2) in [NVEnc 4.43](https://github.com/rigaya/NVEnc/releases/tag/4.43), please have a try.
--vpp-subburn track=1,scale=2.0

**Comment by pwacooijmans** [comment]
What are the correct inputs for --vpp-subburn shaping=""?
Since I can't seem to find the correct settings for them.

**Comment by rigaya** [comment]
Is is "simple" or "complex".

Please note that details of the options are written on [NVEncC_Options.en.md](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-subburn-param1value1param2value2), rather than --help which only lists options.

**Comment by bigdwg71** [comment]
Hi @rigaya, Sorry for the delay on my end. I was out of town.

I gave it a shot, and this looks much better! But may still need a couple tweaks. But thank you for sticking with me! :-)

As you can see from the screenshot, the subtitles are almost in the right place and maybe just a little bit stretched vertically. If I had to guess, this is due to the crop that I applied to the encode. Perhaps the new scaling isn't accounting for crop?

Also, there appears to be a strange vertical green that I called out in the screenshot. Maybe a related issue?

![image](https://user-images.githubusercontent.com/26982284/61560846-725cfd80-aa3b-11e9-8299-84a745041781.png)

**Comment by bigdwg71** [comment]
And actually after giving it a closer look, I think the PGS subtitles look squished and your burned in ones, look good. I suspect this has to do with the video being cropped and the PGS subtitles just copied over from source to this cropped version.

For comparison, I found the same scene in the original MKV and noticed that neither has the proper subtitle placement:

![image](https://user-images.githubusercontent.com/26982284/61561520-362a9c80-aa3d-11e9-9673-4d670dc7b56f.png)

So, your text looks good, except for the green line, its just not in the proper position. Not sure if this helps or not.

**Comment by rigaya** [comment]
I've tried fixes to the green line and the position issue in [NVEnc 4.44](https://github.com/rigaya/NVEnc/releases/tag/4.44).

About the position, it might not be as same as the overlay, but should be better now.

**Comment by bigdwg71** [comment]
@rigaya Finally got some time to test these improvements. The position is definitely better now, so that's great! 

Sadly, I still see the green lines on the top and side of burnt in subtitles:

![subtitle-green-side](https://user-images.githubusercontent.com/26982284/63212948-2e602580-c0d9-11e9-99ba-950b10596210.jpg)
![subtitle-green-top](https://user-images.githubusercontent.com/26982284/63212949-2e602580-c0d9-11e9-85cd-7fde2ddb772d.jpg)

I really do appreciate all your efforts on this.

**Comment by rigaya** [comment]
May I have the sup file and the output resolution?

I cannot reproduce the green lines you have.

**Comment by bigdwg71** [comment]
Sure thing!

Original Resolution: 3840x2160
Detected Crop: 0,278,0,278
Cropped Resolution: 3840x1604


[04.zip](https://github.com/rigaya/NVEnc/files/3512163/04.zip)

**Comment by rigaya** [comment]
Thank you, I have reproduced the issue, and will fix it in the next release.

**Comment by bigdwg71** [comment]
You are truly the best! Thank you again!

**Comment by rigaya** [comment]
Please try for [NVEnc 4.45](https://github.com/rigaya/NVEnc/releases/tag/4.45), I've fixed the initialization problem causing the green line.

**Comment by bigdwg71** [comment]
@rigaya Looks good! No more green lines, placement is great as well! Thank you, again for all your efforts! I didn't intend for this request to be so large so thank you very much for seeing it through. I really appreciate it!

**Comment by rigaya** [comment]
@bigdwg71 Thank you too, for all your testings and providing the samples.
