### ISSUE TITLE
colorspace_conv: failed to build program source.

### ISSUE THREAD

**Issue by aliofwind** [rigaya/NVEnc#118]
D:\video>nvencc64 -i FIFA.World.Cup.2018.Final.France.Vs.Croatia.2160p.WEBRip.x265.10bit.HDR.mkv -o test.mp4 --vpp-colorspace hdr2sdr=ture,source_peak=1000.0,ldr_nits=100.0 -u quality --vbrhq 0 --vbr-quality 25 -b 4 --ref 4 --trim 0:4000 --output-res 1920x1080
colorspace_conv: failed to build program source.

**Comment by djrooli** [comment]
Same error message for me too.
Also --vpp-colorspace is missing from the options list: NVEncC64.exe --help >help.txt

**Comment by rigaya** [comment]
The problem seems to be that the feature requires "nvrtc-builtins64_101.dll" which I haven't included on NVEnc 4.37. I will include this dll in [NVEnc 4.38](https://github.com/rigaya/NVEnc/releases/tag/4.38).

**Comment by rigaya** [comment]
I'll close this issue, as it should be fixed with NVEnc 4.38. Please reopen if you have any related issues.
