### ISSUE TITLE
Feature request: HDR10+ metadata adding

### ISSUE THREAD

**Issue by hyllm** [rigaya/NVEnc#119]
Is it possible to use and add HDR10+ dynamic metadata from JSON file (same like for x265)? Thanks.

**Comment by Selur** [comment]
+ may be even additionally add the function of 'hdr10plus_parser' and thus be able to extract and add the meta data (hdr10plus_parser can be used to extract the meta data)

**Comment by rigaya** [comment]
I've added new feature to add HDR10+ dynamic metadata from JSON file ([--dhdr10-info](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--dhdr10-info-string-hevc-only)), and will add bitstream generated by libhdr10plus.

I'm not yet sure if the implementation is fine, as I don't have HDR10+ json file for actual videos, and just have tested with a small sample [here](https://bitbucket.org/multicoreware/x265/downloads/). The output could be parsed by [hdr10plus_parser](https://github.com/quietvoid/hdr10plus_parser), but when we use B frames, the sequence of the metadata gets changed, as hdr10plus_parser seems to output in decoded order, and not presented order.

**Comment by ValZapod** [comment]
@rigaya 
I have a question: first if you can ENCODE hdr10+ with nvenc, does it mean that you can magically decode and show it with nvdec?
Second: do you understand that ffmpeg as for now could not do such thing? Neither encode not decode hdr10+. Are you going to integrate your work in ffmpeg? That way many people will use it, no? It will be very very cool)))

By the way, there are already blu-ray disks with hdr10+ (SMPTE ST 2094 App 4, Version 1, HDR10+ Profile A compatible). I will post torrent hashes for them, so you can test it))
469555CD21C263735EE87FA885507AE4584C217C // blu-ray to mkv
F7F7381099F6F8FF4803D0CA48AE8A41924DD8AC // blu-ray in iso
76068BB997D80D9DBC27D58FC80305C9A902E013 // bly-ray in iso

**Comment by Selur** [comment]
> does it mean that you can magically decode and show it with nvdec?
No nvdec doesn't read the dynamic data

> do you understand that ffmpeg as for now could not do such thing? 
code for adding hdr10+ data can be found in the x265 source code, see:
https://bitbucket.org/multicoreware/x265/commits/all?search=hdr10%2B

**Comment by ValZapod** [comment]
@Selur 
That one patch was superseeded, use that one https://patchwork.ffmpeg.org/patch/11773/
Does that patch will be hw accelerated at all? Like for example hwaccel by parts while metadata is constant?
I suppose that should be possible... Or you can use Cuda if ffmpeg were to make it work.

**Comment by Selur** [comment]
> Does that patch will be hw accelerated at all? 
don't see any code there at refers to nvdec, so I doubt there will be hardware decoding

**Comment by ValZapod** [comment]
@Selur 
I don't think the the patch will have any references to nvenc (or any hw accel.). Usually it is done on another level, no?

**Comment by Selur** [comment]
not totally sure, whether libnvdec requires the raw stream with the meta data in it or not.
-> we will see

**Comment by ValZapod** [comment]
@Selur
BTW, I also found Dolby demo disk (vision+atmos, march 2018) yesterday (torrent hash 1F89889E0642497F74B0C54C98E079E4A8303C65).
Maybe you know when Dolby Vision with ICtCp color space will be supported? After all ICtCp is already present in ffmpeg.

**Comment by Selur** [comment]
No clue, I doubt that Dolby Vision related stuff will come to ffmpeg anytime soon since all the stuff about it is closed source and afaik anyone who had a look at some of the code had to sign NDAs,...

**Comment by hydra3333** [comment]
I'm not sure how to use this option, cold someone please post an example sequence of preliminary commands/options as well as nvencc usage ?
thanks

**Comment by hydra3333** [comment]
Also, just wondering, if I have a HDR source, is HDR metadata supposed to be auto-passthrough ? It doesn't seem as if it is eg colourspace etc.

**Comment by hyllm** [comment]
when trying to use hdr10+ metadata i get:

---------------- Error Video encoding using NVEnc 4.55 ----------------

Video encoding using NVEnc 4.55 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: The instruction at 0xp referenced memory at 0xp. The memory could not be s.

**Comment by ValZapod** [comment]
@hyllm Not enough information, obviously, give files and command line...

**Comment by hyllm** [comment]
sorry for that.. forgot to attach. :) i have samples ready at home.. wil post later? what hosting you prefer for it?

**Comment by ValZapod** [comment]
So, some updates, IPTPQc2 of Dolby Vision (that is what I called ICtCp) may be supported soon (is working in VLC placebo, not perfect yet). https://github.com/mpv-player/mpv/issues/7326 Also may find decoding double layer. Also google promised to gave HDR10+ patches... Finally...

**Comment by rigaya** [comment]
Now that --dhdr10-info copy can copy hdr10plus metadata, I’ll have this issue closed.
