### ISSUE TITLE
Insufficient NVIDIA driver version, Required 378.66, Installed 0.0

### ISSUE THREAD

**Issue by stax76** [rigaya/NVEnc#12]
Thanks for the update. Something isn't yet working correctly, I'm getting following error with 3.15:

> Insufficient NVIDIA driver version, Required 378.66, Installed 0.0
> Failed to initialize CUDA.

After that I updated my driver to:

384.94-desktop-win10-64bit-international-whql

The problem persists, 3.14 is fine.

**Comment by rigaya** [comment]
Thank you, x64 version didn't work as you have said.
Now fixed with NVEnc 3.16.

**Comment by stax76** [comment]
Thanks for the quick solution. :-)
