### ISSUE TITLE
ISSUE: --vpp-colorspace still has issues

### ISSUE THREAD

**Issue by djrooli** [rigaya/NVEnc#120]
Dear Rigaya! Thanks for the quick fix. 

I have tried to use the HDR2SDR conversion and I still have issues with it.
As you adviced I used this switch: --vpp-colorspace matrix=smpte240m:bt709 the smpte240m matrix is still giving the error "failed to build program source". - using the sample file below.

Also I have tried this method: --vpp-colorspace hdr2sdr=true,source_peak=1000.0,ldr_nits=100.0
with a sample video: 
HDR format                               : SMPTE ST 2094 App 4, Version 1, HDR10+ Profile A compatible
The result was transparent to the original video (washed out colors) as I have SDR screen.

I think it is the matrix, this matrix is missing from nvencc.
I will give a try with bt2020, but first I have to get a sample from somewhere.

Update: with bt2020 It works perfectly with this:  --vpp-colorspace hdr2sdr=true,source_peak=1000.0,ldr_nits=100.0

**Comment by djrooli** [comment]
Thank you for your answer, no rush! I do not have videos with smpte240m matrix, I found this bug accidentally.

**Comment by rigaya** [comment]
Missing matrix for smpte240m has been added in NVEnc 4.39.
