### ISSUE TITLE
Is it a cropping issue, or just me?

### ISSUE THREAD

**Issue by djrooli** [rigaya/NVEnc#121]
Hello rigaya!
I experienced another thing I assume is not a normal behavior in version 4.38.

<details> 
  <summary>I have SW-The Phantom menace remux. </summary>
   Video
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Format settings, GOP                     : M=1, N=12
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 2 h 16 min
Bit rate mode                            : Variable
Bit rate                                 : 30.2 Mb/s
Maximum bit rate                         : 35.6 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.608
Stream size                              : 28.7 GiB (85%)
Default                                  : No
Forced                                   : No 
</details>

<details> 
  <summary>I used AVSP to check the crop calues.</summary>
   ![AVSP](https://user-images.githubusercontent.com/50361400/57507514-546a7280-72ff-11e9-8394-e99f0559fcaf.PNG) 
</details>

<details> 
  <summary>So I used these values: --crop 0,130,0,130 and I got this result.</summary>
   ![h265](https://user-images.githubusercontent.com/50361400/57507660-b034fb80-72ff-11e9-98fe-1c13b3b59901.PNG)
</details>

<details> 
  <summary>So I've changed the values to: --crop 0,130,0,128 and I got this result.</summary>
  ![h265_2](https://user-images.githubusercontent.com/50361400/57507733-e6727b00-72ff-11e9-8c79-7df999ba4893.PNG)
</details>

<details> 
  <summary>So I've changed the values again to: --crop 0,128,0,128 and I got this result.</summary>
   ![h265_3](https://user-images.githubusercontent.com/50361400/57508096-e626af80-7300-11e9-8f4a-73704904185d.PNG)
</details>

<details> 
  <summary>So I've changed the values again to: --crop 0,132,0,132 and I got this result.</summary>
   ![h265_4](https://user-images.githubusercontent.com/50361400/57508380-a7ddc000-7301-11e9-88e8-00fd92716890.PNG)
</details>

As you can see on the 1st picture (AVSP) with values 130,130 should be the full picture image and one black line on the bottom and on the top as well, but on the second picture it's not like that.

On the last picture the value 132,132 cropped the picture and took 1 line each from the top and bottom. I prefer not to crop any lines from the picture, but I've made several tests using 132,130,128 values and it seems to me that, because the picture has odd vertical pixel value,
the encoder somehow doesn't want to put it in the middle.

I'm not an expert, so if I wrote stupid things then I'm sorry wasting your time.

ps. I'll answer your email soon.

**Comment by rigaya** [comment]
It seems like there is a issue when you use --avhw and the crop value cannot be divided by 4.

I'll try solving this in the next release.

**Comment by rigaya** [comment]
I've tried fixing this in NVEnc 4.39, by changing the implementation of cropping from avcuvid to CUDA when using --avhw and --crop together.

**Comment by djrooli** [comment]
It works perfectly now. Thank you very much! ;)
