### ISSUE TITLE
-vpp tweak issue in 4.38

### ISSUE THREAD

**Issue by PhoO3nX** [rigaya/NVEnc#122]
Apparently with the new change in 4.38, now when i encode a video with vpp tweak filter

ex : 
NVEncC64.exe --lossless --codec h265 --preset quality --profile main10 --output-depth 10 --vpp-resize lanczos --output-res 1440x1080 --gop-len 0 --vpp-pmd apply_count=9,strength=50,threshold=50 --vpp-tweak saturation=0.98,contrast=0.99,gamma=0.99 -i C:\NVEnc\wm01.mkv -o C:\NVEnc\lol_temp\wm01_lossless_h265.mkv

Video out is green or with a unique RGB color. 

If i use an older version like 4.36 en 4.37 (even with lanczos4), all is fine, video out is normal with my applied parameters. I have tried without others filters, this issue is only on the 4.38 version.

**Comment by rigaya** [comment]
Currently I'm not being able to reproduce the error. It might depend on the input, as the filter path changes. Would you mind providing the log when you get the problem (green output)?

**Comment by rigaya** [comment]
I'm not sure yet, but it might be related to --vpp-resize issue, and if it is the case, it might be fixed in [NVEnc 4.41](https://github.com/rigaya/NVEnc/releases/tag/4.41).

**Comment by PhoO3nX** [comment]
@Rigaya sorry for the delay, yes in the 4.42 release i do not have issue with --vpp-tweak anymore ;)

Thank you, closed :D
