### ISSUE TITLE
Feature request: 12bit with 4:4:4 chroma support

### ISSUE THREAD

**Issue by Peter82kr** [rigaya/NVEnc#123]
Please add support for 12bit 4:4:4 chroma encoding

**Comment by rigaya** [comment]
Do you have trouble with it?

Should be already supported in NVEnc 4.37.

**Comment by Peter82kr** [comment]
I dont have problem.
Here is answer: https://forum.selur.net/showthread.php?tid=1002

**Comment by Selur** [comment]
NVEncC (x64) 4.29 (r977) with --check-features does mention 10bit and 4:4:4, but not 12bit
Readme.md doesn't mention  12bit support,...
=> please add an indication for 12bit to '--check-features'

**Comment by Selur** [comment]
sorry meant NVEncC (x64) 4.39 (r1094), it also shows:
--output-depth <int>         set output bit depth ( 8(default), 10 )
no mention of 12bit anywhere,..

**Comment by rigaya** [comment]
I think 12bit support is for decode only, and not about encoding, as there is nothing mentioned about it in the NVENC SDK docs.

I will write about 12bit decoding in the next release.

**Comment by rigaya** [comment]
12bit YUV444 decode is supported from NVEnc 4.37, but **encoding** is not supported, as it's not supported by the NVENC SDK 9.0 ([it only mentions about 10bit](https://github.com/rigaya/NVEnc/blob/master/NVEncSDK/Common/inc/nvEncodeAPI.h#L992)). Sorry for confusing you in the first comment of mine.
