### ISSUE TITLE
Feature Request: --chapter (support for matroska xml format)

### ISSUE THREAD

**Issue by djrooli** [rigaya/NVEnc#124]
Hello Rigaya, first of all thank you very much for the new version!

As BD m2ts doesn't have chapter information (as long as I know), I was using Chapter Grabber 5.4
to grab chapters from the BD folder (playlist). Unfortunately It doesn't support Nero or Apple chapter formats at all.

I have tried chapter editor from videohelp, but that mainly supports matroska xml chapter format,
it has database too to download/upload chapters.

(Chapter Grabber has database too, but I was unable to connect for a long time)

So if you will have time to add matroska chapter format, that would be handy sometimes so no need to mux the chapters in subsequently. (or any of Chapter Grabber supported format, if it's easier)

This feature is not essential, so only if you will have free time.

Thank you in advance.

**Comment by rigaya** [comment]
I've added support for chapter in matroska format in [NVEnc 4.41](https://github.com/rigaya/NVEnc/releases/tag/4.41). I've checked the parsing with [the sample file](https://github.com/nmaier/mkvtoolnix/blob/master/examples/example-chapters-1.xml), it seems to work fine.

**Comment by djrooli** [comment]
Thank you very much, rigaya!
ありがとうございました
