### ISSUE TITLE
Is that a vpp-nnedi precision issue or not?

### ISSUE THREAD

**Issue by DJATOM** [rigaya/NVEnc#125]
I decided to compare fp16 vs. fp32 `--vpp-nnedi field=top,nns=256,nsize=8x6,prescreen=none,weightfile="C:\Program Files (x86)\VapourSynth\plugins64\nnedi3_weights.bin",prec=fp16 (fp32)` and noticed that results are not the same. Is that due to less precision or something might be wrong with the code? I'm not CUDA programming expert to find it on my own.

Comparison (both encodes were lossless): https://slowpics.org/comparison/a60f6261-ea83-41f7-b783-13f0f15191b5

**Comment by rigaya** [comment]
It's natural for you to get the different result between fp16 and fp32, as it's precision and implementation is not the same.

**Comment by DJATOM** [comment]
Okay then, so for the best results I should stick with fp32.
