### ISSUE TITLE
Wrog info about AQ strenth and some important new options.

### ISSUE THREAD

**Issue by Cumberiron** [rigaya/NVEnc#126]
Hello Rigaya!

The new SDK 9 Turing updates : https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9331-nvidia-gpu-video-technologies-overview-applications-and-optimization-techniques.pdf

Rigaya can you adjust the info of NVENCC , because it falsely claims that AQ strength  is only a H264 feautre, despite it work very well on NVENC HEVC (I don't know that it is a new feature in SDK 9 or a new feature of Turing card, but as I said, I workd well in NVENCC.

Proof:
This is the original sample video: https://sendgb.com/IiPWx675tUC

Here are some comparison pictures in the zip file 8Mbyte.
https://sendgb.com/QgMYpBXSaGN

Can you add some options for NVENCC, which works in NVENC FFMPEG version and SDK9?

Like:

option for Async Encoding for HEVC (SDK 9 knows this)
option for intra refresh for HEVC ( FFMPEG NVENC version also use it)
option for the so-called "surfaces" 0-64 (works great in FFMPEG NVENC HEVC)
option for non reference p frames in NVENC HEVC (FFMPEG NVENC knows that)

Best Regards!
Alexander

**Comment by rigaya** [comment]
I have updated the info about [RTX2070](https://github.com/rigaya/NVEnc/commit/cf8651bead05aa18e5d693f0cb2246025bde70e2), now showing AQ active also in HEVC.

_Others_
- Async is always enabled in NVEncC to enhance performance, and could not be turned off. (Turning it off will only result poor performance)
- Intra refresh is option mainly for low latency encode mainly targetting real-time broadcasting. NVEncC does not focus on it.
- "Surfaces" ... what does it mean?
- Option to enable non reference p frames is added in [NVEnc 4.42](https://github.com/rigaya/NVEnc/releases/tag/4.42).

**Comment by devil40xxx** [comment]
-surfaces          <int>        E..V..... Number of concurrent surfaces (from 0 to 64) (default 0)  @rigaya

**Comment by rigaya** [comment]
Thanks for the information.

Then it is equivalent to what is shown on the log like...
```
Input Buffers  CUDA, 32 frames
```

In NVEncC, "surface" is treated differently, the nunber of the buffer frames is calculated automatically in NVEncC (also with lower resolution, extra frames is added so the encoder can run processing concurrently, to enhance performance).

**Comment by Cumberiron** [comment]
Hello Rigaya!

What is the so-called "MAX quality" option in FFMPEG version of NVENC (in OBS)?

The guy speaks about a technology, where the NVENC chip and CUDA can work together as a COMBO for an even better quality encoding, which is far superior over the simple NVENC encoding.
Watch this video from that time-point:
https://youtu.be/-HLXjnfmizc?t=262

Best regards!
Alexander

**Comment by rigaya** [comment]
In the video it says that "MAX quality" is 2pass encoding + CUDA refinement. I don't know what is CUDA refinement, but the 2pass encoding is just what --cbrhq or --vbrhq does.

You can see discussion about so called "Psycho Visual Tuning" in #102, it seems to be something related to --aq, --aq-temporal, --aq-strength.

I can't tell exactly what they are, but you know OBS is a large project, its hard to look into source codes of them.

**Comment by Cumberiron** [comment]
Hello Rigaya!

Yes, something working with Cuda cores, because When I select FFMPEG 2pass slow VBR HEVC, the GPU panel of the Task manager shows GPU 3D usage during the encoding. But only in this "2pass" encoding mode. However it doesn't show usage during NVENCC encoding.

Can you make some researches, what is it more exactly, what does it do, what are its advantages of this technology, and how can you implement this DUAL Cuda/NVENC combo technology in your NVENCC.

Thank you!
Alexander

**Comment by rigaya** [comment]
Yes, I think checking ffmpeg should be easier than checking OBS.

Would you let me know the exact options of the ffmpeg when GPU 3D was used?

I tried options below on RTX2070 (430.86 driver), but wasn't successful.
ffmpeg -y -i input.mkv -vcodec hevc_nvenc -rc vbr_hq -preset slow -rc-lookahead 32 -bf 3 -spatial_aq true -temporal_aq true output.mkv

![image](https://user-images.githubusercontent.com/815947/59202187-e9021200-8bd6-11e9-9a85-7a45a733adcc.png)

**Comment by Cumberiron** [comment]
-vcodec hevc_nvenc -preset 5 -profile:v 2 -level 0 -tier high -rc vbr_hq -2pass 1 -qmin 0 -qmax 51 -b:v 2500k -spatial_aq 1 -aq-strength 8 -temporal_aq 0 -surfaces 64 -no-scenecut 0 -refs 7 -nonref_p 1 -strict_gop 1 -g 600 -bf 4 -preset slow


So the GPU 3D was between 3-15% in a GF GTX 1660 card during encoding. Other stronger/faster Nvidia cards can have lower percentages. And don't forget, that the GPU decode of FFMPEG NVENC is not internal so it has slower HW decoding than NVENCC.

**Comment by Cumberiron** [comment]
Unlike the rigid Pascal chip,  the TURING Engine can collaborate with external CPU implementations to share the encoding process. This can lead to a very fast and very high quality hybrid encoding mode.

That's why MAinconcept started to build its own Turing based SDK.

http://www.digitaltvnews.net/?p=32668


Leading codec provider, MainConcept, optimizes its HEVC/H.265 Video Encoding SDK by leveraging NVIDIA RTX GPU capabilities to accelerate HEVC Video compression

AACHEN, Germany and LAS VEGAS — MainConcept® GmbH, a leading technology provider specializing in codecs and streaming for broadcast and OTT, today announced that its latest release of HEVC / H.265 Video Encoder SDK will dramatically increase encoding speed by leveraging functions of the NVIDIA® Video Codec, available with the latest Turing architecture-powered NVIDIA RTX™ GPUs.

MainConcept licenses codec technologies, such as Software Development Kits (SDKs) and ready-to-use products, to the professional broadcast and OTT market. Software vendors, including Adobe, Autodesk, Sony and MAGIX use the flexible libraries from the MainConcept Codec SDK to build video transcoders, live encoders, editing applications, streaming servers and cloud services.

Up until now, MainConcept users had the choice between using either MainConcept’s proven algorithms or opting for best encoding speed through pure hardware encoding to achieve the highest quality video. The new release adds a hybrid encoding mode, allowing the user to get the best of both worlds. MainConcept software controls the encoding power of the GPU, thereby drastically reducing CPU load to allow finer-grained control over the encoding process. This unique approach accelerates the most frequently used operating points for OTT encoding, where high density and pristine video quality is required.

“We are pleased to see the new encoding features and APIs added to the Turing family,” said Deacon Johnson, SVP of Sales at MainConcept. **“This new generation of GPUs enables us to implement the hybrid solution that we’ve always dreamed of.** The speed and quality increase at OTT-relevant encoding sizes and bitrates is what the market has been waiting for.”

“Combining MainConcept’s expertise in bitrate handling and encoding quality with the processing power offered by the NVIDIA Video Codec creates an exciting solution for OEMs,” said Andrew Page, Manager of M&E Advanced Technology at NVIDIA.

Hybrid GPU Encoding is available in MainConcept HEVC SDK 11.0, scheduled to release at the NAB 2019 in Las Vegas.

**Comment by rigaya** [comment]
I've tested your options but again could not see GPU 3D usage with pure ffmpeg sw decoding, I think "3-15% in a GTX1660" is too low to think that it is using "Hybrid solution". Looking into ffmpeg's NVENC implmentation, it was not so special, most of the options in ffmpeg could be mapped into options of NVEncC.

**Comment by rigaya** [comment]
I'll close this issue, as the main issue on the title of this issue has been resolved.
