### ISSUE TITLE
Green line

### ISSUE THREAD

**Issue by ArturAlekseev** [rigaya/NVEnc#128]
Hello,
First - a lot of thanks for you work on nvencc!

Looks like the issue with green line at the left is not totally fixed.
In version 4.40 & 4.41 I get it when encoding source that has resolution 688x368p.

**Comment by rigaya** [comment]
Thanks for reporting this issue, should be fixed in [NVEnc 4.42](https://github.com/rigaya/NVEnc/releases/tag/4.42).

**Comment by rigaya** [comment]
I'll close this issue, as this issue should have been fixed. Please re-open if you have related issues.
