### ISSUE TITLE
Free H.264 MVC 3D Decoder with NVEnc - Corrupt video (Green Color)

### ISSUE THREAD

**Issue by tabnk** [rigaya/NVEnc#13]
I'm trying to use **Free H.264 MVC 3D Decoder** (https://forum.doom9.org/showthread.php?t=169651 ) to PIPE to NVEnc.

FRIMDecode64.exe -i:mvc "video.264" "video.mvc" -sbs -hw  -o - | NVEncC64.exe --raw -i -  --input-res 3840x1080 --fps 23.975 --cqp 20:23:25 --preset quality  -o "video_out.h264"

Always get out corrupt output from NVEnc. 

If use Avisynth, it is fine.

**Comment by rigaya** [comment]
Thank you fro reporting.

I was not able to run FRIMDecode64.exe on my environment (as I don't have a system with QSV + NVEnc), but it looks like a general problem with raw reader of NVEncC. It should be fixed with NVEncC 3.18.

**Comment by tabnk** [comment]
Tks., it's fixed.
