### ISSUE TITLE
help missing '--nonrefp'

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#130]
> Add option to automatically insert non reference P frames. (--nonrefp, #126 )

The help doesn't list the new option. :)

**Comment by Selur** [comment]
also: the help output states that aq-strength is a H.264 only option, https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md doesn't.

**Comment by Cumberiron** [comment]
Despite AQ strength option (0-15) **performs astonishingly good** even in NVENC HEVC. (I tested it many-many times.) and it is not listed in help and in the change log.

**Comment by rigaya** [comment]
--nonrefp has been [added](https://github.com/rigaya/NVEnc/commit/d7b07fa7083980b9bf6afefdba23c1fcebcc18a9) to help in NVEnc 4.44.
