### ISSUE TITLE
Question about: --mux-option

### ISSUE THREAD

**Issue by djrooli** [rigaya/NVEnc#131]
Hello Rigaya!

How can I add an external (for example hun_forced.srt) subtitle to the video file?
I wanted to ask you to add an --add-sub switch, but I think ---mux-option can do it, but how?

Thank you for your answer.

**Comment by rigaya** [comment]
Sorry, the app doesn't have ability to add subtitles from another file. (--mux-option cannot do that.)

I'll think about adding that feature.

**Comment by djrooli** [comment]
Thank you for your answer.
If you are willing to do that, may I suggest to make an option as well where to insert it.
I mean: as subtitle track no. 1 or 2 or 3.

Thank you in advance.
All the best.

**Comment by djrooli** [comment]
Thank you very much! ;) Now, no need to mux the video after conversion! ;)
