### ISSUE TITLE
HDR10+ metadata seems not applying

### ISSUE THREAD

**Issue by iykkim** [rigaya/NVEnc#133]
Hi.
I have a question about HDR10+ metadata applying.

I'm doing 4K blu-ray ripped video contents re-encoding which hass HDR10+ metadata with the extracted dhdr metadata json file by hdr10plus_parser utility.
It looks manipulating hdr10+ json metadata well during the encoding as I can see hdr10plus_gen.exe process up and running with nvencc64 process too.
But when I check the completed video file, there is no HDR10+ metadata showing from MediaInfo v19.07, also hdr10plue_parser utility too..
So it seems not properly or at all applied HDR10+ metadata when encoding with the --dhdr10-info option.
Please check this and let me know if I need to doing some other works to properly apply the HDR10+ metadata when encoding.

And always appreciate your works.

**Comment by iykkim** [comment]
FYI, I uploaded the sample HDR10+ 4K file clip, json file and encoded file in below OneDrive link;
https://1drv.ms/f/s!ApSX3ujJA5Tvgowsto7h_-ODYjTedw

Alita- sample.hevc file is the sample 4K clip file with HDR10+ metadata,
meta.json file is the extracted HDR10+ metadata by hdr10plus_parser utility,
Alita- encSample.hevc file is the re-encoded file with meta.json done as below command;

nvencc64 -c h265 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) --colorprim bt2020 --transfer smpte2084 --colormatrix bt2020nc--max-cll 737,130 --dhdr10-info meta.json -u quality --mv-precision Q-pel --profile main10 --output-depth 10 --lookahead 32 --aq --vbrhq 33089 -i input.avs -o Alita- encSample.hevc

* input.avs is created by DGIndexNV utility.

**Comment by rigaya** [comment]
Thanks for the samples, I'll try to check what is causing the problem.

**Comment by iykkim** [comment]
While waiting, I tried the meta.json with x265 v3.1.8 and uploaded the sample file naming as "Alita- x265sample.hevc" in the OneDrive share above and HDR10+ metadata seems applied well.
So hdr10plus_parser created metadata looks no problem.

**Comment by hyllm** [comment]
experiencing the same problem

**Comment by rigaya** [comment]
Should be fixed with [NVEnc 4.44](https://github.com/rigaya/NVEnc/releases/tag/4.44).

**Comment by iykkim** [comment]
Thanks for update but there is other problem...
When I use "--dhdr10-info" option, encoding is starting but terminate after some seconds so there is 0 byte of encoding file created.
Without --dhdr10-info option, encoding is done well as usual.
