### ISSUE TITLE
nvenc in staxrip and ryzen 3750H with 1660Ti

### ISSUE THREAD

**Issue by drk222** [rigaya/NVEnc#135]
Hi everybody. 
I have just tried to encode with staxrip on my new notebook and it looks like staxrip/nvenc cannot detect my graphic card correctly.

HW encoding with integrated vega 10 works fine, NVEnc on another program (Handbrake) works with 1660ti too..

Tried latest version of staxrip, then latest version of NVEnc but no luck...

NVEnc Error (2.0.2.4)

H.265/HEVC isn't supported by the graphics card.

StaxRip.ErrorAbortException: H.265/HEVC isn't supported by the graphics card.
   v StaxRip.NVEnc.Encode()
   v StaxRip.GlobalClass.ProcessVideo()
   v System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v StaxRip.GlobalClass.ProcessJob(String jobPath)

-------------------------- System Environment --------------------------

StaxRip    : 2.0.2.4
Windows    : Windows 10 Home 1809
Language   : Czech (Czechia)
CPU        : AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
GPU        : NVIDIA GeForce GTX 1660 Ti, AMD Radeon(TM) RX Vega 10 Graphics
Resolution : 1920 x 1080
DPI        : 120

------------------------ MediaInfo Source File ------------------------

**Comment by pwacooijmans** [comment]
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix#Encoder

**Comment by drk222** [comment]
pwacooijmans?
Why u post list of supported gpus?
Of course 1660ti is suported by nvenc. I have problem just with staxrip in combination with nvenc. And after posting in staxrip support pages i was told that this is becouse of nvenc bug and i should post it here....
Maybe the problem is with another gpu in system, but another aplication (handbrake) can detect it wo problem.

**Comment by rigaya** [comment]
I don't know about StaxRip error, but you might first try
```
NVEncC64.exe --check-hw
```
and might get a clue for the problem.

**Comment by drk222** [comment]
after --check-hw:
[NVENC API v9.0, CUDA 10.1]
reader: raw, avi, avs, vpy, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4]
Loaded nvEncodeAPI64.dll.
InitCuda: device #0.

Checking Environment Info...
NVEncC (x64) 4.43 (r1143) by rigaya, Jul 14 2019 15:18:21 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (17763)
CPU            AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (4C/8T)
GPU            #0: GeForce GTX 1660 Ti (431.60)
NVENC / CUDA   NVENC API 9.0, CUDA 10.1, schedule mode: auto
cuInit: Success.
cuDeviceGetCount: Success.
cuDeviceGet: ID:0.
cuDeviceComputeCapability: Success: 7.5.
NVENC capabilities: OK.
using cuda schedule mode: auto.
cuCtxCreate: Success.
cuCtxPopCurrent: Success.
cuvidInit: Success.
cuvidCtxLockCreate: Success.
InitCuda: Success.
nvEncodeAPICreateInstance(APIVer=0x70020009): Success.
NvEncOpenEncodeSessionEx(device_type=NV_ENC_DEVICE_TYPE_CUDA): Success.
nvEncDestroyEncoder: success.
Closing perf monitor...
Avaliable Codec(s)
H.264/AVC
H.265/HEVC

Then again tested staxrip with nvenc 4.42 and now it works, du no what happen/changed from previous days ......

**Comment by drk222** [comment]
Well there was 1 change. Late night i updated to latest nvidia game ready drivers.

**Comment by rigaya** [comment]
I'll close this issue as it seems to have resolved.
