### ISSUE TITLE
nvidia driver 431.60 cuda went from 10.2 to 10.1 why?

### ISSUE THREAD

**Issue by pwacooijmans** [rigaya/NVEnc#136]
Dear Rigaya maybe you have a clue, your NVEncC64.exe used to report cuda 10.2 during encoding now with the new driver from nvidia 431.60 cuda went back to 10.1 again. Why is this? any clue?

**Comment by rigaya** [comment]
Actually the latest CUDA version out should be "CUDA 10.1 **Update 1**", so it might be only that NVIDIA just changed the description in the latest driver (or might be planning for 10.2 in the future).

You generally do not need to care about CUDA minor version in NVEncC, as it has no influence on encoding. (what is more important is NVENC API ver)
