### ISSUE TITLE
DTS audio profiles not working

### ISSUE THREAD

**Issue by hmartin417** [rigaya/NVEnc#137]
When encoding audio to DTS, the only profile that works is the DTS profile. All other profiles do not work. Additionally, when encoding to other audio codecs (truehd), it doesn't update the bitrate of the audio portion. It still shows original track bitrate info. Can we please get a fix for these issues. I'm currently using a RTX2060

**Comment by djrooli** [comment]
Is NVEncc capable of encoding DTS or THD? As far as I know it can only decode, as it uses ffmpeg and these codecs are licensed codecs. Maybe I'm wrong. Anyways, Rigaya, allow me to say a big thank you for the external audio support!

**Comment by hmartin417** [comment]
Per my GPU these options are supported. Decode and encode. See below.
 
set NVEnc="E:\Tools\NVEnc\NVEncC64.exe"

"E:\Tools\NVEnc\NVEncC64.exe" --check-device
DeviceId #0: GeForce RTX 2060

"E:\Tools\NVEnc\NVEncC64.exe" --check-codecs
D-: Decode
-E: Encode
---------------------
D- 8svx_exp        : 8SVX exponential
D- 8svx_fib        : 8SVX fibonacci
DE aac             : AAC (Advanced Audio Coding)
D- aac_fixed       : AAC (Advanced Audio Coding)
D- aac_latm        : AAC LATM (Advanced Audio Coding LATM syntax)
DE ac3             : ATSC A/52A (AC-3)
DE ac3_fixed       : ATSC A/52A (AC-3)
D- adpcm_4xm       : ADPCM 4X Movie
DE adpcm_adx       : SEGA CRI ADX ADPCM
D- adpcm_afc       : ADPCM Nintendo Gamecube AFC
D- adpcm_agm       : ADPCM AmuseGraphics Movie
D- adpcm_aica      : ADPCM Yamaha AICA
D- adpcm_ct        : ADPCM Creative Technology
D- adpcm_dtk       : ADPCM Nintendo Gamecube DTK
D- adpcm_ea        : ADPCM Electronic Arts
D- adpcm_ea_maxis_xa: ADPCM Electronic Arts Maxis CDROM XA
D- adpcm_ea_r1     : ADPCM Electronic Arts R1
D- adpcm_ea_r2     : ADPCM Electronic Arts R2
D- adpcm_ea_r3     : ADPCM Electronic Arts R3
D- adpcm_ea_xas    : ADPCM Electronic Arts XAS
D- adpcm_ima_amv   : ADPCM IMA AMV
D- adpcm_ima_apc   : ADPCM IMA CRYO APC
D- adpcm_ima_dat4  : ADPCM IMA Eurocom DAT4
D- adpcm_ima_dk3   : ADPCM IMA Duck DK3
D- adpcm_ima_dk4   : ADPCM IMA Duck DK4
D- adpcm_ima_ea_eacs: ADPCM IMA Electronic Arts EACS
D- adpcm_ima_ea_sead: ADPCM IMA Electronic Arts SEAD
D- adpcm_ima_iss   : ADPCM IMA Funcom ISS
D- adpcm_ima_oki   : ADPCM IMA Dialogic OKI
DE adpcm_ima_qt    : ADPCM IMA QuickTime
D- adpcm_ima_rad   : ADPCM IMA Radical
D- adpcm_ima_smjpeg: ADPCM IMA Loki SDL MJPEG
DE adpcm_ima_wav   : ADPCM IMA WAV
D- adpcm_ima_ws    : ADPCM IMA Westwood
DE adpcm_ms        : ADPCM Microsoft
D- adpcm_mtaf      : ADPCM MTAF
D- adpcm_psx       : ADPCM Playstation
D- adpcm_sbpro_2   : ADPCM Sound Blaster Pro 2-bit
D- adpcm_sbpro_3   : ADPCM Sound Blaster Pro 2.6-bit
D- adpcm_sbpro_4   : ADPCM Sound Blaster Pro 4-bit
DE adpcm_swf       : ADPCM Shockwave Flash
D- adpcm_thp       : ADPCM Nintendo THP
D- adpcm_thp_le    : ADPCM Nintendo THP (little-endian)
D- adpcm_vima      : LucasArts VIMA audio
D- adpcm_xa        : ADPCM CDROM XA
DE adpcm_yamaha    : ADPCM Yamaha
DE alac            : ALAC (Apple Lossless Audio Codec)
D- als             : MPEG-4 Audio Lossless Coding (ALS)
D- amrnb           : AMR-NB (Adaptive Multi-Rate NarrowBand)
D- amrwb           : AMR-WB (Adaptive Multi-Rate WideBand)
D- ape             : Monkey's Audio
DE aptx            : aptX (Audio Processing Technology for Bluetooth)
DE aptx_hd         : aptX HD (Audio Processing Technology for Bluetooth)
D- ass             : ASS (Advanced SubStation Alpha) subtitle
D- atrac1          : ATRAC1 (Adaptive TRansform Acoustic Coding)
D- atrac3          : ATRAC3 (Adaptive TRansform Acoustic Coding 3)
D- atrac3al        : ATRAC3 AL (Adaptive TRansform Acoustic Coding 3 Advanced Lossless)
D- atrac3plus      : ATRAC3+ (Adaptive TRansform Acoustic Coding 3+)
D- atrac3plusal    : ATRAC3+ AL (Adaptive TRansform Acoustic Coding 3+ Advanced Lossless)
D- atrac9          : ATRAC9 (Adaptive TRansform Acoustic Coding 9)
D- bmv_audio       : Discworld II BMV audio
D- cc_dec          : Closed Caption (EIA-608 / CEA-708)
DE comfortnoise    : RFC 3389 comfort noise generator
D- cook            : Cook / Cooker / Gecko (RealAudio G2)
DE dca             : DCA (DTS Coherent Acoustics)
D- dolby_e         : Dolby E
D- dsd_lsbf        : DSD (Direct Stream Digital), least significant bit first
D- dsd_lsbf_planar : DSD (Direct Stream Digital), least significant bit first, planar
D- dsd_msbf        : DSD (Direct Stream Digital), most significant bit first
D- dsd_msbf_planar : DSD (Direct Stream Digital), most significant bit first, planar
D- dsicinaudio     : Delphine Software International CIN audio
D- dss_sp          : Digital Speech Standard - Standard Play mode (DSS SP)
D- dst             : DST (Digital Stream Transfer)
D- dvaudio         : Ulead DV Audio
D- dvbsub          : DVB subtitles
D- dvdsub          : DVD subtitles
DE eac3            : ATSC A/52 E-AC-3
D- evrc            : EVRC (Enhanced Variable Rate Codec)
DE flac            : FLAC (Free Lossless Audio Codec)
DE g722            : G.722 ADPCM
DE g723_1          : G.723.1
DE g726            : G.726 ADPCM
DE g726le          : G.726 little endian ADPCM ("right-justified")
D- g729            : G.729
D- gremlin_dpcm    : DPCM Gremlin
D- gsm             : GSM
D- gsm_ms          : GSM Microsoft variant
D- hcom            : HCOM Audio
D- iac             : IAC (Indeo Audio Coder)
D- ilbc            : iLBC (Internet Low Bitrate Codec)
D- imc             : IMC (Intel Music Coder)
D- interplay_dpcm  : DPCM Interplay
D- interplayacm    : Interplay ACM
D- jacosub         : JACOsub subtitle
D- libaribb24      : libaribb24 ARIB STD-B24 caption decoder
-E libmp3lame      : libmp3lame MP3 (MPEG audio layer 3)
DE libopus         : libopus Opus
DE libspeex        : libspeex Speex
-E libtwolame      : libtwolame MP2 (MPEG audio layer 2)
DE libvorbis       : libvorbis
-E libwavpack
D- mace3           : MACE (Macintosh Audio Compression/Expansion) 3:1
D- mace6           : MACE (Macintosh Audio Compression/Expansion) 6:1
D- metasound       : Voxware MetaSound
D- microdvd        : MicroDVD subtitle
DE mlp             : MLP (Meridian Lossless Packing)
D- mov_text        : 3GPP Timed Text subtitle
D- mp1             : MP1 (MPEG audio layer 1)
D- mp1float        : MP1 (MPEG audio layer 1)
DE mp2             : MP2 (MPEG audio layer 2)
-E mp2fixed        : MP2 fixed point (MPEG audio layer 2)
D- mp2float        : MP2 (MPEG audio layer 2)
D- mp3             : MP3 (MPEG audio layer 3)
D- mp3adu          : ADU (Application Data Unit) MP3 (MPEG audio layer 3)
D- mp3adufloat     : ADU (Application Data Unit) MP3 (MPEG audio layer 3)
D- mp3float        : MP3 (MPEG audio layer 3)
D- mp3on4          : MP3onMP4
D- mp3on4float     : MP3onMP4
D- mpc7            : Musepack SV7
D- mpc8            : Musepack SV8
D- mpl2            : MPL2 subtitle
DE nellymoser      : Nellymoser Asao
D- on2avc          : On2 Audio for Video Codec
DE opus            : Opus
D- paf_audio       : Amazing Studio Packed Animation File Audio
DE pcm_alaw        : PCM A-law / G.711 A-law
D- pcm_bluray      : PCM signed 16|20|24-bit big-endian for Blu-ray media
DE pcm_dvd         : PCM signed 16|20|24-bit big-endian for DVD media
D- pcm_f16le       : PCM 16.8 floating point little-endian
D- pcm_f24le       : PCM 24.0 floating point little-endian
DE pcm_f32be       : PCM 32-bit floating point big-endian
DE pcm_f32le       : PCM 32-bit floating point little-endian
DE pcm_f64be       : PCM 64-bit floating point big-endian
DE pcm_f64le       : PCM 64-bit floating point little-endian
D- pcm_lxf         : PCM signed 20-bit little-endian planar
DE pcm_mulaw       : PCM mu-law / G.711 mu-law
DE pcm_s16be       : PCM signed 16-bit big-endian
DE pcm_s16be_planar: PCM signed 16-bit big-endian planar
DE pcm_s16le       : PCM signed 16-bit little-endian
DE pcm_s16le_planar: PCM signed 16-bit little-endian planar
DE pcm_s24be       : PCM signed 24-bit big-endian
DE pcm_s24daud     : PCM D-Cinema audio signed 24-bit
DE pcm_s24le       : PCM signed 24-bit little-endian
DE pcm_s24le_planar: PCM signed 24-bit little-endian planar
DE pcm_s32be       : PCM signed 32-bit big-endian
DE pcm_s32le       : PCM signed 32-bit little-endian
DE pcm_s32le_planar: PCM signed 32-bit little-endian planar
DE pcm_s64be       : PCM signed 64-bit big-endian
DE pcm_s64le       : PCM signed 64-bit little-endian
DE pcm_s8          : PCM signed 8-bit
DE pcm_s8_planar   : PCM signed 8-bit planar
DE pcm_u16be       : PCM unsigned 16-bit big-endian
DE pcm_u16le       : PCM unsigned 16-bit little-endian
DE pcm_u24be       : PCM unsigned 24-bit big-endian
DE pcm_u24le       : PCM unsigned 24-bit little-endian
DE pcm_u32be       : PCM unsigned 32-bit big-endian
DE pcm_u32le       : PCM unsigned 32-bit little-endian
DE pcm_u8          : PCM unsigned 8-bit
DE pcm_vidc        : PCM Archimedes VIDC
D- pcm_zork        : PCM Zork
D- pgssub          : HDMV Presentation Graphic Stream subtitles
D- pjs             : PJS subtitle
D- qcelp           : QCELP / PureVoice
D- qdm2            : QDesign Music Codec 2
D- qdmc            : QDesign Music Codec 1
D- ralf            : RealAudio Lossless
DE real_144        : RealAudio 1.0 (14.4K)
D- real_288        : RealAudio 2.0 (28.8K)
D- realtext        : RealText subtitle
DE roq_dpcm        : id RoQ DPCM
DE s302m           : SMPTE 302M
D- sami            : SAMI subtitle
DE sbc             : SBC (low-complexity subband codec)
D- sdx2_dpcm       : DPCM Squareroot-Delta-Exact
D- shorten         : Shorten
D- sipr            : RealAudio SIPR / ACELP.NET
D- smackaud        : Smacker audio
D- sol_dpcm        : DPCM Sol
DE sonic           : Sonic
-E sonicls         : Sonic lossless
D- srt             : SubRip subtitle
D- ssa             : ASS (Advanced SubStation Alpha) subtitle
D- stl             : Spruce subtitle format
D- subrip          : SubRip subtitle
D- subviewer       : SubViewer subtitle
D- subviewer1      : SubViewer1 subtitle
D- tak             : TAK (Tom's lossless Audio Kompressor)
D- text            : Raw text subtitle
DE truehd          : TrueHD
D- truespeech      : DSP Group TrueSpeech
DE tta             : TTA (True Audio)
D- twinvq          : VQF TwinVQ
D- vmdaudio        : Sierra VMD audio
-E vorbis          : Vorbis
D- vplayer         : VPlayer subtitle
D- wavesynth       : Wave synthesis pseudo-codec
DE wavpack         : WavPack
D- webvtt          : WebVTT subtitle
D- wmalossless     : Windows Media Audio Lossless
D- wmapro          : Windows Media Audio 9 Professional
DE wmav1           : Windows Media Audio 1
DE wmav2           : Windows Media Audio 2
D- wmavoice        : Windows Media Audio Voice
D- ws_snd1         : Westwood Audio (SND1)
D- xan_dpcm        : DPCM Xan
D- xma1            : Xbox Media Audio 1
D- xma2            : Xbox Media Audio 2
D- xsub            : DivX subtitles (XSUB)

"E:\Tools\NVEnc\NVEncC64.exe" --check-profiles dca
profile name for "dca"
  DTS
  DTS-ES
  DTS 96/24
  DTS-HD HRA
  DTS-HD MA
  DTS Express

**Comment by djrooli** [comment]
I see, I have the same GPU, I've never tried to convert DTS or THD audio with NVEncC. I will try.

**Comment by hmartin417** [comment]
Did you ever get to try the DTS and THD?

**Comment by djrooli** [comment]
Not yet, sorry, now time to play with this nowdays. I'm struggling with version 4.45 for some reason it gives me error messages about the switches, but I'm using script for nvencc.

**Comment by rigaya** [comment]
The libavcodec (which does the audio encoding) only seems to support DTS profile at this time. Therefore, it won't be able to encode in other profiles.
