### ISSUE TITLE
Encoding terminate with dhdr10-info option in v4.44

### ISSUE THREAD

**Issue by iykkim** [rigaya/NVEnc#138]
Thanks for v4.44 update but there is other problem...
When I use "--dhdr10-info" option, encoding is starting but terminate after some seconds so there is 0 byte of encoding file created.
Without --dhdr10-info option, encoding is done well as usual.

* I opened new issue for your convenience as it seems uncomfortable to see as comment of previous #133 issue.

**Comment by rigaya** [comment]
Unfortunately, I'm not able to reproduce the problem. I'm testing using the sample json file [Tool_Verification_new_hdr10plus_llc.json](https://bitbucket.org/multicoreware/x265/downloads/),

NVEncC64.exe -b 0 -c hevc --output-depth 10 --profile main10 --dhdr10-info Tool_Verification_new_hdr10plus_llc.json -i input.mkv -o output.265

I was able to parse the metadata by [hdr10plus_parser](https://github.com/quietvoid/hdr10plus_parser),

hdr10plus_parser.exe output.265 output.json

Is it possible to have a copy of json file you are using for "--dhdr10-info"?

**Comment by iykkim** [comment]
It's in the OneDrive link as name "meta.json" in #133 that I was uploaded with sample HDR10+ clip.
Please see below link again, I still maintaining this link;
  https://1drv.ms/f/s!ApSX3ujJA5Tvgowsto7h_-ODYjTedw

The "meta.json" is extracted by hdr10plus_parser tool and this sample clip is from 4K HDR10+ Blu-Ray ripped file and I think it's suitable for the development and testing.

**Comment by rigaya** [comment]
Thanks, I have reproduced the issue.

Would you please try **without**  --lookahead?

I've found out it works without lookahead, but whenever you enable lookahead it crushes **inside** NVENC API NvEncEncodePicture(), and currently not being able to find out how to avoid it.

**Comment by iykkim** [comment]
I'm confirmed too that it's finally encoding well without --lookahead option.
Thanks for your confirm and answer.
And is the default value 16 still applying without --lookahead? 
Then I have no more concern without it.

**Comment by rigaya** [comment]
>And is the default value 16 still applying without --lookahead?
Unfortunately no, without --lookahead, the lookahead feature is fully disabled. Using --dhdr10-info and lookahead crushes regardless of the value of lookahead, when calling NvEncEncodePicture() of NVENC API which sends dynamic hdr10 SEI prefix to the NVENC driver.

**Comment by iykkim** [comment]
I see.
Then looks no other way except not using lookaheah option for now until Nvidia fix this  in SDK.
Thanks again.
