### ISSUE TITLE
NVEnc Error (NVenc 4.44 on Staxrip 2.0.3.0) Unknown option: "cuda" #37

### ISSUE THREAD

**Issue by coxinator138** [rigaya/NVEnc#139]
I'm having trouble encoding at all with NVenc x264 with NVenc Cuda selected.

Add any file to encode
Use settings NVenc x264 with NVenc Cuda decoding selected
Try to encode the file
Here's the error I'm getting

Error Video encoding using NVEnc 4.44 (2.0.3.0)

Video encoding using NVEnc 4.44 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------------- Video encoding using NVEnc 4.44 -------------------

C:\Users\jdcox215\Downloads\Compressed\StaxRip-x64-2.0.3.0-stable\Apps\Encoders\NVEnc\NVEncC64.exe --avhw cuda --vbr 8000 --preset quality --level 4.1 --bframes 8 --ref 4 --cabac -i "F:\Blu Ray\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!.mkv" -o "F:\Blu Ray\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_temp\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_new_out.h264"

Error: Unknown option: "cuda"

StaxRip.ErrorAbortException: Video encoding using NVEnc 4.44 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------------- Video encoding using NVEnc 4.44 -------------------

C:\Users\jdcox215\Downloads\Compressed\StaxRip-x64-2.0.3.0-stable\Apps\Encoders\NVEnc\NVEncC64.exe --avhw cuda --vbr 8000 --preset quality --level 4.1 --bframes 8 --ref 4 --cabac -i "F:\Blu Ray\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!.mkv" -o "F:\Blu Ray\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_temp\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_new_out.h264"

Error: Unknown option: "cuda"

at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 339
at StaxRip.NVEnc.Encode() in D:\Projekte\VB\staxrip\Encoding\NVEnc.vb:line 82
at StaxRip.GlobalClass.ProcessVideo() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 227
at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.b__0()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 137

Desktop:

OS: Windows 10 Pro Insider Preview Build 18963
NVEnc 4.44
Logs attached in files
I had been using the exact same settings as I am for this encode for a lot of the other encodes I did today and it worked..... I updated to Staxrip 2.0.3.0 and it stopped working.... so then I continued using 2.0.2.4 and it still wouldn't work...
[Dragon.Ball.Z.Kai.-.S01E01.-.Prologue.to.Battle.The.Return.of.Goku._new_staxrip.log](https://github.com/rigaya/NVEnc/files/3523079/Dragon.Ball.Z.Kai.-.S01E01.-.Prologue.to.Battle.The.Return.of.Goku._new_staxrip.log)

**Comment by rigaya** [comment]
I have removed cuda option from --avhw in NVEnc 4.44, as recent NVIDIA chips seems to always use NVDEC for decoding and not CUDA ([link](https://devtalk.nvidia.com/default/topic/1043763/video-codec-and-optical-flow-sdk/two-encoders-one-decoder-what-to-do-/)). Sorry for not updating the help about this, I will update in the help in the next release.

Please use "NVenc native" in StaxRip, or simply "--avhw" from commandline.

**Comment by coxinator138** [comment]
Thank you for replying! I started to use Nvenc native and I didn’t notice much FPS loss. Thank you!   
  

  
  

  
  
>
