### ISSUE TITLE
est. file size ?  can we have this in the cmd information bar please.

### ISSUE THREAD

**Issue by zerowalkx** [rigaya/NVEnc#140]
good morning, it would be possible to please add this information about the estimated size of the result, thank you very much.

it's very useful.

![Sin título](https://user-images.githubusercontent.com/54515635/63657636-d88b1d80-c769-11e9-87da-4d171eda5015.jpg)
![nvc](https://user-images.githubusercontent.com/54515635/63657643-daed7780-c769-11e9-962a-b300158be4e1.jpg)

**Comment by rigaya** [comment]
This feature was added in [NVEnc 4.46](https://github.com/rigaya/NVEnc/releases/tag/4.46). Please note that it will be available only when the console has enough width.

![image](https://user-images.githubusercontent.com/815947/63780897-d53b9180-c923-11e9-8e24-cfb3fa7d1b08.png)

**Comment by rigaya** [comment]
Somehow binaries built on appveyor wasn't uploaded automatically as always, I uploaded manually now.

**Comment by ZeroCool22** [comment]
> 
> 
> good morning, it would be possible to please add this information about the estimated size of the result, thank you very much.
> 
> it's very useful.
> 
> ![Sin título](https://user-images.githubusercontent.com/54515635/63657636-d88b1d80-c769-11e9-87da-4d171eda5015.jpg)
> ![nvc](https://user-images.githubusercontent.com/54515635/63657643-daed7780-c769-11e9-962a-b300158be4e1.jpg)

What software is that?

**Comment by zerowalkx** [comment]
> 
> 
> > good morning, it would be possible to please add this information about the estimated size of the result, thank you very much.
> > it's very useful.
> > ![Sin título](https://user-images.githubusercontent.com/54515635/63657636-d88b1d80-c769-11e9-87da-4d171eda5015.jpg)
> > ![nvc](https://user-images.githubusercontent.com/54515635/63657643-daed7780-c769-11e9-962a-b300158be4e1.jpg)
> 
> What software is that?

what software ?  i dont understand

**Comment by rigaya** [comment]
I'll close this issue, as this feature has been added.
