### ISSUE TITLE
Error: Unknown option

### ISSUE THREAD

**Issue by djrooli** [rigaya/NVEnc#144]
Hello Rigaya!

Since version 4.44 I have problem with my bat file.
I'm having this error every single time:

<img width="228" alt="Capture" src="https://user-images.githubusercontent.com/50361400/63877460-f950ae80-c9c7-11e9-8b55-cff90560c5f1.PNG">

If I copy over the 4.43 bat and delete "cuda" from --avhw than it doesn't work either.
My bat file is working only with 4.43. (Also new versions of my bat files are working with v.4.43)

If you have time, can you reproduce the issue?

The purpose of this .bat file is just copy over to the movie directory and you can easily config the switches. 

[nvencc_bat_files.zip](https://github.com/rigaya/NVEnc/files/3552091/nvencc_bat_files.zip)

The difference from 4.43 to 4.44 and above is the "cuda" has been removed as you were wrote it.
And the directory for the exe must be changed when you test it.
Also I add all the new features as you add them to the new versions, so the bats are not the same. (In this case it only 4.43 differs from the others in terms of switches (options).

I would be pleased if you could take a look at it and see what could the problem be, if you have 5 spare minutes.

Thank you very much in advance.

**Comment by rigaya** [comment]
Thank you for reporting the problem.

I found out that I had broken --output-format in NVEnc 4.44, and should have been fixed on [NVEnc 4.47](https://github.com/rigaya/NVEnc/releases/tag/4.47).

**Comment by djrooli** [comment]
Thank you Rigaya! ;)
