### ISSUE TITLE
Subburn and trimming results in out of sync subtitles & much more.

### ISSUE THREAD

**Issue by ls-milkyway** [rigaya/NVEnc#146]
Hi!
I have a mkv file which needs to precisely cut (so selected --trim) and then burnt with ass subtitle file using --vpp-subburn command and finally encoded...i.e.

Staxrip command:

--vbrhq 13896 --preset quality --vpp-subburn filename="G:\ep1.ass",charcode=utf-8,shaping=complex --vpp-unsharp --vpp-tweak contrast=1.05 --weightp --bframes 4 --ref 4 --gop-len 250 --lookahead 32 --nonrefp --aq-strength 1 --vbr-quality 25 --aq --cuda-schedule auto --mv-precision q-pel --cabac --bref-mode middle --direct auto --output-res 1280x720 --trim 236:69398

The above command results in out of sync ass subtitle burned to the video....I thought putting --vpp-subburn after --trim i.e.

--vbrhq 13896 --preset quality --vpp-unsharp --vpp-tweak contrast=1.05 --weightp --bframes 4 --ref 4 --gop-len 250 --lookahead 32 --nonrefp --aq-strength 1 --vbr-quality 25 --aq --cuda-schedule auto --mv-precision q-pel --cabac --bref-mode middle --direct auto --output-res 1280x720 --trim 236:69398  --vpp-subburn filename="G:\ep1.ass",charcode=utf-8,shaping=complex

although subtitles are in sync but result in a video cut... which is not precise (very similar to approx cut by mkvmerge)

Thought of using ts_offset  to adjust the timeline due to trimming ...but results in error by staxrip latest stable....opened issue at staxrip ...since it's internal subburn is also not working.

**Comment by rigaya** [comment]
--vpp-subburn assumes the subtitle is already trimmed when the subtitle source is from a external file.

When you want to apply --trim to the sub, the subtitle must come from the same input file you are trying to use --trim on, so you need to use "--vpp-subburn track=x" instead of "--vpp-subburn filename=x".

You can first mux the ass file using [mkvmerge](https://mkvtoolnix.download/downloads.html) and create a new mkv file with the subtitle.

mkvmerge.exe -o muxed.mkv input.mkv "G:\ep1.ass"

Then please use --vpp-subburn with track options.

NVEncC64.exe --vpp-subburn track=1,shaping=complex --trim 236:69398 -i muxed.mkv -o output.mkv

**Comment by ls-milkyway** [comment]
Thanks for quick reply ....yeah i have already tried that by muxing ass subtitle and using command...staxrip latest stable hangs after executing ffmpeg then it completely executes ..nvenc commands....and doesn't do anything after encoding .......i mean it does not remux to create a final output but just hangs ..plz check screenshot and log file generated....
![hangs](https://user-images.githubusercontent.com/55090624/64549385-3e70cb00-d34e-11e9-8ae2-7bb2a0c8b66a.jpg)
[staxrip.log](https://github.com/rigaya/NVEnc/files/3591621/staxrip.log)

Command:

--vbrhq 13896 --preset quality --vpp-subburn track=1,shaping=complex --vpp-unsharp --vpp-tweak contrast=1.05 --weightp --bframes 4 --ref 4 --gop-len 250 --lookahead 32 --nonrefp --aq-strength 1 --vbr-quality 25 --aq --cuda-schedule auto --mv-precision q-pel --cabac --bref-mode middle --direct auto --output-res 1280x720 --trim 237:69397

**Comment by ls-milkyway** [comment]
Ok I see, I was directly using  "--vpp-subburn track=1" from example code instead of "--vpp-subburn track=1,shaping=complex" that certainly proves there is no such issue with nvenc...but staxrip does hang.

Ok I also found a way to stop staxrip from getting stuck.....i.e one needs to un-check enabled option from Container Configuration->Subtitles plus make sure that Option->Subtitles->Demux Subtitle is set to "None" for successful in sync burning of ass.

But don't know that this is a actual issue with staxrip to be listed at their github or not.

Thanks once again for suggesting to add "shaping=complex" which I could never have concluded by looking at the examples.

**Comment by rigaya** [comment]
I'll close this issue, as this issue should have been resolved. Please re-open if you have related issues.
