### ISSUE TITLE
--vpp-resize  Rezise 1080p  to 720p ???

### ISSUE THREAD

**Issue by zerowalkx** [rigaya/NVEnc#147]
hello, how can I reduce the size of 1920x1080 to 1280x720 using the option --vpp-resize ?

I do not see any example of how to use it, thank you very much for the help and example. 

thanks so much

**Comment by Last-Order** [comment]
Have you tried --output-res?
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--output-res-intxint

**Comment by kusingen** [comment]
Hi.
--vpp-resize defines algorithm used --output-res defines desired output resolution
You have to use --output-res or both

I was wondering if it would be possible to implement quick downsize options like --down720p and --down1080p that would not require to input resolution manually but would calculate it from input resolution maintaining aspect ratio. I'm using it in a .CMD file in a loop that encodes everything in a hotfolder and changing resolution is impossible for different input resolutions this way.
THX.

**Comment by djrooli** [comment]
--output-res is the first option you have to use. If you want to crop (delete the top and bottom black parts too) then you have to use --crop I'm using AVSP and calc.exe :) to calculate both crop and resize. --vpp-resize defines the algorithm, you can choose what gives you the best.

**Comment by rigaya** [comment]
As djrooli has mentioned, please use --output-res option.
