### ISSUE TITLE
It's normal?

### ISSUE THREAD

**Issue by ZeroCool22** [rigaya/NVEnc#148]
**PC Specs:**

I7 77OOK **|** CORSAIR 32 GB **|** MSI GTX 1080TI 11GB GAMING X.

**Nvidia Drivers:** 436.15 STANDARD - Game Ready.

**Version of the program:** StaxRip-x64-**2.0.3.0**-stable

**NVEnc Version:** 4.47_x64

**Usage** of CPU & GPU is this:

![Screenshot_4](https://user-images.githubusercontent.com/13344308/64482304-c8415c80-d1c5-11e9-8358-f8595df48219.png)

If you look at the Task Manager it says the GPU usage if about **50%** but if you look at the bottom of the program screen console it says **9%**.

Is there a way i can make the program use **more the GPU and less CPU**?

Thx in advance!

**Comment by rigaya** [comment]
It is normal.

NVEnc mostly uses Video Engine(VE) and not the GPU. You are getting 48% VE utilization on your log, which is nearly maximum you can go with single stream encoding on GTX1080Ti, as you have 2 Video Engines on the chip.

**Comment by ZeroCool22** [comment]
> 
> 
> It is normal.
> 
> NVEnc mostly uses Video Engine(VE) and not the GPU. You are getting 48% VE utilization on your log, which is nearly maximum you can go with single stream encoding on GTX1080Ti, as you have 2 Video Engines on the chip.

Thx!
