### ISSUE TITLE
CRF (Constant Rate Factor) Is it possible to implement it ?

### ISSUE THREAD

**Issue by zerowalkx** [rigaya/NVEnc#149]
CRF (Constant Rate Factor) encode mode

Would it be possible to implement this method additionally ?

thanks so mcuh

**Comment by rigaya** [comment]
You might want to try similar quality based encoding by
```
"--vbrhq 0 --vbr-quality <float>"
```

[--vbr-quality](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vbr-quality-float) takes value between 0.0 - 51.0, you might try it starting from around 25.0.

**Comment by zerowalkx** [comment]
> 
> 
> You might want to try similar quality based encoding by
> 
> ```
> "--vbrhq 0 --vbr-quality <float>"
> ```
> 
> [--vbr-quality](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vbr-quality-float) takes value between 0.0 - 51.0, you might try it starting from around 25.0.

Thanks so much
