### ISSUE TITLE
NVenc: --weightp is not compatible with the new Nvidia driver (387.92)?

### ISSUE THREAD

**Issue by ms4r75** [rigaya/NVEnc#15]
I've updated the Nvidia driver with the last 387.92 and StaxRip stopped working with my encoder setup. 
After some tests, step by step, I found out that the switch "--weightp" is the reason.
I tried with StaxRip 1.7.0 stable and 1.7.0.2 test build.
My configuration:
Intel Core I7 4770k with NVidia GTX1080
Windows 10 Pro 64bit

P.S.
I tried H265 encoding only

Regards

**Comment by rigaya** [comment]
Thank you for your report.

I've been testing with --weightp with 387.92 driver, but seems to have no problem.

```
Y:\QSVTest>x64\NVEncC64_3.23.exe -i sample_movie_1080p.mkv -o test.mp4 -b 0 --weightp

NVEncC (x64) 3.23 (r667) by rigaya, Sep 26 2017 20:51:36 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (15063)
CPU            Intel Core i7-7700K @ 4.20GHz [TB: 4.70GHz] (4C/8T)
GPU            #0: GeForce GTX 1080 (20 EU) @ 1835 MHz (387.92)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
Vpp Filters    copyDtoD
Output Info    H.264/AVC high @ Level auto
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: h264 => mp4
Encoder Preset default
Rate Control   CQP  I:20  P:23  B:25
Lookahead      off
GOP length     240 frames
B frames       0 frames
Ref frames     3 frames, LTR: off
AQ             off
Others         mv:auto cabac deblock adapt-transform:auto weightp

encoded 2293 frames, 103.09 fps, 8553.01 kbps, 97.51 MB
encode time 0:00:22, CPU: 1.3%, GPU: 4.6%, VE: 22.8%, GPUClock: 1853MHz, VEClock: 1663MHz
frame type IDR   10
frame type I     10,  avgQP  20.00,  total size   1.64 MB
frame type P   2283,  avgQP  23.00,  total size  95.87 MB
```

Would you mind showing me the exact command line that Staxrip has generated?

**Comment by ms4r75** [comment]
Can you try also with H265?

**Comment by ms4r75** [comment]
however this is my log with a test file


-------------------------- System Environment --------------------------

StaxRip    : 1.7.0.3
Windows    : Windows 10 Pro 1703
Language   : Italian (Italy)
CPU        : Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
GPU        : NVIDIA GeForce GTX 1080
Resolution : 1920 x 1080
DPI        : 96

------------------------ MediaInfo Source File ------------------------

D:\Download\test.mkv

General
Complete name           : D:\Download\test.mkv
Format                  : Matroska
Format version          : Version 4 / Version 2
File size               : 127 MiB
Duration                : 5 min 2 s
Overall bit rate        : 3 519 kb/s
Writing application     : Lavf57.71.100
Writing library         : Lavf57.71.100
ErrorDetectionType      : Per level 1

Video
ID                      : 1
Format                  : AVC
Format/Info             : Advanced Video Codec
Format profile          : Main@L4.1
Format settings         : CABAC / 2 Ref Frames
Format, CABAC           : Yes
Format, RefFrames       : 2 frames
Codec ID                : V_MPEG4/ISO/AVC
Duration                : 5 min 2 s
Nominal bit rate        : 2 500 kb/s
Width                   : 1 728 pixels
Height                  : 720 pixels
Display aspect ratio    : 2.40:1
Frame rate mode         : Constant
Frame rate              : 23.976 (24000/1001) FPS
Color space             : YUV
Chroma subsampling      : 4:2:0
Bit depth               : 8 bits
Scan type               : Progressive
Bits/(Pixel*Frame)      : 0.084
Writing library         : x264 core 130 r2273
Default                 : Yes
Forced                  : No

Audio #1
ID                      : 2
Format                  : AAC
Format/Info             : Advanced Audio Codec
Format profile          : LC
Codec ID                : A_AAC-2
Duration                : 5 min 2 s
Channel(s)              : 6 channels
Channel positions       : Front: L C R, Side: L R, LFE
Sampling rate           : 48.0 kHz
Frame rate              : 46.875 FPS (1024 SPF)
Compression mode        : Lossy
Delay relative to video : -33 ms
Language                : Italian
Default                 : Yes
Forced                  : No

Audio #2
ID                      : 3
Format                  : AAC
Format/Info             : Advanced Audio Codec
Format profile          : LC
Codec ID                : A_AAC-2
Duration                : 5 min 2 s
Channel(s)              : 6 channels
Channel positions       : Front: L C R, Side: L R, LFE
Sampling rate           : 48.0 kHz
Frame rate              : 46.875 FPS (1024 SPF)
Compression mode        : Lossy
Delay relative to video : -33 ms
Default                 : Yes
Forced                  : No

------------- Demux MKV using mkvextract 16.0.0 pre 01582 -------------

D:\Archivio\Multimedia\StaxRip\Apps\MKVToolNix\mkvextract.exe tracks D:\Download\test.mkv 1:"D:\Download\test_temp\test ID1 -33ms Italian.aac" 2:"D:\Download\test_temp\test ID2 -33ms.aac" --ui-language en

Extracting track 1 with the CodecID 'A_AAC' to the file 'D:\Download\test_temp\test ID1 -33ms Italian.aac'. Container format: raw AAC file with ADTS headers
Extracting track 2 with the CodecID 'A_AAC' to the file 'D:\Download\test_temp\test ID2 -33ms.aac'. Container format: raw AAC file with ADTS headers

Start:    12:12:13
End:      12:12:14
Duration: 00:00:00

General
Complete name         : D:\Download\test_temp\test ID1 -33ms Italian.aac
Format                : ADTS
Format/Info           : Audio Data Transport Stream
File size             : 13.1 MiB
Overall bit rate mode : Variable

Audio
Format                : AAC
Format/Info           : Advanced Audio Codec
Format version        : Version 4
Format profile        : LC
Bit rate mode         : Variable
Channel(s)            : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 13.1 MiB (100%)

------------- Mux AAC to M4A using MP4Box 0.7.2-DEV-rev79 -------------

D:\Archivio\Multimedia\StaxRip\Apps\MP4Box\MP4Box.exe -add "D:\Download\test_temp\test ID1 -33ms Italian.aac:name= " -new "D:\Download\test_temp\test ID1 -33ms Italian.m4a"

AAC ADTS import  - sample rate 48000 - MPEG-4 audio - 6 channels
Setting up iTunes/iPod file...
Saving D:\Download\test_temp\test ID1 -33ms Italian.m4a: 0.500 secs Interleaving

Start:    12:12:14
End:      12:12:14
Duration: 00:00:00


General
Complete name         : D:\Download\test_temp\test ID1 -33ms Italian.m4a
Format                : MPEG-4
Format profile        : Apple audio with iTunes info
Codec ID              : M4A  (isom/M4A /mp42)
File size             : 13.0 MiB
Duration              : 5 min 2 s
Overall bit rate mode : Variable
Overall bit rate      : 362 kb/s
Encoded date          : UTC 2017-10-14 10:12:14
Tagged date           : UTC 2017-10-14 10:12:14

Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : mp4a-40-2
Duration              : 5 min 2 s
Bit rate mode         : Variable
Bit rate              : 361 kb/s
Maximum bit rate      : 436 kb/s
Channel(s)            : 2 channels
Channel(s)_Original   : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 13.0 MiB (100%)
Title                 : 
Encoded date          : UTC 2017-10-14 10:12:14
Tagged date           : UTC 2017-10-14 10:12:14
General
Complete name         : D:\Download\test_temp\test ID2 -33ms.aac
Format                : ADTS
Format/Info           : Audio Data Transport Stream
File size             : 11.0 MiB
Overall bit rate mode : Variable

Audio
Format                : AAC
Format/Info           : Advanced Audio Codec
Format version        : Version 4
Format profile        : LC
Bit rate mode         : Variable
Channel(s)            : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 11.0 MiB (100%)

------------- Mux AAC to M4A using MP4Box 0.7.2-DEV-rev79 -------------

D:\Archivio\Multimedia\StaxRip\Apps\MP4Box\MP4Box.exe -add "D:\Download\test_temp\test ID2 -33ms.aac:name= " -new "D:\Download\test_temp\test ID2 -33ms.m4a"

AAC ADTS import  - sample rate 48000 - MPEG-4 audio - 6 channels
Setting up iTunes/iPod file...
Saving D:\Download\test_temp\test ID2 -33ms.m4a: 0.500 secs Interleaving

Start:    12:12:14
End:      12:12:15
Duration: 00:00:00


General
Complete name         : D:\Download\test_temp\test ID2 -33ms.m4a
Format                : MPEG-4
Format profile        : Apple audio with iTunes info
Codec ID              : M4A  (isom/M4A /mp42)
File size             : 11.0 MiB
Duration              : 5 min 2 s
Overall bit rate mode : Variable
Overall bit rate      : 305 kb/s
Encoded date          : UTC 2017-10-14 10:12:15
Tagged date           : UTC 2017-10-14 10:12:15

Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : mp4a-40-2
Duration              : 5 min 2 s
Bit rate mode         : Variable
Bit rate              : 304 kb/s
Maximum bit rate      : 366 kb/s
Channel(s)            : 2 channels
Channel(s)_Original   : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 10.9 MiB (99%)
Title                 : 
Encoded date          : UTC 2017-10-14 10:12:15
Tagged date           : UTC 2017-10-14 10:12:15

----------------------- Indexing using ffmsindex -----------------------

D:\Archivio\Multimedia\StaxRip\Apps\Plugins\both\ffms2\ffmsindex.exe D:\Download\test.mkv D:\Download\test_temp\test.ffindex

Writing index... done.

Start:    12:12:15
End:      12:12:15
Duration: 00:00:00

--------------------------- AviSynth Script ---------------------------

LoadPlugin("D:\Archivio\Multimedia\StaxRip\Apps\Plugins\both\ffms2\ffms2.dll")
FFVideoSource("D:\Download\test.mkv", colorspace = "YUV420P8", \
              cachefile = "D:\Download\test_temp\test.ffindex")

-------------------------- Script Properties --------------------------

Source Frame Count : 7241
Source Frame Rate  : 23.976024
Source Duration    : 00:05:02.0100000
Target Frame Count : 7241
Target Frame Rate  : 23.976024
Target Duration    : 00:05:02.0100000

----------------------- MediaInfo Audio Source 1 -----------------------

General
Complete name         : D:\Download\test_temp\test ID1 -33ms Italian.m4a
Format                : MPEG-4
Format profile        : Apple audio with iTunes info
Codec ID              : M4A  (isom/M4A /mp42)
File size             : 13.0 MiB
Duration              : 5 min 2 s
Overall bit rate mode : Variable
Overall bit rate      : 362 kb/s
Encoded date          : UTC 2017-10-14 10:12:14
Tagged date           : UTC 2017-10-14 10:12:14

Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : mp4a-40-2
Duration              : 5 min 2 s
Bit rate mode         : Variable
Bit rate              : 361 kb/s
Maximum bit rate      : 436 kb/s
Channel(s)            : 2 channels
Channel(s)_Original   : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 13.0 MiB (100%)
Title                 : 
Encoded date          : UTC 2017-10-14 10:12:14
Tagged date           : UTC 2017-10-14 10:12:14

----------------------- MediaInfo Audio Source 2 -----------------------

General
Complete name         : D:\Download\test_temp\test ID2 -33ms.m4a
Format                : MPEG-4
Format profile        : Apple audio with iTunes info
Codec ID              : M4A  (isom/M4A /mp42)
File size             : 11.0 MiB
Duration              : 5 min 2 s
Overall bit rate mode : Variable
Overall bit rate      : 305 kb/s
Encoded date          : UTC 2017-10-14 10:12:15
Tagged date           : UTC 2017-10-14 10:12:15

Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : mp4a-40-2
Duration              : 5 min 2 s
Bit rate mode         : Variable
Bit rate              : 304 kb/s
Maximum bit rate      : 366 kb/s
Channel(s)            : 2 channels
Channel(s)_Original   : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 10.9 MiB (99%)
Title                 : 
Encoded date          : UTC 2017-10-14 10:12:15
Tagged date           : UTC 2017-10-14 10:12:15

---------------- Error Video encoding using NVEnc 3.23 ----------------

Video encoding using NVEnc 3.23 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Funzione non corretta.


------------------- Video encoding using NVEnc 3.23 -------------------

D:\Archivio\Multimedia\StaxRip\Apps\NVEnc\NVEncC64.exe --vbrhq 3500 --codec h265 --preset quality --level 4.1 --output-depth 10 --weightp --lookahead 32 --aq --vpp-edgelevel --vpp-deband -i D:\Download\test_temp\test_new.avs -o D:\Download\test_temp\test_new_out.h265

NVEncC (x64) 3.23 (r667) by rigaya, Sep 26 2017 20:51:36 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (15063)
CPU            Intel Core i7-4770K @ 3.50GHz [TB: 4.20GHz] (4C/8T)
GPU            #0: GeForce GTX 1080 (20 EU) @ 1809 MHz (387.92)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     Avisynth 2.60(yv12)->p010 [AVX2], 1728x720, 24000/1001 fps
Vpp Filters    copyHtoD
cspconv(p010 -> yv12(16bit))
edgelevel: strength 5.0, threshold 20.0, black 0.0, white 0.0
deband: mode 1, range 15, threY 15, threCb 15, threCr 15
ditherY 15, ditherC 15, blurFirst no, randEachFrame no
cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
1728x720p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        3500 kbps (Max: 19200 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       0 frames
Ref frames     3 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto
cspconv: error at cudaMemcpy2DAsync (convertCspFromNV12(p010 -> yv12(16bit))): unknown error.
Error while running filter "cspconv".
Error cudaEventSynchronize: 30 (cudaErrorUnknown).

------------------- Video encoding using NVEnc 3.23 -------------------

D:\Archivio\Multimedia\StaxRip\Apps\NVEnc\NVEncC64.exe --vbrhq 3500 --codec h265 --preset quality --level 4.1 --output-depth 10 --weightp --lookahead 32 --aq --vpp-edgelevel --vpp-deband -i D:\Download\test_temp\test_new.avs -o D:\Download\test_temp\test_new_out.h265

NVEncC (x64) 3.23 (r667) by rigaya, Sep 26 2017 20:51:36 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (15063)
CPU            Intel Core i7-4770K @ 3.50GHz [TB: 4.20GHz] (4C/8T)
GPU            #0: GeForce GTX 1080 (20 EU) @ 1809 MHz (387.92)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     Avisynth 2.60(yv12)->p010 [AVX2], 1728x720, 24000/1001 fps
Vpp Filters    copyHtoD
cspconv(p010 -> yv12(16bit))
edgelevel: strength 5.0, threshold 20.0, black 0.0, white 0.0
deband: mode 1, range 15, threY 15, threCb 15, threCr 15
ditherY 15, ditherC 15, blurFirst no, randEachFrame no
cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
1728x720p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        3500 kbps (Max: 19200 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       0 frames
Ref frames     3 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto
cspconv: error at cudaMemcpy2DAsync (convertCspFromNV12(p010 -> yv12(16bit))): unknown error.
Error while running filter "cspconv".
Error cudaEventSynchronize: 30 (cudaErrorUnknown).

Start:    12:12:47
End:      12:13:02
Duration: 00:00:14

**Comment by ms4r75** [comment]
this is my line: 
--vbrhq 3500 --codec h265 --preset quality --level 4.1 --output-depth 10 --weightp --lookahead 32 --aq --vpp-edgelevel --vpp-deband

If i try without '--weightp', everything works fine.

**Comment by rigaya** [comment]
Thanks, I was able to reproduce the issue.

I'll check whether this could be avoided by the app, or it is some kind of driver issue and we should wait for driver update.

**Comment by ms4r75** [comment]
Great! Thank you

**Comment by ms4r75** [comment]
New Nvidia driver 388.00, same issue...

**Comment by rigaya** [comment]
Driver 388.13 seems to work out fine, please have a try.

```
Y:\QSVTest>x64\NVEncC64_3.23.exe --vbrhq 3500 -c h265 --preset quality -i sakura_op.mp4 -o test.mp4 --level 4.1 --output-depth 10 --weightp --lookahead 32 --aq --vpp-edgelevel --vpp-deband
NVEncC (x64) 3.23 (r667) by rigaya, Sep 26 2017 20:51:36 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (15063)
CPU            Intel Core i9-7980XE @ 2.60GHz [TB: 4.21GHz] (18C/36T)
GPU            #0: GeForce GTX 1060 6GB (10 EU) @ 1708 MHz (388.13)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     avcuvid: H.264/AVC, 1280x720, 30/1 fps
Vpp Filters    cspconv(nv12 -> yv12(16bit))
               edgelevel: strength 5.0, threshold 20.0, black 0.0, white 0.0
               deband: mode 1, range 15, threY 15, threCb 15, threCr 15
                       ditherY 15, ditherC 15, blurFirst no, randEachFrame no
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
               1280x720p 1:1 30.000fps (30/1fps)
               avwriter: hevc => mp4
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        3500 kbps (Max: 19200 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     300 frames
B frames       0 frames
Ref frames     3 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto

encoded 3501 frames, 260.70 fps, 3259.59 kbps, 45.35 MB
encode time 0:00:13, CPU: 0.7%, GPU: 15.9%, VE: 83.7%, GPUClock: 1834MHz, VEClock: 1650MHz
frame type IDR   25
frame type I     25,  avgQP  19.88,  total size   1.92 MB
frame type P   3476,  avgQP  21.58,  total size  43.43 MB
```

**Comment by ms4r75** [comment]
No, still not working for me. First time it stopped around 5% and secondo time (with video encoding only) at 51.9%.

P.S.
Congratulations for your CPU ^_^
![immagine](https://user-images.githubusercontent.com/5512575/32391024-e4427c64-c0d0-11e7-870f-8b64cf6606dd.png)

**Comment by dmurd** [comment]
harp, this doesn't work for me either. very sad
relevant excerpts from log
---------------- Error Video encoding using NVEnc 3.23 ----------------

Video encoding using NVEnc 3.23 failed with exit code: -1073740791 (0xC0000409)

The exit code might be a system error code: The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.

------------------- Video encoding using NVEnc 3.23 -------------------

E:\Downloads\StaxRip-x64-1.7.0.0-stable\Apps\NVEnc\NVEncC64.exe --cqp 22:24:26 --codec h265 --preset quality --output-depth 10 --weightp --lookahead 30 --sar 16:11 --vpp-edgelevel --cabac --no-deblock -i "\\mediashare\Storage5\films\Spring in a Small Town\Spring-in-a-Small-Town2017-04-2702-25.mkv" -o "\\mediashare\Storage5\films\Spring in a Small Town\Spring-in-a-Sma..._temp\Spring-in-a-Small-Town2017-04-2702-25_new1_out.h265"

NVEncC (x64) 3.23 (r667) by rigaya, Sep 26 2017 20:51:36 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (16299)
CPU            Intel Core i5-7600K @ 3.80GHz [TB: 4.20GHz] (4C/4T)
GPU            #0: GeForce GTX 1080 Ti (28 EU) @ 1683 MHz (388.13)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     avcuvid: MPEG2, 704x576, 25/1 fps
Vpp Filters    cspconv(nv12 -> yv12(16bit))
edgelevel: strength 5.0, threshold 20.0, black 0.0, white 0.0
cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
704x576p 16:11 25.000fps (25/1fps)
Encoder Preset quality
Rate Control   CQP  I:22  P:24  B:26
Lookahead      on, 30 frames, Adaptive I, B Insert
GOP length     250 frames
B frames       0 frames
Ref frames     3 frames, LTR: off
AQ             off
CU max / min   auto / auto
Others         mv:auto

Start:    5:20:14 PM
End:      5:20:52 PM
Duration: 00:00:37

**Comment by alom7** [comment]
I have the same issue. I'm actually able to encode some clips but on many I have the exact same crash while --weightp is enabled. Can't paste the crash log now but I'm on newest build of Win10 x64, encoding on GTX 1060, with staxRip 1.7 and 1.7.0.4.

**Comment by rigaya** [comment]
I'm currently not able to fix this issue, will probably have to disable weightp on HEVC encoding.

**Comment by ms4r75** [comment]
so is it lost forever?

**Comment by pberenyi** [comment]
Hi,

just as an info, 388.31 and GTX 1050 has the same issue with the weightp option.

**Comment by ircopdd** [comment]
NVEncC (x64) 3.23 (r667) by rigaya, Sep 26 2017 20:51:36 (VC 1900/Win/avx2)
OS Version     Windows 7 x64 (7601)
CPU            Intel Core i7-3930K @ 3.20GHz (6C/12T)
GPU            #0: GeForce GTX 1060 6GB (10 EU) @ 1784 MHz (388.31)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     avcuvid: H.265/HEVC, 1280x720, 24000/1001 fps
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main10 @ Level auto
1280x720p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   CQP  I:25  P:28  B:30
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       0 frames
Ref frames     8 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

**Comment by rigaya** [comment]
I was not able to find out what is going wrong with weightp, so unfortunately I decided to disable it on HEVC encoding. (NVEncC 3.25)

You can override this behavior and still use weightp by using "--weightp force", but this is only for testing, and not recommended.

**Comment by rigaya** [comment]
Thank you everyone for sharing the problem, I will merge this issue to #34 , and close this issue.
