### ISSUE TITLE
Psycho-visual options , --psy-rd & --psy-rdoq , are available with NVEncC? 

### ISSUE THREAD

**Issue by zerowalkx** [rigaya/NVEnc#150]
hello, Psycho-visual options , --psy-rd & --psy-rdoq ,are available with NVEncC?  , h264 and h265 ?

https://x265.readthedocs.io/en/default/cli.html#psycho-visual-options

thank you for your reply

**Comment by rigaya** [comment]
No, psycho-visual options are not available for NVENC at this time. There are not available on the NVENC SDK.

**Comment by rigaya** [comment]
I'll close this issue as the topic has been answered.
