### ISSUE TITLE
Burning in 2K Blu-ray .sup with transparency, brightness and contrast for 4K HDR

### ISSUE THREAD

**Issue by pwacooijmans** [rigaya/NVEnc#152]
Dear Rigaya,

Hereby I would like a feature request to add an option to burn in 2K Blu-ray subtitles with Transparency, Brightness and Contrast for 4K HDR.

**Comment by rigaya** [comment]
I think --vpp-subburn can already do 2K to 4K resizing and position adjustment.

However, I don't think "changing" 2K subs to grey value and transparency is possible, because there is no such information on 2K subs, they don't have the data for the "correct" color values you have mentioned. Most 2K subs don't have transparency.

**Comment by pwacooijmans** [comment]
Is it possible to add it...i mean substracting is easy with bdsup2sub but
vica versa is the problem

Op di 17 sep. 2019 15:52 schreef rigaya <notifications@github.com>:

**Comment by rigaya** [comment]
--spp-subburn will automatically compare subtitle resolution to video resolution to set resize ratio and burns in the resized subs. Also it has option "scale=&lt;float&gt;" to specify resize ratio manually.

**Comment by pwacooijmans** [comment]
Ah well was worth a try and an optimal setting that supports most movies?
Also not possible?

Op di 17 sep. 2019 15:54 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
I know what --vpp-subburn does...use it almost every day...it's just about
adding a certain greyscale and transparency to a 2k sup and i'd be very
happy

Op di 17 sep. 2019 17:05 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by rigaya** [comment]
> adding a certain greyscale and transparency to a 2k sup and i'd be very happy

So you just need to modify transparency and brightness, right? The word "correct" was a bit confusing, as no transparency is the original value for 2K subs.

I've added options to modify transparency, brightness and contrast of the subtitles in [NVEnc 4.49](https://github.com/rigaya/NVEnc/releases/tag/4.49). Would this help you?

**Comment by pwacooijmans** [comment]
Yes a lot thx :)

Op wo 18 sep. 2019 15:12 schreef rigaya <notifications@github.com>:

**Comment by pwacooijmans** [comment]
--vpp-subburn filename="D:\Push the Tempo\La La Land (2016) Untouched sample_temp\La La Land (2016) Untouched sample ID4 Dutch.sup",shaping="complex",scale=2.0,transparency=0.1,brightness=-0.3,contrast=0.7

![Transparency 0 1, brightness -0 3, contrast 0 7](https://user-images.githubusercontent.com/30800180/65175036-5f25d880-da52-11e9-9342-43b7e0035b92.png)

Looks very 4k Sup :)....thank you so much and this is really from a 2k Blu-ray :)

**Comment by pwacooijmans** [comment]
Last question I have is it possible to output the new suptitle that I burned in to a .sup file? That would be the most epic solution to actually be able to make 4k.sup files with these settings :)

**Comment by pwacooijmans** [comment]
![Transparency 0 1, Brightness -0 2, Contrast 0 7](https://user-images.githubusercontent.com/30800180/65179455-1c1c3300-da5b-11e9-83fc-aa06f35f2b8a.png)
might be a bit too white but these are the settings:
--vpp-subburn filename="D:\Push the Tempo\La La Land (2016) Untouched sample_temp\La La Land (2016) Untouched sample ID4 Dutch.sup",shaping="complex",scale=2.0,transparency=0.1,brightness=-0.2,contrast=0.7

**Comment by pwacooijmans** [comment]
![Transparency 0 15, Brightness -0 25, Contrast 0,67 Subtitle at 90% resize](https://user-images.githubusercontent.com/30800180/65182099-d2cee200-da60-11e9-9000-b2c1671abf70.png)
--vpp-subburn filename="D:\Push the Tempo\La La Land (2016) Untouched sample_temp\La La Land (2016) Untouched sample ID4 Dutch.sup",shaping="complex",scale=2.0,transparency=0.15,brightness=-0.25,contrast=0.67
at 90% resize with bdsup2sub++

**Comment by pwacooijmans** [comment]
last one is my favorite so far...anyone any better versions than that?

**Comment by pwacooijmans** [comment]
[Templates used.zip](https://github.com/rigaya/NVEnc/files/3628337/Templates.used.zip)

**Comment by djrooli** [comment]
Have you tried to "demux" the .sup first with TSMUXER Nightly? There you can adjust the subtitle.
I always use tsmuxer to make sup from srt then I resize with bdsup2sub then just use subburn, so I can get a yellow desired perfect subtitle with nvenc. I think you can make a script for txmuxer to resize in one go, but I haven't figured it out yet. - Just a thought!

**Comment by rigaya** [comment]
>  is it possible to output the new suptitle that I burned in to a .sup file?

Unfortunately not. I’ll close the issue as the major topic of this issue has been covered.
