### ISSUE TITLE
Burning in original 4K HDR blu-ray sups with the corresponding transparency,brightness and contrast so they look exactly the same.

### ISSUE THREAD

**Issue by pwacooijmans** [rigaya/NVEnc#153]
Dear Rigaya,

Feature request number 10002, can you make it possible to burn in original 4K HDR blu-ray suptitles with there corresponding transparency,brightness and contrast? simply by adding a command hdrsubtitle? so they look exactly the same? You can check how it looks in HDR with mpc-be mediaplayer. It simulates HDR on normal none HDR monitors.

**Comment by pwacooijmans** [comment]
https://drive.google.com/drive/folders/1gN7u1F1lp-ldLHQjXXTpDcMOlwoigQZU?usp=sharing
hereby a link with the tools used to compare between the 2 and see that it's much too bright etc etc after burning in.

**Comment by rigaya** [comment]
So why not you adjust them using transparency, brightness and contrast options I just added?

**Comment by pwacooijmans** [comment]
That was only ment for 2k for original 4k sups it should be copy paste for
the values

Op vr 20 sep. 2019 14:07 schreef rigaya <notifications@github.com>:

**Comment by rigaya** [comment]
I'm sorry but I don't get what you mean. If you think it's too bright, then you can use negative values for "brightness". Those options aren't only for 2K subs,

**Comment by pwacooijmans** [comment]
Whats the point in adjusting a 4k original sup when its perfect already?

Op vr 20 sep. 2019 14:20 schreef rigaya <notifications@github.com>:

**Comment by pwacooijmans** [comment]
I am just looking for the option to make them look the same 4k hdr
compressed or not

Op vr 20 sep. 2019 14:22 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
Cause this way there are 100x100x100 options its a bit hard te find the
right one

Op vr 20 sep. 2019 14:24 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
And its not like i have to do this 1 time only but 500+ times a year

Op vr 20 sep. 2019 14:26 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by rigaya** [comment]
> Whats the point in adjusting a 4k original sup when its perfect already?

Didn't you just say it's too bright? If it's perfect, then just leave it default, --vpp-subburn is burning the sup just like it is coded in it.

**Comment by pwacooijmans** [comment]
The point is its not...just check the google link i posted and check
oblivion uhd sample and oblivion uhd sample new

Op vr 20 sep. 2019 14:42 schreef rigaya <notifications@github.com>:

**Comment by pwacooijmans** [comment]
Its not burning in suptitles like its coded cuz the suptitles are different
in brightness contrast and transparency

Op vr 20 sep. 2019 14:47 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
You can check this easily with mpc-be

Op vr 20 sep. 2019 14:50 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
[MPC-BE.1.5.3.x64-installer.zip](https://github.com/rigaya/NVEnc/files/3635967/MPC-BE.1.5.3.x64-installer.zip)

**Comment by rigaya** [comment]
> Its not burning in suptitles like its coded cuz the suptitles are different

I think burning in the subtitles as coded is what --vpp-subburn shall do. Also, I don't know why it is different after burning in with --vpp-subburn, so I won't be able to implement the conversion you expect.

**Comment by pwacooijmans** [comment]
Well I am no programmer so can't help you with that sorry, however thx a
lot for your time.

Op vr 20 sep. 2019 om 15:16 schreef rigaya <notifications@github.com>:

**Comment by rigaya** [comment]
I’ll close the issue as vpp-sub urn shall be working fine.
