### ISSUE TITLE
Spline16 resizing produces slice-like artifacts

### ISSUE THREAD

**Issue by sneaker2** [rigaya/NVEnc#154]
Hi,

I'm seeing "slice-like" artifacts when using the Spline16 resizer. The number of slices seems to be depending on the (target) resolution. When resizing 3840x1714 -> 1920x858 I see 4 horizontal "slices". The second and fourth slices seem a lot sharper than the other two slices. Also, there is some distortion as if the slices are slightly moved. Look at e.g. the lower teeth of the woman.

I'm using a GTX 1660 Ti on Windows 7 x64 with Nvidia driver 436.30.

Sample files, screenshots, logs:
[https://mega.nz/#F!9lUxjY6T!T3vg_krpGRyXa-6JKUpsiA](https://mega.nz/#F!9lUxjY6T!T3vg_krpGRyXa-6JKUpsiA)

**Comment by rigaya** [comment]
Thank you for letting me know about the artifact, actually one of the factor for spline16 was set wrong. Now should be fixed on [NVEnc 4.50](https://github.com/rigaya/NVEnc/releases/tag/4.50).

**Comment by rigaya** [comment]
I'll close this issue, as this issue should have been fixed. Please re-open if you have related issues.
