### ISSUE TITLE
Frame count ?  can we have this in the cmd information bar please.

### ISSUE THREAD

**Issue by zerowalkx** [rigaya/NVEnc#155]
hello rigaya 

 it would be possible to please add this information about the Frames Count,

Thank you very much.

BTW:  the latest version says 4.50 but when you download it is 4.49 you have to change this, thanks
https://github.com/rigaya/NVEnc/releases

![Sin título](https://user-images.githubusercontent.com/54515635/65558276-b1a44080-defb-11e9-8f46-46a7bf30025b.jpg)
![nv](https://user-images.githubusercontent.com/54515635/65558277-b1a44080-defb-11e9-9b55-cf60491852c8.jpg)

**Comment by rigaya** [comment]
Feature added in [NVEnc 4.51](https://github.com/rigaya/NVEnc/releases/tag/4.51). Please note that total frame number is not available in some readers.

![image](https://user-images.githubusercontent.com/815947/66321608-cea92c80-e95b-11e9-9406-185e50fc1b0e.png)

**Comment by rigaya** [comment]
I'll close this issue, as this feature has been added.
