### ISSUE TITLE
non-mod2 crop values resulting to mod2 picture

### ISSUE THREAD

**Issue by kusingen** [rigaya/NVEnc#156]
Hi.
I have 4k source with height of 1606px that I want to downsize to 1080p. Simple calculation says target height is 803. That is unsupported - it's not mod2. Making it 802 or 804 is possible but resizing that way will produce too many picture changes to my liking.
I tried to crop 0,1,0,1 (I find it better to loose 1 line from top and bottom and resize nicely by factor of 2) but that is unsupported as well - every crop value has to be mod2. Why?
Why is it not good enough if the resulting picture has mod2 dimensions? This way I could crop to 1604 and downsize to 802.
THX for explanation.

**Comment by rigaya** [comment]
When we think about YUV420 format, chroma pixels has only half the resolution. Therefore when you think of cropping 1 luma pixel, it's like cropping 0.5 chroma pixels, which is not available.

**Comment by kusingen** [comment]
:) didn't see that coming...
