### ISSUE TITLE
H.265/HEVC isn't supported by the graphics card. (I have a 1080 TI)

### ISSUE THREAD

**Issue by ZeroCool22** [rigaya/NVEnc#158]
**PC Specs:**

I7 77OOK **|** CORSAIR 32 GB **|** MSI GTX 1080TI 11GB GAMING X.

**Nvidia Drivers:** 436.15 STANDARD - Game Ready.

**Version of the program:** StaxRip-x64-**x64-2.0.4.4-beta

**NVEnc Version:** 4.50_x64

![Screenshot_7](https://user-images.githubusercontent.com/13344308/65649921-ec32d980-dfde-11e9-8926-b592e5f6ac2a.png)

I only have this problem when use a version of NVEnc above of **4.48** x64, with 4.48 everything works fine:

![Screenshot_8](https://user-images.githubusercontent.com/13344308/65650253-74fe4500-dfe0-11e9-97a4-df6397a0b19d.png)

Full Log: https://pastebin.com/0pip7jqi

**Comment by rigaya** [comment]
The major change which might cause your issue is the change in the build, but I'm not sure as current build works fine on my system.

I've created another build for NVEnc 4.50 ([NVEncC_4.50v2_x64.7z](https://github.com/rigaya/NVEnc/releases/tag/4.50)), does this work for you?

**Comment by ZeroCool22** [comment]
> 
> 
> The major change which might cause your issue is the change in the build, but I'm not sure as current build works fine on my system.
> 
> I've created another build for NVEnc 4.50 ([NVEncC_4.50v2_x64.7z](https://github.com/rigaya/NVEnc/releases/tag/4.50)), does this work for you?

Thx you very much for take the time to help me, i don't know what happened but now it works, maybe because i was using StaxRip Stable and Beta version to make comparisions of speed etc...

Now i'm just using, StaxRip-x64-**2.0.4.4-beta** and **NVEnc 4.50**.

**Comment by rigaya** [comment]
I'm glad to know it now works. I'll close this issue.

**Comment by Patman86** [comment]
> 
> 
> > The major change which might cause your issue is the change in the build, but I'm not sure as current build works fine on my system.
> > I've created another build for NVEnc 4.50 ([NVEncC_4.50v2_x64.7z](https://github.com/rigaya/NVEnc/releases/tag/4.50)), does this work for you?
> 
> Thx you very much for take the time to help me, i don't know what happened but now it works, maybe because i was using StaxRip **Stable** and **Beta** versions to make comparisions of speed etc... and maybe that cause some conflicts. (?)
> 
> Now i'm just using, StaxRip-x64-**2.0.4.4-beta** and **NVEnc 4.50**.

One question. Which version of NVEnc do you use now? Normal or v2?
