### ISSUE TITLE
4.50 (both v1 and v2): wrong version number in exe

### ISSUE THREAD

**Issue by gnucian** [rigaya/NVEnc#159]
This is a small cosmetic issue, but the 64bit exe file shows a wrong version number when it's run.

![NVEnc_4 50_wrong_version_info](https://user-images.githubusercontent.com/3157518/65839888-68bb0600-e2c6-11e9-8814-eb5d2ebfa114.jpg)
<4.50 v1>

![NVEnc_4 50v2_wrong_version_info](https://user-images.githubusercontent.com/3157518/65839893-78d2e580-e2c6-11e9-98d5-7945ff3517ae.jpg)
<4.50 v2>

Thanks.

**Comment by rigaya** [comment]
Thanks for letting me know, [NVEnc 4.51](https://github.com/rigaya/NVEnc/releases/tag/4.51) shall show "4.51" as expected.
