### ISSUE TITLE
GPU / VE  (44%, 20%) (low usage, not at maximum)???

### ISSUE THREAD

**Issue by zerowalkx** [rigaya/NVEnc#160]
Hi, rigaya

It's normal that you don't use 100% on the GPU and the VE ? I mean it's normal that this varies a lot ? sometimes it's 50% sometimes it's more and less, on other occasions.etc,  is there any way to control this or depends on the video source ?

or I need to activate some option, and accelerate to use 100 % or as close to this maximum speed ?

For example in Avisynth+ I have to add at the end in the script:
Prefetch(16)  

with this option in Avisynth+ I can use the 16 threads that my processor has, it uses 100% of the capacity of the processor. and the encoding is finished much faster.

Here in NVEncC we have to activate some option to increase the speed and use 100% of the GPU and VE ?

![Sin título](https://user-images.githubusercontent.com/54515635/65856075-41942100-e326-11e9-95a6-4c10623a7afe.jpg)

Thank you very much for your help

**Comment by rigaya** [comment]
Most of the time, especially for encoding a video smaller than fullHD (1920x1080), it is quite difficult to achieve 100% VE usage using Avisynth input, and usually requires hardware decoding to be enabled.

This can be used by using "--avhw" option and directly setting the target video file as input. If you require video editing by Avisynth+, it'll be difficult to fully utilize the VE.

**Comment by zerowalkx** [comment]
> Most of the time, especially for encoding a video smaller than fullHD (1920x1080), it is quite difficult to achieve 100% VE usage using Avisynth input, and usually requires hardware decoding to be enabled.
> 
> This can be used by using "--avhw" option and directly setting the target video file as input. If you require video editing by Avisynth+, it'll be difficult to fully utilize the VE.

As I understand your answer is better to use the option --avhw as input directly, and not to use the Avisynth ? 

could you please make an example of how it would be :

Thanks for your help

**Comment by iykkim** [comment]
Just FYI.
I'm also doing lot of encoding with nvencc64 as situation below;

- Mpeg2 FullHD source to HEVC FullHD
- H.264 FullHD source to HEVC FullHD
- HEVC 4K source to HEVC 4K: In this case, I only decrease video bitrate around to 30 Mbps from 4K bluray rip source for decrease size and keep exact same quality as ripped source.

VE utilization and encoding fps that I experiencing are;
- Mpeg2 to HEVC FullHD: About 45%, 240 fps
- H.264 to HEVC FullHD: About 45%, 140 fps
- HEVC to HEVC 4K: About 45%, 69 fps

When I doing dual encoding ( you know, Nvidia GTX has dual nvenc encode chipset so it can run 2 encode jobs simultaneously ) then;
- Mpeg2 to HEVC FullHD: About 85%, 210 fps
- H.264 to HEVC FullHD: About 85%, 130 fps
- HEVC to HEVC 4K: About 85%, 58 fps

It's my assumption that VE utilization showing for overall of nvenc chipset usage so if you just doing single encoding then it will not over 50% as it will use only one nvenc encode chipset of GTX adapter.
And I also agree to rigaya's reply above as it will not use all 100% for encode only.
And Nvidia GTX adapter seems utilize enough of nvenc chipset resource when encoding.

I'm not a technical expert of Nvidia so just can say in my experience and I think more technical answer can be done by Nvidia support/forum...

**Comment by pwacooijmans** [comment]
Secondly your graphics card does NOT support B-frames so you better set bframes to 0.
Third ref can't be 0.
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix#Encoder
here a link to check weather your card supports b frames or not.

**Comment by Demicro** [comment]
This happens to me when both the Intel and Nvidia GPUs are active. For example, when using a laptop with the integrated screen, NVENC does not show any GPU activity. However, when I connect the HDMI and the laptop uses the Nvidia GPU for the display instead of the Intel one, it does show GPU activity during encoding.

**Comment by rigaya** [comment]
I'll close this issue as [I have already answered](https://github.com/rigaya/NVEnc/issues/160#issuecomment-536592755) for this topic.
