### ISSUE TITLE
SMDegrain, QTGMC, TFM , NNEDI3,  (CUDA versions) = please add in NVEncc 

### ISSUE THREAD

**Issue by zerowalkx** [rigaya/NVEnc#161]
Hi rigaya 👍 

You could implement SMDegrain, QTGMC , TFM , NNEDI3, these plugins are very popular and give high quality results in Avisynth, they were already passed to CUDA so you wouldn't have to work much (I could be wrong).

You could include them in NVEncC, the results are very high quality and very good. and that is what is always used in Avisynth.

The user and the project is also in Japanese so it will be easier for you to understand if you see for yourself here I leave the link:

https://github.com/nekopanda/AviSynthCUDAFilters

https://github.com/nekopanda/AviSynthCUDAFilters/releases

With this it would be very good and we would not have to use Avisynth Almost never . Since the Plugins or Scripts most used in Avisynth are QTGMC , TFM, NNEDI3, and SMDegrain , They were already passed to CUDA , It would be ideal to include it in NVEncc, and it would help us a lot.

please add in NVEncc.

Thank you very much for your help

**Comment by rigaya** [comment]
Currently NVEncC has nnedi3 for deinterlace(--vpp-nnedi) only. Porting the other filters are not so easy, even if there are source code of CUDA. Actually, --vpp-nnedi took for month to re-implement.

The other filters are more large and complicated filters, and in addition some of them are a mixture of some more filters. For example, SMDegrain, QTGMC uses MVTools, which is a combination of many filters.

Although I understand it would be nice to have them in NVEncC as you have said, it would take so much time to implement, so I would prefer using them simply from Avisynth.

**Comment by zerowalkx** [comment]
> 
> 
> Currently NVEncC has nnedi3 for deinterlace(--vpp-nnedi) only. Porting the other filters are not so easy, even if there are source code of CUDA. Actually, --vpp-nnedi took for month to re-implement.
> 
> The other filters are more large and complicated filters, and in addition some of them are a mixture of some more filters. For example, SMDegrain, QTGMC uses MVTools, which is a combination of many filters.
> 
> Although I understand it would be nice to have them in NVEncC as you have said, it would take so much time to implement, so I would prefer using them simply from Avisynth.

if implemented in NVencc, would it increase the encoding speed ? or would it be the same as using them through Avisynth ?

**Comment by rigaya** [comment]
if implemented in NVencc, there is a chance to to get better performance as it would be able to use hardware decoder if possible. However, it shall be difficult to be a noticeable improvement, as those filters, especially QTGMC and NNEDI3, are rather heavy filters, and the effect of decoding will be very small.

**Comment by rigaya** [comment]
I'll close this issue, as these can be used via avs reader, and will be difficult for me to have time implement all these filters for NVEncC.

**Comment by rainman74** [comment]
Finally QTGMC is implemented! 🙏🙏🙏
