### ISSUE TITLE
Encoding Software, GUi... for NVENC

### ISSUE THREAD

**Issue by zerowalkx** [rigaya/NVEnc#163]
Hi. rigaya How are you?

Please,  can you recommend me some GUI for the NVENC encoder 

the following programs use NVEnc :

- StaxRip
- Vidcoder
- Handbrake
- Hybrid 
- Simple x264/x265 Launcher
- MediaCoder
- xMedia Recode
- XviD4PSP
- And many more... 

Do you know any other program that has NVEnc GUI? 

Maybe you can make one for all users, that way your program would be massively used by many people and maybe over time you can make some money.

Thanks for your help

**Comment by rigaya** [comment]
I don't know much about GUIs, I think NVEncC is used from StaxRip or Hybrid.

For Japanese video editing software [Aviutl](http://spring-fragrance.mints.ne.jp/aviutl/). I already have a GUI for NVEncC as it's plugin. (That is NVEnc.auo, actually included in this repository)

![image](https://user-images.githubusercontent.com/815947/66491731-342d2280-eaee-11e9-9e45-06ca269b6880.png)

There are no more plan for any other GUI by myself, neither English version of NVEnc.auo. Unfortunately, I just don't have more time, as I can only work on these mainly on weekends. Moreover. I want work with not only NVEnc, but also [QSVEnc](https://github.com/rigaya/QSVEnc) and [VCEEnc](https://github.com/rigaya/VCEEnc).

**Comment by rigaya** [comment]
I'll close this issue as the topic has been answered.
