### ISSUE TITLE
Element at ??? ending at ??? exceeds containing master element ending at ???

### ISSUE THREAD

**Issue by patpatqu** [rigaya/NVEnc#165]
I always get an error message at the end of each encoding:

[matroska,webm @ 000001b626fe86c0] Element at 0x1e9e37ba3 ending at 0x1e9e4494a exceeds containing master element ending at 0x1e9e37b9c

The output video seems fine BTW!

**Comment by rigaya** [comment]
It seems to be the [message from matroska demuxer (libavformat)](https://www.mail-archive.com/ffmpeg-user@ffmpeg.org/msg21735.html).

If you see nothing wrong at the end of the video, I think I can just leave it as it is, until I update the libavformat dll.

**Comment by rigaya** [comment]
I've updated libavformat.dll in [NVEnc 4.60](https://github.com/rigaya/NVEnc/releases/tag/4.60), now I see no error message anymore.

**Comment by patpatqu** [comment]
Fixed, and thank you for your attention!

**Comment by rigaya** [comment]
Thanks you for confirming, I'll close this issue.
