### ISSUE TITLE
Video after Encoding ist wrong, if Video is black at the beginning

### ISSUE THREAD

**Issue by Alci09** [rigaya/NVEnc#167]
If i encode a video which is purly black at the beginning for example 5 seconds, the result length of the output video is 5 seconds shorter. The output video just starts at the position where the video is the first time not black. Seems that samething trims the blacks at the beginning. The result is then also out of sync with the audio by 5 seconds.

Using a nvidia geforce 1070 with driver 436.48. Input material was a 1080p hevc hdr video, which i wanted to convert to a 1080p hevc SDR version.

**Comment by rigaya** [comment]
I'm finding this issue difficult to solve, as there is no implementation intended to skip black beginning, and I haven't gone through such problems.

There might be some patterns in the timestamp which the app does not expect.

**Comment by schm0** [comment]
I have the same problem with some files.
I try to encode from h264 to h264.
The resulting file is 5 sec shorter causing an audio desync.
But the desync starts to occur at the middle of the file.

**Comment by rigaya** [comment]
> Big Gap was found between 2 frames, avsync might be corrupted

This shows some unexpected timestamp are there (might be corrupted as you have said) in the input file. Might be difficult to check without the input file.

**Comment by Noisrevid** [comment]
I get this issue when using the NVEnc Hardware Decoder..    have to switch to AviSynth to make sure it doesn't happen..    It didn't happen in prior versions it seems but recently it seems to mess up my encodes if there is "blank" video (fully black intros) in my movies.

**Comment by rigaya** [comment]
Adding --timestamp-passthrough can change this behavior.

I’ll have this issue closed.
