### ISSUE TITLE
3D MVC encoding with NVenc ?

### ISSUE THREAD

**Issue by mansonreznor** [rigaya/NVEnc#168]
Hello, 

I need the MVC hardware of Nvenc. Does rigaya Nvenc support it ?
It is possible to "activate" or add this functionality ?

My project is to recode 3D Bluray using full Nvenc decode / encode.

Thanks

**Comment by rigaya** [comment]
I'm sorry, but  I have no plan to support MVC encoding at this time.

**Comment by djrooli** [comment]
mansonreznor: you can use Frim64 alongside with NVEnc, but you get the stereo 3D output.
You can archieve the 2 x Full HD (2K) resolution supported by PC media players, but as you use the Nvidia card for the conversion, you need high bitrate to keep quality, so the size of your output video will not be much smaller. For MVC, I recommend DVDFab (paid software).

**Comment by wcapes** [comment]
Can you please reconsider support for MVC, there are users out there that use this format and would appreciate support, otherwise thanks for the time and efforts

**Comment by rigaya** [comment]
I'm sorry, but I have no plan to support this.
