### ISSUE TITLE
Nvidia Encode H264 at 5K or above 

### ISSUE THREAD

**Issue by tabnk** [rigaya/NVEnc#170]
General H264 Profile spec support resolution higher than 4K. For example H 264 Profile Level 6.0, 6.1 and 6.2 can go up to 8,192×4,320@60 FPS.

Is there a way for NVEnc encode above that ?

**Comment by warrex1979** [comment]
The maximun resolution NVEnc supports for H264 is 4096x4096. For HEVC Pascal and Turing can go up to 8192x8192.

Just launch NVEncC with the "--check-features" option to see what features your device supports.

**Comment by hydra3333** [comment]
Hello.  Fantastic product !!
I have a 2060 Super.  
Just checking, is the NVEnc tool capable of encoding at 8192x8192 using the 2060 ?

**Comment by rigaya** [comment]
> Just checking, is the NVEnc tool capable of encoding at 8192x8192 using the 2060 ?

Yes, I think you are right, as [the driver says so](https://github.com/rigaya/NVEnc/blob/master/GPUFeatures/rtx2060.txt).

There are no software limitations, but you might hit limitation of your RAM of the system or the GPU RAM size, as 8K is really big in frame size.

**Comment by hydra3333** [comment]
OK, Thank You.
No doubt you are right; my not having done any calcs - it's a lowly 8Gb model :( so with 32Gb system RAM and 64 fixed swapfile we'll know for sure when the day comes to try it :)

**Comment by rigaya** [comment]
I've tested before with 8K in 8GB GPU RAM([please check this link](https://github.com/rigaya/NVEnc/issues/127#issuecomment-499110640)), and it worked out fine (but was very slow).

If you are using lookahead, please try without it, as the lookahead option eats too much memory.

**Comment by hydra3333** [comment]
Thank you for the link https://github.com/rigaya/NVEnc/issues/127#issuecomment-499110640

> encoded 995 frames, 0.50 fps, 46363.95 kbps, 229.37 MB

My goodness, 1/2 an fps encoding 8k on a GeForce RTX 2070 gpu ?  
For H.265/HEVC circa 1,000 frames @ 230Mb which I make out to be about 19,852 Mb per hour :)   
It'd have to be a really really really over the top documentary for that to be worth my while :D

I reckon I won't rush to purchase an 8k telly !

**Comment by rigaya** [comment]
I'll close this issue, as the first question has been answered.
