### ISSUE TITLE
Multi Level L1 references automatically leads to error

### ISSUE THREAD

**Issue by Starkler** [rigaya/NVEnc#171]
Hello Rigaya!

The usage of Multi Level L1 references automatically leads to error. IT does not work.

However  Multi Level L0 references works, it can even achieve a very little gain in quality.

Can you fix the Multi-Level L1 references?

Thank you!

**Comment by rigaya** [comment]
Hello, could you let me know the options you're using and the error(s) you're getting?

I'm fine on RTX2070 with the options below for example.

NVEncC64.exe --avhw -i input.ts -o ouput.265 -c hevc --ref 6 --multiref-l0 5 --multiref-l1 4

**Comment by Starkler** [comment]
> 
> 
> Hello, could you let me know the options you're using and the error(s) you're getting?
> 
> I'm fine on RTX2070 with the options below for example.
> 
> NVEncC64.exe --avhw -i input.ts -o ouput.265 -c hevc --ref 6 --multiref-l0 5 --multiref-l1 4

Hello!

Here are the screenshot of the options :

https://i.ibb.co/23RsXBs/k-p.png

**Comment by rigaya** [comment]
Thanks for the screenshot.

In the screen shot, it looks like the option is set as "--multiref-l 7", however it should be "--multiref-l**1** 7".

**Comment by Starkler** [comment]
Thank you! I tried it, it worked with the corrected "--multiref-l1 7" tag. However what is the difference between L0 references and L1 references? Which is better quality?

**Comment by rigaya** [comment]
Glad to hear it now works. About L0/L1 multiref, I also know little about it.

Below is reffered from [the quotes in NVENC SDK](https://github.com/rigaya/NVEnc/blob/master/NVEncSDK/Common/inc/nvEncodeAPI.h#L1406) (and it does not say much).

**numRefL0**
_Specifies max number of reference frames in reference picture list L0, that can be used by hardware for prediction of a frame._ 

**numRefL1**
_Specifies max number of reference frames in reference picture list L1, that can be used by hardware for prediction of a frame._

**Comment by Starkler** [comment]
> 
> 
> Glad to hear it now works. About L0/L1 multiref, I also know little about it.
> 
> Below is reffered from [the quotes in NVENC SDK](https://github.com/rigaya/NVEnc/blob/master/NVEncSDK/Common/inc/nvEncodeAPI.h#L1406) (and it does not say much).
> 
> **numRefL0**
> _Specifies max number of reference frames in reference picture list L0, that can be used by hardware for prediction of a frame._
> 
> **numRefL1**
> _Specifies max number of reference frames in reference picture list L1, that can be used by hardware for prediction of a frame._

Hi!

As I see in the SDK, many of the options were not implemented in Nvencc and in the  FFMPEG NVENC yet.
For example Force intra option. Can you put it to Nvencc ?

Thank you!

**Comment by rigaya** [comment]
> As I see in the SDK, many of the options were not implemented in Nvencc and in the FFMPEG NVENC yet.

Unfortunately, I'm not adding all the options SDK provides, as that will be too much of work, and some of them are difficult to use (some requires advanced knowledge about the specific codecs).

> For example Force intra option. Can you put it to Nvencc ?

Do you mean you want to force to insert keyframe? That could be done by [--keyfile](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--keyfile-string) option.

Or if you mean intra refresh related options, I have not add those as I thought they are not required for this app, as main target of intra refresh is to minimize encoding latency, which I'm not focusing on this app.

**Comment by dixie-flatliner** [comment]
With bframes and any bref-mode enabled, setting multiref-l0 above six or multiref-l1 above two results in a driver hang on my GTX 1660 Super. This makes sense to me, as according to the x265 documents (https://x265.readthedocs.io/en/default/cli.html), a) a conformant HEVC stream can have a maximum of 8 l0 references, b) enabling bframes adds 1 ref to the list of l0 references, and c) using bframes as references (which x265 calls --b-pyramid) adds another, and 6+2=8 after all. 

Presumably this also means the maximum number of l1 refs is four, but I'd have to dig through the HEVC specification to find out.

Would it be possible to add a mechanism to prevent the total number of l0/l1 refs from rising above 8/4 total? I can remember to avoid bad settings without issue, but I could see it being a big problem for less experienced users.

**Comment by rigaya** [comment]
Thanks for letting me know the issue and the proposal, [NVEnc 4.56](https://github.com/rigaya/NVEnc/releases/tag/4.56) will now check the value depending on the B frame and bref-mode settings.

**Comment by dixie-flatliner** [comment]
Glad I was useful!

**Comment by rigaya** [comment]
I'll close this issue as the main topic has been resolved. Thanks you for the discussions here.
