### ISSUE TITLE
NVEncC64.exe has stopped working after the last nvidia driver update.

### ISSUE THREAD

**Issue by Kapiroto** [rigaya/NVEnc#173]
PS C:\Users\Kapiroto> NVEncC64.exe --check-features
This error might occur when shortage of memory, or when trying to encode more than 2 streams by NVEnc.
In Geforce, simultaneous encoding is limited up to 2, due to the NVIDIA's driver limitation.
Error on NvEncOpenEncodeSessionEx(device_type=NV_ENC_DEVICE_TYPE_CUDA): 10 (NVENC indicates that the API call failed because it was unable to allocate enough memory to perform the requested operation.)
NVEncC (x64) 4.55 (r1224) by rigaya, Nov  5 2019 15:40:51 (VC 1916/Win/avx2)
  [NVENC API v9.1, CUDA 10.1]
 reader: raw, avi, avs, vpy, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4]
This error might occur when shortage of memory, or when trying to encode more than 2 streams by NVEnc.
In Geforce, simultaneous encoding is limited up to 2, due to the NVIDIA's driver limitation.
Error on NvEncOpenEncodeSessionEx(device_type=NV_ENC_DEVICE_TYPE_CUDA): 10 (NVENC indicates that the API call failed because it was unable to allocate enough memory to perform the requested operation.)

Environment Info
OS : Windows 10 x64 (18363)
CPU: Intel Core i7-4790K @ 4.00GHz [TB: 4.40GHz] (4C/8T)
RAM: Used 7366 MB, Total 16324 MB
GPU: #0: GeForce GTX 1080 Ti (3584 cores, 1670 MHz)[PCIe3x16][441.20]

No NVEnc support.
PS C:\Users\Kapiroto>

**Comment by rigaya** [comment]
I've tested 441.20, but worked out fine.

NVEncC (x64) 4.56 (r1236) by rigaya, Nov 18 2019 21:42:40 (VC 1923/Win/avx2)
  [NVENC API v9.1, CUDA 10.1]
 reader: raw, avi, avs, vpy, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4]
Loaded nvEncodeAPI64.dll.
InitCuda: device #0.

Checking Environment Info...
NVEncC (x64) 4.56 (r1236) by rigaya, Nov 18 2019 21:42:40 (VC 1923/Win/avx2)
OS Version     Windows 10 x64 (18362)
CPU            AMD Ryzen 7 3700X 8-Core Processor (8C/16T)
gpuinfo: found nvcuda.dll.
gpuinfo: cuInit(0): success.
gpuinfo: cuvidInit(0): success.
gpuinfo: Found 1 CUDA device(s).
gpuinfo: checking for device #0.
gpuinfo:   cuDeviceGet: success
gpuinfo:   cudaDeviceGetAttribute: CUDA 6.1
gpuinfo:   PCIBusId: 0000:0C:00.0
gpuinfo:   Got GPU Info from NVML.
gpuinfo:   NV Driver version: 441200.
gpuinfo:   CUDA Driver version: 10020.
gpuinfo:   getHWDecCodecCsp
GPU            #0: GeForce GTX 1080 (441.20)
NVENC / CUDA   NVENC API 9.1, CUDA 10.2, schedule mode: auto
cuInit: Success.
cuDeviceGetCount: Success.
cuDeviceGet: ID:0.
cuDeviceComputeCapability: Success: 6.1.
NVENC capabilities: OK.
using cuda schedule mode: auto.
cuCtxCreate: Success.
cuCtxPopCurrent: Success.
cuvidInit: Success.
cuvidCtxLockCreate: Success.
InitCuda: Success.
nvEncodeAPICreateInstance(APIVer=0x71020009): Success.
NvEncOpenEncodeSessionEx(device_type=NV_ENC_DEVICE_TYPE_CUDA): Success.
nvEncDestroyEncoder: success.
Closing perf monitor...
Avaliable Codec(s)
H.264/AVC
H.265/HEVC


One difference might be OS version? (I have not yet updated to 1909).

**Comment by Kapiroto** [comment]
Maybe that is the problem. Yesterday I upgraded to OS to 1909. I will reinstall the Nvidia driver using DDU to see if I have results.

**Comment by Kapiroto** [comment]
Apparently it was some bug. After reinstalling the driver and restarting Windows, it returned to normal.
Thanks.

PS C:\Users\Kapiroto> NVEncC64.exe --check-features
NVEncC (x64) 4.55 (r1224) by rigaya, Nov  5 2019 15:40:51 (VC 1916/Win/avx2)
  [NVENC API v9.1, CUDA 10.1]
 reader: raw, avi, avs, vpy, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4]

Environment Info
OS : Windows 10 x64 (18363)
CPU: Intel Core i7-4790K @ 4.00GHz [TB: 4.40GHz] (4C/8T)
RAM: Used 5954 MB, Total 16324 MB
GPU: #0: GeForce GTX 1080 Ti (3584 cores, 1670 MHz)[PCIe3x16][441.20]

List of available features.
Codec: H.264/AVC
Max Bframes               4
B Ref Mode                yes
RC Modes                  63
Field Encoding            yes
MonoChrome                no
FMO                       no
Quater-Pel MV             yes
B Direct Mode             yes
CABAC                     yes
Adaptive Transform        yes
Max Temporal Layers       0
Hierarchial P Frames      no
Hierarchial B Frames      no
Max Level                 51
Min Level                 1
4:4:4                     yes
Min Width                 33
Max Width                 4096
Min Height                17
Max Height                4096
Multiple Refs             no
Max LTR Frames            8
Dynamic Resolution Change yes
Dynamic Bitrate Change    yes
Forced constant QP        yes
Dynamic RC Mode Change    no
Subframe Readback         yes
Constrained Encoding      yes
Intra Refresh             yes
Custom VBV Bufsize        yes
Dynamic Slice Mode        yes
Ref Pic Invalidiation     yes
PreProcess                no
Async Encoding            yes
Max MBs                   65536
Lossless                  yes
SAO                       no
Me Only Mode              yes
Lookahead                 yes
AQ (temporal)             yes
Weighted Prediction       yes
10bit depth               no

Codec: H.265/HEVC
Max Bframes               0
B Ref Mode                no
RC Modes                  63
Field Encoding            no
MonoChrome                no
Quater-Pel MV             yes
B Direct Mode             no
Max Temporal Layers       0
Hierarchial P Frames      no
Hierarchial B Frames      no
Max Level                 62
Min Level                 1
4:4:4                     yes
Min Width                 65
Max Width                 8192
Min Height                33
Max Height                8192
Multiple Refs             no
Max LTR Frames            7
Dynamic Resolution Change yes
Dynamic Bitrate Change    yes
Forced constant QP        yes
Dynamic RC Mode Change    no
Subframe Readback         yes
Constrained Encoding      no
Intra Refresh             yes
Custom VBV Bufsize        yes
Dynamic Slice Mode        yes
Ref Pic Invalidiation     yes
PreProcess                no
Async Encoding            yes
Max MBs                   262144
Lossless                  yes
SAO                       yes
Me Only Mode              yes
Lookahead                 yes
AQ (temporal)             no
Weighted Prediction       yes
10bit depth               yes
