### ISSUE TITLE
Can you add a PSNR and/or SSIM measurement tool which prompt the quality for NVENCC after encoding?

### ISSUE THREAD

**Issue by Starkler** [rigaya/NVEnc#178]
Hello Rigaya!

Can you add a PSNR and/or SSIM measurement tool which prompt the quality for NVENCC after encoding?

Thank you!

**Comment by rigaya** [comment]
I'm thinking adding PSNR/SSIM measurement is not easy stuff to implement.

As NVENC SDK does not have the functionality to calculate them during encoding, I shall need to decode the output bitstream and then compare with the input.

I'll keep in mind about this and might try when I have time.

**Comment by Starkler** [comment]
Thank you Rigaya!
Exactly with the method as the X264 did it: "decode the output bitstream and then compare with the input." 
And if you have that, you can simply copy/put that measurement tool immediatelly to your other projects like VCEENC QSVENC .

**Comment by rigaya** [comment]
PSNR/SSIM calculation tools are added in [NVEnc 4.60](https://github.com/rigaya/NVEnc/releases/tag/4.60).

But actually it's implementation is NVEnc specific, as I needed to implement by using hw decoder + CUDA, to have enough speed to catch up to the hw encoder.

**Comment by rigaya** [comment]
I'll close this issue now, as the ssim/psnr calculation tool has been added in NVEnc 4.60, and has been stable from NVEnc 4.62.
