### ISSUE TITLE
How to convert HLG video to SDR

### ISSUE THREAD

**Issue by Last-Order** [rigaya/NVEnc#179]
NVENC version: 4.56

I'm trying to convert a HLG to a SDR video and I've tried the following command:

```
D:\Downloads\Compressed\NVEncC_4.56_x64\NVEncC64.exe -i "F:\Temp\xxxxx.m2ts" --vpp-colorspace matrix=bt2020nc:bt709,transfer=arib-srd-b67:bt709,range=limited:limited --output-res 1920x1080 --audio-copy --trim 26916:27305 -o f:/test3.mkv
```

But I can't get a correct result, the color is much more white than before. Here is the screenshot:

![image](https://user-images.githubusercontent.com/3362825/69934540-2d7ac480-150d-11ea-914f-a01321235e34.png)

I also tried `--vpp-colorspace hdr2sdr=mobius` or  `--vpp-colorspace hdr2sdr=reinhard` and the result seems even worse.

My question is, is there a way to convert HLG video to SDR video with correct color? Thanks!

**Comment by rigaya** [comment]
Unfortunately, HLG → SDR is not supported in current version. I'll check if I can add it.

**Comment by Last-Order** [comment]
Thanks for your reply. Please contact me if you need a example video.

**Comment by rigaya** [comment]
Support for HLG to SDR has been added in [NVEnc 4.57](https://github.com/rigaya/NVEnc/releases/tag/4.57).

Please try the following command.

--vpp-colorspace transfer=arib-std-b67:bt709,matrix=bt2020nc:bt709,colorprim=bt2020:bt709,hdr2sdr=hable

**Comment by Last-Order** [comment]
Tried it and it works as expected! Thanks!
