### ISSUE TITLE
NVenc: --weightp is not compatible with the new Nvidia driver (388.13)?

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#18]
If use --weightp nvenc crashes out after some time with error 0xC0000409

**Comment by ircopdd** [comment]
NVEncC (x64) 3.23 (r667) by rigaya, Sep 26 2017 20:51:36 (VC 1900/Win/avx2)
OS Version     Windows 7 x64 (7601)
CPU            Intel Core i7-3930K @ 3.20GHz (6C/12T)
GPU            #0: GeForce GTX 1060 6GB (10 EU) @ 1784 MHz (388.31)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     avcuvid: H.265/HEVC, 1280x720, 24000/1001 fps
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main10 @ Level auto
1280x720p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   CQP  I:25  P:28  B:30
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       0 frames
Ref frames     8 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
Error on nvEncLockBitstream: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

**Comment by rigaya** [comment]
I think this issue is same with #15.

I was not able to find out what is going wrong with weightp, so unfortunately I decided to disable it on HEVC encoding. (NVEncC 3.25)

You can override this behavior and still use weightp by using "--weightp force", but this is only for testing, and not recommended.
