### ISSUE TITLE
nvencc yielded larger filesizes than expected vs ffmpeg

### ISSUE THREAD

**Issue by hydra3333** [rigaya/NVEnc#181]
Hello, I am doing something wrong with settings and would value your advice.

I have a source .mp4 of interlaced h.264, which needs to be deinterlaced to be played on a Chromecast Ultra.
`07/12/2019  03:17 PM        49,032,399 0.source.mp4`

ffmpeg deinterlacing and transcoding produces filesizes in the expected ranges
```
07/12/2019  08:55 PM        49,826,101 0.source.FF.h264_nvenc.mp4
07/12/2019  08:55 PM        31,580,622 0.source.FF.hevc_nvenc.mp4
```

nvencc deinterlacing and transcoding produces filesizes about 5 to 6 times expectation.
```
07/12/2019  08:56 PM       281,478,324 0.source.NVENCC.h264.mp4
07/12/2019  08:56 PM       346,072,892 0.source.NVENCC.hevc.mp4
```

Advice would be appreciated on how to produce similar file-sizes for similar qualities, or perhaps even pointers to what may be causing the differences.

Thank you.

ffmpeg Commandlines:

`"C:\SOFTWARE\ffmpeg\0-homebuilt-x64\ffmpeg.exe" -v verbose -flags2 showall -i "G:\HDTV\test\0.source.mp4" -sn -map_metadata -1 -vsync 0 -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0,format=pix_fmts=yuv420p,setdar=dar=16/9" -c:v h264_nvenc -pix_fmt yuv420p -preset slow -bf 2 -g 50  -rc:v vbr_hq -rc-lookahead:v 32 -cq 18 -qmin 10 -qmax 30 -coder cabac -strict experimental -profile:v high -level 5.1 -movflags +faststart+write_colr -c:a libfdk_aac -cutoff 18000  -y "G:\HDTV\test\0.source.FF.h264_nvenc.mp4" 
`

`"C:\SOFTWARE\ffmpeg\0-homebuilt-x64\ffmpeg.exe" -v verbose -flags2 showall -i "G:\HDTV\test\0.source.mp4" -sn -map_metadata -1 -vsync 0 -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -filter_complex "[0:v]yadif=0:0:0,format=pix_fmts=yuv420p,setdar=dar=16/9" -strict experimental -c:v hevc_nvenc -pix_fmt nv12 -preset slow -rc:v vbr_hq -2pass 1 -rc-lookahead:v 32 -cq 16 -qmin 10 -qmax 35 -spatial_aq 1 -temporal_aq 1 -strict experimental -profile:v main -level 5.1 -movflags +faststart+write_colr -c:a libfdk_aac -cutoff 18000 -y "G:\HDTV\test\0.source.FF.hevc_nvenc.mp4"` 

nvencc Commandlines:

```
"C:\SOFTWARE\NVEncC\NVEncC64.exe" --avhw --interlace tff --input-analyze 60 --vpp-deinterlace adaptive --input "G:\HDTV\test\0.source.mp4" --video-track 1 --codec h264 --avsync forcecfr --output-depth 8 --preset quality --vbrhq 0 --vbr-quality 18 --lookahead 32 --aq --aq-temporal --aq-strength 0 --mv-precision Q-pel --cabac --level 5.1 --profile high --audio-codec aac --audio-ignore-decode-error 1000 --chapter-copy --key-on-chapter --vpp-perf-monitor --output-buf 64 --output-thread 1 --log-level info --output "G:\HDTV\test\0.source.NVENCC.h264.mp4" 
NVEncC (x64) 4.57 (r1261) by rigaya, Dec  5 2019 22:53:35 (VC 1923/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            AMD Ryzen 9 3900X 12-Core Processor (12C/24T)
GPU            #0: GeForce RTX 2060 SUPER (2176 cores, 1665 MHz)[PCIe3x16][441.20]
NVENC / CUDA   NVENC API 9.1, CUDA 10.2, schedule mode: auto
Input Buffers  CUDA, 44 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 25/1 fps
Deinterlace    adaptive
AVSync         forcecfr
Vpp Filters    copyDtoD
Output Info    H.264/AVC high @ Level 5.1
               1920x1080p 1:1 25.000fps (25/1fps)
               avwriter: h264, #1:mp3float/2ch -> aac/2ch/192kbps, chap => mp4
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        0 kbps (Max: 288000 kbps)
Target Quality 18.00
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     250 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on(spatial, temporal, strength auto)
Others         mv:Q-pel cabac deblock adapt-transform:auto bdirect:auto 
[59.1%] 48 frames: 34.19 fps, 25962 kb/s, remain 0:00:01, GPU 9%, VE 18%, est out size 10.1MB
[65.1%] 223 frames: 101.00 fps, 22002 kb/s, remain 0:00:01, GPU 12%, VE 98%, est out size 35.9MB
[70.6%] 403 frames: 133.98 fps, 21163 kb/s, remain 0:00:01, GPU 12%, VE 98%, est out size 57.6MB
[76.1%] 583 frames: 153.02 fps, 20984 kb/s, remain 0:00:01, GPU 11%, VE 98%, est out size 76.7MB
[81.6%] 751 frames: 162.84 fps, 20170 kb/s, remain 0:00:01, GPU 11%, VE 98%, est out size 88.5MB
[87.1%] 933 frames: 172.39 fps, 20098 kb/s, remain 0:00:01, GPU 11%, VE 91%, est out size 102.7MB
[92.6%] 1118 frames: 179.92 fps, 19617 kb/s, remain 0:00:00, GPU 11%, VE 91%, est out size 112.9MB
[100.0%] 1303 frames: 185.77 fps, 19261 kb/s, remain 0:00:00, GPU 12%, VE 98%, est out size 119.7MB
[100.0%] 1473 frames: 188.46 fps, 19039 kb/s, remain 0:00:00, GPU 12%, VE 98%, est out size 133.7MB
[100.0%] 1658 frames: 192.37 fps, 18954 kb/s, remain 0:00:00, GPU 11%, VE 93%, est out size 149.9MB
[100.0%] 1843 frames: 195.63 fps, 18916 kb/s, remain 0:00:00, GPU 11%, VE 93%, est out size 166.2MB
[100.0%] 2023 frames: 197.83 fps, 18738 kb/s, remain 0:00:00, GPU 12%, VE 98%, est out size 180.8MB
[100.0%] 2198 frames: 199.27 fps, 18684 kb/s, remain 0:00:00, GPU 11%, VE 98%, est out size 195.8MB
[100.0%] 2383 frames: 201.42 fps, 18786 kb/s, remain 0:00:00, GPU 11%, VE 96%, est out size 213.5MB
[100.0%] 2568 frames: 203.24 fps, 18675 kb/s, remain 0:00:00, GPU 11%, VE 98%, est out size 228.7MB
                                                                               
encoded 2999 frames, 203.35 fps, 18574.82 kbps, 265.63 MB
encode time 0:00:14, CPU: 7.3, GPU: 10.9, VE: 85.3, GPUClock: 1919MHz, VEClock: 1772MHz
frame type IDR   32
frame type I     32,  avgQP  13.56,  total size   11.62 MB
frame type P    786,  avgQP  16.10,  total size  117.05 MB
frame type B   2181,  avgQP  17.96,  total size  136.96 MB

Vpp Filter Performance
copyDtoD:    18.6 us
```

```
"C:\SOFTWARE\NVEncC\NVEncC64.exe" --avhw --interlace tff --input-analyze 60 --vpp-deinterlace adaptive --input "G:\HDTV\test\0.source.mp4" --video-track 1 --codec hevc --avsync forcecfr --output-depth 8 --preset quality --vbrhq 0 --vbr-quality 16 --lookahead 32 --aq --aq-temporal --aq-strength 0 --mv-precision Q-pel --level 5.1 --profile main --audio-codec aac --audio-ignore-decode-error 1000 --chapter-copy --key-on-chapter --vpp-perf-monitor --output-buf 64 --output-thread 1 --log-level info --output "G:\HDTV\test\0.source.NVENCC.hevc.mp4" 
NVEncC (x64) 4.57 (r1261) by rigaya, Dec  5 2019 22:53:35 (VC 1923/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            AMD Ryzen 9 3900X 12-Core Processor (12C/24T)
GPU            #0: GeForce RTX 2060 SUPER (2176 cores, 1665 MHz)[PCIe3x16][441.20]
NVENC / CUDA   NVENC API 9.1, CUDA 10.2, schedule mode: auto
Input Buffers  CUDA, 44 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 25/1 fps
Deinterlace    adaptive
AVSync         forcecfr
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main @ Level auto
               1920x1080p 1:1 25.000fps (25/1fps)
               avwriter: hevc, #1:mp3float/2ch -> aac/2ch/192kbps, chap => mp4
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        0 kbps (Max: 38400 kbps)
Target Quality 16.00
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     250 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on
CU max / min   auto / auto
Others         mv:Q-pel 
[60.6%] 88 frames: 39.98 fps, 28993 kb/s, remain 0:00:01, GPU 8%, VE 99%, est out size 20.1MB
[64.6%] 217 frames: 72.19 fps, 27075 kb/s, remain 0:00:02, GPU 8%, VE 99%, est out size 43.4MB
[68.6%] 343 frames: 89.98 fps, 26017 kb/s, remain 0:00:02, GPU 8%, VE 99%, est out size 62.0MB
[72.6%] 468 frames: 101.36 fps, 25853 kb/s, remain 0:00:02, GPU 8%, VE 99%, est out size 79.5MB
[76.6%] 593 frames: 109.45 fps, 25771 kb/s, remain 0:00:02, GPU 8%, VE 99%, est out size 95.1MB
[80.1%] 713 frames: 114.59 fps, 25364 kb/s, remain 0:00:02, GPU 8%, VE 99%, est out size 107.7MB
[84.1%] 843 frames: 120.05 fps, 25013 kb/s, remain 0:00:01, GPU 9%, VE 99%, est out size 119.6MB
[88.1%] 968 frames: 123.72 fps, 24697 kb/s, remain 0:00:01, GPU 9%, VE 99%, est out size 129.4MB
[92.1%] 1081 frames: 125.35 fps, 24351 kb/s, remain 0:00:01, GPU 9%, VE 99%, est out size 136.3MB
[96.1%] 1218 frames: 129.22 fps, 23967 kb/s, remain 0:00:00, GPU 9%, VE 99%, est out size 144.8MB
[100.0%] 1348 frames: 131.73 fps, 23692 kb/s, remain 0:00:00, GPU 8%, VE 99%, est out size 152.3MB
[100.0%] 1473 frames: 133.48 fps, 23525 kb/s, remain 0:00:00, GPU 9%, VE 99%, est out size 165.2MB
[100.0%] 1598 frames: 134.98 fps, 23260 kb/s, remain 0:00:00, GPU 9%, VE 99%, est out size 177.2MB
[100.0%] 1697 frames: 134.21 fps, 23364 kb/s, remain 0:00:00, GPU 9%, VE 99%, est out size 189.1MB
[100.0%] 1848 frames: 137.38 fps, 23270 kb/s, remain 0:00:00, GPU 9%, VE 99%, est out size 205.1MB
[100.0%] 1973 frames: 138.44 fps, 23180 kb/s, remain 0:00:00, GPU 8%, VE 99%, est out size 218.1MB
[100.0%] 2098 frames: 139.37 fps, 23034 kb/s, remain 0:00:00, GPU 8%, VE 99%, est out size 230.4MB
[100.0%] 2223 frames: 140.19 fps, 23091 kb/s, remain 0:00:00, GPU 8%, VE 99%, est out size 244.8MB
[100.0%] 2348 frames: 140.96 fps, 23195 kb/s, remain 0:00:00, GPU 8%, VE 99%, est out size 259.7MB
[100.0%] 2473 frames: 141.66 fps, 23087 kb/s, remain 0:00:00, GPU 8%, VE 99%, est out size 272.2MB
[100.0%] 2598 frames: 142.29 fps, 22986 kb/s, remain 0:00:00, GPU 9%, VE 99%, est out size 284.7MB
                                                                               
encoded 2999 frames, 144.55 fps, 22882.53 kbps, 327.23 MB
encode time 0:00:20, CPU: 7.4, GPU: 8.3, VE: 92.9, GPUClock: 1915MHz, VEClock: 1767MHz
frame type IDR   32
frame type I     32,  avgQP  11.41,  total size   13.95 MB
frame type P    786,  avgQP  13.77,  total size  161.27 MB
frame type B   2181,  avgQP  15.72,  total size  152.01 MB

Vpp Filter Performance
copyDtoD:    18.6 us

```

**Comment by hydra3333** [comment]
Also, would this be a valid example of how audio filter loudnorm would be called ?
`--audio-filter loudnorm="I=-16:TP=0.0:LRA=11:measured_I=-22.98:measured_LRA=17.20:measured_TP=-6.75:measured_thresh=-34.19:offset=-0.58:linear=true:print_format=summary"`

**Comment by ls-milkyway** [comment]
Plz read nvidia's ffmpeg guide ...above commands will not be implemented by ffmpeg and it will not throw any errors if you try to incorporate x264 settings....but these settings will not be implemented during encoding....only those settings mentioned in nvidia's official guide will work.

I was also excited when i saw many x264 settings working with cuda plus hybrid (cpu & gpu) commands of ffmpeg...but they result in very poor encodes.....I  have wasted much of my time on ffmpeg only to find out that nvencc (though large files) have 50-60% better quality if used with staxrip with fine tunning.

I have done extensive research by comparing quality using VMAF,SSIM and other quality metrics...believe me nvencc is the best out there (with staxrip).

**Comment by rigaya** [comment]
@hydra3333 Based on my experience, "--vbr-quality 18" is rather to small and it is expected that you get a large file size. Please try for larger value, around 23 - 28. I don't know what will match the -cq of ffmpeg.

Thanks for pointing out the problem of the log, it seems to be always saying Level auto on HEVC encoding. I'll fix this on next release.

As you have assumed, "cutoff" option is not available on native aac encoder of ffmpeg. (other options are fine). Unfortunately, I cannot make fdk_aac available because a binary with it cannot be distributed, as you might know, it requires "--enable-nonfree" option when building ffmpeg.

**Comment by Starkler** [comment]
> e implemented by ffmpeg and it will not throw any errors if you try to incorporate x264 settings....but these settings will not be implemented during encoding....only those settings mentioned in nvidia's official guide will work.
> 
> I was also excited when i saw many x264 settings working with cuda plus hybrid (cpu & gpu) commands of ffmpeg...but they result in very poor encodes.....I have wasted much of my time on ffmpeg only to find out that nvencc (though large files) have 50-60% better quality if used with staxrip with fine tunning.
> 
> I have done extensive research by comparing quality using VMAF,SSIM and other quality metrics...believe me nvencc is the best out there (with staxrip).

Hi!
Hybrid is better and more stable than Staxrip.

**Comment by hydra3333** [comment]
@rigaya thank you for the information, I'll try larger values around 23 - 28 for  "--vbr-quality", and play with loudnorm.  Oh well about fdk_aac, wasn't sure if licensing had changed, it was worth asking :)

May I check in regard to --vpp-deinterlace ... is it the "purevideo" (motion adaptive?) deinterlacer ?

@ls-milkyway I get OK looking encodes out of ffmpeg, nvencc uses the same underpinning technology, nvdec/nvenc , as I understand it.   As yet I don't see a cost/benefit need to use staxrip as another layer a layer on top of nvencc ;) If there is something specific, perhaps you could outline it ?

@Starkler  as yet I don't see a cost/benefit need to use Hybrid as another layer a layer on top of nvencc ;)  If there is something specific, perhaps you could outline it ?

**Comment by ls-milkyway** [comment]
@hydra3333 Yep they both uses the same technology..but ffmpeg strangely allows some x264 settings which are not defined by nvdec/nvenc for eg: `-psy 1 -psy-rd 1.0:0.0` and did not show any errors (may be it was hybrid cpu/gpu command).

I created a sample (1080p) by combining various types of movie scenes (high action, low-light, landscapes etc.) for testing ffmpeg, nvencc, hybrid & staxrip encoding quality using quality metrics VMAF.SSIM & VQM (at same x264 settings).

Strangely ffmpeg was poorest (in scores) both for cpu, gpu and hybrid (cpu/gpu) commands..the cpu encoding was also compared to handbrake's encoding....it seems to me that ffmpeg does not handle some x264 settings well...

Further, nvencc and hybrid had same scores and were almost equal in quality to staxrip...but staxrip's encodes simply outperformed both when some video filters were used such as unsharp and vpp2 tweak (the same equivalent filters where also used in hybrid and nvencc) . I strictly made sure all the settings and filter parameters to be the same during encoding.

But staxrip did outperform slightly in scores (hybrid did throw some errors during encoding...so i had to adjust it) also 720p scores were better in staxrip ...i could not find the reason ...may be due to staxrip's spline64 resize algo or may something other.. it did better.

Everyone has it own opinion some find hybrid better, others plain command line nvencc (core used by hybrid & staxrip) but purely on scores,GUI (some better stability than hybrid) i found staxrip better option....

**Comment by Starkler** [comment]
> ncoding...so i had to adjust it) also 720p scores were better in staxrip ...i could not find the reason ...may be due to staxrip's spline64 resize algo or may something other.. it did better.

There is no difference in HW encoding between Staxrip or Hybrid, because both use also NVENCC coding engine of Rigaya, but Hybrid has a more elegant and comfortable gui, and Hybrid is a more stable less buggy software

**Comment by ls-milkyway** [comment]
@Starkler 

I have already mentioned that:

> Everyone has it own opinion some find hybrid better, others plain command line nvencc (**core used by hybrid & staxrip**) but purely on scores,GUI (some better stability than hybrid) i found staxrip better option....

further to make things more clear ...one can simply copy cli command from the GUI ( of both staxrip & hybrid) and run them on Nvencc for same results...it was just the selection of resize algorithm (I may have selected lancoz or any other in the case of hybrid/nvencc and spline64 in case of staxrip) resulting in different scores ......

In my opinion staxrip's GUI is compact ...I had to traverse less for encoding settings....It was easy to find them......may be as I found difficult to look for all the settings in HYBRID and incompatibility arose due to mismatch... that was the reason why HYBRID (more stable) threw more errors.
**Everybody has his/her own taste I found staxrip better.**

**Comment by rigaya** [comment]
> PS the hevc nvencc encode log says
> H.265/HEVC main @ Level auto
> even though level 5.1 was specified ?

[NVEnc 4.58](https://github.com/rigaya/NVEnc/releases/tag/4.58) shall fix this problem.

**Comment by hydra3333** [comment]
thank you.
