### ISSUE TITLE
Hardcoded subtitles colorless?

### ISSUE THREAD

**Issue by ls-milkyway** [rigaya/NVEnc#183]
Hi !
Nvencc version 4.55 used in staxrip 2.0.6.0 has suddenly stopped showing hardcoded ass/ssa subtitles in color? And this seems to happen in only some mkv files?

Everything else is perfect but hard-coded subtitles are colorless, whereas players (vlc, windows media) are showing subtitle in color?Even handbrake and vidcoder (using nvenc) encodes are showing the burnt subtitles in color for the same mkv file?

Command used: "track=1,charcode=utf-8,shaping=complex" was working well earlier.
Also tried --input-analyze 60 or 180, which is not working.

FYI:
I am resizing 1920->720 , cropping and changing aspect ratio to 1.7777 (to remove black bars).....resulting in colorless subtitles hard-coded (but not in vidcoder) anybody any ideas plz??

Yep, this is an issue with Nvenc as I have used the command generated by staxrip on latest version 4.58 but ass subtitles are still colorless?
Command:
NVEncC64.exe --avhw --cqp 18:20:22 --preset quality --qp-max 51 --qp-min 18 --aq-strength 1 --aq --bref-mode middle --bframes 4 --ref 4 --gop-len 250 --lookahead 32 --nonrefp --weightp --cuda-schedule auto --colormatrix bt709 --colorprim bt709 --transfer bt709 --vpp-subburn "track=1,charcode=utf-8,shaping=complex" --vpp-unsharp --vpp-tweak brightness=-0.03,contrast=1.03 --direct auto --mv-precision q-pel --cabac --crop 0,138,0,138 --output-res 1280x720 --trim 0:52004 -i "D:\Videos\Makemkv\ep1.mkv" -o "D:\Videos\Makemkv\ep1_new_out.h264"

Then I merged video & audio using mkvtoolnix and found hard-coded ass subtitles colorless?

May be I thought that this is due to color declaration mismatchis ass file...so I used aegisub to declare color: tv bt709 but still the same results??For details of original file plz check ffprobe results below:

{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1001/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1088,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 40,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "24000/1001",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "BPS-eng": "8456505",
                "DURATION-eng": "00:38:46.199000000",
                "NUMBER_OF_FRAMES-eng": "55773",
                "NUMBER_OF_BYTES-eng": "2458939236",
                "_STATISTICS_WRITING_APP-eng": "mkvmerge v41.0.0 ('Smarra') 64-bit",
                "_STATISTICS_WRITING_DATE_UTC-eng": "2019-12-20 22:41:07",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
            }
        },
        {
            "index": 1,
            "codec_name": "eac3",
            "codec_long_name": "ATSC A/52B (AC-3, E-AC-3)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 6,
            "bits_per_sample": 0,
            "dmix_mode": "-1",
            "ltrt_cmixlev": "-1.000000",
            "ltrt_surmixlev": "-1.000000",
            "loro_cmixlev": "-1.000000",
            "loro_surmixlev": "-1.000000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "BPS-eng": "768000",
                "DURATION-eng": "00:38:46.208000000",
                "NUMBER_OF_FRAMES-eng": "72694",
                "NUMBER_OF_BYTES-eng": "223315968",
                "_STATISTICS_WRITING_APP-eng": "mkvmerge v41.0.0 ('Smarra') 64-bit",
                "_STATISTICS_WRITING_DATE_UTC-eng": "2019-12-20 22:41:07",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
            }
        },
        {
            "index": 2,
            "codec_name": "ass",
            "codec_long_name": "ASS (Advanced SSA) subtitle",
            "codec_type": "subtitle",
            "codec_time_base": "0/1",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 2326208,
            "duration": "2326.208000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "BPS-eng": "53",
                "DURATION-eng": "00:34:54.930000000",
                "NUMBER_OF_FRAMES-eng": "288",
                "NUMBER_OF_BYTES-eng": "13989",
                "_STATISTICS_WRITING_APP-eng": "mkvmerge v41.0.0 ('Smarra') 64-bit",
                "_STATISTICS_WRITING_DATE_UTC-eng": "2019-12-20 22:41:07",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
            }
        }
    ],
    "format": {
        "filename": "ep1.mkv",
        "nb_streams": 3,
        "nb_programs": 0,
        "format_name": "matroska,webm",
        "format_long_name": "Matroska / WebM",
        "start_time": "0.000000",
        "duration": "2326.208000",
        "size": "2682875003",
        "bit_rate": "9226603",
        "probe_score": 100,
        "tags": {
            "encoder": "libebml v1.3.9 + libmatroska v1.5.2",
            "creation_time": "2019-12-20T22:41:07.000000Z"
        }
    }
}
I am i missing something here??

**Comment by ls-milkyway** [comment]
Ok, this may not be an issue with nvencc as staxrip version 2.0.4.0 with nvencc 4.46 behaving in the same way....ssa/ass subtitles hardcoded without color in a particular movie clip.
FYI:
I am resizing 1920->720 , cropping and changing aspect ratio to 1.7777 (to remove black bars).....resulting in colorless subtitles hardcoded anybody any ideas??

**Comment by ls-milkyway** [comment]
Yep, this is an issue with Nvenc as I have used the command generated by staxrip on latest version 4.58 but ass subtitles are still colorless?
Command:
`NVEncC64.exe --avhw --cqp 18:20:22 --preset quality --qp-max 51 --qp-min 18 --aq-strength 1 --aq --bref-mode middle --bframes 4 --ref 4 --gop-len 250 --lookahead 32 --nonrefp --weightp --cuda-schedule auto --colormatrix bt709 --colorprim bt709 --transfer bt709 --vpp-subburn "track=1,charcode=utf-8,shaping=complex" --vpp-unsharp --vpp-tweak brightness=-0.03,contrast=1.03 --direct auto --mv-precision q-pel --cabac --crop 0,138,0,138 --output-res 1280x720 --trim 0:52004 -i "D:\Videos\Makemkv\ep1.mkv" -o "D:\Videos\Makemkv\ep1_new_out.h264"`

Then I merged video & audio using mkvtoolnix and found hard-coded ass subtitles colorless?

**Comment by rigaya** [comment]
Thanks for pointing out the issue, should be fixed by [NVEnc 4.59](https://github.com/rigaya/NVEnc/releases/tag/4.59).

**Comment by rigaya** [comment]
I'll close this issue as this error should be fixed now. Please re-open if you have any related issues.
