### ISSUE TITLE
Question: --delogo

### ISSUE THREAD

**Issue by djrooli** [rigaya/NVEnc#184]
Hello Rigaya!

I tried to remove logo from a video, but I got this error message:

**_avcuvid: codec png(rgba) unable to decode by cuvid.
failed to initialize file reader(s).
Failed to open input file._**

I tried it with avsw and avhw, no luck.

I am using a transparent png from the sceenshot of the film, containing only the logo.

Am I doing something wrong?

I am using this param: --vpp-delogo screen.png

Thank you for your answer.

**Comment by rigaya** [comment]
--vpp-delogo is ported from an [Aviutl](http://spring-fragrance.mints.ne.jp/aviutl/) plugin "delogo.auf" and requires ".lgd" file created by "logoscan.auf" which defines the logo. It cannot take png file as input.

I don't know if there is a English explanation for this.

**Comment by djrooli** [comment]
Thanks for your answer, I think I just give up on that, I have to find another way, unfortunately I can't make it work. Logoscan.auf's translation is not complete, I get weird characters as error message, can't download or create lgd file, I think I'm stucked with this. Did not find any tutorial either. Anyways thank you! ;)

**Comment by rigaya** [comment]
I'll close this issue as the topic has been answered.
