### ISSUE TITLE
Request:  Add De-Interlace only for frames marked as Interlaced

### ISSUE THREAD

**Issue by agressiv** [rigaya/NVEnc#187]
All of ffmpeg's de-interlace filters have the option to de-interlace frames that marked as interlaced and leave the others alone.

https://ffmpeg.org/ffmpeg-filters.html#nnedi

>  Set which frames to deinterlace, by default it is all. Can be all or interlaced.

It would be great if NVEncC's interlace options had the option for the same.  Right now on hybrid content it will attempt to de-interlace progressive frames giving it a "shimmering" effect.

**Comment by rigaya** [comment]
I've added new options "--interlace auto" for this in [NVEnc 4.62](https://github.com/rigaya/NVEnc/releases/tag/4.62), with this options de-interlacers will check for the interlace flag each frame, please have a try.
```
--interlace auto --vpp-nnedi field=auto
```

**Comment by rigaya** [comment]
Previous NVEnc 4.62 had problem with command line parsing and had a problem that it could not accept --interlace auto, this has been fixed in [NVEnc 4.63](https://github.com/rigaya/NVEnc/releases/tag/4.63).

**Comment by rigaya** [comment]
I'll close this issue as the feature has been added. Please let me now if you have any more problems.
