### ISSUE TITLE
VUI HDR haven't enough options, need --limitrange, --chromaloc, --masterdisplay, --maxcll...

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#19]
Please, add this options for full HDR support:
--limitrange or --fullrange tv or --tvrange (like --range <full|limited> in x265);
--chromaloc <int>;
--masterdisplay <string> G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1);
--maxcll MaxCLL;
--maxfall MaxFALL;

**Comment by rigaya** [comment]
NVEncC already has option "--fullrange".

For --chromaloc, --masterdisplay, --maxcll, --maxfall MaxFALL, NVENC SDK does not have corresponding API, so it could not be added to NVEncC.

**Comment by drSHLEFF** [comment]
I know about --fullrange, but need option for Limited color range (for TV and Broadcast).
At the moment there is only one way, that produce a limited color range - using option: "--videoformat component". Is it possible to make a separate option for the color range: Limited ?
![inked2017-11-26_li](https://user-images.githubusercontent.com/11748220/33240133-338b56d0-d2c2-11e7-9db8-c74f54fa04f2.jpg)

**Comment by lgoncal** [comment]
[](https://github.com/SK-Hardwired/nv_hevc_hdr_patcher/blob/master/nvhsp.py)
can this be used by NVEncC

**Comment by rigaya** [comment]
[NVEncC 3.28](https://github.com/rigaya/NVEnc/releases/tag/3.28) adds options --master-display, --max-cll. (checked with MediaInfo)

**Comment by drSHLEFF** [comment]
Thanks, all works perfectly!
