### ISSUE TITLE
NVEncC does not respect the color characteristics of the source material

### ISSUE THREAD

**Issue by warrex1979** [rigaya/NVEnc#190]
I am experimenting with converting 8bit 1080p content to 10bit qHD (960x540) HEVC. I am going to 10bit to avoid banding at lower bitrates. Checking NVEncC's output I noticed shifted colors compared to the source and compared an encode via Handbrake (x265 10bit).

Turns out that NVEncC ignores the color characteristics of the source material and just seems to set color based on the **output** resolution. SD content is set to BT.601 and HD content is set to BT.709. Is there any good reason for this behaviour and if not can you fix it?

I do know that I can just add "--colorprim bt709 --transfer bt709 --colormatrix bt709" but I currently think that I should no have to.

**Comment by rigaya** [comment]
This behavior is expected, as NVEncC leaves color characteristics "undefined" by default, and most media players automatically uses BT.601 for SD and BT.709 for HD whenever color characteristic params are unspecified.

Therefore, it is required to specify color characteristic options whenever you need them.

**Comment by warrex1979** [comment]
Thank you for your answer! I took a look with ffprobe at the output.

Again, is there any reason that makes it advantageous to not copy the tags from the source like Handbrake does or might this get implemented sometime in the future?

**Comment by rigaya** [comment]
The reason for this default behavior is that this is the same as x264.exe or x265.exe (the CLI encoder), which also leaves color characteristics "undefined" by default.

Although I'm not planning to change this default behavior, I'll consider to add feature to copy color characteristics from the input file when possible, like "--colorprim copy --transfer copy --colormatrix copy". (But you still will need to add this options.)

**Comment by warrex1979** [comment]
Thanks. This will will do and make NVEncC yet again more suitable for batch encoding differing source content.

**Comment by devil40xxx** [comment]
> The reason for this default behavior is that this is the same as x264.exe or x265.exe (the CLI encoder), which also leaves color characteristics "undefined" by default.
> 
> Although I'm not planning to change this default behavior, I'll consider to add feature to copy color characteristics from the input file when possible, like "--colorprim copy --transfer copy --colormatrix copy". (But you still will need to add this options.)

@rigaya 

 Very cool idea!

It take me alomst half an hour to find transfer HLG  using " --transfer arib-std-b67".

And taliking about batch encoding, could you add an line of current file name to show (in CMD window) of which file has been encoded? 

Because sometime when error occured we just can't find  which is it at once  :")

**Comment by rigaya** [comment]
The new release [NVEnc 4.62](https://github.com/rigaya/NVEnc/releases/tag/4.62) has options to copy color characteristic params from input file, when using avhw/avsw reader.
  - [--colormtarix](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--colormatrix-string) auto
  - [--colorprim](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--colorprim-string) auto
  - [--transfer](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--transfer-string) auto
  - [--chromaloc](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--chromaloc-int-or-auto) auto
  - [--colorrange](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--colorrange-string) auto

------
> And taliking about batch encoding, could you add an line of current file name to show (in CMD window) of which file has been encoded?

@devil40xxx [NVEnc 4.62](https://github.com/rigaya/NVEnc/releases/tag/4.62) will now show output filename on the top.

**Comment by devil40xxx** [comment]
@rigaya  thx for the great job.I tested the new options and they all work fine. 

Except the "--chromaloc auto". 

 In a common WEB-DL viedo (with Range:TV,Primaries:bt709,Transfer:bt-709,ColorSpace :bt-709,Location:left ) . When using "--chromaloc auto" will change the location to "center".

The werid thing is without using "--chromaloc auto" you will get the an encoded file with "Location:left".

**Comment by devil40xxx** [comment]
I tested more files and found out if there no  colorrange  define in mkvs, using auto will lead to the output file  with range "TV" .

@rigaya

**Comment by rigaya** [comment]
Thanks, I'll work on the problem of "chromaloc" and "colorrange" in the next release.

**Comment by rigaya** [comment]
[NVEnc 4.63](https://github.com/rigaya/NVEnc/releases/tag/4.63) shall fix handling of chromaloc and colorange.

**Comment by devil40xxx** [comment]
> [NVEnc 4.63](https://github.com/rigaya/NVEnc/releases/tag/4.63) shall fix handling of chromaloc and colorange.

In mutilple case show the fix work, thanks for the good job.

**Comment by rigaya** [comment]
Thank you for confirming, I'll close this issue.
