### ISSUE TITLE
Will NVEnc support yuv444 output in future?

### ISSUE THREAD

**Issue by AceCLee** [rigaya/NVEnc#192]
Hello Rigaya!

Will NVEnc support yuv444 output in future? Some videos might need yuv444 output if format of input video stream is yuv444.

Thanks!

**Comment by Selur** [comment]
afaik yuv444 should already be supported:
```
...
--profile <string>           set codec profile
                                  H.264: baseline, main, high(default), high444
                                  HEVC : main, main10, main444
...
   --lossless                   for lossless (YUV444 only) / default: off
...
```
assuming you use the right profile or lossless encoding,....

**Comment by AceCLee** [comment]
> afaik yuv444 should already be supported:
> 
> ```
> ...
> --profile <string>           set codec profile
>                                   H.264: baseline, main, high(default), high444
>                                   HEVC : main, main10, main444
> ...
>    --lossless                   for lossless (YUV444 only) / default: off
> ...
> ```
> 
> assuming you use the right profile or lossless encoding,....

Thanks!
