### ISSUE TITLE
vpp-subburn doesn't work with 4k and scaling

### ISSUE THREAD

**Issue by bigdwg71** [rigaya/NVEnc#193]
Having an issue with 4.60 and 4.61 where vpp-subburn doesn't seem to work with "--vpp-subburn track=2,scale=2.0"

The encode completes with errors, but the video file plays except there are no subtitles burned in....

"resize: only supported on device memory." suggests the scale command isn't being properly executed.

Command:

NVEncC64.exe --avhw --vbrhq 0 --codec h265 --output-depth 10 --level 5.1 --profile main10 --tier high --lookahead 32 --gop-len 24 --bframes 5 --qp-init 20 --vbr-quality 20 --aq --aq-temporal --max-bitrate 55000 --key-on-chapter --mv-precision Q-pel --crop 0,280,0,280 --vpp-subburn track=2,scale=2.0 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,20) --max-cll 793,679 -i "d:\MakeMKV\Captain America - The Winter Soldier.mkv" -o "d:\MakeMKV\Captain America - The Winter Soldier.h265"

Output:

NVEncC (x64) 4.61 (r1307) by rigaya, Jan 16 2020 14:49:35 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (18362)
CPU            Intel Core i7-9700K @ 3.60GHz [TB: 5.00GHz] (8C/8T)
GPU            #0: GeForce RTX 2070 (2304 cores, 1830 MHz)[PCIe3x16][441.20]
NVENC / CUDA   NVENC API 9.1, CUDA 10.2, schedule mode: auto
Input Buffers  CUDA, 46 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 24000/1001 fps
Vpp Filters    crop: 0,280,0,280/cspconv(p010 -> yv12(16bit))
               subburn: track #2, scale x2.00
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level 5.1
               3840x1600p 1:1 23.976fps (24000/1001fps)
Encoder Preset default
Rate Control   VBRHQ
Bitrate        0 kbps (Max: 55000 kbps)
Target Quality 20.00
Initial QP     I:20  P:20  B:20
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     24 frames
B frames       5 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on
CU max / min   auto / auto
Others         mv:Q-pel
resize: only supported on device memory./s, remain 0:33:24, GPU 12%, VE 97%, VD 29%, est out size 22836.7MB
resize: only supported on device memory./s, remain 0:33:21, GPU 12%, VE 98%, VD 25%, est out size 23339.9MB
resize: only supported on device memory.
resize: only supported on device memory.
resize: only supported on device memory./s, remain 0:33:22, GPU 16%, VE 97%, VD 24%, est out size 23342.7MB
resize: only supported on device memory./s, remain 0:33:21, GPU 14%, VE 96%, VD 24%, est out size 23368.0MB
resize: only supported on device memory./s, remain 0:33:21, GPU 16%, VE 99%, VD 30%, est out size 23605.2MB
resize: only supported on device memory./s, remain 0:33:20, GPU 17%, VE 96%, VD 31%, est out size 23603.8MB
resize: only supported on device memory.
resize: only supported on device memory./s, remain 0:33:20, GPU 10%, VE 100%, VD 26%, est out size 23555.0MB
resize: only supported on device memory./s, remain 0:33:19, GPU 8%, VE 99%, VD 26%, est out size 23811.2MB
resize: only supported on device memory./s, remain 0:33:18, GPU 9%, VE 98%, VD 28%, est out size 23856.1MB
resize: only supported on device memory./s, remain 0:33:20, GPU 75%, VE 94%, VD 26%, est out size 23960.5MB
resize: only supported on device memory./s, remain 0:33:21, GPU 70%, VE 92%, VD 27%, est out size 23941.1MB
resize: only supported on device memory./s, remain 0:33:20, GPU 63%, VE 87%, VD 25%, est out size 23976.6MB
resize: only supported on device memory.
resize: only supported on device memory./s, remain 0:33:22, GPU 74%, VE 93%, VD 26%, est out size 23965.9MB
resize: only supported on device memory./s, remain 0:33:24, GPU 71%, VE 89%, VD 24%, est out size 24014.3MB
resize: only supported on device memory./s, remain 0:33:30, GPU 72%, VE 87%, VD 26%, est out size 24194.2MB
resize: only supported on device memory./s, remain 0:33:37, GPU 72%, VE 98%, VD 28%, est out size 24346.3MB
resize: only supported on device memory./s, remain 0:33:36, GPU 76%, VE 83%, VD 25%, est out size 24358.4MB
resize: only supported on device memory./s, remain 0:33:37, GPU 85%, VE 91%, VD 30%, est out size 24372.7MB
resize: only supported on device memory.
resize: only supported on device memory./s, remain 0:33:37, GPU 63%, VE 99%, VD 29%, est out size 24378.4MB
resize: only supported on device memory./s, remain 0:33:38, GPU 66%, VE 94%, VD 27%, est out size 24340.5MB
resize: only supported on device memory./s, remain 0:33:42, GPU 69%, VE 89%, VD 25%, est out size 24355.1MB
resize: only supported on device memory./s, remain 0:33:38, GPU 26%, VE 100%, VD 31%, est out size 24220.3MB
resize: only supported on device memory.kb/s, remain 0:16:56, GPU 55%, VE 97%, VD 27%, est out size 22140.8MB

Thanks in advance!

**Comment by rigaya** [comment]
Thank you for letting me know, I was able to reproduce the issue. I'll fix this in the next release.

**Comment by bigdwg71** [comment]
As always, @rigaya thanks for all your hard work on this tool.

**Comment by rigaya** [comment]
[NVEnc 4.62](https://github.com/rigaya/NVEnc/releases/tag/4.62) has the fix for this problem included, so now it should work fine for vpp-subburn with scaling option.

**Comment by bigdwg71** [comment]
@rigaya 4.62 resolved this. Thank you very much!
