### ISSUE TITLE
Unsupported interlaced csp conversion: nv16 -> yv12

### ISSUE THREAD

**Issue by Carl-Robert** [rigaya/NVEnc#194]
I'm trying to encode an interlaced mpeg2video yuv422 video to progressive hevc output. For some reason this master video is unable to be decoded using --avhw, so I'm using --avsw which is outputting to nv16 format. Cspconv tries to then convert nv16 to yv12 for vpp-yadif, but fails.

The command is as follows `NVEncC64.exe -c hevc -o output.mkv -i input.mpg --avsw --interlace tff --vpp-yadif mode=tff`

The error I get is
```
cspconv: unsupported interlaced csp conversion: nv16 -> yv12.
Error while running filter "cspconv".
```

**Comment by rigaya** [comment]
Unfortunately, yuv422 support is limited, and only progressive video is supported. You might need to use Avisynth (ConvertToYV12(interlaced=true)) or VapourSynth for interlaced colorformat conversion.

**Comment by rigaya** [comment]
[NVEnc 4.62](https://github.com/rigaya/NVEnc/releases/tag/4.62) will be able to handle yuv422 interlaced videos via yuv444.

**Comment by rigaya** [comment]
I'll close this issue as this error should be fixed now. Please re-open if you have any related issues.

**Comment by Carl-Robert** [comment]
Can confirm, my video converts flawlessly now. Thanks!
