### ISSUE TITLE
negative overflow of subburn event start time data

### ISSUE THREAD

**Issue by AceCLee** [rigaya/NVEnc#195]
Hello Rigaya!

I found 
```
const int64_t nStartTime = av_rescale_q(m_subData->pts, av_make_q(1, AV_TIME_BASE), av_make_q(1, 1000)) - vidInputOffsetMs + tsOffsetMs;
```
in [NVEncFilterSubburn.cpp#L470](https://github.com/rigaya/NVEnc/blob/ea14e7c64a87a474fc1a64ed35ba1e749e650296/NVEncCore/NVEncFilterSubburn.cpp#L470)

may lead to negative overflow

I can't burn in subtitle with it and I get some debug information.

debug info of subburn:

> Event at -9223372036854768828, +4010: 0,0,Sub-CN,,0,0,0,,{\fad(500,500)}??????????? ???????? ?????24?????
> Event at -9223372036854768238, +2540: 113,0,Sub-CN,,0,0,0,,????????
> Event at -9223372036854764818, +4000: 1,0,Sub-CN,,0,0,0,,{\fad(500,500)}????? ???? ????  ?????? ?????? 
> Event at -9223372036854764698, +2130: 114,0,Sub-CN,,0,0,0,,??????????
> Event at -9223372036854761318, +1920: 115,0,Sub-CN,,0,0,0,,??????????????
> Event at -9223372036854758108, +3960: 116,0,Sub-CN,,0,0,0,,????????????
> Event at -9223372036854752598, +1620: 117,0,Sub-CN,,0,0,0,,??????????
> Event at -9223372036854750308, +3420: 118,0,Sub-CN,,0,0,0,,????????????
> Event at -9223372036854746178, +3750: 119,0,Sub-CN,,0,0,0,,???????????????

original start time:

> Dialogue: 0,0:00:06.98,0:00:10.99,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:07.57,0:00:10.11,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:10.99,0:00:14.99,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:11.11,0:00:13.24,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:14.49,0:00:16.41,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:17.70,0:00:21.66,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:23.21,0:00:24.83,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:25.50,0:00:28.92,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:29.63,0:00:33.38,Sub-CN,,0,0,0,,
> Dialogue: 0,0:00:34.55,0:00:38.01,Sub-CN,,0,0,0,,

Thanks!

**Comment by rigaya** [comment]
I'm sorry but I cannot get the point...

- m_subData->pts > 0 as you have shown in original start time
- to_millisecond(m_subData->pts) >= vidInputOffsetMs
- tsOffsetMs = 0

So we should not get a negative output here.

**Comment by AceCLee** [comment]
In c++, if the operands of an operator have differing types,  those operands are ordinarily converted to the same type. When the signedness differs, c++ compiler will treat the signed operand as unsigned operand.

For instance,

```
#include <iostream>
using namespace std;

int main(int argc, const char **argv)
{
    unsigned int a = 10;
    // b will be saved in memory with Two's complement form
    int b = -50;
    // b will be treated as a normal unsigned int,
    // -50 in Two's complement form is the same as 4294967246 in memory
    // result will be 4294967256
    cout << a + b << endl;
    return 0;
}
```

You can try to run this code.

In my opinion, maybe signedness of operands in
```
const int64_t nStartTime = av_rescale_q(m_subData->pts, av_make_q(1, AV_TIME_BASE), av_make_q(1, 1000)) - vidInputOffsetMs + tsOffsetMs;
```
 differs.

**Comment by rigaya** [comment]
Unfortunately, all of the operands here was int64_t(singed).

As the value is near ‭AV_NOPTS_VALUE (0x8000000000000000), I'm now assuming that "vidInputOffsetMs" was 0x8000000000000000. I've tried a work around for it in [NVEnc 4.62](https://github.com/rigaya/NVEnc/releases/tag/4.62), so would you please have a try?

**Comment by AceCLee** [comment]
NVEnc 4.62 works successfully.
ありがとうございます。

**Comment by rigaya** [comment]
Thank you for confirming, nice to hear it now works.
