### ISSUE TITLE
werid tags in encoded mkvs

### ISSUE THREAD

**Issue by devil40xxx** [rigaya/NVEnc#196]
I had been noticed it for a lwhile.

After encoded with " --audio-copy  --sub-copy --chapter-copy" to mkv,  the files will be add  one "goble tags" and 1~2 "tags ".

It can be check in the MTVoolNix GUI.

After removed them and re-multiplexed with MTVoolNix. The file size was significant decreased.

**Comment by rigaya** [comment]
About "tags" you have mentioned, do you mean the ones below?

![image](https://user-images.githubusercontent.com/815947/73609689-a254a280-4613-11ea-96ff-d23abeae6f59.png)

They are copied by NVEncC from the input file, and don't look like taking some much size... (might depend on the input)

**Comment by devil40xxx** [comment]
![img](https://user-images.githubusercontent.com/44527608/73656220-a1cb1300-46ca-11ea-8aeb-90fe0b282180.png)

It looks like this way.  

@rigaya

**Comment by rigaya** [comment]
Would you please show it in the "Info tool" tab on the left side of MKVToolnix? It can show the number and size of the tag.

**Comment by devil40xxx** [comment]
[infotool-info.txt](https://github.com/rigaya/NVEnc/files/4148222/Body.Parts.1991.1080p.BluRay.REMUX.AVC.DTS-HD.MA.2.0-FGT.1.opus_HEVC10R25.txt)

I outputed the info file for you to check. And after double checked I found some tags add by my pre-aduios processing by FFMPEG. But I am quite sure nvenc added at least one tag in the process.

@rigaya

**Comment by rigaya** [comment]
Thank you for providing the info. As you have
```
|+ Tags size 1088 data size 1082
```
the tag data is rather small, which could be ignored (just 1KB).

I'm now thinking the file size reduction is not related to the presence of the tag, but just simply by remuxing.

**target**
Output of NVEncC, 6,583,211,395 byte
![image](https://user-images.githubusercontent.com/815947/73662459-2de73580-46df-11ea-9e32-0234ab8a2453.png)

**Remuxed by MKVToolnix, removing tags** →　6,548,432,363 byte
**Remuxed by MKVToolnix, with tags** → 6,548,432,423 byte (somehow little bit smaller)

Regardless of the presence of the tag, around 40MB is saved.

It seems like some kind of optimization(?) by MKVToolnix reduces the file size.

**Comment by devil40xxx** [comment]
I agreed. 


> It seems like some kind of optimization(?) by MKVToolnix reduces the file size.
