### ISSUE TITLE
Feature Request: Add metadata without encode

### ISSUE THREAD

**Issue by tazlord** [rigaya/NVEnc#199]
Thank you for creating this wonderful tool.

I was unable to find any options that would allow you to modify/add metadata to a video file without encoding it. This type of feature would be very useful. 

Maybe allowing a "copy" video codec and specifying the metadata as usual would be the easiest method? Specifying "copy" codec ignores any video encoding specific options. 

Example for HDR HEVC:
`--codec copy --colormatrix <string> --colorprim <string> --transfer <string> --master-display <string> -i <input_file> -o <output_file>`

Above options will disable encoding and produce a new file with metadata tags added/modified.

**Comment by villos** [comment]
parse hdr info to json hdr10plus_parser
and generate file  again with hdr10plus_gen

**Comment by rigaya** [comment]
I’m sorry but I don’t have plans to support video copy features.
