### ISSUE TITLE
Variable QP?

### ISSUE THREAD

**Issue by 404Fox** [rigaya/NVEnc#20]
I noticed there is settings for a minimum, maximum, and initial QP. This would imply there is a variable QP mode, although such a mode is not specified as an option.

**Comment by rigaya** [comment]
My understanding is that minimum, maximum, and initial QP which can be set throught NVENC SDK is for bitrate modes (such as VBR, VBRHQ, ...).

It limits or suggests QP used in bitrate modes, and unfortunately Variable QP does not exist in NVENC SDK.
