### ISSUE TITLE
vpp-subburn doesn't import external subtitles with given filename

### ISSUE THREAD

**Issue by dibolek** [rigaya/NVEnc#200]
When i use this command line:

`--vpp-subburn brightness=-0.1,filename="J:\TVShows\The.Unicorn\Season.1\The.Unicorn.S01E05.No.Small.Parts.(WEBRip, 720p, HEVC, AAC, 2ch).ass"`

i get this message at nvencc64 console output:

`Could not find subtitle track #2, vpp-subburn for track #2 will be disabled.`

but with this:

`--vpp-subburn brightness=-0.1,filename="J:\TVShows\The.Unicorn\Season.1\napisy.ass"`

nvencc works just as intended.

BTW What does that console output mean and does it make any changes to encoded video output:
`Neither PlayResX nor PlayResY defined. Assuming 384x288`

Thanks.

**Comment by rigaya** [comment]
Filename with comma (",") needs escape, as it separates options names such as "brightness" or "filename", therefore please use [NVEnc 4.63](https://github.com/rigaya/NVEnc/releases/tag/4.63) with command lines below.
```
--vpp-subburn brightness=-0.1,filename="\"J:\TVShows\The.Unicorn\Season.1
\The.Unicorn.S01E05.No.Small.Parts.(WEBRip, 720p, HEVC, AAC, 2ch).ass\""
```

**Comment by dibolek** [comment]
Thank you for explanation and quick implementation. Now it works fine.
