### ISSUE TITLE
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)

### ISSUE THREAD

**Issue by TheJulkka** [rigaya/NVEnc#202]
NVEncC (x64) 4.63 (r1367) by rigaya, Feb 10 2020 14:25:09 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (18362)
CPU            Intel Core i7-4790K @ 4.00GHz [TB: 4.40GHz] (4C/8T)
GPU            #0: GeForce RTX 2070 SUPER (2560 cores, 1905 MHz)[PCIe3x16][442.19]
NVENC / CUDA   NVENC API 9.1, CUDA 10.2, schedule mode: auto
Input Buffers  CUDA, 46 frames
Input Info     Avisynth+ 2.60(yv12)->nv12 [AVX2], 1920x1080, 24000/1001 fps
Vpp Filters    copyHtoD
cspconv(nv12 -> p010)
Output Info    H.265/HEVC main10 @ Level auto
1920x1080p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        0 kbps (Max: 28800 kbps)
Target Quality auto
Initial QP     I:6  P:6  B:6
QP range       I:8-18  P:8-18  B:8-18
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       5 frames [ref mode: each]
Ref frames     5 frames, MultiRef L0:auto L1:auto
AQ             off
CU max / min   auto / auto
Others         mv:Q-pel aud
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
nvenc : Error on NvEncEncodePicture: 17 (NVENC HW encode driver requires more input buffers to produce an output bitstream)
encoded 2208 frames, 154.74 fps, 22130.56 kbps, 242.95 MB
encode time 0:00:14, CPU: 40.7, GPU: 8.1, VE: 92.8, GPUClock: 2012MHz, VEClock: 1864MHz
frame type IDR   41
frame type I     41,  total size   10.65 MB
frame type P    924,  total size  125.62 MB
frame type B   1243,  total size  106.69 MB

Start:    17.10.30
End:      17.10.46
Duration: 00:00:15

General
Complete name        : E:\Video\How_Not_Summon_Demon_D2\extra\How_Not_Summon_Demon_D2_t09_temp\How_Not_Summon_Demon_D2_t09_new_out.h265
Format               : HEVC
Format/Info          : High Efficiency Video Coding
File size            : 243 MiB

Video
Format               : HEVC
Format/Info          : High Efficiency Video Coding
Format profile       : Main 10@L4@High
Width                : 1 920 pixels
Height               : 1 080 pixels
Display aspect ratio : 16:9
Frame rate           : 23.976 (24000/1001) FPS
Color space          : YUV
Chroma subsampling   : 4:2:0
Bit depth            : 10 bits

**Comment by TheJulkka** [comment]
i got that error while encoding and the video output is a bit choppy compared to the source.

**Comment by SiV44** [comment]
When the lookahead option is turned off, there is no error.

**Comment by rigaya** [comment]
Thanks you for reporting this problem, shall be fixed in [NVEnc 4.64](https://github.com/rigaya/NVEnc/releases/tag/4.64).

**Comment by SiV44** [comment]
No longer displays an error.
Thank you very much.

**Comment by TheJulkka** [comment]
i checked my self and works fine now thanks.

**Comment by rigaya** [comment]
Thank you for confirming!
