### ISSUE TITLE
Questions about hdr2sdr

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#204]
doc states for hable:
>Trys to preserve both bright and dark detailes, but with rather dark result. You may specify addtional params (a,b,c,d,e,f) for the hable tone-mapping function below.
and
> example3: using hdr2sdr (hable tone-mapping) and setting the coefs (this is example for the default settings)
--vpp-colorspace hdr2sdr=hable,source_peak=1000.0,ldr_nits=100.0,a=0.22,b=0.3,c=0.1,d=0.2,e=0.01,f=0.3,w=11.2

-> What happend to 'w' ?

Also do the other modes need source_peak and/or ldr_nits?

**Comment by rigaya** [comment]
Please forget about "w", I forgot to remove it from the examples. it's now calculated by source_peak / ldr_nits. 

It is the same for other modes (mobius, reinhard).

**Comment by rigaya** [comment]
I'll close this issue, as the question has been answered.
