### ISSUE TITLE
nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

### ISSUE THREAD

**Issue by Abu3safeer** [rigaya/NVEnc#207]
Hello, I am really happy with NVEnc, it is very stable and fast, and gets the job done quickly. 
I have encoded several videos with no issues at all, but I came across one video that I cannot encode with this encoder at all.

First of all I tried using x264 to make sure the video is encodable and not corrupted, and it worked just fine with x264.

This is the mediainfo for the video:
```
Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.1
Format settings             : CABAC / 6 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 6 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 24 min 13 s
Bit rate                    : 2 821 kb/s
Width                       : 1 976 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 1.85:1
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Standard                    : NTSC
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.055
Stream size                 : 489 MiB (97%)
Default                     : Yes
Forced                      : No
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709
```

This is the command:
```
NVEncC64.exe --cqp 18 --preset quality --level 4 -i video.avs -o 168.264
```
As you might noticed, I use avs file to burn a subtitle on the video.

This is the error message, I even used ---log and it has the same output message:
```
nvenc : Failed to Initialize the encoder
nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
```

**Comment by rigaya** [comment]
Please try removing "--level 4", as it only allows up to 1920x1080. I think that should be the reason for your error.

**Comment by Abu3safeer** [comment]
It worked, thank you very much, 
what is the lower level that can handle this resolution, because I use level 5 to make my video playable on old devices.

**Comment by rigaya** [comment]
I think level 4.2 should be the minimum. If you require level 4.1 or below, you might need to crop the video into 1920x1080.

Please refer to the table below for details.
https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels

**Comment by Abu3safeer** [comment]
Thank you, I use x264 with level 4, and looks like it just works.
I didn't expect to have such a weird aspect ratio, so I will use x264 on this file only.

Thank you again.
