### ISSUE TITLE
Feature Request - Loading BDMV PLAYLIST

### ISSUE THREAD

**Issue by 2ndR** [rigaya/NVEnc#209]
Or you need to enter multiple split files

**Comment by rigaya** [comment]
You shall be able to select BDMV playlist by using bluray protocol with [--input-option](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--input-option-string1string2) starting from [NVEnc 4.68](https://github.com/rigaya/NVEnc/releases/tag/4.68).

Selecting playlist 1 could be done by the option below.
```
-i bluray:D:\ --input-option palylist:1
-i bluray:BD.iso --input-option palylist:1
```

Please note that the BDMV must be decrypted.

**Comment by 2ndR** [comment]
It is working as expected. Thank you
