### ISSUE TITLE
Updated Windows binary?

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#21]
Latest version over at GoogleDrive (https://drive.google.com/drive/folders/0BzA4dIFteM2dS1ZUT1FjTnF3Q0E) is 3.23, your blog (http://rigaya34589.blog135.fc2.com/blog-entry-977.html) states the latest to be 3.24.
-> would be nice if you could update the version over in the GoogleDrive.
Thanks. :)

**Comment by rigaya** [comment]
I have released 3.25, and have updated both Onedrive & Googledrive binary.

**Comment by Selur** [comment]
Thanks!
