### ISSUE TITLE
Platform Option - Linux

### ISSUE THREAD

**Issue by Eldenissio** [rigaya/NVEnc#210]
Is it possible to compile NVEncC64 to work on Linux natively?

**Comment by rigaya** [comment]
Sorry, No. I will not have enough time to maintain the app for 2 platforms.

**Comment by rigaya** [comment]
I've changed my mind and added initial support for Linux in [NVEnc 5.01](https://github.com/rigaya/NVEnc/releases/tag/5.01).
Currently, I've tested build on Ubuntu now, but possibly should work for other distributions.

**Comment by rigaya** [comment]
I'll close this issue, as the option has been added. Please let me now if you have any problems.
