### ISSUE TITLE
Can i convert thousands of .jpg images to video?

### ISSUE THREAD

**Issue by elemention** [rigaya/NVEnc#211]
How can i convert thousands of .jpg images to video?

**Comment by rigaya** [comment]
When the filename of  images are like,
F:\temp\images_000000.jpg
F:\temp\images_000001.jpg
F:\temp\images_000002.jpg
F:\temp\images_000003.jpg
...

you can use the following command line. 
```
x64\NVEncC64.exe -i F:\temp\images_%06d.jpg --input-format image2 -o F:\temp\test.mp4
```

**Comment by elemention** [comment]
Many thanks. Working great!

The list of my files is something like this:

F:\temp\2020'03'08-**19'28'53**__Adobe Premiere Pro_as_.jpg
F:\temp\2020'03'08-**19'29'09**__Adobe Premiere Pro_as_.jpg
F:\temp\2020'03'08-**19'29'55**__Adobe After Effects_as_.jpg
F:\temp\2020'03'08-**19'30'11**__Adobe Premiere Pro_as_.jpg
F:\temp\2020'03'08-**19'31'01**__Adobe After Effects_as_.jpg
F:\temp\2020'03'08-**19'32'58**__Adobe After Effects_as_.jpg
F:\temp\2020'03'08-**19'34'15**__Adobe After Effects_as_.jpg
...

Is there a solution to convert any image, regardless of name, by file modification time or according to the name based on the date from the example above?
Of course, I can rename files using "bulk rename utility", but I would like to exclude the renaming operation, if possible.

**Comment by rigaya** [comment]
Unfortunately, I don't know any more than this we can do now.
