### ISSUE TITLE
--chapter-copy not working when source is MPLS

### ISSUE THREAD

**Issue by MartyMcNuts** [rigaya/NVEnc#215]
Hello and thanks for this great tool!!

I've been using NVEncC64 to convert some of my BD and UHD movies and have noticed that when the input source is the playlist, --chapter-copy does not copy the chapters from the source to the output file.

example command:

NVEncC_4.69_x64\NVEncC64 --avhw -i bluray:N:\MOVIE_NAME\ --input-option playlist:00001 --chapter-copy --audio-copy 1 --output-res 3840x2160 --fps 23.976 --codec h265 --preset quality --level 5.0 --profile main10 --tier high --output-depth 10 --lookahead 32 --vbrhq 25000 --output-buf 64 --colorprim bt2020 --colormatrix bt2020nc --transfer smpte2084 --chromaloc 2 --master-display copy --max-cll copy -o N:\MOVIE_NAME\CONVERTED_MOVIE.mkv

When you get a moment, can you please take a look.

Cheers
MM

**Comment by rigaya** [comment]
--chapter-copy is a options to copy chapters which is extracted by libavformat (the demuxer).

Unfortunately, --chapter-copy will not work when reading MPLS, as libavformat seems to not extract chapters when using bluray protocol. I've tested not only NVEncC but also with ffmpeg, but could not work out to copy chapters from MPLS.

One way to copy chapters might be to first copy the playlist to mkv format with chapters, and transcode afterwards.

**Comment by MartyMcNuts** [comment]
Ok. Thanks for looking into it.
