### ISSUE TITLE
HELP light problem at nvenc

### ISSUE THREAD

**Issue by YinnVI** [rigaya/NVEnc#216]
When i try to encode with NVENC the results of the light are different from QSVENC it appears darker in NVENC, 

**Encoder : StaxRip 2.0.8.0**

How do i make it as bright as in QSVENC? PLEASE HELP

![ASLI](https://user-images.githubusercontent.com/26527969/78537894-61972680-781a-11ea-916b-11b0e34bc51e.jpg)
Original file without being encoded
-----------
![NORMAL](https://user-images.githubusercontent.com/26527969/78537293-7626ef00-7819-11ea-9891-13423feb4b16.jpg)
This QSVENC
-----------
![NOUK](https://user-images.githubusercontent.com/26527969/78537368-9a82cb80-7819-11ea-88f8-1ccb36ea5ae9.jpg)
And THis NVENC
-----------
How do i make it as bright as in QSVENC? PLEASE HELP

Sorry my english bad

**Comment by djrooli** [comment]
what command line did you use? also mediainfo of the file. (video part only)

**Comment by YinnVI** [comment]
> what command line did you use? also mediainfo of the file. (video part only)

QSVENC:
--codec hevc --profile main10 --bframes 5 --ref 5 --b-adapt --direct-bias-adjust --mbbrc --output-buf 128 --input-buf 3 --output-thread 1 --colorrange full --fullrange --icq 29

NVENC:
--cqp 32 --codec h265 --preset quality --profile main444 --tier high --output-depth 10 --aq-strength 3 --aq --bref-mode middle --ref 5 --cuda-schedule auto --output-buf 128 --colorrange full --mv-precision q-pel --cabac

**Comment by rigaya** [comment]
I think you shall not need --colorrange full in most cases, and that might be causing the problem here.

**Comment by YinnVI** [comment]
> I think you shall not need --colorrange full in most cases, and that might be causing the problem here.

Thanks
