### ISSUE TITLE
support for rotate/transpose video

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#217]
would be nice if NVEncC could flip and rotate a video like ffmpegs transpose/transpose_npp filters.

**Comment by rigaya** [comment]
[NVEnc 5.00](https://github.com/rigaya/NVEnc/releases/tag/5.00) adds [--vpp-rotate](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-rotate-int) for rotation, and [--vpp-transform](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-transform-param1value1param2value2) for transpose and flips.

**Comment by Selur** [comment]
Thanks! :)

**Comment by rigaya** [comment]
I'll close this issue now.
