### ISSUE TITLE
Can you add adjustable Temporal AQ for NVENC

### ISSUE THREAD

**Issue by Cuberlain** [rigaya/NVEnc#219]
Hello Rigaya!

Can you add adjustable Temporal AQ for NVENC? Because only turn on and turn off option is possible in NVENC.

**Comment by rigaya** [comment]
Unfortunately, adjustment for temporal AQ is not provided by the NVENC SDK, so it cannot be added.

**Comment by rigaya** [comment]
I'll close this topic as the question has been answered.

**Comment by hydra3333** [comment]
Just wondering, as the flag can be set in ffmpeg ?
