### ISSUE TITLE
VFW/Directshow version of NVENC

### ISSUE THREAD

**Issue by Cuberlain** [rigaya/NVEnc#220]
Hello Rigaya! 

There is a really *enormous demand* for a VFW/Directshow version of NVENC among users.
IS it possible to implement your existing NVENC codec in VFW/Directshow codec, or somebody must rewrite it from the basics?

Can you make such codec with the very same options what your present NVENC  provides?

Best regards!
Bye!

**Comment by rigaya** [comment]
> IS it possible to implement your existing NVENC codec in VFW/Directshow codec, or somebody must rewrite it from the basics?
It's a completely different interface. so you must rewrite it, and you need somebody who knows of the basis of VFW/Directshow.

**Comment by stax76** [comment]
It would be interesting to hear why you think VFW has enormous demand. It's probably only a minority and has no real advantages.

**Comment by Cuberlain** [comment]
> 
> 
> It would be interesting to hear why you think VFW has enormous demand. It's probably only a minority and has no real advantages.

I don't consider content creators as minority, who record/capture lossless videos from their DSLRs to their computer storage. Mayvbe it is minority from the viewpoint of DVD blu-ray grabbers who spread films illegally on torrent sites....

**Comment by bilogic** [comment]
Supporting VFW makes it usable in any other encoding software that uses VFW, akin to being open sourced.

**Comment by bilogic** [comment]
Maybe this can help whoever interested in understanding VFW https://github.com/jackun/openencodevfw
The trouble have is, I don't understand NVENC nor VFW 😂

**Comment by bilogic** [comment]
See also https://www.codeproject.com/Articles/421869/H-264-CUDA-Encoder-DirectShow-Filter-in-Csharp

**Comment by bilogic** [comment]
Or modify https://github.com/MasterNobody/x264vfw/blob/master/codec.c to use NVENC functions instead

**Comment by rigaya** [comment]
I'm sorry, but currently I have no plan for this.
