### ISSUE TITLE
 The problem of copying multiple audio tracks from one audio track

### ISSUE THREAD

**Issue by shookgao** [rigaya/NVEnc#222]
Hello Rigaya!
I want to convert one audio track into two audio tracks, one copy, and one coded as ac3. I wrote it this way, but the result is only one ac3 audio track. How should I modify it?
`nvencc64 --avhw --codec hevc --audio-copy 1 --audio-codec 1?ac3 --audio-bitrate 640 -i i.mkv -o o.mkv`

**Comment by rigaya** [comment]
Unfortunately, copying and encoding the same audio track is not possible in current implementation (it'll be complicated to implement).

**Comment by shookgao** [comment]
ffmpeg can use -map to solve this problem. I don't know if Nvencc's pipe can be used. ffmpeg is used like this:
`ffmpeg -i a.mkv -map 0:0 -map 0:1 -map 0:1 -c:v libx265 -c:a:0 copy -c:a:1 ac3 b.mkv`

**Comment by quamt** [comment]
Here you go:

`ffmpeg -y -i "Black1.mp4" -map 0:0 -map 0:1 -map 0:1 -codec:a copy -f nut - | NVEncC64 --avsw -i - --audio-copy 1 --audio-codec 2?ac3 -o "BlackEnc.mp4"`

You need to adjust video as you need. This is only to show how to use one audio and output to 2 streams one is copied one is ac3 audio.

**Comment by shookgao** [comment]
Hi quamt, 
Thank you very much for your reply, but it seems that this method can not use hardware acceleration, I finally gave up this idea.

**Comment by quamt** [comment]
@shookgao 
Did you try:
`ffmpeg  -hwaccel cuda -y -i "Black1.mp4" -map 0:0 -map 0:1 -map 0:1 -codec:a copy -codec:v rawvideo -pix_fmt yuv420p -f nut - | NVEncC64 --avsw -i - --audio-copy 1 --audio-codec 2?ac3 -o "BlackEnc.mp4"`

**Comment by shookgao** [comment]
@quamt 
I tried it, this method can achieve the dual track effect I want, 
But there are still two problems, one is that the subtitles don't know how to transmit, and the other is that the speed is still not very satisfactory, the speed of using pipe in this way is about 70FPS, and the speed of directly using nvencc is 370FPS!
Although the speed is not very satisfactory, but I still hope to get an answer to the problem of subtitles, thank you!

**Comment by quamt** [comment]
@shookgao 
For highest possible speed I suggest using:
`ffmpeg -i "FILE.mkv" "FILE.ass" "FILE.ac3"  && "D:\NVEncC\NVEncC64.exe" --avhw --interlace auto --vpp-afs preset=anime --audio-source "FILE.ac3":1?codec=aac;bitrate=384 --audio-source "FILE.ac3":copy --sub-source "FILE.ass" -i "FILE.mkv" -c avc -u quality -o "FILE_enc.mkv"`

**Comment by shookgao** [comment]
Thanks for the reply, I think this problem is solved.
