### ISSUE TITLE
 Compilation fails under ubuntu18.04

### ISSUE THREAD

**Issue by shookgao** [rigaya/NVEnc#225]
All of the above are successful, but failed in the sixth step, and prompted when executing ./configure:
`checking for cuda (CUDA_PATH=/usr/local/cuda)...cuda not supported.`
CUDA installation should be no problem, ffmpeg can already use hardware encoding and decoding normally

**Comment by rigaya** [comment]
> checking for cuda (CUDA_PATH=/usr/local/cuda)...cuda not supported.

Maybe the CUDA_PATH is pointing the wrong directory.

Do you have following files installed?
```
/usr/local/cuda/include/cuda.h
/usr/local/cuda/lib64/libcuda.so
/usr/local/cuda/lib64/libcudart.so
/usr/local/cuda/lib64/libnvrtc.so
/usr/local/cuda/lib64/libnppif.so
/usr/local/cuda/lib64/libnppig.so
/usr/local/cuda/lib64/libnppc.so
```

For further information, please overwrite the "configure" script with the attached one and rerun.
[configure.zip](https://github.com/rigaya/NVEnc/files/4622511/configure.zip)

**Comment by shookgao** [comment]
I have completed the compilation, thank you; the reason for the problem may be that I have installed other versions of the graphics driver; Later, I installed a new virtual machine and installed the driver completely in your way without encountering any problems.

**Comment by rigaya** [comment]
Thank you for confirming, nice to hear it compiles now.
