### ISSUE TITLE
 Hope to add the option to set the default stream

### ISSUE THREAD

**Issue by shookgao** [rigaya/NVEnc#226]
Hello rigaya, 
 Hope to add the option to set the default stream，ability to set default video, audio and subtitles for output files, the parameter corresponding to ffmpeg is `-disposition:a:0 default`,  there is also a function to clear the original video tag, the corresponding parameter is: `-map_metadata -1`.
These two parameters are very useful for generating clean output files, I hope to consider increasing, thank you！

**Comment by rigaya** [comment]
I've added new options to [NVEnc 5.02](https://github.com/rigaya/NVEnc/releases/tag/5.02), which enables us to set default stream and handle metadata. Please check for the link for the details and examples.

**For setting default stream**
- [--audio-disposition](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--audio-disposition-intstringstring)
- [--sub-disposition](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--sub-disposition-intstring)

**For metadata handling (including clearing out metadata)**
  - [--metadata](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--metadata-string-or-stringstring)
  - [--video-metadata](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--video-metadata-string-or-stringstring)
  - [--audio-metadata](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--audio-metadata-string-or-stringstring)
  - [--sub-metadata](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--sub-metadata-string-or-stringstring)

**Comment by shookgao** [comment]
@rigaya Thank you very much! I tried it, there seems to be a bug, --audio-copy and --sub-copy are invalid.
`nvencc64 --avhw --profile main10 --preset quality --codec hevc  --crop 0,140,0,140  --audio-copy 2 --sub-copy 12 --chapter-copy --metadata clear --video-metadata clear --audio-metadata clear --sub-metadata clear --audio-disposition 1?default,forced --sub-disposition 1?default,forced -i "00356.m2ts" -o "c:\\mys\\00356.m2ts.mkv"
--------------------------------------------------------------------------------
c:\\mys\\00356.m2ts.mkv
--------------------------------------------------------------------------------
Max B frames are 0 frames.
NVEncC (x64) 5.02 (r1541) by rigaya, May 23 2020 19:20:00 (VC 1925/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            Common KVM processor (8C/8T)
GPU            #0: GeForce GTX 1050 (640 cores, 1455 MHz)[PCIe3x16][445.87]
NVENC / CUDA   NVENC API 9.1, CUDA 11.0, schedule mode: auto
Input Buffers  CUDA, 17 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
Vpp Filters    crop: 0,140,0,140/cspconv(nv12 -> yv12(16bit))
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
               1920x800p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc, dts, ac3, ac3, ac3, ac3, subtitle#1, subtitle#2,
                subtitle#3, subtitle#4, subtitle#5, subtitle#6, subtitle#7,
                subtitle#8, subtitle#9, subtitle#10, subtitle#11, subtitle#12,
                subtitle#13 => matroska
Encoder Preset quality
Rate Control   CQP  I:20  P:23  B:25
Lookahead      off
GOP length     240 frames
B frames       0 frames [ref mode: disabled]
Ref frames     3 frames
AQ             off
CU max / min   auto / auto
Others         mv:auto`

**Comment by rigaya** [comment]
You want to copy audio#2 and sub#12, am I right? Then how about using option below?

nvencc64 --avhw --profile main10 --preset quality --codec hevc --crop 0,140,0,140 --audio-copy 2 --sub-copy 12 --chapter-copy --metadata clear --video-metadata clear --audio-metadata 2?clear --sub-metadata 12?clear --audio-disposition 2?default,forced --sub-disposition 12?default,forced -i "00356.m2ts" -o "c:\mys\00356.m2ts.mkv"

**Comment by rigaya** [comment]
I'll close this issue, as the requested feature has been already added. Please let me now if you face problem with this feature.
