### ISSUE TITLE
DTS 7.1 to AC3 5.1, the result is mono

### ISSUE THREAD

**Issue by shookgao** [rigaya/NVEnc#227]
`nvencc --avhw --preset quality --profile main10 --codec hevc --audio-codec 1?ac3 --audio-bitrate 1?640 -i a.mkv -o b.mkv`
DTS 5.1 to AC3 5.1, the result is no problem, but DTS 7.1 to AC3 5.1, the result is mono AC3;
If you add the parameter `--audio-stream 1?5.1`, then you can also get the 5.1 channel AC3, but I do n’t know if there is any problem.

**Comment by quamt** [comment]
@shookgao 
Did you try adding 
--audio-stream 1?5.1

**Comment by rigaya** [comment]
It is a problem caused by trying to convert into ac3 7.1ch, but 7.1ch not supported by ac3 codec.

It shall be proper to explicitly convert into 5.1ch by "--audio-stream 1?5.1" as you have mentioned.

**Comment by shookgao** [comment]
Thanks.
