### ISSUE TITLE
Ubuntu18.04にてpthreadのコンパイルエラーがでる

### ISSUE THREAD

**Issue by mimaburao** [rigaya/NVEnc#228]
### 概要
コンパイル時にpthread関連のエラーがでる。原因はconfigureが吐く、config.makのライブラリリンクを修正した。すると問題なくnvenccが生成された。
### 対処
公式通りに環境を整える。make -j4後にpthreadにてエラーが発生した場合リンクがうまく行っていない場合がある。
config.maxのファイルにおいてLDFLAGSの行で、
-pthreadを-lpthreadとすべて直す。
"-l"としてライブラリを指定しないといけないが、抜けているpthreadが散見された。これは何故なのか原因は不明である。

### 環境
- Linux Mint19.8(Ubuntu18.04系統)
- cmake 3.17

**Comment by rigaya** [comment]
"-pthread" はgccの[コンパイル・リンク時に使用するオプション](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html)ですが、nvccでリンクする際の"-lpthread"と混ぜてしまったのが原因かと思います。

[linuxブランチ](https://github.com/rigaya/NVEnc/tree/linux)のほうで、ご指摘のように"-lpthread"のみを使用するよう対応を試みました。  
- configureへの変更 → 8ec0a4c
- テストビルド: OK → https://travis-ci.org/github/rigaya/NVEnc/builds/687905678

もともと手元ではエラーが発現しないため確証はないですが、これでお試しいただけますでしょうか。問題が解消できていましたらマージします。

**Comment by mimaburao** [comment]
45ed015の対応で解決しました。

**Comment by rigaya** [comment]
45ed015 で解決したとのことで安心しました。masterブランチにマージしました。

テストや調査、ありがとうございました。
