### ISSUE TITLE
--sub-source xxx.sup, subtitles are messy

### ISSUE THREAD

**Issue by shookgao** [rigaya/NVEnc#229]
`--sub-source xxx.sup`, sometimes it ’s normal, sometimes it ’s advanced, sometimes it ’s overlapped, and it feels like the subtitle timeline is confusing.
I have tested on both Windows and Linux and both have the same problem

**Comment by rigaya** [comment]
It depends on the combination of the input video & sup file, might be that the timestamp are not matched. There is a case that the timestamp of the video does not start from 0.

**Comment by shookgao** [comment]
Indeed!
