### ISSUE TITLE
VUI HDR not applying 

### ISSUE THREAD

**Issue by wolfhowling** [rigaya/NVEnc#23]
None of the VUI info applies unless --fullrange is set or the --videoformat is set to something other than undef

**Comment by drSHLEFF** [comment]
+100

**Comment by wolfhowling** [comment]
Can it be set to apply on --videoformat undef?

**Comment by rigaya** [comment]
Thanks for reporting.
It has been fixed with 3.26, now you can set VUI info without --videoformat or --fullrange.

**Comment by drSHLEFF** [comment]
Thank you. It works :)
And to make it absolutely perfect, it would be nice to add the possibility of integrating HDR metadata into the video track (--master-display) for full hardware player support.
For example: 
MasteringDisplay_ColorPrimaries : R: x=0.680000 y=0.320000, G: x=0.265000 y=0.690000, B: x=0.150000  y=0.060000, White point: x=0.312700 y=0.329000
MasteringDisplay_Luminance : min: 0.0050 cd/m2, max: 1000.0000 cd/m2
MaxCLL : 1000 cd/m2
MaxFALL : 293 cd/m2

P.S: I know that the NVIDIA SDK doesn't support HDR metadata integration, but we must figure out how to do it :)

**Comment by alando22** [comment]
Yes, please! HDRMetadata ist very nessasary.

**Comment by rigaya** [comment]
[NVEncC 3.28](https://github.com/rigaya/NVEnc/releases/tag/3.28) adds options --master-display, --max-cll. (checked with MediaInfo)

**Comment by drSHLEFF** [comment]
Oh, yeee! Thank you 👍
