### ISSUE TITLE
Copy audio details to the field "name" (mkv)

### ISSUE THREAD

**Issue by zbijelic** [rigaya/NVEnc#230]
Hello,

It will be great if you can add the encoding details of the audio track to the audio field "name".

You list the info before encoding :

#2:ac3/5.1(side) -> **aac/5.1(side)/192kbps**,
#3:dca/5.1(side) -> **aac/5.1(side)/192kbps**
#4:truehd/7.1 -> **aac/7.1/192kbps**

with the container matroska it will not be a problem, but with other containers I'm not sure...

**Comment by rigaya** [comment]
I'm sorry, but I was not able to get what you exactly mean by "the audio field "name"". Audio stream information such as codec, channels, samplerates, disposition and metadata are copied to the output file. Not all are shown in the log, as I think it will be too long and tedious to be always shown in the log.

I think at least we don't have problem when using matroska, mp4/mov and ts...

**Comment by rigaya** [comment]
Unfortunately, I have no plan for this issue, so I'll close this issue.
