### ISSUE TITLE
configure時にlibav*,libswresampleでnoの場合の対処

### ISSUE THREAD

**Issue by mimaburao** [rigaya/NVEnc#232]
### 概要
5.02のバージョンにおいてconfigureでlibav関連、libswresampleでnoとなってしまう場合の対処である。
### 対処方法
すべて公式の通りインストールを行う。configureの段階で跳ねられる場合に、
`./configure --extra-ldflags="-L/usr/local/cuda/lib64"`
とするとconfigureが通る場合がある。
これは、ライブラリのリンクが見つけられない場合が主な障害である。そこで、ライブラリが存在するcudaをインストールした場所(/usr/local/cuda/lib64)を直に指定する。こうすることでリンカがライブリマウントを行うことができる。そして、makeは公式どおり行くはずである。
### 要因
私の場合であるけど、CUDAを別にインストールした。もしくはffmpegをオプションを付けたいために自分でビルト&インストールした場合に起こるようだ。この場合は/usr/local/libだけをリンカは探しにいってしまう。

### 環境
linux mint 19.3
cuda 10.2

**Comment by rigaya** [comment]
おそらくご自身でビルドされたffmpegでCUDAを使用したため、そのffmpegのリンク時にCUDA関係のライブラリが追加で必要となったためと思います。

<自ビルドしたffmpegインストール先>/lib/x64/pkgconfig/libav*.pcにffmpegのリンク時に必要な情報が書いてあるはずなので、configureはそれを読み取って必要なリンクオプションを決定しています。何らかの理由で、本来必要なはずの"-L/usr/local/cuda/lib64"が"*.pc"から欠落したのだと思われます。

ただ、不足があればご指摘のように--extra-ldflagsで対応いただければと問題ないかと思います(そのためのオプションなので…)。

**Comment by mimaburao** [comment]
了解です。ありがとうございました。
