### ISSUE TITLE
About FPS of output video

### ISSUE THREAD

**Issue by RinaOgata** [rigaya/NVEnc#234]
The source video framerate is 60.00, but I want to change it to 29.97.

I use the command '--fps 29.97', the total time doubled.

Is there anyone who can help me solve the problem?

**Comment by rigaya** [comment]
Have you tried "--vpp-select-every 2"?

You shall be able to halve the fps (60.00 → 30.00).

If you require exactly 29.97(30000/1001) fps from 60.00fps, unfortunately it is not possible by NVEncC alone.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered. Please let me now if you have any more problems.
