### ISSUE TITLE
Pre-Build Linux Version?

### ISSUE THREAD

**Issue by netleader** [rigaya/NVEnc#239]
Hi,
thank you for offering a linux version. Do you think you can offer prebuild *.deb packages? For the major versions of Ubuntu or Debian? Maybe the community can help you setting up a automated build?

**Comment by rigaya** [comment]
Though we [already have a auto build for build testing](https://travis-ci.org/github/rigaya/NVEnc), I'm totally new to building deb packages, having no idea for automated deb build. (Things like how to update "changelog" file automatically... and so on)

**Comment by Selur** [comment]
pre-build binaries would be nice (don't need a deb package) or some sort of build script,...

**Comment by rigaya** [comment]
I've tried building Linux deb package in [NVEnc 5.34](https://github.com/rigaya/NVEnc/releases/tag/5.34), being automatically build. I've made a package as nvencc has some dependencies with other packages such as libavfromat and so on.

Usage of these package is shown [here](https://github.com/rigaya/NVEnc/blob/master/Install.en.md).

If you have problems, please let me know, as I'm new to creating these kind of packages.

**Comment by rigaya** [comment]
I'll close this issue as currently deb & rpm package is available.
