### ISSUE TITLE
Encode pcm audio to aac during render

### ISSUE THREAD

**Issue by wwaag76** [rigaya/NVEnc#241]
What is the correct command line for encoding pcm to aac during a render.  Here is my current command line which does not work.  Thanks in advance.

`nvencc64 -i "C:\Temp\MKV Test\GeoffTest.avi" -o "C:\Temp\GrazieNeatVideo\GeoffTest-Loop-Frame 744 to 965.mp4" --codec h264  --cqp 23 --audio-source "C:\Temp\MKV Test\GeoffTest.wav" --audio-codec aac  --audio-bitrate 192`

**Comment by rigaya** [comment]
Please try options below.

nvencc64 -i "C:\Temp\MKV Test\GeoffTest.avi" -o "C:\Temp\GrazieNeatVideo\GeoffTest-Loop-Frame 744 to 965.mp4" --codec h264 --cqp 23 **--audio-source "C:\Temp\MKV Test\GeoffTest.wav":codec=aac;bitrate=192**

**Comment by wwaag76** [comment]
That works `fine.`  Would this be correct syntax or adding an audio delay.

nvencc64 -i "C:\Temp\MKV Test\GeoffTest.avi" -o "C:\Temp\MKV Test\GeoffTest.mp4" --codec h264 --cqp 23 --audio-source "C:\Temp\MKV Test\GeoffTest.wav":codec=aac;bitrate=192 --audio-delay 44

It runs, but there is no delay added.

**Comment by wwaag76** [comment]
That works great.  Can you please make the same changes to both qsvencc and vceencc?  That would be much appreciated.  Thank you.

**Comment by rigaya** [comment]
I have added the same change in [QSVEnc 4.04](https://github.com/rigaya/QSVEnc/releases/tag/4.04).

Please wait for a while for VCEEnc, as I'm now struggling with the other change in it...

**Comment by rigaya** [comment]
The same feature has been added in [VCEEnc 6.03](https://github.com/rigaya/VCEEnc/releases/tag/6.03).
