### ISSUE TITLE
Crash x265 reencode using NVEnc (Nvidia x265 Hardware encode)

### ISSUE THREAD

**Issue by noblemd00** [rigaya/NVEnc#242]
stax76:
"It's much likely a nvenc issue, I don't have hardware/driver to reproduce it, so there is not much I can do, but somebody should report it to the nvenc author.
https://github.com/rigaya/NVEnc/issues"

see my StaxRip issue report:
https://github.com/staxrip/staxrip/issues/227

Works ok with StaxRip previous version (2.1.1.9) using NVEnc ver 5.03 but not new StaxRip version 2.1.3.0 using NVEnc ver 5.04

**Comment by rigaya** [comment]
Thank you for letting me know, [NVEnc 5.05](https://github.com/rigaya/NVEnc/releases/tag/5.05) shall fix the HW HEVC decode issue we've had in 5.04.

**Comment by rigaya** [comment]
I'll close this issue, as the issue should have been fixed. Please let me now if you the problem has not yet fixed.
