### ISSUE TITLE
Advise on setting to remove grain

### ISSUE THREAD

**Issue by schm0** [rigaya/NVEnc#243]
Hi!
Is there any filter/setting to remove grain?
Thanks.

**Comment by rigaya** [comment]
Unfortunately not, there are no filters for removing grains, currently we need to use some filters on Avisynth or VapourSynth for that purpose.

**Comment by schm0** [comment]
Doing this via avisynth is so slow.
Do you have any plans to implement a degrain filter in nvenc?

**Comment by rigaya** [comment]
> Do you have any plans to implement a degrain filter in nvenc?

Not at this time, as the degrain filter such as SMDegrain needs MVTools, which requires too much of work to implement.

**Comment by Cuberlain** [comment]
Yes, good work always needs enough time... :)

**Comment by rigaya** [comment]
I'm sorry but I'll close this issue, as unfortunately I have no plan adding extra degrain filters now.
