### ISSUE TITLE
--master-display 13250 uknow option

### ISSUE THREAD

**Issue by Gotischer** [rigaya/NVEnc#244]
when try to use --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) i get error that 13250 uknow option

**Comment by rigaya** [comment]
Seems to be the error of parsing command line, but I don't seem to have problem with it on NVEnc 5.06. Below works fine.

x64\NVEncC64.exe -i input.ts -o output.mp4 --audio-copy -c hevc --profile main10 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)

Would you show the full command line options?

**Comment by Gotischer** [comment]
Sure this is 

NVEncC64.exe --avhw --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --bframes 0 --ref 5 --gop-len 12 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto --output-buf 32 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --mv-precision q-pel --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) --max-cll 1529,380 --crop 0,276,0,276 -i .\sonic.mkv -o so.h265

**Comment by Gotischer** [comment]
> Seems to be the error of parsing command line, but I don't seem to have problem with it on NVEnc 5.06. Below works fine.
> 
> x64\NVEncC64.exe -i input.ts -o output.mp4 --audio-copy -c hevc --profile main10 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)
> 
> Would you show the full command line options?

Sure this is

NVEncC64.exe --avhw --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --bframes 0 --ref 5 --gop-len 12 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto --output-buf 32 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --mv-precision q-pel --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) --max-cll 1529,380 --crop 0,276,0,276 -i .\sonic.mkv -o so.h265

**Comment by rigaya** [comment]
Hmm, still unable to reproduce the error, runs fine from command prompt.

Would you please run the options in command prompt with the attached binary, adding "--debug-cmd-parser", and share the screen shot?
[NVEncC64_test_build.zip](https://github.com/rigaya/NVEnc/files/4819981/NVEncC64_test_build.zip)


For me, it runs fine as below.

Y:\Test>x64\NVEncC64.exe --avhw --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --bframes 0 --ref 5 --gop-len 12 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto --output-buf 32 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --mv-precision q-pel --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) --max-cll 1529,380 --crop 0,276,0,276 -i .\LG_2_DEMO_4K_L_H_03_Daylight.mkv -o Y:\temp\test.h265 --debug-cmd-parser

↓The output log↓
--master-display seems to be parsed correct.
```
arg[  1]: --avhw
arg[  2]: --vbrhq
arg[  3]: 160000
arg[  4]: --codec
arg[  5]: h265
arg[  6]: --preset
arg[  7]: quality
arg[  8]: --output-depth
arg[  9]: 10
arg[ 10]: --bframes
arg[ 11]: 0
arg[ 12]: --ref
arg[ 13]: 5
arg[ 14]: --gop-len
arg[ 15]: 12
arg[ 16]: --lookahead
arg[ 17]: 32
arg[ 18]: --no-b-adapt
arg[ 19]: --no-i-adapt
arg[ 20]: --qp-init
arg[ 21]: 1
arg[ 22]: --max-bitrate
arg[ 23]: 160000
arg[ 24]: --vbr-quality
arg[ 25]: 21
arg[ 26]: --aq
arg[ 27]: --cuda-schedule
arg[ 28]: auto
arg[ 29]: --output-buf
arg[ 30]: 32
arg[ 31]: --colormatrix
arg[ 32]: bt2020nc
arg[ 33]: --colorprim
arg[ 34]: bt2020
arg[ 35]: --transfer
arg[ 36]: smpte2084
arg[ 37]: --mv-precision
arg[ 38]: q-pel
arg[ 39]: --master-display
arg[ 40]: G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)
arg[ 41]: --max-cll
arg[ 42]: 1529,380
arg[ 43]: --crop
arg[ 44]: 0,276,0,276
arg[ 45]: -i
arg[ 46]: .\LG_2_DEMO_4K_L_H_03_Daylight.mkv
arg[ 47]: -o
arg[ 48]: Y:\temp\test.h265
arg[ 49]: --debug-cmd-parser
parsing   1: --avhw
parsing   2: --vbrhq
parsing   4: --codec
parsing   6: --preset
parsing   8: --output-depth
parsing  10: --bframes
parsing  12: --ref
parsing  14: --gop-len
parsing  16: --lookahead
parsing  18: --no-b-adapt
parsing  19: --no-i-adapt
parsing  20: --qp-init
parsing  22: --max-bitrate
parsing  24: --vbr-quality
parsing  26: --aq
parsing  27: --cuda-schedule
parsing  29: --output-buf
parsing  31: --colormatrix
parsing  33: --colorprim
parsing  35: --transfer
parsing  37: --mv-precision
parsing  39: --master-display
parsing  41: --max-cll
parsing  43: --crop
parsing  45: -i
parsing  47: -o
parsing  49: --debug-cmd-parser
--------------------------------------------------------------------------------
Y:\temp\test.h265
--------------------------------------------------------------------------------
NVEncC (x64) 5.06 (r1573) by rigaya, Jun 19 2020 18:54:39 (VC 1926/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            Intel Core i9-7980XE @ 2.60GHz [TB: 4.10GHz] (18C/36T)
GPU            #0: GeForce RTX 2070 (2304 cores, 1710 MHz)[PCIe3x16][446.14]
NVENC / CUDA   NVENC API 9.1, CUDA 11.0, schedule mode: auto
Input Buffers  CUDA, 41 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 60000/1001 fps
Vpp Filters    crop: 0,276,0,276/cspconv(p010 -> yv12(16bit))
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
               3840x1608p 1:1 59.940fps (60000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        160000 kbps (Max: 160000 kbps)
Target Quality 21.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames
GOP length     12 frames
B frames       0 frames [ref mode: disabled]
Ref frames     5 frames, MultiRef L0:auto L1:auto
AQ             on
CU max / min   auto / auto
VUI            matrix:bt2020nc,colorprim:bt2020,transfer:smpte2084
MasteringDisp  G(0.265000 0.690000) B(0.150000 0.060000) R(0.680000 0.320000)
               WP(0.312700 0.329000) L(4000.000000 0.005000)
MaxCLL/MaxFALL 1529/380
Others         mv:Q-pel

encoded 2860 frames, 38.29 fps, 67455.77 kbps, 383.69 MB
encode time 0:01:14, CPU: 1.0%, GPU: 3.9%, VE: 85.0%, VD: 10.1%, GPUClock: 1903MHz, VEClock: 1769MHz
frame type IDR  239
frame type I    239,  total size   72.98 MB
frame type P   2621,  total size  310.71 MB
```

**Comment by Gotischer** [comment]
Well i try with CMD and works fine but with powershell i got error maybe is a incompatibility problem with powershell?

![image](https://user-images.githubusercontent.com/6912517/85416950-ad618e00-b534-11ea-94e3-fd70b030034d.png)

**Comment by rigaya** [comment]
Ah, I see, I didn't think of power shell. PS seems to treat brackets specially, so you will need double quotations.
```
--master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)"
```

**Comment by Gotischer** [comment]
> Ah, I see, I didn't think of power shell. PS seems to treat brackets specially, so you will need double quotations.
> 
> ```
> --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)"
> ```

😮 I didn't idea about that thx for your help
