### ISSUE TITLE
Issue With UHD Blu-Ray Playback Using HEVC Encoded Stream

### ISSUE THREAD

**Issue by jdobbs1954** [rigaya/NVEnc#245]
**Note:  See update at the end of this issue explanation**

I am creating a UHD stream for authoring an UHD Blu-Ray using the new versions of TSMUXER.   I use TSMUXER to create discs with other encoders (e.g. x265) without issues.   When I use NVENCC here is what I see:

1.  The disc will load and play.  The player recognizes it as UHD and HDR.
2.  If I simply let it play, it works fine.
3.  Any attempt to fast forward or rewind results in a blank screen (audio only).
4.  Any attempt to skip to a chapter results in a blank screen (audio only).

The playback cannot recover once the screen goes blank.   The only way to recover is to remove the disc and reinsert it.   

Example command line used:

"nvencc.exe" --avhw --vpp-pad 0,276,0,278 -i "D:\SOURCE_DISC\BDMV\STREAM\00000.m2ts" --codec hevc --preset default --profile main10 --output-depth 10 --chromaloc 2 --colorprim bt2020 --transfer smpte2084 --colormatrix bt2020nc --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) --qp-min 0 --vbrhq 0 --vbr-quality 25 --sar 1:1 --aud --pic-struct --vbv-bufsize 45000 --max-bitrate 48000 --gop-len 24 --slices 4 -o "D:\OUTPUT_FOLDER\VID_00000.hevc"

Looking at the output from NVENCC, I'm guessing (but only guessing) that this may be the issue:

According to "White Paper Blu-ray Disc Read-Only Format Coding constraints on HEVC video streams for BD-ROM Version 3.0", page 6, each GOP (Group of Pictures) of the HEVC stream must start with an IDR (of course) -- and will contain one SPS (Sequence Parameter Set), one VPS (Video Parameter Set), and at least one PPS (Picture Parameter Set), and no more than 30 PPSs.

In dumping out the HEVC stream I'm finding that only the first GOP (the first IDR frame and following P/B frames in the file) meets this requirement. All the others IDR frames (start of GOP) I've looked at only have an AUD (Access Unit Delimeter) and a couple SEI's (Supplemental Enhancement Information) preceding the IDR slice.

Is there an existing way to enable the inclusion of a SPP, VPS, and PPS in every GOP during encoding?   If not, how hard would it be to include this as a option?

**[UPDATE]**  I wrote some code to test this theory.   I inserted the SPP/VPS/PPS header into all the IDR frames and it fixed the issue.    I've now successfully authored an UHD/HDR movie using TSMUXER.

Please add a command line feature that will include these headers on all GOP IDR frames.   X265 currently has that option.  It is called --repeat-headers.

**Comment by rigaya** [comment]
Thank you for checking the behavior and letting me know how to resolve.

I have added option to add headers per GOP in [NVEnc 5.07](https://github.com/rigaya/NVEnc/releases/tag/5.07), please have a try.

**Comment by jdobbs1954** [comment]
Thanks!   I'll give it a try and report later today.

**Comment by jdobbs1954** [comment]
Thanks.   I tried the option today – but, unfortunately, it resulted in an encode failure.  I submitted a new issue report.

**Comment by rigaya** [comment]
I'll close this issue as the related issue #245 has also been closed. Thank you for reporting the issue.
