### ISSUE TITLE
5.07 NVEncC64.exe returns nothing

### ISSUE THREAD

**Issue by JJKylee** [rigaya/NVEnc#246]
_NVEncC64.exe_ in _NVEncC_5.07_x64.7z_ returns nothing.

**My system**:
Windows 10 Home 19041.329 x64
GTX 1060 with Max-Q
GeForce Game Ready Driver 451.48 (06/24/2020)

By contrast, 5.06 has no problem.

**Comment by jeffkiku2019** [comment]
I got a "npp64_10_dll" missing message. If that was your problem as well, it was handled in closed  issue #110. A link to download the dll's zip file is provided near the bottom of page.

**Comment by rigaya** [comment]
@JJKylee Would you let me know the option you're using when NVEncC64.exe crushes? I'm not able to reproduce the problem. Also, should I think "returns nothing" as "crushing without any log", or "output file size is 0"?

**Comment by agressiv** [comment]
yeah I had to copy that nppc64_10.dll into the folder, and then it worked.

**Comment by JJKylee** [comment]
> @JJKylee Would you let me know the option you're using when NVEncC64.exe crushes? I'm not able to reproduce the problem. Also, should I think "returns nothing" as "crushing without any log", or "output file size is 0"?

I just typed `.\NVEncC64.exe`, and the prompt is back with an empty result.

As @jeffkiku2019 proposed, I downloaded and unzipped _npp64_10_dll.zip_, and put the _dll_'s (_nppc64_10.dll_, _nppif64_10.dll_, _nppig64_10.dll_) in there in the same folder as _NVEncC64.exe_. The problem is gone after this.

Well, 5.06 was working OK even without these _dll_'s, so I was able to put resizing related _dll_'s that someone else had built. (_nppc64_11.dll_, _nppif64_11.dll_, _nppig64_11.dll_) As you can see from the file names, they are newer versions. And they were working good with 5.06.

I'm curious: why has 5.07 suddenly become dependent on the above three _...10.dll_'s? I'm kind of sad to find that I can't use newer _dll_'s with NVEnc any more.

**Comment by rigaya** [comment]
Now I should have removed requirement of nppc64_10.dll in [NVEnc 5.08](https://github.com/rigaya/NVEnc/releases/tag/5.08), hope it helps.

**Comment by JJKylee** [comment]
5.08 is working well without dependency issues.
Many thanks. :)
