### ISSUE TITLE
Question: Is NVENC Multi-pass capability available in NVEncC?

### ISSUE THREAD

**Issue by jeffkiku2019** [rigaya/NVEnc#248]
I was reading the Nvidia Video Codec SDK 10.0.26, specifically the NVENC VideoEncoder API ProgGuide.pdf (dated June 2020), and on page 10, section "3.8.4. Multi pass frame encoding", it describes the way to set the rate control mode to use two passes instead of one when encoding a frame. Is this capability available through an option in NVEncC? If not, any chance it will be added in the near future?

The flag to set it is described in nvEncodeAPI.h:
typedef enum _NV_ENC_PARAMS_RC_MODE
{
    NV_ENC_PARAMS_RC_CONSTQP                = 0x0,       /**< Constant QP mode */
    NV_ENC_PARAMS_RC_VBR                    = 0x1,       /**< Variable bitrate mode */
    NV_ENC_PARAMS_RC_CBR                    = 0x2,       /**< Constant bitrate mode */
    NV_ENC_PARAMS_RC_CBR_LOWDELAY_HQ        = 0x8,       /**< Deprecated, use NV_ENC_PARAMS_RC_CBR + NV_ENC_TWO_PASS_QUARTER_RESOLUTION / NV_ENC_TWO_PASS_FULL_RESOLUTION +
                                                              lowDelayKeyFrameScale=1 */
    NV_ENC_PARAMS_RC_CBR_HQ                 = 0x10,      /**< Deprecated, use NV_ENC_PARAMS_RC_CBR + NV_ENC_TWO_PASS_QUARTER_RESOLUTION / NV_ENC_TWO_PASS_FULL_RESOLUTION */
    NV_ENC_PARAMS_RC_VBR_HQ                 = 0x20       /**< Deprecated, use NV_ENC_PARAMS_RC_VBR + NV_ENC_TWO_PASS_QUARTER_RESOLUTION / NV_ENC_TWO_PASS_FULL_RESOLUTION */
} NV_ENC_PARAMS_RC_MODE;

Thanks for a great program. I really appreciate all the work you've done with HEVC.

**Comment by hydra3333** [comment]
Thanks. Can you post a link to (or the pdf)  NVENC VideoEncoder API ProgGuide.pdf ?

ffmpeg has options added. http://ffmpeg.org/pipermail/ffmpeg-user/2020-July/049267.html

**Comment by jeffkiku2019** [comment]
@hydra3333
The following link will take you to the Nvidia page where you can download a zip file containing the SDK information. Click on the link under the title "For application developers". This will take you to a login/signup page. You must have an Nvidia login to download the SDK. It's free, you just need to provide an email address, your organization, your area of interest and create a password. Once you've logged-in, a page will open with a link to download the Video Codec SDK 10.0.26. After you've downloaded and unzipped the file, the API Programming Guide can be found in the "Doc" folder.  

https://developer.nvidia.com/nvidia-video-codec-sdk/download

You can also view this document online at:

https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-video-encoder-api-prog-guide/index.html

You can use the navigation pane on the left side of the page to view other topics in the documentation.

**Comment by hydra3333** [comment]
Thanks !

**Comment by rigaya** [comment]
NVENC SDK API v10.0 support has been added on [NVEnc 5.10](https://github.com/rigaya/NVEnc/releases/tag/5.10), adding [--multipass](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--multipass-string) option which enables us to set the multi pass frame encoding modes. Please note that using API v10.0 features will require NVIDIA driver 445.87 or later.

**Comment by jeffkiku2019** [comment]
@rigaya

Thanks for the really quick response. When I said "near future", I was thinking of weeks or months, not days. I did some testing with the "--multipass 2pass-full" option and it seems to be working based on the increased encode time. In terms of picture quality, I did not notice that much of a change from a single pass, but the single pass quality was excellent to begin with. There was something unexpected. The "2pass-full" encode processed around 29 fps, the "2pass-quater" processed around 35 fps, but the "none" mode processed only 39 fps. With SDK API 9.1 the same command line processed around 60 fps. Any thoughts as to why API 10 is so noticeably slower? The Nvidia Driver version is 451.48. Here's the command line I used on both APIs:

NVEncC64.exe --avhw --codec hevc --preset quality --profile main10 --aud --aq --colormatrix bt2020nc --colorprim bt2020 --cuda-schedule auto --ref 5 --gop-len 24  --lookahead 32 --bref-mode middle --output-depth 10 --output-buf 32 --qp-init 1 --qp-min 0 --repeat-headers --sar 1:1 --max-bitrate 20000 --vbv-bufsize 25000 --vbr 15000 --vbr-quality 20 --multipass none --transfer smpte2084 --mv-precision q-pel --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) --max-cll 940,819 --log "H:\_AWORKZZ\NVENC_MP-05.log" -i "H:\_AWORK00\Test4K.m2ts" -o "H:\_AWORKZZ\Test4K_Encode.m2ts"
Thanks.

**Comment by rigaya** [comment]
> Any thoughts as to why API 10 is so noticeably slower? 

I think this is because the encoder preset has been changed from 3 level (performance, default, quality) to 7 levels (P1 ～ P7) in API 10, and they not always correspond to each other. Please refer to p.20 - p.22 of the pdf below.

http://developer.download.nvidia.com/video/gputechconf/gtc/2020/presentations/s21337-nvidia-video-technologies-video-codec-and-optical-flow-sdk.pdf

Currently, "performance" maps to "P1", "default" maps to "P4", "quality" maps to "P7" in API 10. I have also added "P0" ～ "P7" for [--preset](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#-u---preset) in [NVEnc 5.11](https://github.com/rigaya/NVEnc/releases/tag/5.11) so you can test other presets added in API 10.

**Comment by jeffkiku2019** [comment]
@rigaya 
Thanks for the link and the page nbrs (so I didn't have to read the whole thing!) The chart on page 20 explained it perfectly. I was running at P7 (highest quality, slowest speed) which accounted for the 39 fps. When I set the preset to P5, the encode actually ran faster than my API 9.1 tests (65 fps vs 60 fps) and the picture quality was still very good. There doesn't seem to be much of a performance difference between P6 and P7 (42 fps vs 39 fps), but very noticeable ones between P4, P5 and P6 (96 fps vs 65 fps vs 42 fps).  These were all done in Single Pass mode on a 4K HDR file. Thanks for solving the mystery. Now I can try more tests with 2pass-full.

**Comment by rigaya** [comment]
@warrex1979  Thanks for pointing out the problem of the documentation, I've fixed it now.

**Comment by eviluess** [comment]
_MAX) (default 0)
  -multipass         <int>        E..V....... Set the multipass encoding (from 0 to 2) (default disabled)
     disabled        0            E..V....... Single Pass
     qres            1            E..V....... Two Pass encoding is enabled where first Pass is quarter resolution
     fullres         2            E..V....... Two Pass encoding is enabled where first Pass is full resolution
