### ISSUE TITLE
v5.10 Multipass Mode Not Changing

### ISSUE THREAD

**Issue by jdobbs1954** [rigaya/NVEnc#249]
1.  It seems as though the new version (v5.10) stays in multipass mode 2pass-full no matter what mode is selected.
2.  Setting --multipass 2pass-quater or --multipass none has no effect -- the encoder still reports 2pass-full
3.  If you leave the --multipass parameter completely out of the command line -- the encoder still reports 2pass-full

Also -- is the parameter 2pass-quater spelled incorrectly and should be 2pass-quarter?

**Comment by rigaya** [comment]
> Also -- is the parameter 2pass-quater spelled incorrectly and should be 2pass-quarter?

Ah, yes, fixed in [NVEnc 5.11](https://github.com/rigaya/NVEnc/releases/tag/5.11).

> If you leave the --multipass parameter completely out of the command line -- the encoder still reports 2pass-full

Are you using "--vbrhq"? This option is for the previous API 9.1 version, and is mapped to "--vbr --multipass 2pass-full" in API v10.0, as it is written in the release note of [NVEnc 5.10](https://github.com/rigaya/NVEnc/releases/tag/5.10). Please try using "--vbr".

**Comment by jdobbs1954** [comment]
Yes.  I was using --vbrhq.   So, if I understand it correctly, the multipass option only applies to VBR since it is always set to 2pass-full when vbrhq is used?   Now that you mention it, I think I read somewhere that the vbrhq mode automatically enables 2 pass.   Is there any difference, then, between --vbr --multipass 2pass-full and simply --vbrhq?

**Comment by rigaya** [comment]
> Is there any difference, then, between --vbr --multipass 2pass-full and simply --vbrhq?

There is no difference in current implementation, as it is simply mapped as written in NVEnc 5.10 release note.

However, it is not recommended to use --vbrhq for API 10. "--vbrhq" is there just for compatibility to previous API version, and it will be dropped when I cut API 9 support in the future.

**Comment by tabnk** [comment]
-vbrhq mapped to "--vbr --multipass 2pass-full"..

Does that imply both had SAME encoded video quality?

**Comment by rigaya** [comment]
It's already written above, there is no difference in current implementation, as it is simply mapped as written in NVEnc 5.10 release note.
