### ISSUE TITLE
default-duration of video track in mkv header not set

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#250]
The mkv header produced by nvencc doesn't have this element: **duration of 1 frame in nano seconds**.
Example: fps=23.976  -> 41708333
You can see it with MKVToolNix - header editor.

Some players read first the header and start playing. If that field doesn't exist then it reads the stream property.
So KODI reads first the mkv header, starts and breaks (!!) if the element doesn't exist. Then reads stream info, and goes on.
I'm streaming from my server, and so get a break/stutter at start of every mkv generated by nvencc.
Please correct it by setting the header field to 1/fps.

**Comment by rigaya** [comment]
I have made change to add default-duration segment to mkv header in [NVEnc 5.12](https://github.com/rigaya/NVEnc/releases/tag/5.12), please have a try.

![image](https://user-images.githubusercontent.com/815947/88479437-20be4b80-cf8a-11ea-851d-7a6baed29d89.png)

**Comment by fzold** [comment]
Worked.
Thanks and greetings from Germany!
