### ISSUE TITLE
--vpp-subburn doesn't work

### ISSUE THREAD

**Issue by NueXini** [rigaya/NVEnc#254]
NVEncC64.exe --profile high --level 4.1 --vbrhq 2000 --vpp-subburn filename="sub.sup" -i "20200509.ts" -o "20200509.mp4"

The subtitle cannot display.

**Comment by rigaya** [comment]
Please check if timestamp of "sub.sup" matches to the one in "20200509.ts" file, as ts files may have some timestamp offset.

**Comment by NueXini** [comment]
> Please check if timestamp of "sub.sup" matches to the one in "20200509.ts" file, as ts files may have some timestamp offset.

Thanks , You are right. The video's timestamp is wrong.After repairing,sub can display

**Comment by rigaya** [comment]
Nice to hear it now works, I'll close the issue.
