### ISSUE TITLE
Allow to define AviSynth DLL location via command line

### ISSUE THREAD

**Issue by stax76** [rigaya/NVEnc#256]
I would like to suggest adding support to define the AviSynth DLL location via command line in nvenc, qsvenc and vceenc.

If that is too much work then support it via environment variable, I use the name AviSynthDLL in one of my components.

Or better support both were CLI has higher priority.

Why is it useful?

In staxrip we want to support installed avisynth and also portable avisynth. We want to have the possibility to use portable mode even when avisynth is installed. This is currently not possible because avisynth is installed in system32. Only a soft link workaround is possible but this requires admin rights (or developer mode) and that is very unfortunate for a portable app.

**Comment by stax76** [comment]
Sample code found in the frameserver.dll of staxrip:

```
WCHAR* dllPath = _wgetenv(L"AviSynthDLL");
HMODULE dll;

if (FileExists(dllPath))
    dll = LoadLibrary(dllPath);
else
    dll = LoadLibrary(L"AviSynth.dll");

if (!dll)
{
    std::string msg = GetWinErrorMessage(GetLastError());
    throw std::runtime_error("Failed to load AviSynth+: \r\n\r\n" + msg);
}
```

**Comment by rigaya** [comment]
New option [--avsdll](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--avsdll) has been added to specify AviSynth DLL location in [NVEnc 5.14](https://github.com/rigaya/NVEnc/releases/tag/5.14), please have a try.

And you want the same option in QSVEncC/VCEEncC?

**Comment by stax76** [comment]
Awesome thanks, I knew you would be the first to support it. The same for QSVEncC/VCEEncC would be great.

Unfortunately I don't have NVIDIA hardware to test, I've only a GT 1030 at the moment and I'm not sure if my PC can fit a better card. I could test QSVEncC since I have a good Intel CPU.

Here is some more info on the background:

https://github.com/staxrip/staxrip/issues/254#issuecomment-651896601

https://staxrip.readthedocs.io/faq.html#why-does-avisynth-portable-mode-require-soft-links

The biggest problem is ffmpeg because they are blocking default DLL loading preventing to search in PATH which means portable mode is impossible without soft link even when avisynth is not installed.

https://trac.ffmpeg.org/ticket/8836#ticket

**Comment by rigaya** [comment]
Thanks, I've understood the background more for this now.

The updated [QSVEncC 4.07](https://github.com/rigaya/QSVEnc/releases/tag/4.07) shall have the same option --avsdll.

**Comment by stax76** [comment]
Thank you
