### ISSUE TITLE
Is it possible to add the VPP filter Brightness/Contrast/Saturation/Hue for --avhw?

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#26]
If you use --avhw reader there is no way to change the brightness/contrast/saturation/hue. It remains to use avisynth/vapoursynth reader with the Tweak software filter. But unfortunately, the only normally working filter for removing interlacing is hardware "vpp-deinterlace adaptive", all anothers (include all software deinterlace filters) are much worse, and "vpp-afs" also changes the hue of the video - which is absolutely unacceptable.
Question: Is it possible to change the brightness/contrast/saturation/hue with -- avhw reader?

**Comment by rigaya** [comment]
I have added color tweak filter (vpp-tweak), which can adjust brightness, contrast, gamma, saturation and hue. [-> usage](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-tweak-param1value1param2value2)

But I don't think  "vpp-afs" changes the hue...

**Comment by drSHLEFF** [comment]
Thank you!)
