### ISSUE TITLE
Max bitrate/VBV-Buffer value not set for H264 files (when --bluray is not added)

### ISSUE THREAD

**Issue by avwtp** [rigaya/NVEnc#260]
No idea how this is supposed to work as I normally have always used --bluray when generating mp4/mts files but omitting this option results in the generated file header is missing Max bitrate and VBV-buffer information.   Oddly the output shows it's being read:

Bitrate        3500 kbps (Max: 22700 kbps)
Target Quality 1.00
Initial QP     I:20  P:23  B:25
VBV buf size   22700 kbit

But various tools don't show it as added to the file MediaInfo:
Video
ID                             : 256 (0x100)
Menu ID                        : 1 (0x1)
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.1
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Format settings, GOP           : M=4, N=24
Codec ID                       : 27
Duration                       : 16 s 16 ms
Bit rate                       : 3 349 kb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.067
Stream size                    : 6.39 MiB (95%)

vs. --bluray run as the added line:
Maximum bit rate               : 22.7 Mb/s

Using H264 Steam Viewer, the problem file has SPS HRD field as:
=== HRD ===
 cpb_cnt_minus1 : 0 
 bit_rate_scale : 0 
 cpb_size_scale : 0 
   bit_rate_value_minus1[0] : 0 
   cpb_size_value_minus1[0] : 0 
   cbr_flag[0] : 0 
 initial_cpb_removal_delay_length_minus1 : 0 
 cpb_removal_delay_length_minus1 : 0 
 dpb_output_delay_length_minus1 : 0 
 time_offset_length : 0 

don't know if it's supposed to be elsewhere also.

I've attached two logs.   Only difference between runs is that the failing one has "--slices 4" instead of "--bluray". 

Let me know if you need me to upload the result files.

[nvencc_23974.log](https://github.com/rigaya/NVEnc/files/5093456/nvencc_23974.log)
[nvencc_BD23974.log](https://github.com/rigaya/NVEnc/files/5093457/nvencc_BD23974.log)

**Comment by rigaya** [comment]
--max-bitrate/--vbv-bufsize is working, but it is only that the value is not written to the bitstream.

By adding "--pic-struct" option, I can see max bitrate information by MediaInfo. (--bluray option adds --pic-struct automatically, as it is required for bluray compatibility)

**Comment by avwtp** [comment]
Excellent!   I couldn't believe there was a bug here.   I confirmed that adding --pic-struct does the issue.  Thanks.
