### ISSUE TITLE
Syntax for --Chapter file

### ISSUE THREAD

**Issue by avwtp** [rigaya/NVEnc#261]
Could someone please give me the syntax for each entry in the chapter file?    

I know I could dive in and read the code :)   NVEnc is very feature rich but I haven't been able to find a how-to guide on the more research intensive options.

Thanks.

**Comment by jdobbs1954** [comment]
Browse to this link and search for "chapter":

https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md

**Comment by avwtp** [comment]
Fantastic. Thank you.   Got chapters to work,   It is really slow tho, .6x vs without chapter/key-on-chapter it's 1.5x (I'm frameserving from Premier Pro and using AVS to correctly pipe into NVEncc. 

I'm also using --key-on-chapter but the actual I-frame insertion (keyframe) is different between nero and matroska formats, with Nero format always working (proper @frame Iframe) and matroska mostly.   Still investigating.

**Comment by avwtp** [comment]
Need some help here.

How do I disable what appears to be an **automatic --trim insertion** based on NVEncC input analysis?

The issue is that --trim blocks the --key-on-chapter option is is why I'm not getting all i-frame insertions I was expecting.

What's a bit odd is that if I put the MTS file directly as input, trim gets done, but if I frame-serve the MTS file it's all fine.

[nvencc.log](https://github.com/rigaya/NVEnc/files/5104729/nvencc.log)

**Comment by rigaya** [comment]
ts/mts files does not always start from IDR frame, so it is required to cut out the first few frames which cannot be decoded till you find the first IDR frame. This is the reason why the --trim is required to be added (automatically), and unfortunately it cannot be removed.

There is a difference how the other decoders handle this problem, for example some insert dummy frames for the first un-decodable frames. This makes it difficult to insert chapter and key frame accurately. If input mts via avs, you shall not have this problem as the first frame is clearly known.

**Comment by avwtp** [comment]
Excellent explanation, it all makes sense now.  Thanks.
