### ISSUE TITLE
NVEnc Pipe to Output

### ISSUE THREAD

**Issue by legion7298** [rigaya/NVEnc#262]
Hi. First of all, I thank you very much for your amazing work. I'd like to make a strong suggestion. Your work works so well that it's almost perfect.
If there is a function to send the pipe output,
I'm sure it'll be a more amazing piece of work.

Currently, nvenc or other encoding programs can receive pipes as input for other programs, but cannot export them as output.

For example, avs2pipemod blah blah | nvenc -i -i test.mkv is possible.

nvenc <option> -i test.avs -o - | ffmpeg -i -c:v blah blah is impossible. Because nvenc is not exported to the output of the pipe.

I look forward to working on this part and look forward to seeing your wonderful work upgraded.

----------------------------------------------------------------------------------------------------------------------------------------------
こんにちは。まず、素晴らしい仕事をしてくれてありがとう。 私は強い提案をしたい。 あなたの仕事はとてもうまくいっているので、ほとんど完璧です。
パイプ出力を送信する機能がある場合は、
もっと素晴らしい作品になると思います。

現在、nvenc などの符号化プログラムは、他のプログラムの入力としてパイプを受け取ることができますが、出力としてエクスポートすることはできません。

たとえば、avs2pipemodblahblah | nvenc -i -i test.mkv が可能です。

nvenc <オプション> -i test.avs -o - | ffmpeg -i -c:vblahblah は不可能です。 nvencはパイプの出力にエクスポートされないからです。

私はこの部分に取り組むことを楽しみにしていますし、あなたの素晴らしい作品がアップグレードされるのを楽しみにしています。

**Comment by rigaya** [comment]
NVEncC already supports pipe output, it can be used as below. It is required to specify --output-fromat when you use this feature, as the output format cannot be determined from the output file name.

**Sending raw ES**
NVEncC64.exe -i input.mp4 -o - --output-format raw | ffmpeg.exe -y -i - -c:v copy test.mkv

**Sending video & audio**
NVEncC64.exe -i input.mp4 --audio-copy -o - --output-format nut | ffmpeg.exe -y -i - -c:v copy -c:a aac test.mkv

**Comment by rigaya** [comment]
I’ll have the issue closed as the topic has been answered.
