### ISSUE TITLE
Is it possible to run hlsl shaders

### ISSUE THREAD

**Issue by tyeeman** [rigaya/NVEnc#263]
I found a nice hlsl shader I like (It's a sharpener called Adaptive Sharpen). Can it be run via NVEnc?

**Comment by rigaya** [comment]
Unfortunately not, NVEnc cannot handle hlsl, as I've never written or handled hlsl. 

Currently, NVEnc filters are all implemented in CUDA only.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
