### ISSUE TITLE
NVencC & VirtualDub External Encoder

### ISSUE THREAD

**Issue by VD-NVencC** [rigaya/NVEnc#264]
I'd like to export from VirtualDub using your encoder but I'm experiencing some difficulties

something like this runs slowly compared to using cli
`--cqp 18:18:18 --preset quality --profile high444 --colormatrix bt709 --raw --input-res %(width)x%(height) --fps %(fpsnum)/%(fpsden) -i - -o "%(tempvideofile)"`

they have this tab where you have to select what YUV colorspace you're in, yuv420p works fine with the above command, but much slower than something like staxrip, and the yuv444p is outputting junk. I suspect it's related to the --raw argument? I've tried using something like --avsw like the cli did automagically, without a --raw argument I get pipe ended errors.

![NVencC](https://user-images.githubusercontent.com/71042674/92654339-4f338400-f2b5-11ea-8b68-10be68a318f2.png)

**Comment by rigaya** [comment]
> something like this runs slowly compared to using cli

I've testing myself, but it runs smooth even when using from VirtualDub, it might depend on the decoder or filters used. The sample below does not have any filters in it.

![image](https://user-images.githubusercontent.com/815947/92742595-c0109400-f3ba-11ea-84c6-d548dd12fc20.png)

> and the yuv444p is outputting junk

Current --raw supports only yv12(yuv420) so I'll update NVEncC to support yuv444 in the next release.

**Comment by VD-NVencC** [comment]
No filters here yet, 
are we not going to see hardware acceleration on Input using --raw Pipe stuff?
or what decoder option is holding me back?
![cli](https://user-images.githubusercontent.com/71042674/92757056-fdd9d200-f352-11ea-949f-d8b32c896696.png)
![vd2pipe](https://user-images.githubusercontent.com/71042674/92757057-fe726880-f352-11ea-9386-7d1b4b3cf5a9.png)

**Comment by rigaya** [comment]
Yes, your screen shots looks like it's cpu limited.

> are we not going to see hardware acceleration on Input using --raw Pipe stuff

When using --raw from VirtualDub, we hw decoding will not be utilized, so it'll depend on the decoder which VirtualDub utilizes. I'm actually new to VirtualDub, so I don't know about the details of the decoders used.

I was using Avisynth script as a input for VirtualDub, using LWLibavVideoSource as a reader.

**Comment by VD-NVencC** [comment]
Okay I can try that, I had just tried whatever stax was using in it's avs script. It's better but not quite par yet.
![vd2-avs-nvencc](https://user-images.githubusercontent.com/71042674/92825098-d3a90400-f394-11ea-9a7d-1ceb635489c3.png)

**Comment by rigaya** [comment]
It is natural that there is an overhead when using VirtualDub compared to StaxRip, as StaxRip should be directly passing avs file to NVEncC, but VirtualDub is passing frame data through pipe to NVEncC.

The new NVEnc 5.15 coming soon should support passing yuv444 by adding "--raw --input-csp yuv444p".

![image](https://user-images.githubusercontent.com/815947/92998119-fc76f800-f552-11ea-9c31-133bc4fcb82b.png)

**Comment by VD-NVencC** [comment]
Thanks, works great here! Even if VD2 takes twice as long, it's much better than before for my simple tasks.
![speed](https://user-images.githubusercontent.com/71042674/93012328-20433980-f565-11ea-851b-95ec3d26675f.png)
