### ISSUE TITLE
Unsupported CSP Conversion

### ISSUE THREAD

**Issue by wwaag76** [rigaya/NVEnc#265]
I get the following error:
cspconv: unsupported csp conversion: p210 -> yv12.
Error while running filter "cspconv".

Here is the complete log:

--------------------------------------------------------------------------------
C:\Temp\P1000045-04-Proxy.mp4
--------------------------------------------------------------------------------
NVEncC (x64) 5.14 (r1632) by rigaya, Aug  4 2020 21:41:03 (VC 1926/Win/avx2)
OS Version     Windows 10 x64 (19041)
CPU            Intel Core i7-8700K @ 3.70GHz [TB: 4.39GHz] (6C/12T)
GPU            #0: GeForce GTX 1050 Ti (768 cores, 1392 MHz)[PCIe3x16][452.06]
NVENC / CUDA   NVENC API 10.0, CUDA 11.0, schedule mode: auto
Input Buffers  CUDA, 20 frames
Input Info     avsw: h264(yuv422(10bit))->p210 [SSE2], 3840x2160, 30000/1001 fps
AVSync         forcecfr
Vpp Filters    copyHtoD
               cspconv(p210 -> yv12)
               resize(spline36): 3840x2160 -> 1280x720
               cspconv(yv12 -> nv12)
Output Info    H.264/AVC high @ Level auto
               1280x720p 1:1 29.970fps (30000/1001fps)
               avwriter: h264, #1:pcm_s16be/2ch -> aac/stereo/128kbps => mp4
Encoder Preset performance
Rate Control   CQP  I:23  P:23  B:23
Lookahead      off
GOP length     300 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames
AQ             off
VUI            matrix:bt709,colorprim:bt709,transfer:bt709,range:full
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto 
cspconv: unsupported csp conversion: p210 -> yv12.
Error while running filter "cspconv".
                                                                               
encoded 0 frames, 0.00 fps, 0.00 kbps, 0.00 MB

Suggestions?

**Comment by rigaya** [comment]
I've added the missing p210 -> yv12 conversion in [NVEnc 5.15](https://github.com/rigaya/NVEnc/releases/tag/5.15), which shall fix this issue, please have a try.

**Comment by wwaag76** [comment]
This works very well.  Could it also be added to vceenc and qsvencc?  Thank you so much.

**Comment by rigaya** [comment]
QSVEncC should already has the support for this, and I'll add support for this in the future release of VCEEncC.

**Comment by rigaya** [comment]
Support for YUV422 10bit was added in [VCEEnc 6.06](https://github.com/rigaya/VCEEnc/releases/tag/6.06).
