### ISSUE TITLE
--sub-copy and --vpp-subburn should not be set at the same time

### ISSUE THREAD

**Issue by samhutchins** [rigaya/NVEnc#268]
Hi!

I've just discovered this project, very cool! I currently transcode using ffmpeg, and I frequently want to burn a subtitle track _and_ copy a second subtitle track. For example: many films have a forced subtitle track for foreign audio and, to save myself many headaches with playback devices that ignore the forced flag, I like to just burn that track into the video. I also want to include the "full" subtitle track in the output though, so that I can optionally turn that on if the dialogue is hard to hear

I tried using `--vpp-subburn track=2 --sub-copy 1` to burn track 2 and copy track 1, but I got an error: `--sub-copy and --vpp-subburn should not be set at the same time`. Would it be possible for this limitation to be lifted?

**Comment by rigaya** [comment]
I've understood the background of lifting this limitation.

The limitation is set to simplify the implementation. I'll try to relax the limitation in the next release.

**Comment by rigaya** [comment]
I have relaxed the limitation now in [NVEnc 5.16](https://github.com/rigaya/NVEnc/releases/tag/5.16), you can now use --sub-copy and --vpp-subburn at the same time.

**Comment by samhutchins** [comment]
@rigaya Thanks! Downloading now...

**Comment by rigaya** [comment]
I’ll close this issue as the change has been applied.
