### ISSUE TITLE
Failed cuvidCreateDecoder error

### ISSUE THREAD

**Issue by wwaag76** [rigaya/NVEnc#269]
I get an error when trying to encode 5760x2880 video.  If I add, --avsw, it works OK.  Here's the log.

Here's the command line:
nvencc64 -i "H:\TestFootage\KwikProxyDemo\Download Insta360 ONE X Sample Footage And RAW Photos.mp4" --codec h264  --vbr 12000 --preset performance --fps 30000/1001 --avsync forcecfr  --output-res 2160x1080 -o "H:\TestFootage\KwikProxyDemo\Download Insta360 ONE X Sample Footage And RAW Photos_TMP.mp4"

2020/09/27  09:37:14  ----------------------------------------------------------------------------------
2020/09/27  09:37:14  --V:\Dropbox\Barry\Download Insta360 ONE X Sample Footage And RAW Photos_TMP.mp4
2020/09/27  09:37:14  ----------------------------------------------------------------------------------
2020/09/27  09:37:14  --NVEncC (x64) 5.15 (r1658) by rigaya, Sep 12 2020 15:05:21 (VC 1916/Win/avx2)
2020/09/27  09:37:14  --OS Version     Windows 10 x64 (19041)
2020/09/27  09:37:14  --CPU            Intel Core i7-8700K @ 3.70GHz [TB: 4.29GHz] (6C/12T)
2020/09/27  09:37:14  --GPU            #0: GeForce GTX 1050 Ti (768 cores, 1392 MHz)[PCIe3x16][456.38]
2020/09/27  09:37:14  --NVENC / CUDA   NVENC API 10.0, CUDA 11.1, schedule mode: auto
2020/09/27  09:37:14  --Input Buffers  CUDA, 16 frames
2020/09/27  09:37:14  --Input Info     avcuvid: H.264/AVC, 5760x2880, 30000/1001 fps
2020/09/27  09:37:14  --AVSync         forcecfr
2020/09/27  09:37:14  --Vpp Filters    copyDtoD
2020/09/27  09:37:14  --Output Info    H.264/AVC high @ Level auto
2020/09/27  09:37:14  --               2160x1080p 1:1 29.970fps (30000/1001fps)
2020/09/27  09:37:14  --               avwriter: h264 => mp4
2020/09/27  09:37:14  --Encoder Preset performance
2020/09/27  09:37:14  --Rate Control   VBR
2020/09/27  09:37:14  --Multipass      none
2020/09/27  09:37:14  --Bitrate        12000 kbps (Max: 162000 kbps)
2020/09/27  09:37:14  --Target Quality auto
2020/09/27  09:37:14  --Initial QP     I:20  P:23  B:25
2020/09/27  09:37:14  --VBV buf size   auto
2020/09/27  09:37:14  --Lookahead      off
2020/09/27  09:37:14  --GOP length     300 frames
2020/09/27  09:37:14  --B frames       3 frames [ref mode: disabled]
2020/09/27  09:37:14  --Ref frames     3 frames
2020/09/27  09:37:14  --AQ             off
2020/09/27  09:37:14  --Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto 
2020/09/27  09:37:14  --cuvid: Failed cuvidCreateDecoder 1 (CUDA_ERROR_INVALID_VALUE)
2020/09/27  09:37:14  --                                                                               
2020/09/27  09:37:14  --encoded 0 frames, 0.00 fps, 0.00 kbps, 0.00 MB
2020/09/27  09:37:14  --encode time 0:00:00, CPULoad: 1.1

**Comment by wwaag76** [comment]
Please disregard.  Just discovered that limit of avc decoding is 4096 x 4096.

**Comment by rigaya** [comment]
OK, I'll close the issue.
