### ISSUE TITLE
Support for alternative transfer characteristics SEI

### ISSUE THREAD

**Issue by badyu17** [rigaya/NVEnc#272]
Hi,

I was using NVEncC to re-encode few 4K HLG files which worked perfectly and I was happy with the result but I noticed that I can only define VUI part for transfer characteristics and not add additional SEI message which I found is required for HLG.

This can be observed by additional MediaInfo output which shows:

Transfer characteristics: HLG / HLG (source file)
Transfer characteristics: HLG (encoded file)

Adding this Alternative transfer characteristics SEI is possible in x265 with '--atc-sei' option. Can this be implemented in NVEncC as an additional option?

Thank you for your great work.

**Comment by rigaya** [comment]
I've added option which will add the additional SEI for HLG in [NVEnc 5.19](https://github.com/rigaya/NVEnc/releases/tag/5.19) as [--atc-sei](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--atc-sei-string-or-int), please have a try.

**Comment by badyu17** [comment]
Thanks Rigaya

I just tested new option. It should be working but there is one thing. MediaInfo is now reporting two rows of information instead of one for "transfer"  when I use --atc-sei arib-std-b67

Transfer characteristics                 : HLG
transfer_characteristics_Original   : HLG / HLG

I don't know if it's of any help but here is the log of ffmpeg's trace_headers option

Original

![orig](https://user-images.githubusercontent.com/10170297/97804565-095dc100-1c51-11eb-9174-4739f6b0b983.png)

NVenc

![nvenc](https://user-images.githubusercontent.com/10170297/97804579-209cae80-1c51-11eb-842f-4bd9c4932014.png)

**Comment by rigaya** [comment]
I don’t seem to have trouble myself, there is only single "Transfer characteristics" line in MediaInfo.

x64\NVEncC64.exe -i "4K_HLG_Sample.MP4" -o F:\temp\test.mp4 -c hevc --output-depth 10 --transfer arib-std-b67 --colormatrix bt2020nc --colorprim bt2020 --atc-sei arib-std-b67
![image](https://user-images.githubusercontent.com/815947/97805083-3cc33e80-1c97-11eb-960b-e490abb2f224.png)

**Comment by badyu17** [comment]
That's weird, maybe it's a bug in NVencC matroska muxer but this only happens when NVencC's output is mkv. MediaInfo output is same as yours when I either remux NVEnc mkv to mp4 or when the output is raw h265.

**Comment by rigaya** [comment]
Thanks, I also got two "Transfer characteristics" line when I wrote in mkv format.

Checking the mkv video header with mkvtoolnix, it seems like the first line is coming from mkv header as it only has the VUI part for transfer characteristics.

Transfer characteristics : HLG < **from mkv header**
transfer_characteristics_Original : HLG / HLG < **from HEVC stream**

I'll try if I can avoid this.

**Comment by rigaya** [comment]
I've changed mux behavior in [NVEnc 5.20](https://github.com/rigaya/NVEnc/releases/tag/5.20), to avoid two lines showing up for Transfer characteristics in MediaInfo when writing to mkv format.
