### ISSUE TITLE
Support for the 12bit HEVC encoding of the new GF 3000 series cards + AV1 HW decoding support

### ISSUE THREAD

**Issue by Cuberlain** [rigaya/NVEnc#273]
Hello Rigaya!

What is your opinion about this?

Support for the 12bit HEVC encoding of the new GF 3000 series cards + AV1 HW decoding support

**Comment by rigaya** [comment]
NVENC SDK 11 was out supporting these features, so I have added experimental support for them in [NVEnc 5.18](https://github.com/rigaya/NVEnc/releases/tag/5.18), but not tested as I don't have the Ampere GPUs.

**Comment by Cuberlain** [comment]
Thank you!
