### ISSUE TITLE
Errors trying to compile

### ISSUE THREAD

**Issue by asheimo** [rigaya/NVEnc#274]
Trying to build the solution tinyxml & NVEncSDK compile file but the other projects fail to compile with errors like;

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"compute_30,compute_30\" -gencode=arch=compute_50,code=\"compute_50,compute_50\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64" -x cu   -I.\inc -I..\NVEncSDK -I..\NVEncSDK\Common -I..\NVEncSDK\Common\inc -I..\NVEncSDK\Core -I..\NVEncSDK\Core\include -I..\ffmpeg_lgpl\include -I..\ttmath -I..\ChapterRW -I..\jitify -I..\dtl -I..\cppcodec -I..\tinyxml2 -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\Include\um" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I\include -I\include -I\include -I\include\vapoursynth -I\common -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" --source-in-ptx -G -lineinfo  --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--display_error_number --diag_suppress=negative_shift_count --diag_suppress=signed_one_bit_field --diag_suppress=expr_has_no_effect --diag_suppress=177   --diag_suppress=186 --diag_suppress=815  --diag_suppress=1444 --diag_suppress=2465" -g  -use_fast_math -D_CRT_SECURE_NO_WARNINGS -DNVENC_AUO -DWIN32 -D_DEBUG -D_LIB -D_MBCS -Xcompiler "/EHsc /W4 /nologo /Od /FdC:\Users\Andy\source\repos\NVEnc\_build\x64\Debug\obj\NVEncCore\NVEncCore.pdb /FS /Zi /RTC1 /MDd " -o C:\Users\Andy\source\repos\NVEnc\_build\x64\Debug\obj\NVEncCore\NVEncFilterSubburn.cu.obj "C:\Users\Andy\Source\Repos\NVEnc\NVEncCore\NVEncFilterSubburn.cu" -Xcompiler "/wd"4819" /wd"4505" /wd"4127" /FS"" exited with code 1.	NVEncCore	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.1.targets	785	

I followed the instructions for how to compile. what do you think I could be missing?

**Comment by rigaya** [comment]
It's difficult to say from that error message. CUDA11 might be causing the issue, as I'm using CUDA 10.1 SDK.

**Comment by asheimo** [comment]
well, I rebuilt a 2nd machine I have and redid everything as before and now get this error when building NVencC

LNK1181	cannot open input file 'C:\<path>\NVEnc\_build\Win32\Debug\obj\NVEncCore\ram_speed_x86.asm.obj'	

I looked and the file is not there but there is this file: ram_speed_x86.obj

**Comment by rigaya** [comment]
Please try for x64 build, and not win32 build. Win32 build needs VC2015 + CUDA 8.0.

**Comment by asheimo** [comment]
I changed to building for x64, downgraded to CUDA 10.1. Now I get a buch of errors about identifiers that are undefined

![image](https://user-images.githubusercontent.com/33631251/97062924-13096980-156b-11eb-8ca0-c8d026b83d70.png)

**Comment by rigaya** [comment]
I've also tried clean install of VC2019 + CUDA 10.1.2, the target Windows SDK version needed change to the one installed (8.1→10), but others turned out fine.

![image](https://user-images.githubusercontent.com/815947/97065501-bf3d6580-15e8-11eb-9926-103ff4a076a3.png)


You shall look for the first error on the build log and find out the reason of that.

**Comment by asheimo** [comment]
I had already updated the SDK version. I deleted the whole thing and recloned it. Do you think I'm missing a reference or path somewhere. Let me know if there is something I can show you that you think might help. I am sorry, I am a noob with C++, I know VB, and C#, so I'm learning.

![image](https://user-images.githubusercontent.com/33631251/97085722-3aa11600-15ed-11eb-9103-e9af1bad221a.png)

![image](https://user-images.githubusercontent.com/33631251/97085748-573d4e00-15ed-11eb-9c9a-6965fe5090fe.png)

![image](https://user-images.githubusercontent.com/33631251/97085761-6a501e00-15ed-11eb-92f1-7aeeb33bcde3.png)

![image](https://user-images.githubusercontent.com/33631251/97085770-79cf6700-15ed-11eb-8e9d-3a43a058e957.png)

**Comment by asheimo** [comment]
Could my problem have something to do with NVENC_AUO resolving to 1?

**Comment by rigaya** [comment]
You have your environment variable wrong.
```
"VAPORSYNTH_SDK" should be "VAPOURSYNTH_SDK"
```

Also, NVENC_AUO = 1 should not be there. As written in the table below from [Build.en.md](https://raw.githubusercontent.com/rigaya/NVEnc/master/Build.en.md) you need to select "RelStatic" configuration for NVEncC build. You might have selected "Release" mode, which adds NVENC_AUO = 1.

| Configurations   | For Debug build | For Release build |
|:---------------------|:------|:--------|
|NVEncC(64).exe | DebugStatic | RelStatic (← You need this one) |
|NVEnc.auo (win32 only) | Debug | Release (←You might have this one) |
|cufilters.auf (win32 only) | DebugFilters | RelFilters |

Please make sure you have selected "RelStatic".

![image](https://user-images.githubusercontent.com/815947/97095509-29aede00-169b-11eb-9097-f637eca0e8ee.png)

**Comment by asheimo** [comment]
well that brought us closer the only things that seem to be left are this:

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(218,5): warning MSB8065: Custom build for item "ram_speed_x64.asm" succeeded, but specified output "c:\users\andy\nvenc\_build\x64\relstatic\obj\nvenccore\ram_speed_x64.asm.obj" has not been created. This may cause incremental build to work incorrectly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(218,5): warning MSB8065: Custom build for item "cpu_info_x64.asm" succeeded, but specified output "c:\users\andy\nvenc\_build\x64\relstatic\obj\nvenccore\cpu_info_x64.asm.obj" has not been created. This may cause incremental build to work incorrectly.

LNK1181	cannot open input file 'C:\Users\andy\NVEnc\_build\x64\RelStatic\obj\NVEncCore\ram_speed_x64.asm.obj'	

Again I appreciate your putting up with me.

**Comment by rigaya** [comment]
I don't know whats is causing this, as I've never had this kind of error messages.

- Output directory (c:\users\andy\nvenc_build) is wrong, should be under "$(SolutionDir)\\_build". I don't know why it is changed. If you have editted the solution/project file, please undo for simplicity (except for the Windows SDK version).
- Please check if yasm is correctly added in the PATH, and the version is the latest 1.3.0.
  ![image](https://user-images.githubusercontent.com/815947/97098831-f5501780-16c4-11eb-9dfe-dd6fd077ed92.png)

- Assembly custom build which is causing the error should be like below for "RelStatic" "x64" build. The output should be in $(OutDir)obj\$(ProjectName)\%(Filename).asm.obj.
![image](https://user-images.githubusercontent.com/815947/97098845-1d3f7b00-16c5-11eb-925a-3e7afc7f99af.png)

**Comment by asheimo** [comment]
I went through and triple checked the paths and found a couple errors to clean up. I recloned the project again. I am remembering to set to RelStatic and x64. Still getting the messages that ...has not been created. So once we are able to fix this last issue that should be it. I am searching on my end as well to see if I can find an answer.

![image](https://user-images.githubusercontent.com/33631251/97108765-ef970980-16a5-11eb-9a5f-11ced4060be2.png)

**Comment by asheimo** [comment]
If I manually copy the items and name them as the output should be it allows the compile to complete. So I at least have a workaround. I just can't find why the output is failing.

**Comment by rigaya** [comment]
OK, nice to hear that at least all the errors except the assembly custom build thing is gone. I also cannot find out whats wrong, at least your command line seems fine.

**Comment by asheimo** [comment]
Since the remaining issue isn't with your code I'm going to close the issue. If/when I find the answer I'll comment just so you can know in case it comes up again. Thanks again for your time and support.
