### ISSUE TITLE
"--avhw" crash with some files while "--avsh" goes through

### ISSUE THREAD

**Issue by slomorbo** [rigaya/NVEnc#275]
Hi,
First of all, a huge thank you for your app!

I use your app to re-encode camera footage (source is H264, variable frame rate)
I'm facing an issue where  some of the files make nvencc "crash" if i use the hardware decoder (--avhw). The same file goes through if i'm using the software decoder (--avsw).

[sample clip](editedout)

nvencc put out this error in the console while using --avhw, and the process terminate

`[mp4 @ 000002b87e7eb340] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 109920 >= 109890
Error FlushEncoder: 20.`

To futher investigate the issue, i grabed a copy of ffmpeg.exe and did some testing :

using hardware decoding and the hardware encoding with ffmpeg, the encoding process work and the resulting file is fine
although it's giving this error messsage at the exact same place where nvencc would have crashed

`[h264 @ 00000209514f7080] Frame num change from 4 to 5
[h264 @ 00000209514f7080] decode_slice_header error`

On others problematic files, the ffmpeg error is similar, but every file goes through while using the hardware decoder.

Thank for your help!

**Comment by rigaya** [comment]
Thank you for the sample clip and the information of the error, it seems to be something related to the timestamp.

However I was not able to reproduce the issue with your sample clip, the encoding turned out fine with --avhw as below.

```
>x64\NVEncC64_5.17.exe -i sample.mp4 -o test.mp4 --avhw --avsync vfr --audio-copy
--------------------------------------------------------------------------------
F:\temp\test.mp4
--------------------------------------------------------------------------------
[h264 @ 00000266ea54d100] error while decoding MB 159 119, bytestream -7
[h264 @ 00000266ea54d100] error while decoding MB 159 119, bytestream -7
[h264 @ 00000266ea54d100] error while decoding MB 159 119, bytestream -5
[h264 @ 00000266ea54d100] error while decoding MB 156 119, bytestream -5
[h264 @ 00000266ea54d100] error while decoding MB 127 119, bytestream -8
[h264 @ 00000266ea54d100] error while decoding MB 132 119, bytestream -6
[h264 @ 00000266ea54d100] error while decoding MB 31 119, bytestream -6
[h264 @ 00000266ea54d100] error while decoding MB 105 119, bytestream -6
[h264 @ 00000266ea54d100] error while decoding MB 50 118, bytestream -6
[h264 @ 00000266ea54d100] error while decoding MB 159 119, bytestream -5
[h264 @ 00000266ea54d100] error while decoding MB 91 114, bytestream -5
[h264 @ 00000266ea54d100] error while decoding MB 74 112, bytestream -5
NVEncC (x64) 5.17 (r1669) by rigaya, Oct 15 2020 21:52:37 (VC 1927/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            Intel Core i9-7980XE @ 2.60GHz [TB: 4.10GHz] (18C/36T)
GPU            #0: GeForce RTX 2070 (2304 cores, 1710 MHz)[PCIe3x16][456.71]
NVENC / CUDA   NVENC API 10.0, CUDA 11.1, schedule mode: auto
Input Buffers  CUDA, 16 frames
Input Info     avcuvid: H.264/AVC, 2560x1920, 30000/1001 fps
AVSync         vfr
Vpp Filters    copyDtoD
Output Info    H.264/AVC high @ Level auto
               2560x1920p 1:1 29.970fps (30000/1001fps)
               avwriter: h264, aac => mp4
Encoder Preset default
Rate Control   CQP  I:20  P:23  B:25
Lookahead      off
GOP length     300 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             off
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto

encoded 261 frames, 132.15 fps, 6281.15 kbps, 6.52 MB
encode time 0:00:01, CPU: 2.9%, GPU: 2.0%, VE: 49.5%, VD: 18.5%, GPUClock: 1665MHz, VEClock: 1545MHz
frame type IDR   1
frame type I     1,  avgQP  20.00,  total size  1.14 MB
frame type P    65,  avgQP  23.00,  total size  4.52 MB
```

Would you let me know the exact command line you have tried?

**Comment by slomorbo** [comment]
I'm using this command line (result from the sample clip provided) ;

`nvencc64 --avhw -c hevc -i sample.mp4 --output-res 960x-2 --vpp-resize lanczos4 --preset quality --avsync vfr -o out_sample.mp4"
--------------------------------------------------------------------------------
out_sample.mp4
--------------------------------------------------------------------------------
[h264 @ 00000158c7e0d000] error while decoding MB 159 119, bytestream -7
[h264 @ 00000158c7e0d000] error while decoding MB 159 119, bytestream -7
[h264 @ 00000158c7e0d000] error while decoding MB 159 119, bytestream -5
[h264 @ 00000158c7e0d000] error while decoding MB 156 119, bytestream -5
[h264 @ 00000158c7e0d000] error while decoding MB 127 119, bytestream -8
[h264 @ 00000158c7e0d000] error while decoding MB 132 119, bytestream -6
[h264 @ 00000158c7e0d000] error while decoding MB 31 119, bytestream -6
[h264 @ 00000158c7e0d000] error while decoding MB 105 119, bytestream -6
[h264 @ 00000158c7e0d000] error while decoding MB 50 118, bytestream -6
[h264 @ 00000158c7e0d000] error while decoding MB 159 119, bytestream -5
[h264 @ 00000158c7e0d000] error while decoding MB 91 114, bytestream -5
[h264 @ 00000158c7e0d000] error while decoding MB 74 112, bytestream -5
Max B frames are 0 frames.
NVEncC (x64) 5.18 (r1672) by rigaya, Oct 17 2020 22:48:45 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            AMD Ryzen 7 2700X Eight-Core Processor (8C/16T)
GPU            #1: GeForce GTX 1050 Ti (768 cores, 1417 MHz)[PCIe3x16][456.71]
NVENC / CUDA   NVENC API 11.0, CUDA 11.1, schedule mode: auto
Input Buffers  CUDA, 17 frames
Input Info     avcuvid: H.264/AVC, 2560x1920, 30000/1001 fps
AVSync         vfr
Vpp Filters    cspconv(nv12 -> yv12)
               resize(lanczos4): 2560x1920 -> 960x720
               cspconv(yv12 -> nv12)
Output Info    H.265/HEVC main @ Level auto
               960x720p 1:1 29.970fps (30000/1001fps)
               avwriter: hevc => mp4
Encoder Preset quality
Rate Control   CQP  I:20  P:23  B:25
Lookahead      off
GOP length     300 frames
B frames       0 frames [ref mode: disabled]
Ref frames     3 frames
AQ             off
CU max / min   auto / auto
Others         mv:auto repeat-headers
[mp4 @ 00000158e323b340] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 109920 >= 109890
Error FlushEncoder: 20.

encoded 56 frames, 155.99 fps, 1815.29 kbps, 0.40 MB
encode time 0:00:00, CPU: 1.1%, GPU: 1.0%, GPUClock: 1303MHz, VEClock: 1177MHz
frame type IDR  1
frame type I    1,  avgQP  20.00,  total size  0.31 MB
frame type P   55,  avgQP  23.00,  total size  0.09 MB`

**Comment by slomorbo** [comment]
Using your command line it's work fine on my part also,

the culprit seem to be when i'm using the `-c hevc` option while using `--avhw`

**Comment by rigaya** [comment]
Thanks, I was able to reproduce the issue. I'll check if I could avoid this crash.

**Comment by rigaya** [comment]
The hw decoder was returning invalid timestamp, one frame had a timestamp smaller than the previous frame (sw decoder does not have this problem).

I have added a wrokaround for this in [NVEnc 5.19](https://github.com/rigaya/NVEnc/releases/tag/5.19), avoiding crash we have faced in the sample file.

**Comment by slomorbo** [comment]
I've been testing with other problematic files and i can confirm that they all work fine now with version 5.19!
A huge thank you !
