### ISSUE TITLE
--sub-copy (falsely) flags first subtitle to "default" instead of copying neutral (incl. original metadata flags)

### ISSUE THREAD

**Issue by Rincemac** [rigaya/NVEnc#277]
あいさつ Rigaya,

I am not sure if this is maybe already noted somewhere else, so sorry if it is!

**Short Behavioral Description**
`--sub-copy `behaviour unexpectedly does not just "copy" all metadata flags for subtitles. Instead the option seems to set `"Default = YES`" for _Subtitle 1_ in output if no such flag exists or is set to "NO" in input file.

Ex.: an original MKV has 5 subtitles, all of them different languages, _none_ of them are set as "Default = YES" (ie none gets shown when playing in VLC or other compatible player software by default)

When using `--sub-copy` on such a file, the first subtitle copied gets a "Default = YES" flag set by NVenc. This is unexepected.

**Current NVEnc Behavior**
Using `--sub-copy` to natively copy all or selected input file subtitles to output file, the _first_ subtitle copied gets set as `"Default = YES"`, even when original file's subtitle is `"Default = NO"`. 

Important note - I tested a few scenarios: 

1) 1st Subtitle track > forced=yes, default=no: --sub-copy sets "Default=Yes". 
2) 1st Subtitle track > forced=no, default=no: --sub-copy sets "Default=Yes"
3) file with 2 (and more) different subtitle tracks 
1st Subtitle track > forced=no, default=no, 
2nd track > default=yes 
`--sub-copy `does _not_ change default flag on subtitle track 1 (!), it respects the default flag already set.

**Conclusion** = `--sub-copy` seems to only set Default=Yes when _no_ "default=YES" tracks exist in input file?

**Expected Behavior**
`--sub-copy `should just natively copy (any) subtitle or all subtitles with all metadata flags "untouched".
If (any and all) subtitle metadata flag reads `"Default = NO"` this should remain intact, same as` "Default = YES"` metadata flag should be copied correctly without manipulating it. 

**workaround**
One possible workaround right now (for me) is to also cue MKVPROPEDIT in a batch execution, but this gets very complex as it would need to handle a variety of scenarios and numbers of subtitles (like "forced" subs, "non-forced but default" and "non-default" scenarios) - so it would help if the --sub-copy behaviour would just respect the original file's metadata flags 100%.

Maybe you can fix it in one of the next builds, that would be highly appreciated.

どうもありがとう

**Comment by rigaya** [comment]
This is the default behavior of the mkv muxer in libavformat, it will set the first track of the subtitle to "default" when no track is set to "default" from the input. This is quite understandable as it is natural to have one "default" track in the output file.

If you do not require this change in "default" dispostion, it is possible to change this behavior by adding "--mux-option default_mode:infer_no_subs" or "--mux-option default_mode:passthrough". Below are the possible values for "--mux-option default_mode:xxx".
- infer (default)  
  For each track type, mark the first track of disposition default as default, for video, audio and subtitles.
- infer_no_subs  
  For each track type, mark the first track of disposition default as default, but only for video and audio
- passthrough
  Let the default flag as-is.

Please note that this only applies for mkv format.

**Comment by Rincemac** [comment]
Thanks for the clarification. I wasn't aware that libav "dictates" a default flag to be set without further options (learn something new every day). 

Downwide of that behaviour will be that a "default" track gets shown automatically by many AV players (soft and hardware) if the option "don't show default subtitle" is not toggleable.

I wasn't aware of the option flags you mentioned being available, thanks! I'll be using this from now on when it makes sense.

I'm closing this as this solves my issue.
