### ISSUE TITLE
Suggestion: Change error level of "--colormatrix auto" is only supported with avsw/avhw."  from Red to Yellow

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [rigaya/NVEnc#279]
Imho, the error should not be a showstopper. 
It's kinda inconvenient to remember, what you can or can't feed to encoder. Better let user know, but don't stop.

**Comment by rigaya** [comment]
I'm sorry but I reject this suggestion, as I want to strongly notice users that the option specified is not working as intended in this case.

**Comment by vasyl-zabolotniy** [comment]
Would make sense if it were about specific parameter settings, but when it's 'auto' - the code should be 'smart' i.e. just skip the parameter if it's undefined in the source. My opinion is that user expect such behavior, and rightly so.
