### ISSUE TITLE
"--frame-packing" option is very necessary for stereoscopic videos define frame arrangement!

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#28]

**Comment by drSHLEFF** [comment]
For example ffmeg with nvenc already have it:

enum | NV_ENC_STEREO_PACKING_MODE {   NV_ENC_STEREO_PACKING_MODE_NONE = 0x0, NV_ENC_STEREO_PACKING_MODE_CHECKERBOARD = 0x1, NV_ENC_STEREO_PACKING_MODE_COLINTERLEAVE = 0x2,NV_ENC_STEREO_PACKING_MODE_ROWINTERLEAVE = 0x3,   NV_ENC_STEREO_PACKING_MODE_SIDEBYSIDE = 0x4, NV_ENC_STEREO_PACKING_MODE_TOPBOTTOM = 0x5, NV_ENC_STEREO_PACKING_MODE_FRAMESEQ = 0x6 }
-- | --

https://ffmpeg.org/doxygen/3.2/group__ENCODER__STRUCTURE.html#gae71f3990dca0c59451b88cfc41dc488b

**Comment by EoD** [comment]
It seems that you could use frame-packing by using an auo configuration?
https://github.com/rigaya/NVEnc/blob/1586795dc8e8b422909ebb2e39b06401d6cd9bac/NVEnc/prm/auo_conf_convert.cpp#L332

@rigaya can you confirm this?

**Comment by rigaya** [comment]
I'm sorry, but I have no plan to support this feature.
