### ISSUE TITLE
Slow encoding + 100% Video Econde in 3080

### ISSUE THREAD

**Issue by alhatmy** [rigaya/NVEnc#280]
Was using the same transcode on the same files through RTX 1080 ti, it was utilizing 30-40% of Video Encode from GPU and much faster. But with the same app/file to test (latest NVEnc), it takes double the time, uses 100% of Video Encode and the output size is double the expected!
Is there any option to change?

**Comment by alhatmy** [comment]
NVEncC (x64) 5.22 (r1732) by rigaya, Dec  1 2020 21:01:52 (VC 1928/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            Intel Core i7-8700K @ 3.70GHz [TB: 4.70GHz] (6C/12T)
GPU            #0: GeForce RTX 3080 (8704 cores, 1710 MHz)[PCIe3x16][457.30]
NVENC / CUDA   NVENC API 11.0, CUDA 11.1, schedule mode: auto
Input Buffers  CUDA, 20 frames
Input Info     AviSynth+ 3.6.1 r3300(yv12)->nv12 [AVX2], 1920x1080, 24000/1001 fps
Vpp Filters    copyHtoD
Output Info    H.264/AVC high @ Level 4
               1920x1080p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   CQP  I:18  P:18  B:18
Lookahead      off
GOP length     240 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             off
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto

**Comment by rigaya** [comment]
You might need to adjust the parameters on a new generation GPU. As RTX30** supports more encoding features compared to GTX10**, it might be that "--preset quality" is mapped to a slower setting.

I suggest checking out for other [--preset](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#-u---preset) levels, and changing the cqp value to get the file size you need.

**Comment by rigaya** [comment]
I'll close the issue as the topic has been answered.
