### ISSUE TITLE
Is it possible to make NVENC a hybrid (CPU & GPU) encoder in the future?

### ISSUE THREAD

**Issue by Cuberlain** [rigaya/NVEnc#281]
Hello Rigaya!

Is it possible to transform Rigaya's version of NVENC into a very high quality and ultra-fast hybrid (CPU GPU) encoder?
Like in this forum thread on Videohelp: https://forum.videohelp.com/threads/397933-Main-Concept-Hybrid-GPU-HEVC-Encoder

**Comment by Cuberlain** [comment]
https://www.mainconcept.com/hybridgpu.html

**Comment by rigaya** [comment]
I'm afraid I won't be able to do this, it's difficult only with programming skills. You'll need codec specific knowledge and also the understanding of the encoder internals, which I don't have.
