### ISSUE TITLE
nvenc ffmpeg and NVEenc

### ISSUE THREAD

**Issue by abactuon** [rigaya/NVEnc#282]
Why am I getting better video quality when using ffmpeg than nvencc?
Nvencc turns out more bitrate, but everything is kind of "blurry".
h264->hevc

ffmpeg-nonfree.exe -i test.mkv -sn -map_metadata -1 -c:v hevc_nvenc -cq 25  -c:a libfdk_aac -ac 2 -ar 44100 _test.mkv

NVEncC64.exe --preset P7 --tier high --avhw --output-buf 64 --codec hevc --output-depth 8 --colormatrix bt709 --colorprim bt709 --colorrange full --transfer auto --fullrange --audio-codec 1?opus --audio-stream 1?stereo:stereo --audio-samplerate 48000 --audio-bitrate 96 -i test.mkv -o _test.mkv

**Comment by rigaya** [comment]
I recommend to use "--vbr 0 --vbr-quality" in nvencc when using constant quality mode, which is equivalent for "-cq" in ffmpeg.

The options for ffmpeg and nvencc you've shared actually uses different encoding mode, which seems to be the cause of your issue. For NVEncC it is using constant **qp** mode and **not** constant **quality** mode, which is natural that the file size grows bigger with blurry results.

Using the options below, you shall be able to get a similar result.

**ffmpeg**
x64\ffmpeg -i sample_movie_1080p.mpg -an -c:v hevc_nvenc -cq 25 F:\temp\test_ffmpeg.mp4

**nvencc**
x64\NVEncC64.exe **--preset P4 --vbr 0 --vbr-quality 25** -i sample_movie_1080p.mpg -c hevc --level 5.0 --tier high -o F:\temp\test_nvenc.mp4 


Here are the filesize and the ssim based quality for the options above when encoding the same input file.
```
NVEncC 10417.5 kbps, SSIM All 0.980197
ffmpeg 9363.2 kbps,  SSIM All 0.974174
```

NVEncC comes with rather larger size but with better quality, and not "blurry". I think it is quite acceptable and reasonable.

**Comment by Cuberlain** [comment]
FFMPEG NVENC has fewer options, and usually provides lower quality than Rigaya's version.

**Comment by abactuon** [comment]
Maybe I'm doing something wrong?
D:\Media\Convert\NVEncC\NVEncC64.exe --preset P4 --vbr 0 --vbr-quality 25 -i E:\test.mkv -c hevc --level 5.0 --tier high -o E:\test_nvenc.mkv

Input : test.mkv - 1,34GB Bitrate 7914
Output : test_nvenc.mkv - 17,5MB Bitrate 715

The quality is terrible.

**Comment by rigaya** [comment]
@abactuon Thank you for the logs, from the log it seems like max bitrate is somehow set to "0", I seem to have some kind of bug around here. It seems to happen when the output is 720p.

As a workaround please try setting max bitrate explicitly by adding "--max-bitrate 50000" as a example and see if it helps.
