### ISSUE TITLE
[Enhancement] Select audio/subtitles to be copied in output based on language metadata flag?

### ISSUE THREAD

**Issue by Rincemac** [rigaya/NVEnc#283]
挨拶 rigaya,

not sure if it's too complex to implement for NVEnc, but nevertheless I wanted to ask. It would be a great enhancement if possible, not a big deal if not possible or too complex.

### Preface - Enhancement to pre-select any present audio and subtitle tracks based on language metadata flag (ISO 693-2)?

Other s/w encoders offer the option in CLI to pre-select a "preferred" language subtitle to "auto-select" when encoding to output file container with audio streams and subs to *.mkv.

This empowers the user to define their list of language preference and check input streams at decode time for language flag metadata, based on [ISO codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

### In Practicality - usage examples:

When I encode, I want to auto-select English, German, Japanese (if available) in the original input file/stream. 
In handbrake I'd enter: `ger,eng,jap` at commandline options to make the decoder select any and all tracks based on ISO flag (note: if a track is present without this flag, it will be coded as "UNK" for unknown.)

_If_ the preferred language option is present, the encoder takes all the according subtitles & audio streams, pre-selects them to for writing into the output file with no further manual input needed from user.

As for the Audio/Sub disposition, it can be solved automatically by weighting each track based on the given order in commandline Ie. a user gives `eng,ger,jap` -> dispositions are `1:eng,2:ger,3:jap`, ie English is the first "default" track weighted topmost, then German, then Japanese.

This is pretty close to your already available `--audio-disposition [<int>?]<string>[,<string>][]...`), which is based stream numbers.

### An example from [handbrake CLI](https://handbrake.fr/docs/en/1.3.0/cli/command-line-reference.html):

_User defines their preference in parameters handed to program:_ 

_for Audio_
`--audio-lang-list <string>` ->` --audio-lang-list eng,ger,jap`

_for Subtitles_
` --subtitle-lang-list <string>` ->` --subtitle-lang-list eng,ger,jap` (note: the order can be different here vs. audio selections theoretically)

_Define what and how to write-to-output tracks:_
I would automate this when the "language list" parameter is present and passed to the exe to write exactly in that order to output. I don't see the need for a 2nd option "write tracks" as handbrake implements it, as I feel it's redundant. 

On any errors, like "no language track would be selected" (because none of the ISO flags were present or the user forgot to add "UNK" to their list in case of a faulty and badly tagged input file (it happens often), you could 

1) automatically write the first present audio track (aka "default track" to output). 
2) print a yellow warning like "Attention: no valid audio track was selected for output! Please check if you intended this or check your encoding options."

Maybe it's possible to include this option sometime in the future when it's not too complex? Not a big deal if not, but I think it would be a great enhancement and makes NVenc more versatile in scripted environments without the need for a more complex script.

Thanks for reading.

**Comment by rigaya** [comment]
I've added **experimental** feature to select audio and subtitle by language metadata in [NVEnc 5.23](https://github.com/rigaya/NVEnc/releases/tag/5.23), for example,

```
Example1: --audio-copy eng,jpn
Example2: --audio-codec eng?aac --audio-bitrate eng?256 --audio-codec jpn?aac --audio-bitrate jpn?256
```

It's straight-forward extension of current NVEncC interface.

If there is no tracks found for the language specified, it will simple be ignored. I will add printing warning message later, which is the same behavior when selecting audio tracks by numbers.

Please note we still have problems below in current implementation.
- The track order will not be changed and will be left the same as the input file, as currently NVEncC does not have ability to change the track order.
- Likely to run into problem when there is multiple tracks with same language.

**Comment by Rincemac** [comment]
Amazing! Thanks for implementing it in experimental mode. I'll give it a try and will send you feedback on here. I do have some sources with two to three "same-language" tracks present.

No worries about the track order, this can be fixed later on pretty easily using external tools like mkvtoolnix (which can select iso flags in case it's needed).

ありがとうございます

**Comment by Eldenissio** [comment]
I've tried using --audio-copy eng, but the output file had all 3 languages from the source file. Seems like --audio-copy eng doesn't work in my case.
I'll be hoping for update soon, thank You.

**Comment by Rincemac** [comment]
Update on my end (sorry for the belated feedback, I was buried in private matters)

`--audio-copy eng` *works flawlessly in my case*, using a multitude of inputs (one track, different language tracks, etc.) 

Further to this, reading an input file containg **3** english language tracks (in different audio formats) it *correctly* writes all the tracks into the output file, *in the same order as they were present in the input file*. Hope this helps you, @rigaya.

@Eldenissio check if you have the language codes correctly flagged in the input file. The parameter is dependant on correct ISO-flagged tracks in input container. 

You can check most common input container / media formats' internal track setup with [this tool](https://mediaarea.net/en/MediaInfo) (MediaInfo). 

If you get an output like this it's correctly flagged audio:

`Audio #1
ID                             : 2
Format                         : PCM
Codec ID                       : A_PCM/INT/LIT
Duration                       : 2 h 7 min
Bit rate mode                  : Constant
Channel(s)                     : 6 channels
Sampling rate                  : 48.0 kHz
Bit depth                      : 16 bits
Title                          : Surround 5.1
*Language                       : English*
Default                        : Yes
Forced                         : No`

Incorrectly, sometimes the "Language" flag is set to "unkown" (ie. "not set in file") - in which case you'd either have to have a flag reading "unkown" (non-flagged) tracks (I beleve rigaya has not implemented matching an unkown track as of yet), so in this case you'd have to find a way to correctly set the language flag in your input manually or just using the track number.

**Comment by Eldenissio** [comment]
@Rincemac thank's for the tip.
I used **mkvtoolnix** to check input file and indeed, language flag isn't set at all on english track, although if I use old MPC-HC player that has media info built in, it reports language flad English.
I wonder if --audio-copy parameter will have opposite switch, like ffmpeg has, for example --audio-copy **-eng** which will result in all languages, except for english to be copied over from input.

**Comment by Rincemac** [comment]
@Eldenissio - np, glad it got you off in the right direction. 

MPC-HC heavily "assumes" some things I found out. Also, some files are flagged in a non-conformist way. I have had several issues with subititle flags being wrongly set as "default" and found out that MPC-HC and quite a few other s/w & h/w players "assume" the initial track to be a "default" even though no flags are set at all in the original file. So I had to actively flag the "Default to zero" on all of them to not have weird behaviour when playing on different end hardware / software.
 
MPC-HC and most other player logic seems to be "if there is a track, there *has* to be a default (ie. if you have no "default" flag set as 1 and neither a zero, it will assume a "1" for the first track.

Further, MediaInfo used as an external .exe tool instead of its DLL implementation in other tools like MPC-HC is a more "thorough" implementation and gives you the raw data in the streams. It actually reads a bit "into" the file to see what's what while MPC-HC seems to assume a lot of stuff, though I might be wrong about the "whys" here, it's just something I found out using both over here getting different results as well sometimes. Same goes for MKVToolnix, as you can also set a "deep read" parameter in case you get funky results with the default bit depth read of any file. Media files have so many different formats possible that it's a real struggle to get the correct data all the time with just "header" reads.

To your question re: negating a parameter by pre-empting with a "-":

The audio-copy will probably not "inverse" in rigayas' current implementation. It's pretty basic, ie you will not have a "minus" to reverse / detract a track for the moment (it will error out before execution). 

Maybe something he can look into, as I have no idea about the involved complexity in the classes used to read and then inverse input parameters. My C is kind of ... very basic let's say, for now. Might be super simple, might destroy some other things that currently work.

**Comment by Eldenissio** [comment]
@Rincemac wow!
Thank You for the explanation!

**Comment by rigaya** [comment]
I’ll close this issue as the feature for the major topic has been already added and seems to be working fine when tracks has language tags in the input file.
