### ISSUE TITLE
Saturated highlights turn black after conversion 10bit source into 8bit

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [rigaya/NVEnc#284]
likely related to #278 fix, 
test file:  https://drive.google.com/file/d/1mv2LF5cRKNSryofY75fuV0teBQUBbEmW/view?usp=sharing

**Comment by rigaya** [comment]
Thanks you for the samples, fixed in [NVEnc 5.23](https://github.com/rigaya/NVEnc/releases/tag/5.23).
