### ISSUE TITLE
[Feature Request]Add support for Perceptual tone mapping curve (EETF) specified in ITU-R Report BT.2390.

### ISSUE THREAD

**Issue by qwe7989199** [rigaya/NVEnc#285]
I noticed that [mpv](https://mpv.io/manual/master/#options-tone-mapping) has this option.
And it's a recommended tone-mapping method.
Is that possible to add this algorithm as one option of tone-mapping in NVEnC?

**Comment by rigaya** [comment]
I've added conversion in [NVEnc 5.23](https://github.com/rigaya/NVEnc/releases/tag/5.23). Shall work by "[--vpp-colorspace](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-colorspace-param1value1param2value2) hdr2sdr=bt2390".

**Comment by qwe7989199** [comment]
> I've added conversion in [NVEnc 5.23](https://github.com/rigaya/NVEnc/releases/tag/5.23). Shall work by "[--vpp-colorspace](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-colorspace-param1value1param2value2) hdr2sdr=bt2390".

Dear rigaya, I tried the newest release of NVEnc and it actually works.
But I also found some problems in the result.
I simply converted the hdr colorbar file downloaded from [EBU3373](https://tech.ebu.ch/publications/tech3373) which is a [4k mov file](https://tech.ebu.ch/publications/tech3373-v210).

I used the following command:
`nvencc64 -i EBU_HDR_COLOUR_BARS_2160p_v210.mov --codec h264 --vpp-colorspace hdr2sdr=bt2390 -o colorbar_sdr.mp4`

When I compared the result with madVR in potplayer with a SDR monitor, they are obviously different.
And it looks like NVEnc is getting a strange color.

<img width="920" alt="problem" src="https://user-images.githubusercontent.com/10990771/103201824-d7549c80-492b-11eb-8bc7-69c1c5cf8c0e.png">

I also tried to add `source_peak=10000.0,ldr_nits=100.0` but got the same result.

I have no idea about this and hope you can check this problem.
Thank you for your prompt response.

**Comment by rigaya** [comment]
I've checked again for the implmentation and I have made some fixes for the BT.2390 conversion in [NVEnc 5.24](https://github.com/rigaya/NVEnc/releases/tag/5.24).

Checking by MediaInfo, the hdr colorbar video you have shown seems to lack color mastering metadata, I think that the tonemap is not actually applied to the video in madVR. I also think that the hdr2sdr conversion should not be applied to the colorbar, only colormatrix conversion is required for that file.

With other videos which has color mastering metadata, I was able to get similar result by comparing against mpv.

mpv.exe --tone-mapping=bt.2390 --target-peak=100 "inputfile"
NVEncC64.exe -i "inputfile" -o "outputfile" --vpp-colorspace hdr2sdr=bt2390,ldr_nits=100.0

**Comment by qwe7989199** [comment]
> I've checked again for the implmentation and I have made some fixes for the BT.2390 conversion in [NVEnc 5.24](https://github.com/rigaya/NVEnc/releases/tag/5.24).
> 
> Checking by MediaInfo, the hdr colorbar video you have shown seems to lack color mastering metadata, I think that the tonemap is not actually applied to the video in madVR. I also think that the hdr2sdr conversion should not be applied to the colorbar, only colormatrix conversion is required for that file.
> 
> With other videos which has color mastering metadata, I was able to get similar result by comparing against mpv.
> 
> mpv.exe --tone-mapping=bt.2390 --target-peak=100 "inputfile"
> NVEncC64.exe -i "inputfile" -o "outputfile" --vpp-colorspace hdr2sdr=bt2390,ldr_nits=100.0

It does work like mpv, but still slightly different from the result by madvr.
Anyway, thank you for adding this feature!
