### ISSUE TITLE
"colorspace_conv: NVRTC error: NVRTC_ERROR_INVALID_OPTION" error with RTX 3070

### ISSUE THREAD

**Issue by jdsanchezii** [rigaya/NVEnc#286]
**Summary**
We have been experiencing an unusual error when attempting to use the _vpp-colorspace_ filter while using a new Ampere-based GPU (RTX 3070).

**Full Error Text**
>colorspace_conv: failed to build program source.
>colorspace_conv: NVRTC error: NVRTC_ERROR_INVALID_OPTION
>colorspace: failed to setup custom filter.

**Description**
The described error only occurs when trying to use the _vpp-colorspace_ filter. Removing the filter from the command-line allows the encoding to proceed. Please note, error does not occur when using a Turing GPU (RTX 2080). We have also tried the same encode using raw HEVC files. The result was the same. We also tried specifying the exact "from" value for each colorspace option (i.e. matrix=bt2020nc:bt709). The result was the same.

The following is the the command-line being used when the error occurs:
> `nvencc64.exe --avhw --codec hevc --vbrhq 24576 --vbr-quality 1 --qp-init 16 --preset quality --aq-temporal --aq-strength 0 --lookahead 24 --mv-precision Q-pel --bframes 4 --output-res 1920x1080 --vpp-colorspace matrix=auto:bt709,colorprim=auto:bt709,transfer=auto:bt709,range=auto:limited,hdr2sdr=hable,source_peak=1000,ldr_nits=125 --profile main --level 4.1 --tier high --colorrange limited --colorprim bt709 --transfer bt709 --colormatrix bt709 --input input.mkv --output output.mkv`

**check-device Output**
> NVEncC (x64) 5.22 (r1732) by rigaya, Dec  1 2020 21:01:52 (VC 1928/Win/avx2)
>   [NVENC API v11.0, CUDA 10.1]
>  reader: raw, y4m, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]
> 
> Environment Info
> OS : Windows 10 x64 (18363)
> CPU: AMD Ryzen 5 3600XT 6-Core Processor (6C/12T)
> RAM: Used 7136 MB, Total 16334 MB
> 
> #0: GeForce RTX 3070 (5888 cores, 1815 MHz)[PCIe3x16][460.89]
> NVEnc features
> Codec: H.264/AVC
> Encoder Engines           1
> Max Bframes               4
> B Ref Mode                2 (only middle)
> RC Modes                  63
> Field Encoding            0 (no)
> MonoChrome                no
> FMO                       no
> Quater-Pel MV             yes
> B Direct Mode             yes
> CABAC                     yes
> Adaptive Transform        yes
> Max Temporal Layers       4
> Hierarchial P Frames      no
> Hierarchial B Frames      no
> Max Level                 62
> Min Level                 10
> 4:4:4                     yes
> Min Width                 145
> Max Width                 4096
> Min Height                49
> Max Height                4096
> Multiple Refs             yes
> Max LTR Frames            8
> Dynamic Resolution Change yes
> Dynamic Bitrate Change    yes
> Forced constant QP        yes
> Dynamic RC Mode Change    no
> Subframe Readback         yes
> Constrained Encoding      yes
> Intra Refresh             yes
> Custom VBV Bufsize        yes
> Dynamic Slice Mode        yes
> Ref Pic Invalidiation     yes
> PreProcess                no
> Async Encoding            yes
> Max MBs                   65536
> Lossless                  yes
> SAO                       no
> Me Only Mode              1 (I,P frames)
> Lookahead                 yes
> AQ (temporal)             yes
> Weighted Prediction       yes
> 10bit depth               no
> 
> Codec: H.265/HEVC
> Encoder Engines           1
> Max Bframes               5
> B Ref Mode                3 (each + only middle)
> RC Modes                  63
> Field Encoding            0 (no)
> MonoChrome                no
> Quater-Pel MV             yes
> B Direct Mode             no
> Max Temporal Layers       0
> Hierarchial P Frames      no
> Hierarchial B Frames      no
> Max Level                 186
> Min Level                 30
> 4:4:4                     yes
> Min Width                 129
> Max Width                 8192
> Min Height                33
> Max Height                8192
> Multiple Refs             yes
> Max LTR Frames            7
> Dynamic Resolution Change yes
> Dynamic Bitrate Change    yes
> Forced constant QP        yes
> Dynamic RC Mode Change    no
> Subframe Readback         yes
> Constrained Encoding      yes
> Intra Refresh             yes
> Custom VBV Bufsize        yes
> Dynamic Slice Mode        yes
> Ref Pic Invalidiation     yes
> PreProcess                no
> Async Encoding            yes
> Max MBs                   262144
> Lossless                  yes
> SAO                       yes
> Me Only Mode              1 (I,P frames)
> Lookahead                 yes
> AQ (temporal)             yes
> Weighted Prediction       yes
> 10bit depth               yes
> 
> NVDec features
>   H.264/AVC:  nv12, yv12
>   H.265/HEVC: nv12, yv12, yv12(9bit), yv12(10bit), yv12(12bit), yuv444, yuv444(9bit), yuv444(10bit), yuv444(12bit)
>   MPEG1:      nv12, yv12
>   MPEG2:      nv12, yv12
>   MPEG4:      nv12, yv12
>   VP8:        nv12, yv12
>   VP9:        nv12, yv12, yv12(9bit), yv12(10bit), yv12(12bit)
>   VC-1:       nv12, yv12
>   AV1:        nv12, yv12, yv12(9bit), yv12(10bit)

**Comment by rigaya** [comment]
Thank for your report, I've tried fixing this in [NVEnc 5.23](https://github.com/rigaya/NVEnc/releases/tag/5.23). I think it's fixed, but it's not tested as I don't have Ampere gen GPUs myself.

Please have a try when you have time, and would you let me know if it works fine?

**Comment by jdsanchezii** [comment]
> Please have a try when you have time, and would you let me know if it works fine?
This appears to be working properly in the latest release. Thank you.
