### ISSUE TITLE
NPP_STEP_ERROR

### ISSUE THREAD

**Issue by Demicro** [rigaya/NVEnc#287]
NPP_STEP_ERROR when trying to convert a video using the main444 profile with the lanczos filter. Changing the filter with the default does not happen this problem

3840x2160 to 1920x1080

resize: failed to resize: -14, NPP_STEP_ERROR.
Error while running filter "resize".

**Comment by rigaya** [comment]
Thank you for letting me know, I'll have it fixed in the next release.

**Comment by rigaya** [comment]
Thank you for letting me know, shall be fixed in [NVEnc 5.24](https://github.com/rigaya/NVEnc/releases/tag/5.24).
