### ISSUE TITLE
What does vpp-smooth ?

### ISSUE THREAD

**Issue by JibsouX** [rigaya/NVEnc#288]
Hello, i'm wondering what does the setting called "vpp-smooth" really ? https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-smooth-param1value1param2value2
It's a deblock filter like SmoothD/D2 from AviSynth ?

Thanks in advance !

**Comment by rigaya** [comment]
Yes, should be generally the same, but I've refered [ffmpeg spp filter](https://ffmpeg.org/ffmpeg-filters.html#spp-1) for the basics, and is also little simplified to make GPU implementation easier. For example, it cannot use the QP values from the video stream which the original spp can. (It's not easy to implement this)

**Comment by rigaya** [comment]
I'll close this issue, as the question has been answered. Please reopen if you have further queries.
