### ISSUE TITLE
CUDA 11.1 - change of DLL names from _10 to _11 to support --vpp-resize

### ISSUE THREAD

**Issue by mason362** [rigaya/NVEnc#289]
In the recent CUDA releases, the relevant DLLs needed to support --vpp_resize are now versioned to _11.dll file names.
A copy of these to same directory as NVEncC64.exe doesn't allow them to be used. It is necessary to rename them to still use _10.dll file names.

Would it be possible for program to determine the CUDA installation and hence use correct versioned files. 

For now, I am copying nppc64_11.dll, nppif64_11.dll and nppig64_11.dll then renaming them to be _10.dll which seems to work fine.

**Comment by rigaya** [comment]
As current [NVEncC release binaries](https://github.com/rigaya/NVEnc/releases/tag/5.23) are built against CUDA 10, using _11.dll is not recommended, using _10.dll files is recommended.

**Comment by mason362** [comment]
Understood. Will downgrade CUDA to 10.x release and ensure use of _10.dll files.
