### ISSUE TITLE
UHD to FHD results in 1088 output

### ISSUE THREAD

**Issue by Dave--G** [rigaya/NVEnc#29]
Attempting to convert 4K UHD resolution source to 1080p FHD output generates 1088 vertical resolution output.

Example command line:
`NVEncC64.exe --vbrhq 2560 --codec h265 --preset quality --output-depth 10 --gop-len 90 --lookahead 32 --aq --vpp-resize default --output-res 1920x1088 -i "T:\TEST.MP4" -o "D:\Temp\TEST.h265"

Results in output:
NVEncC (x64) 3.23 (r667) by rigaya, Sep 26 2017 20:51:36 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (16299)
CPU            Intel Core i7-8700K @ 3.70GHz [TB: 4.70GHz] (6C/12T)
GPU            #0: GeForce GTX 1080 (20 EU) @ 1860 MHz (388.71)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 30000/1001 fps
Vpp Filters    cspconv(nv12 -> p010)
Output Info    H.265/HEVC main10 @ Level auto
1920x**1088**p 1:1 29.970fps (30000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        2560 kbps (Max: 11520 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     90 frames
B frames       0 frames
Ref frames     3 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto
`
Bug (or question?) is the output info field is 1920x1088 not 1920x1080 as expected.  This appears to break desired 16:9 aspect ratio and damage scaling due to non-^2 ratio.  Suspect this is a MOD 8 vs MOD 16 issue.  Is there any way to set output modulus to 8 instead of 16?

**Comment by rigaya** [comment]
NVEncC can output 1080p in 1920x1080.

Please set --output-res 1920x108**0**, and not to 1920x108**8**.

**Comment by Dave--G** [comment]
Oh gosh.  this certainly looks like the error is on my side.  Somehow I missed the 1088 on the command line.  Thanks for your response, Rigaya.  I will close the bug and look into the issue on my side.
