### ISSUE TITLE
What does “Standard: Reserved” mean ?

### ISSUE THREAD

**Issue by shookgao** [rigaya/NVEnc#290]
Hi, rigaya:  
My conversion is  
 `nvencc --avhw --preset quality --profile main10 --tier high --colorrange auto --videoformat auto --colormatrix auto --colorprim auto --transfer auto --chromaloc auto --max-cll copy --master-display copy --codec hevc --audio-copy 1 --sub-copy 1 -i x.mkv -o y.mkv`;  
results compared with MediaInfo, we found that there was one more parameter and value `Standard: Reserved` after conversion；  
How is this caused and what is the impact?  
[![rbzcDg.png](https://s3.ax1x.com/2020/12/29/rbzcDg.png)](https://imgchr.com/i/rbzcDg)

**Comment by rigaya** [comment]
I also don't know the meaning of this flag in MediaInfo...

**Comment by shookgao** [comment]
@rigaya I found that the problem is caused by the parameter "--videoformat auto". If you cancel this parameter, there will be no such problem. Will it have any effect if you don't use this parameter?

**Comment by rigaya** [comment]
Actually --videoformat auto was not working correctly. As it was difficult to get the corresponding value of the input file from the demuxer, I've decided to remove "auto" from videoformat from [NVEnc 5.25](https://github.com/rigaya/NVEnc/releases/tag/5.25). Sorry for in inconvenience caused here.
