### ISSUE TITLE
check-features fix & feature request

### ISSUE THREAD

**Issue by SiV44** [rigaya/NVEnc#291]
Hello Rigaya,

When using --check-features, the minimum and maximum level information for the H264/AVC codec is:

> Max Level                 62
Min Level                 10

for HEVC:

> Max Level                 186
Min Level                 30

Help file information:

>--level <string>             set codec level
                                - H.264: auto(default), 1, 1b, 1.1, 1.2, 1.3
                                         2, 2.1, 2.2, 3, 3.1, 3.2, 4, 4.1, 4.2
                                         5, 5.1, 5.2
                                - HEVC:  auto(default), 1, 2, 2.1, 3, 3.1, 4
                                         4.1, 5, 5.1, 5.2, 6, 6.1, 6.2

Is it possible to fix this?

--------------------------

Feature request, is it possible to implement any option for sample adaptive offset??
For example:

>--(no-)sao
--(no-)limit-sao
--selective-sao

--------------------------

_Thanks in advance_

**Comment by rigaya** [comment]
> check-features fix

This is not actually wrong as it is returning internal value representing level in NVENC SDK correctly, but as it is not user friendly as you have mentioned, I've changed the --check-features behavior in [NVEnc 5.24](https://github.com/rigaya/NVEnc/releases/tag/5.24), now you shall additionally get the actual value of the level supported like [this](https://github.com/rigaya/NVEnc/blob/master/GPUFeatures/rtx2070.txt).

> Feature request, is it possible to implement any option for sample adaptive offset??

Unfortunately not, NVENC SDK seems to not support this kind of parameters, so it's not possible to add these options.

**Comment by SiV44** [comment]
>This is not actually wrong as it is returning internal value representing level in NVENC SDK correctly, but as it is not user friendly as you have mentioned, I've changed the --check-features behavior in NVEnc 5.24, now you shall additionally get the actual value of the level supported like this.

Great, thank you very much.
I read the NVENC Application Note and API Programming Guide and found no information on levels or encoding up to 8K in H264/AVC but it works fine, the only limitation now is the maximum height and width (4096x4096), could you please change this limit to see if is encoding with higher resolution possible?

---

>Unfortunately not, NVENC SDK seems to not support this kind of parameters, so it's not possible to add these options.

Thank you, SDK does not offer any settings for SAO and we can't do anything about it, however Application Note contains information about this option, that it has been available in HEVC since Pascal generation, and the --check-features option also informs that it is available.
The question is, does this feature work?

**Comment by viliml** [comment]
@SiV44 according to https://developer.nvidia.com/downloads/nvenc-application-note, SAO is always enabled
