### ISSUE TITLE
Main10 when you choose main444 in lossless mode

### ISSUE THREAD

**Issue by Demicro** [rigaya/NVEnc#297]
Video is encoded in main10 when you have set main444 in lossless mode. I do not know if it is so by default or is it some error.
I was expecting something prores type that does 4444 in lossless mode

**Comment by SiV44** [comment]
Hi,
The `--lossless` option forces `--cqp 0:0:0 --profile main10` and disables `--aq`, so this is the default.
I doubt rigaya would limit this option to 4:2:0 if 4:4:4 could be used.
So it remains to use `--cqp 0:0:0 --profile main444 --output-depth 10` without `--lossless` and everything works as it should.

>Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Format Range@L5.1@High
Codec ID                    : V_MPEGH/ISO/HEVC
Duration                    : 1 min 16 s
Bit rate                    : 564 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 29.970 (30000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:4:4
Bit depth                   : 10 bits

YUV is not RGB, and 10 is not 12 bits, but for more, we have to wait, maybe in the next SDK they will give us more options. 

---
Best regards

**Comment by Demicro** [comment]
Thanks for answering. If that method produces the same result then I will use it. I have always used VBR, I am more familiar with that kind of mode

**Comment by SiV44** [comment]
I'm glad that I could help.
Using VBR with the settings `--vbr 0 --profile main444 --output-depth 10 --qp-init 0:0:0 --qp-max 0:0:0 --qp-min 0:0:0 --vbr-quality 1` the result is:

>Format                   : HEVC
Format/Info              : High Efficiency Video Coding
Format profile           : Format Range@L5.1@High
Codec ID                 : V_MPEGH/ISO/HEVC
Duration                 : 1 min 16 s
Bit rate                 : 566 Mb/s
Width                    : 3 840 pixels
Height                   : 2 160 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 29.970 (30000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:4:4
Bit depth                : 10 bits

So, it is similar to CQP mode, only slight difference in bitrate.
After all, VBR is a better mode than CQP.

---
Best regards

**Comment by Demicro** [comment]
I have tried several times and the result is a 90-100 Mb / s bitrate file. During the process it oscillates at more than 40 Mb/s 
I will try to pipe with ffmpeg and use prores. I need to make a cut on a specific frame and ffmpeg does not have that function. It does so based on the duration and not the frame.

**Comment by rigaya** [comment]
About lossless mode, --lossless mode uses 444 only if the input file is 444, and 420 for others.

It is possible to remove this limit by adding "--lossless-ignore-input-csp" like below.

--lossless -c hevc --output-depth 10 --profile main444 --lossless-ignore-input-csp
