### ISSUE TITLE
subburn: error opening file

### ISSUE THREAD

**Issue by seiya-git** [rigaya/NVEnc#298]
![изображение](https://user-images.githubusercontent.com/7394323/104342045-7ae8a400-550b-11eb-9624-fd2eb861b416.png)
`subburn: error opening file: "test.ass": Invalid data found when processing input`
with this test file but working fine with players
[test.ass.txt](https://github.com/rigaya/NVEnc/files/5803386/test.ass.txt)

**Comment by rigaya** [comment]
Thank you for the sample, shall be fixed with [NVEnc 5.26](https://github.com/rigaya/NVEnc/releases/tag/5.26).
