### ISSUE TITLE
YUV option to switch between limited TV (16-235) and full PC (0-255) colorspace

### ISSUE THREAD

**Issue by Walcund** [rigaya/NVEnc#299]
Hello Rigaya!

Can you implement a YUV option to switch between limited TV (16-235) and full PC (0-255) colorspace?

It would be very important!
Thank you for your reply!
Best regards!
Bye!

**Comment by rigaya** [comment]
Will you have a try with conversion by [--vpp-colorspace](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-colorspace-param1value1param2value2)?

**Convert from limited to full**
--vpp-colorspace range=limited:full

**Convert from full to limited**
--vpp-colorspace range=full:limited

**Comment by rigaya** [comment]
I'll close the issue as the topic has been answered.
