### ISSUE TITLE
Deinterlacing y4m pipe input?

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#3]
I tried using '--vpp-deinterlace adaptive' and then had to additionally enable '--avcuvid cuda' which them gave me:
> avcuvid: codec
avcuvid: unable to decode by cuvid.
Failed to open input file.

so my guess is that feeding NVEncC with a y4m pipe and using the deinterlacer is either not supported or not possible. :)

-> Would it be possible to support deinterlacing when NVEnC is fed through a y4m pipe (or isn't that possible due to some SDK restriction)?

**Comment by rigaya** [comment]
Unfortunately, it is not possible to use the current deinterlacer when reading from y4m pipe.

As you have guessed, the problem is due to SDK restriction, the deinterlacer is part of cuvid. Therefore, deinterlacer could be only enabled when using cuvid decode (avcuvid reader).

**Comment by Selur** [comment]
Okay. Thanks for clearing that up. :)
