### ISSUE TITLE
Uneven encoding quality

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/NVEnc#301]
Hello! I am working on integrating this tool into [FastFlix](https://fastflix.org/) and currently trying to near duplicate output of the `FFmpeg` `hevc_nvenc` encoder, and have discovered that there are large spikes and dips when using this tool.

Version 5.25 (r1777) on Windows 10 with GTX 1080.

Examples using [this file](https://github.com/cdgriffith/FastFlix/blob/master/tests/media/Beverly%20Hills%20Duck%20Pond%20-%20HDR10plus%20-%20Jessica%20Payne.mp4)

![nvenc_PSNR](https://user-images.githubusercontent.com/3275435/106072626-211cd800-60ce-11eb-96d7-69c0f29b7f87.png)
* Comparison generated using [FFMetrics](https://github.com/fifonik/FFMetrics)

FFmpeg commands: 
```
"ffmpeg.exe" -y -i "Beverly Hills Duck Pond - HDR10plus - Jessica Payne.mp4" -max_muxing_queue_size 1024 -map 0:0 -c:v hevc_nvenc -pix_fmt p010le -tune:v hq -color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc -spatial_aq:v 1 -tier:v main -rc-lookahead:v 16 -gpu -1 -profile:v main10 -rc:v vbr -pass 1  -b:v 6000k -preset:v slow -2pass 1 -an -sn -dn -f mp4 NUL
"ffmpeg.exe" -y -i "Beverly Hills Duck Pond - HDR10plus - Jessica Payne.mp4" -max_muxing_queue_size 1024 -map 0:0 -c:v hevc_nvenc -pix_fmt p010le -tune:v hq -color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc -spatial_aq:v 1 -tier:v main -rc-lookahead:v 16 -gpu -1 -profile:v main10 -rc:v vbr -pass 2  -2pass 1 -b:v 6000k -preset:v slow -map_metadata -1 -map_chapters 0 "ffmpeg-hevc-nvenc-6000k-slow.mkv"
```

NVEncC command: 
```
NVEncC -i "Beverly Hills Duck Pond - HDR10plus - Jessica Payne.mp4" -c hevc --profile main10 --tier main --output-depth 10 --vbr 6000k --preset quality --multipass 2pass-full --aq --repeat-headers --colormatrix bt2020nc --transfer smpte2084 --colorprim bt2020 --lookahead 16 -o "nvenc-6000k.mkv"
```

I have tried a slew of different options from lowering the GOP, enable /disable aq, all three presets, disabling multipass, main vs main10 profile, main vs high tier, etc... and it always has a similar up and down shape. 

Any help evening out the encode quality would be appreciated! 

Thanks for this great encoder! I look forward to using it on HDR content!

**Comment by rigaya** [comment]
Your input file seems to be VFR(Variable frame rate).

NVEncC assumes CFR(Constant frame rate) by default and that is causing the issue. Frames with non-matching timestamps will get interpolated, causing very low ssim.

By adding "--avsync vfr" to the command line option, and writing in mp4 format (to be the same timebase as the input), will resolve the issue. getting a lot more stable quality as below.

x64\NVEncC64.exe -i "Beverly Hills Duck Pond - HDR10plus - Jessica Payne.mp4" -c hevc --profile main10 --tier main --output-depth 10 --vbr 6000 --preset quality --multipass 2pass-full --aq --repeat-headers --colormatrix bt2020nc --transfer smpte2084 --colorprim bt2020 --lookahead 16 -o "nvenc-6000k.**mp4**" **--avsync vfr**

![SSIM](https://user-images.githubusercontent.com/815947/106132857-d2dc0780-61a7-11eb-822e-f237ef38892a.png)

**Comment by cdgriffith** [comment]
Perfect, you are amazing! Thanks so much!
