### ISSUE TITLE
Wrong cli parameter help for vpp-warpsharp

### ISSUE THREAD

**Issue by Dendraspis** [rigaya/NVEnc#304]
Hello rigaya,

just FYI:  
Whereas the [docs](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-warpsharp-param1value1param2value2) and the [source](https://github.com/rigaya/NVEnc/blob/42d74a6befb3fd78ad91ef97eb7b5d9ff313f3a7/NVEncCore/NVEncCmd.cpp#L435) seem to tell the same story:

```
    threshold=<float> (default=128.0, 0 - 255)
    Threshold used when detencting edges. Raising this value will result stronger sharpening.

    blur=<int> (default=2)
    Number of times to blur. More times of blur will result weaker sharpening.

    type=<int> (default=0)
        0 ... use 13x13 size blur.
        1 ... use 5x5 size blur. This results higher quality, but requires more blur counts.

    depth=<float> (default=16.0, -128.0 - 128.0)
    Depth of warping, raising this value will result stronger sharpening.

    chroma=<int> (default=0)
    Select how to process chroma channels.
        0 ... Use luma based mask to process hcroma channels.
        1 ... Create individual mask for each chroma channels.
```

https://github.com/rigaya/NVEnc/blob/42d74a6befb3fd78ad91ef97eb7b5d9ff313f3a7/NVEncCore/NVEncCmd.cpp#L435-L447

... `NVEncC64.exe --help` isn't. 
`chroma` is missing as well as the `blur`-range and the defaults for `threshold` and `blur` seem to be wrong, too:

```
   --vpp-warpsharp [<param1>=<value>][,<param2>=<value>][...]
     warpsharp filter to enhance edge.
    params
      threshold=<float>         edge mask threshold (default=0.0, 0-255)
      blur=<int>                number of times to blur the edge mask.
                                  (default=0, 0-)
      type=<int>                blur type, 0...13x13, 1...5x5 (default=2)
      depth=<float>             how far to warp (default=0.0, -128 - 128)
```

But I guess this problem solves itself with the next build, right?  ☺️

**Comment by rigaya** [comment]
Actually the [doc](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-warpsharp-param1value1param2value2) is correct, I'll fix --help in the next release.

It's simple, the last comma in line443 of NVEncCmd.cpp is unnecessarily, it shouldn't be there.

**Comment by Dendraspis** [comment]
You're welcome.
So my guess was wrong, there was no building issue - haven't seen the evil comma that has to be removed.  😁 

Thanks.  😊

**Comment by Dendraspis** [comment]
Just because I had the tabs still opened and thought it could help I created this PR:
#305 

Feel free to merge or discard.  ☺️
