### ISSUE TITLE
[Feature Request] use fonts from mkv container for vpp-subburn

### ISSUE THREAD

**Issue by anidl** [rigaya/NVEnc#307]
Hello. Please add feature for vpp-subburn.
When subtitle track is set and container is mkv
vpp-subburn will use additional fonts from mkv itself (like ffmpeg does)

**Comment by anidl** [comment]
also can we have fontsdir for vpp-subburn like ffmpeg does
https://ffmpeg.org/ffmpeg-filters.html#subtitles-1

**Comment by rigaya** [comment]
I7ve added both features requested to [--vpp-subburn](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-subburn-param1value1param2value2) in [NVEnc 5.27](https://github.com/rigaya/NVEnc/releases/tag/5.27), please have a try.
