### ISSUE TITLE
AviSynth Unicode support on Windows 10 1903

### ISSUE THREAD

**Issue by stax76** [rigaya/NVEnc#309]
I would like to request AviSynth Unicode support and long path support on Windows 10 1903.

https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

https://github.com/staxrip/staxrip/wiki/AviSynth-Unicode-support-on-Windows-10-1903

**Comment by rigaya** [comment]
Thank you for the documents to support Win10 long path support.

I've made updates for the manifest and some of the codes, next release (perhaps coming soon) should have support for Win10 long path.

**Comment by stax76** [comment]
Sounds great, thank you.

**Comment by rigaya** [comment]
[NVEnc 5.27](https://github.com/rigaya/NVEnc/releases/tag/5.27) is out, adding support for long path support on Win10.

I'll work on AviSynth Unicode support later, as I'm not sure about this now.

**Comment by stax76** [comment]
Thank you.

For AviSynth Unicode support on Windows 10 often there is no code change needed, but only the manifest change.

**Comment by rigaya** [comment]
Now [NVEnc 5.28](https://github.com/rigaya/NVEnc/releases/tag/5.28) has Avisynth Unicode support , thanks to the manifest you have shown.

I'm also planning to add AviSynth Unicode support and Win10 long path support to QSVEnc/VCEEnc in the next release of them.

**Comment by stax76** [comment]
Thank you rigaya!

I've updated StaxRip and the Wiki.

**Comment by rigaya** [comment]
@stax76  Both Win10 long path support and Avisynth Unicode support has been added in [QSVEnc 4.13](https://github.com/rigaya/QSVEnc/releases/tag/4.13) and [VCEEnc 6.09](https://github.com/rigaya/VCEEnc/releases/tag/6.09).

**Comment by stax76** [comment]
Thank you!

It will be supported in the next StaxRip Beta build.

[Wiki was updated](https://github.com/staxrip/staxrip/wiki/AviSynth-Unicode-support-on-Windows-10-1903).
