### ISSUE TITLE
v3.28 output file from hevc encode metadata doesn't look the same

### ISSUE THREAD

**Issue by hydra3333** [rigaya/NVEnc#31]
I must be doing something wrong or reading it incorrectly.  
Advice welcomed.
Debug log attached.
[2.Real_4K_HDR_60fps_-_Sony_Food_Fizzle.webm.nvencc.log](https://github.com/rigaya/NVEnc/files/1728050/2.Real_4K_HDR_60fps_-_Sony_Food_Fizzle.webm.nvencc.log)

**Comment by hydra3333** [comment]
silly me, I should try a different output format :(

**Comment by hydra3333** [comment]
Hmm. the metadata in the output file seems to be different, eg not like this

[2.Real_4K_HDR_60fps_-_Sony_Food_Fizzle.webm.nvencc.log](https://github.com/rigaya/NVEnc/files/1728225/2.Real_4K_HDR_60fps_-_Sony_Food_Fizzle.webm.nvencc.log)

```
[SIDE_DATA]
side_data_type=Mastering display metadata
red_x=50000/50000
red_y=50000/50000
green_x=50000/50000
green_y=50000/50000
blue_x=50000/50000
blue_y=50000/50000
white_point_x=50000/50000
white_point_y=50000/50000
min_luminance=1000/10000
max_luminance=5000/10000
[/SIDE_DATA]
```

**Comment by rigaya** [comment]
Thank you for reporting, I've checked again, but not yet able to figure out the reason of the difference in ffprobe putput.

Comparing the NVEncC raw output with x265, it looks the same, either on ffprobe or MediaInfo.

[log_compare_x265_nvenccc.txt](https://github.com/rigaya/NVEnc/files/1731501/log_compare_x265_nvenccc.txt)

**x265 raw output**
![mediainfo_x265_raw](https://user-images.githubusercontent.com/815947/36310172-9074bfa6-136a-11e8-8727-ae25a323acb2.png)

**NVEncC raw output**
![mediainfo_nvencc_raw](https://user-images.githubusercontent.com/815947/36310175-93e7b21a-136a-11e8-8917-300a839cbf86.png)

As you have mentioned, metadata info does not show up from ffprobe output (on the log), but I can see it is applied when I check through mediainfo.

**NVEncC mp4 output**
![mediainfo_nvencc_mp4](https://user-images.githubusercontent.com/815947/36310179-94ed0084-136a-11e8-842a-7f1fa96753a6.png)

**Comment by hydra3333** [comment]
Ah OK, thank you.

I'll look into using mediainfo instead of ffprobe, since I currently parse ffprobe output to find and put the correct values into DOS variables to add them into the nvencc commandline.  I hope they're the same although I seem to recall some minor difference in reported value for transfer, but I'll go back and check now.

Thank you and congratulations for creating such a wonderful program.
