### ISSUE TITLE
Files encoded with the --vpp-edgelevel option results in small darker output files since NVEnc version 5.26 or higher

### ISSUE THREAD

**Issue by nagten** [rigaya/NVEnc#310]
**Description**
When encoding video files with the `--vpp-edgelevel` option the end result since version 5.26 seems to be wrong. Encoding results in a smaller darker output file it seems no edge filtering takes place.

**Current NVEnc Behavior**
When encoding sample file "Monarch_HD_1920x1080HQ_25000kbps.mp4" with NVEnc 5.26 or higher and following minimal option command line: 
* "NVEncC64.exe --codec h265 --preset quality --vpp-edgelevel -i Monarch_HD_1920x1080HQ_25000kbps.mp4 -o 5_26_Monarch_HD_1920x1080HQ_25000kbps_out.h265 --log 5_26.log --log-level debug" 

The result is very dark compared to the original and only 74.4 MB in size.

*encoded 1835 frames, 217.75 fps, 10201.85 kbps, 74.46 MB*

In comparison when we encode the same sample file with NVEnc 5.25 or lower the end result has the same colors as the sample file and an expected output file size. 

Command used: 
* "NVEncC64.exe --codec h265 --preset quality --vpp-edgelevel -i Monarch_HD_1920x1080HQ_25000kbps.mp4 -o 5_25_Monarch_HD_1920x1080HQ_25000kbps_out.h265 --log 5_25.log --log-level debug"

*encoded 1835 frames, 176.41 fps, 21482.07 kbps, 156.80 MB*

Source of sample file: https://www.matrox.com/en/video/products/encoders-decoders/monarch-series/test-monarch-hd-video-encoding-quality 

**Expected Behavior**
`--vpp-edgelevel` should work and produce the same results before version 5.26 it seems that somehow the feature to implement `--vpp-warpsharp` broke `--vpp-edgelevel` https://github.com/rigaya/NVEnc/compare/5.25...5.26.

**System Info**
Geforce GTX 1080 TI
Driver version 461.40

Attached debug log files: 5_25.log and 5_26.log

[5_26.log](https://github.com/rigaya/NVEnc/files/5971579/5_26.log)
[5_25.log](https://github.com/rigaya/NVEnc/files/5971582/5_25.log)

**Comment by rigaya** [comment]
Thank you for letting me know, I accidentally broke it when I implemented --vpp-warpsharp as you have pointed out.

Shall be fixed by [NVEnc 5.28](https://github.com/rigaya/NVEnc/releases/tag/5.28).

**Comment by nagten** [comment]
Just tested 2 encodes with 5.28 and `--vpp-edgelevel` works again correctly.

*NVEncC (x64) 5.28 (r1809) by rigaya, Feb 12 2021 13:32:55 (VC 1928/Win/avx2)*
*encoded 1835 frames, 177.47 fps, 21440.08 kbps, 156.49 MB*
