### ISSUE TITLE
Green edge when converting HDR to SDR at some specific resolutions

### ISSUE THREAD

**Issue by Last-Order** [rigaya/NVEnc#313]
When encoding video files at some specific resolutions, `--vpp-colorspace hdr2sdr=hable` produced strange results. There is always a green edge at the right border of the video.

My command: `NVEncC64.exe -i blank.mp4 --vbr 3000 --vpp-colorspace hdr2sdr=hable -o D:/blank.out.mp4`

![image](https://user-images.githubusercontent.com/3362825/108455714-ae0c1900-72a9-11eb-8917-dc266bf110c5.png)

Video sample (270x480, no HDR though): https://48.gigafile.nu/0226-b5df682c59f0bfbf5964a09c08a05c008

**Comment by rigaya** [comment]
Seem to be caused when using unusual width which cannot be divided by 4.  4b4d671 will fix this, and will be included in the next release.

**Comment by rigaya** [comment]
The issue shall be fixed in [NVEnc 5.30](https://github.com/rigaya/NVEnc/releases/tag/5.30).
