### ISSUE TITLE
Dual Nvidia Card Setup

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#315]
I did not find anywhere if this is possible or not.

I tried to use one Nvidia card to decode and the other card to encode, but I ran out of ideas on balancing the task.

**Comment by rigaya** [comment]
The entire process of transcoding will be done on the same card, and it cannot be divided.

There is no advantage in running decode and encode on different card, as they are independent block on the GPU card. Furthermore, it will add additional latency which might harm performance.

**Comment by quamt** [comment]
Ok. Thank you for the info.
