### ISSUE TITLE
Convert dual audio into one

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#317]
Hello,

I have a screen recorder that creates two audio files when recording the screen.
One file is for everything that's being stayed over the mic.
The second one is the output from apps sound or external sound.

Is it possible to combine both files into one while encoding with NVenc?

The screen recorder software takes a long time to render the file, and there are no additional settings on the output nor GPU acceleration for encoding.
Below a screenshot of media info from one of the files
![image](https://user-images.githubusercontent.com/64795789/109106567-01c7a800-776b-11eb-8591-a234021befba.png)

**Comment by rigaya** [comment]
You mean to convert 2 audio streams into 1 audio stream, right?

Unfortunately, NVEncC don't support that kind of audio filters.

**Comment by quamt** [comment]
Ok, understand.
Ill use FFmpeg to do that instead.
“D:\\ffmpeg.exe” -i "test.file" -map 0:0 -map 0:1 -map 0:2 -filter_complex amix=inputs=2 -c:v copy -c:a aac Output.mkv`

Trying to pipe it to NVencC creates error messages, not sure if that's because of the NVencC.
