### ISSUE TITLE
Crash with special characters in input file name

### ISSUE THREAD

**Issue by Opa53** [rigaya/NVEnc#319]
Using NVEnc with StaxRip, it crashes since version 5.28 as soon as special characters like ä, ö, ü (like in German words) are in the input file name. Until version 5.27, it works fine.

**Comment by rigaya** [comment]
NVEnc 5.28 has added Avisynth Unicode support, which requires avs script file to be in UTF-8.

StaxRip 2.1.8.1 Beta or later should support this. Please update if you are using StaxRip before this version.

**Comment by Opa53** [comment]
Many thanks for your prompt reply, StaxRip 2.1.8.4beta indeed solves the problem.
