### ISSUE TITLE
NV_ENC_CAPS_SUPPORT_SAO ?

### ISSUE THREAD

**Issue by JibsouX** [rigaya/NVEnc#320]
Hello Rigaya :).
I'm wondering, is it possible to add a setting to switch of the SAO ?  (NV_ENC_CAPS_SUPPORT_SAO)

Thanks in advance !

**Comment by rigaya** [comment]
Unfortunately "NV_ENC_CAPS_xxx" key is a key to check whether the environment (the hardware and the driver) supports the feature, and not a key to switch it on of off.

The key is used to show the result of --check-features, as a example, please refer to the link below.
https://github.com/rigaya/NVEnc/blob/master/GPUFeatures/rtx2070.txt#L92

I have checked for the switch of SAO in the NVENC SDK, but somehow it's not there, so I assume that it is used automatically depending on the preset you have chosen.

**Comment by JibsouX** [comment]
God damn..
you think it's possible build a test version with a "corrupt"/"tweaked" : 
`add_cap_info(NV_ENC_CAPS_SUPPORT_SAO,                  false, true,  _T("SAO"));`

The idea here is to force the hardware detection to (always) 'False'.
That way the lib will not use SAO ?

**Comment by JibsouX** [comment]
Damn..
Tx for your reply :)
Hope the future update for the dsk will add new settings !
Cheers and tx for your work !

**Comment by rigaya** [comment]
I'll close this issue at this time. I'll add a switch for SAO if the SDK supports it in the future.

**Comment by JibsouX** [comment]
Thanks a lot for your work !
