### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#322]
Hello,

I have a video file that when converted the audio is out of sync.

Tried forcecrf, vbr. Also tested rff setting. 
And tied applying an audio delay, however all fail.

When checking the file with ffprobe it's shows
That the video starts at 0.06633
And the audio starts at 0.00000

I am not sure on how to set this as it seems the audio has a minus delay. Or I misunderstand the ffprobe feedback.

**Comment by quamt** [comment]
Update here the delay information from the file checked with ffprobe

```
codec_type=video|start_time=0.066733
codec_type=audio|start_time=0.000000
```

**Comment by rigaya** [comment]
Minus delay of 66ms is only 2 frames in 30fps which shouldn't be a big problem, might be not a cause of a large avsync error.

Unfortunately, this kind of problem is difficult to check what is going on without the input file.

**Comment by quamt** [comment]
The problem is when it's encoded it becomes more than 10 seconds delay for the audio. Which is very strange.
Would a complete ffprobe result help?

**Comment by rigaya** [comment]
I see, that's strange. "--avsync vfr" doesn't help, right?

> Would a complete ffprobe result help?

Unfortunately not...

**Comment by quamt** [comment]
Yes, correct i tested all --avsync options and none helps, one of them makes it even worse.

**Comment by Eldenissio** [comment]
I also have an issue with --avsync forcecfr/cfr/vfr

I have an original file that has everything in sync if played.
If I do a transcode, I get AV out of sync if no --avsync option is enabled, but if I try to use --avsync forcecfr/cfr/vfr and with/without --vpp-rff I get error:
 _timestamp not acquired successfully from input stream, avsync vfr, vpp-rff cannot be used.
  [0x8] ALL_INVALID
Failed to open input file_
But this has more to do with "Timestamps are unset in a packet for stream 0" (video).
I wonder if there's a way to set the timestamps?

**Comment by rigaya** [comment]
ALL_INVALID indicates that the timestamps could not be got properly from the demuxer. --avsync and --vpp-rff relies on the timestamps, so it will not work.

Most players have some methods to still play such files, but I have decoded to not go into those timestamp problems further.

**Comment by quamt** [comment]
I'm using avisynth script to open the file now and let in run via nvenc.
Audio and Video are no longer out of sync.

**Comment by ValZapod** [comment]
> That the video starts at 0.06633
> And the audio starts at 0.00000

What audio is that? If it is aac, aac does have encoder delay, some initial silence samples must be skipped. Same about some last samples. Usually 1000 sampes are to be skipped with native ffmpeg aac encoder and 2112 with fdk-aac.
