### ISSUE TITLE
Super resolution error

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#324]
Hello,

I tried upscaling with the Nvidia Super but getting the following error

```
resize: failed to resize: -23, NPP_RESIZE_FACTOR_ERROR.
Error while running filter "resize".
```

Is there any limitation?
Upscaling to 1440x1080 from 576x432
Other upscaling algorithm work

```resize(lanczos4): 576x432 -> 1440x1080```

**Comment by rigaya** [comment]
NPP_RESIZE_FACTOR_ERROR is a error coming from NVIDIA npp library.

"super" seems to only support downscaling, so it cannot be used fro upscaling.

**Comment by quamt** [comment]
Oh. I see. Thank you.
