### ISSUE TITLE
Usage of config file

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#325]
I did not see this anywhere and was curious if it is possible to use a config file for the commands that are being used.
For example:
it is now
NVEncC.exe [Options] -i <filename> -o <filename>
With an configfile it couldbe like
NVEncC.exe -c <configfile> -i <filename> -o <filename>

And in the config file are all the commands saved that should be used, for example:
```
# this is the config file
# device used
-d 0
# codec used
-c hevc

etc.....

```

Would this be possible or even doable?

**Comment by rigaya** [comment]
It's not possible now, but it might be interesting as a work item in the future.

**Comment by quamt** [comment]
OK. Thank you for having a look at it.

**Comment by rigaya** [comment]
NVEnc 5.31 will have new option [--option-file](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--option-file-string) which can read option lists from a file.

Please note that this does not support comment lines in current version.

**Comment by quamt** [comment]
tested the new option file and it works great so far. 
Thank you for implementing it.

**Comment by rigaya** [comment]
Thank you for confirming, I'll close this issue.

Also NVEnc 5.32 will now a line starting from "#" will be treated as comment line in --option-file.
