### ISSUE TITLE
VPP YADIF AUTO BUG

### ISSUE THREAD

**Issue by JibsouX** [rigaya/NVEnc#328]
Hello @rigaya !
I have test vpp yadif in auto mode and it shoot an error : Please set input interlace field order (--interlace tff/bff) for vpp-yadif.
And event if i add ttf or bff it still shoot the error !

Tx in advance !

**Comment by rigaya** [comment]
[--interlace](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--interlace-string) option is required for deinterlacing. If you want auto mode for vpp-yadif, please also add "--interlace auto".

**Comment by JibsouX** [comment]
Tx in deed my bad you can shut down this useless issue ! ^^
And Tx again !

By the way if you can add to the VPP filters some native AVS scripts like sharpen() and others it will be awesome !!

Cheers !

**Comment by rigaya** [comment]
> By the way if you can add to the VPP filters some native AVS scripts like sharpen() and others it will be awesome !!

NVEncC already has some sharpen filters but I might think of adding others.
