### ISSUE TITLE
H265 - slices

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#329]
Hello,

I tried to create slices with h265 using --slices 75
When encoding I'm nowhere able to see the slices. 
Am I missing a setting that enables the usage of slices?

`--cqp 18:20:22 --codec h265 --preset quality --output-depth 10 --profile main10 --tier high --slices 75
`

**Comment by rigaya** [comment]
I'm sorry but  I'm not able to get what you mean here, by "nowhere able to see the slices". Do you mean you have checked the raw HEVC bitstream?

As you may know, slices is a partitioning in when coding the frame. Please refer to section "4.1 Partitioning" of the following link.
https://www.vcodex.com/hevc-an-introduction-to-high-efficiency-coding/

Actually slices harm compression efficiency, so it is not recommended to use this except for special cases where the output format requires slices, like the Bluray format in H.264, which required slices 4 or more.

**Comment by quamt** [comment]
I meant, that normally all instructions are visible in the output, or better say when you run it in CLI, everything can be seen, so I wondered, where the slices info is gone too.

I will check theat link.

I guess I had a misunderstanding, as I thought it will improve quality.

Compression efficency you mean getting bigger output files?

**Comment by rigaya** [comment]
> where the slices info is gone too

Ah, OK, slices are not printed in the logs. I'll make it printed whenever slices is specified in the next release.

> Compression efficiency you mean getting bigger output files?

Yes, you shall get slightly bigger file, **or** lower quality when using slices. For example in 1080p encoding...

```
No slices: -c hevc --vbr 0 --vbr-quality 25 --max-bitrate 32500 --ssim
encoded 5203 frames, 368.77 fps, 10411.45 kbps, 215.47 MB
ssim/psnr/vmaf: SSIM YUV: 0.978343 (16.644086), 0.983422 (17.804589), 0.984462 (18.086132), All: 0.980210 (17.035445), (Frames: 5203)

With slices:  -c hevc --vbr 0 --vbr-quality 25 --max-bitrate 32500 --ssim --slices 75
encoded 5203 frames, 348.10 fps, 10619.57 kbps, 219.78 MB
ssim/psnr/vmaf: SSIM YUV: 0.976998 (16.382349), 0.981887 (17.420114), 0.982950 (17.682779), All: 0.978805 (16.737641), (Frames: 5203)
```

**Comment by quamt** [comment]
Thank you.
I'll close this as my question has been answered.
