### ISSUE TITLE
When transcoding file(s) with multiple streams (for example multilanguage subtitles) NVEnc sets all as DEFAULT

### ISSUE THREAD

**Issue by jeryll7** [rigaya/NVEnc#33]
NVEnc should copy DEFAULT attributes from source to destination, sure, this may look as triviality, but for example ffmpeg can copy DEFAULT stream attribute correctly.

This is easily reproducible, just use media file with multiple subtitle stream included, check with mediainfo for how the DEFAULT attribute is set, transcode file with NVEnc with --sub-copy option, then check result file with mediainfo - all subtitle streams will have DEFAULT attribute set.

**Comment by rigaya** [comment]
I have added code to copy attributes of streams (audio & subtitles) in [NVEnc 3.29](https://github.com/rigaya/NVEnc/releases/tag/3.29).

**Comment by jeryll7** [comment]
OK, thanks, I can confirm that NVEnc 3.29 correctly copies audio and subtitles streams default attributes, but unfortunately now VIDEO stream DEFAULT attribute (if set) is not copied (also VIDEO stream LANGUAGE attribute is not copied - is missing in result file).
Should I close this and open a new issue?

**Comment by rigaya** [comment]
OK, [NVEnc 3.30](https://github.com/rigaya/NVEnc/releases/tag/3.30) will copy attribute of video when possible (for avhw/avsw reader).

**Comment by jeryll7** [comment]
Ok, thanks, NVEnc 3.30 now copies stream(s) attributes correctly.
