### ISSUE TITLE
Dolby Vision Copy HDR info

### ISSUE THREAD

**Issue by hmartin417** [rigaya/NVEnc#330]
I know that there has been an option added to copy the HDR metadata for HDR10/HDR10+, but nothing for coping Dolby Vision. If I try to use the HDR commands, they fail every time. Please let me know what options there are. Thanks

**Comment by rigaya** [comment]
Unfortunately, Dolby Vision infos are not supported in NVEncC and cannot be copied as I'm friendly to Dolby Vision.

**Comment by ValZapod** [comment]
You can use -strict experemental to -c copy DV in mp4 to mp4. You can use dovi_tool to generate even new fake DV Metadata!
