### ISSUE TITLE
metadata of 2nd external audio overwrites metadata of the 1st

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#332]
I want to replace internal audio streams with converted ones.
If you add two external audio streams: 
`--audio-source "audio_out.ec3":copy;metadata=title="Mono DD+ 2.0 -27 dB" ^`
`--audio-source "audio_out.ac3":copy;metadata=title="DD 5.1 -27 dB"`
then the second metadata will overwrite the first.
So the two streams get the same metadata.

Same behavior with subtitles.

**Comment by rigaya** [comment]
Thank you for letting me know the issue.

The handling of the parameters when --audio-source was used multiple times was wrong, I have fixed this in  [NVEnc 5.30](https://github.com/rigaya/NVEnc/releases/tag/5.30).

**Comment by fzold** [comment]
Thank you for all your work.
