### ISSUE TITLE
VBRHQ ?

### ISSUE THREAD

**Issue by JibsouX** [rigaya/NVEnc#333]
Hello @rigaya , where is vbrhq , is it removed, and why ?
is vbrhq + -multipass 2pass-full is the same now as vbr + -multipass 2pass-full ??

Thanks in advance !

**Comment by rigaya** [comment]
--vbrhq was a option for NVENC API 9.x and was removed in the next API 10.0 (NVENC does not support that option).

> is vbrhq + -multipass 2pass-full is the same now as vbr + -multipass 2pass-full ??

It is not exactly equivalent, depending on the preset you are using. I have not looked into it further.

**Comment by Teranode** [comment]
Here's the migration table for sdk 10 + https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-preset-migration-guide/index.html

**Comment by rigaya** [comment]
Thank you for sharing the migration table.

I'll close this issue as the topic has been answered.
