### ISSUE TITLE
4K HDR String

### ISSUE THREAD

**Issue by centuryx476** [rigaya/NVEnc#334]
Hello,
I just discovered this amazing project. I just encoded a 4K movie that preserves its HDR using HEVC.
I see the options page [https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md](url)
But I want to be sure about some of the options that could effect quality.

Question on some of the commands:
Tier - Difference between main and high ?
Lookahead - How are ahead should it be looking ?
Bitrate/VBR Target - I can set a custom bitrate of lets say 45000K, what does VBR Target do ?
Ref Frames - Which value should I set ?
B Frames - Which value should I set ?
Level - Which value should I set ?
B Ref Mode - Which value should I set ?

Keep in mind this is for encoding a 4K movies that can be HDR10 or HDR10+

Thank You

**Comment by rigaya** [comment]
You can check the link below for the Tier/Level you need to set. It will depend on the resolution, framerate, ref frames and the maximum bitrate you need.
https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding#Tiers_and_levels

For other options, it depends on the generation on of the GPU and the performance you require, so there is no such thing as this is the best. The options are there to enable you test by changing them.

**Comment by centuryx476** [comment]
Hmmmm ok
