### ISSUE TITLE
After Encode Work

### ISSUE THREAD

**Issue by centuryx476** [rigaya/NVEnc#337]
Hello,
If I have to add a second audio track to the file after I encoded it using Nvenc. If I just pass the video stream normally using ffmpeg and mux in a second audio track. Would the HDR data be preserved ? Do I need to use any special commands for metadata ? Since I am just passing the video stream in theory it will be untouched. I just want to be sure.

Thank You

**Comment by rigaya** [comment]
> If I just pass the video stream normally using ffmpeg and mux in a second audio track. Would the HDR data be preserved ? 

As I'm not a developer of ffmpeg, I cannot ensure if the HDR metadata will be preserved or not.

My advice is to use MediaInfo to check the metadata in the video file.
