### ISSUE TITLE
Second Audio Track

### ISSUE THREAD

**Issue by centuryx476** [rigaya/NVEnc#338]
Hello,
Can support for a second audio track be added ?
I like to preserve the original audio and then make a second track in AAC

Thank You

**Comment by quamt** [comment]
@centuryx476
There was another discussion here with keepinh original and create a 2nd audio stream. 
`https://github.com/rigaya/NVEnc/issues/222`

**Comment by rigaya** [comment]
Thanks for the answer, I'll close this issue as the topic has been answered.
