### ISSUE TITLE
vpp-resize bug? + HLG atc-sei with repeat-headers

### ISSUE THREAD

**Issue by SiV44** [rigaya/NVEnc#339]
Hello rigaya,

In the latest version, when using `--vpp-resize` methods:
`bilinear, nearest, spline16, spline36, spline64, lanczos2, lanczos3, lanczos4, nn, npp_linear, cubic, super, lanczos`
 it always reports that the method is unknown:

>Vpp Filters    cspconv(nv12 -> yv12(16bit))
                       resize(**unknown**): 3840x2160 -> 1920x1080
                       cspconv(yv12(16bit) -> p010)

But it looks like the output files are encoded correctly as each has a different size depending on the method used.

Moving on, when you use `cubic_bspline, cubic_catmull, cubic_b05c03, smooth_edge`, the following error occurs:

>resize: failed to resize: -22, NPP_INTERPOLATION_ERROR.
Error while running filter "resize".

---

Second thing is HLG -> HLG encoding, `--repeat-headers` is always active when using `--atc-sei arib-std-b67`:

`--avhw --vbr 0 --multipass 2pass-full --codec h265 --preset p7 --profile main10 --output-depth 10 --tier high --level 5.1 --avsync cfr --input-analyze 0 --weightp --slices 1 --ref 4 --gop-len 150 --lookahead 32 --nonrefp --no-b-adapt --qp-init 20 --qp-max 23 --qp-min 30 --vbr-quality 28 --aq --aq-strength 15 --colormatrix bt2020nc --colorprim bt2020 --transfer arib-std-b67 --atc-sei arib-std-b67 --colorrange limited --pic-struct --mv-precision q-pel`

>VUI            matrix:bt2020nc,colorprim:bt2020,transfer:arib-std-b67,range:limited
Others         mv:Q-pel weightp nonrefp pic-struct **repeat-headers**

and `--atc-sei unknown`

`--avhw --vbr 0 --multipass 2pass-full --codec h265 --preset p7 --profile main10 --output-depth 10 --tier high --level 5.1 --avsync cfr --input-analyze 0 --weightp --slices 1 --ref 4 --gop-len 150 --lookahead 32 --nonrefp --no-b-adapt --qp-init 20 --qp-max 23 --qp-min 30 --vbr-quality 28 --aq --aq-strength 15 --colormatrix bt2020nc --colorprim bt2020 --transfer arib-std-b67 --atc-sei unknown --colorrange limited --pic-struct --mv-precision q-pel`

>VUI            matrix:bt2020nc,colorprim:bt2020,transfer:arib-std-b67,range:limited
Others         mv:Q-pel weightp nonrefp pic-struct

is this behavior correct?

---

Thanks in advance

**Comment by rigaya** [comment]
--vpp-resize issue shall be fixed in [NVEnc 5.32](https://github.com/rigaya/NVEnc/releases/tag/5.32), now the proper resize moethod will be shown in the log and the modes not working (which was accidentally added in the help) shall be removed from the --help.

> --repeat-headers is always active when using --atc-sei arib-std-b67

This behavior is intended and correct. It is better to have ```--repeat-headers``` enabled when using ```--atc-sei arib-std-b67```, so it is automatically enabled.

**Comment by SiV44** [comment]
>--vpp-resize issue shall be fixed in NVEnc 5.32, now the proper resize moethod will be shown in the log and the modes not working (which was accidentally added in the help) shall be removed from the --help.

It shows correctly and there are no broken modes.

>This behavior is intended and correct. It is better to have --repeat-headers enabled when using --atc-sei arib-std-b67, so it is automatically enabled.

Thank you very much for your answer, your work and your time.

Best Regards
