### ISSUE TITLE
v5.32 Does Nothing, v5.29 Works Fine

### ISSUE THREAD

**Issue by AYColumbia** [rigaya/NVEnc#340]
I use staxrip and the latest version (2.6.0) includes nvenc 5.32 which doesn't do anything with the same command line used on 5.29.  I get no errors, it just starts up and then comes back to the command line.  It does display the output file name but does nothing.

This is the output of -v for both versions.  I have a GTX1050 and running on Windows 10 Pro with latest updates.

NVEncC (x64) 5.32 (r1925) by rigaya, May 18 2021 14:30:14 (VC 1928/Win/avx2)
  [NVENC API v11.0, CUDA 10.1]
 reader: raw, y4m, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]

NVEncC (x64) 5.29 (r1810) by rigaya, Feb 14 2021 06:13:25 (VC 1928/Win/avx2)
  [NVENC API v11.0, CUDA 10.1]
 reader: raw, y4m, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]

I ran a --check-hw and the output from both versions (attached) is a bit different.  If you need more info please let me know.

Here's an example command line I use that works fine in 5.29.
`"C:\MultiMediaTools\StaxRip\Apps\Encoders\NVEnc\NVEncC64.exe"  --device 0 --avhw --codec avc --bluray --vbrhq 7512 --preset quality --vpp-pad 0,60,0,60 --qp-init 18 --qp-max 28 --qp-min 18 --gop-len 12 --lookahead 32 --ref 4 --max-bitrate 40000 --vbv-bufsize 30000 --aq --videoformat ntsc --colormatrix bt709 --colorprim bt709 --transfer bt709 -i "output\clip.mkv" -o "clip.avc"`

[check-hw.529.txt](https://github.com/rigaya/NVEnc/files/6571904/check-hw.529.txt)
[check-hw.532.txt](https://github.com/rigaya/NVEnc/files/6571905/check-hw.532.txt)

**Comment by rigaya** [comment]
I hope updating to [NVEnc 5.33](https://github.com/rigaya/NVEnc/releases/tag/5.33) will fix your problem as your output is raw AVC file.

_Fix issue when writing raw ES file or log file to current directory by relative path._

**Comment by AYColumbia** [comment]
Thank you. I'll give it a try later today or tomorrow and report back.

**Comment by AYColumbia** [comment]
I just had a few minutes to grab 5.33 and test it.  Works great!  Thank you very much for the quick turnaround on the fix. :)
