### ISSUE TITLE
look ahead

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#341]
Hello,

this is more of a question then a issue.

I noticed that there is a maximum look ahead of 32 frames.
Is that a limitation by NVIDIA NVEnc?

I am asking as I came across a tool that supposedly supports 240 and more frames in NVEnc.

**Comment by rigaya** [comment]
Lookahead depth limits is written on the NVENC SDK API, I think it was 32 in the past but seems to be updated (I didn't notice it) and the limit seems to be "31 - bframes".

https://github.com/rigaya/NVEnc/blob/master/NVEncSDK/Common/inc/nvEncodeAPI.h#L1300-L1301

**Comment by quamt** [comment]
Does that mean its possible to have now more look ahead frames?
And should improve the quality if I understand correct...

**Comment by rigaya** [comment]
Sorry, I wrote somewhat confusing.

"31 - bframes" means that the uppler limit of lookahead frames is **_31 minus bframes_**, so if you have 3 bframes, you can only have maximum 28 lookahead frames, as the limitation by NVIDIA NVENC.

Unfortunately, currently we have no chance to have something like 240 lookahead frames like x264 or x265 can do.

**Comment by quamt** [comment]
Oh. I see.
Meaning the more b frames the less lookahead is possible. 
Are that the bframes that are going to be placed into the new encoded material?
Does the option change now in NVEnc or will it remain the same?

**Comment by kusingen** [comment]
Hello. Will it be set to 31 if I use --lookahead 32 or more? Is it NV-API based limitation and was changed recently or is it HW-based affecting only some newer models? I'm currently using 32 in my scripts without errors but I did not update my graphics drivers for some time now...

**Comment by rigaya** [comment]
@quamt 
> Does the option change now in NVEnc or will it remain the same?

It will remain the same, I think nothing need to be changed here.

@kusingen 
> Is it NV-API based limitation and was changed recently or is it HW-based affecting only some newer models?

The comment in the SDK was changed on NVENC SDK 10.0 which was released in 2020 June, and I assume that only the comment was updated to match the actual behavior.

Actually, you need not to care so much about this limitation. The limitation seems to be applied internally in the NVENC, so setting more than the limitation (like --lookahead 32), will produce the same result as the actual limit. Therefore, currently you can go for "--lookahead 32" if you want to set lookahead depth to the maximum length.

**Comment by quamt** [comment]
Thank you @rigaya for all the answers.
Ill close this issue, as everything has been answered.
