### ISSUE TITLE
option-file not working

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#342]
Hello @rigaya 

I tried the option-file and it seems as it is not working.

Command: 
`for %i in (*.mp4) do "D:\rigaya\NVEncC\NVEncC64.exe" -i "%i" -option-file "E:\nvidia.txt"  -o "%~ni-1080-Nvidia.mkv"`

Option file attached.
Strange thing is it worked before.
[nvidia.txt](https://github.com/rigaya/NVEnc/files/6691495/nvidia.txt)

Any setting issue on my side?

**Comment by rigaya** [comment]
There are some errors in the option file and command line.

"-option-file "E:\nvidia.txt"" should be "--option-file "E:\nvidia.txt""
"--c avc" should be "-c avc"
"--b 4" should be "-b 4"
"--output-res 2x1080" should be "--output-res -2x1080"

**Comment by quamt** [comment]
Thank you.
Didn't realize the errors.
