### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#344]
Hello @rigaya,

I've reported this issue some time ago and closed it.
It seems I finally found the problem of my audio being out of sync.

After analyzing the source I noticed that the video and the audio have different frame rates.

Frame rates
`
Video: 23.976 (24000/1001) FPS

Audio: 31.250 FPS (1536 SPF)
`

Is there anyway to compensate this or set it correctly?

Audio has a delay of
Delay: -83ms

**Comment by rigaya** [comment]
I've check some video files which don't have audio delay, but those files also had difference in frame rate between audio and video. Therefore, it seems like the different frame rates is not the cause on audio getting out of sync.

Many audio codecs encodes audio in blocks, containing around thousand samples, like 1024samples per block or 1536samples per block.

The audio "frame rate" seems to be showing this, so 31.250 FPS (1536 SPF) means 1536 samples per block, and as audio has 48000 samples/sec in 48kHz sample rate, it is shown as 48000/1536=31.250FPS.

**Comment by YinnVI** [comment]
same me too, not all but some of video out of sync
source 23:50
output 23:49

**Comment by YinnVI** [comment]
same me too, not all but some of video out of sync
