### ISSUE TITLE
Key-on-chapter does not work when encode with audio

### ISSUE THREAD

**Issue by fireattack** [rigaya/NVEnc#346]
When using only `-chapter-copy --key-on-chapter` to transcode a video, there would be a keyframe at the exact timestamp at each chapter mark.

However, when I use audio encoding together, it does not work.
```
nvencc64 -i raw.mkv --chapter-copy --key-on-chapter -o out_noaudio.mkv
nvencc64 -i raw.mkv --chapter-copy --key-on-chapter --audio-codec aac --audio-bitrate 192 -o out.mkv
```
The chapters in both output files are (reported by `mediainfo`):

```
Menu
00:00:00.000                             : :Chapter 01
00:04:09.082                             : :Chapter 02
00:08:23.836                             : :Chapter 03
```

The keyframes around 4m9s for out_noaudio.mkv are:
```
240.240000 or 0:04:00.240
249.082000 or 0:04:09.082
259.092000 or 0:04:19.091
269.102000 or 0:04:29.102
```
(Correct)

The keyframes around 4m9s for out.mkv are:
```
240.261000 or 0:04:00.261
249.103000 or 0:04:09.103
259.113000 or 0:04:19.113
269.123000 or 0:04:29.123
```

(Wrong).

**Comment by rigaya** [comment]
Actually, this is working fine.

You can see that the difference is always 21-22ms.

This is the delay added by mkv muxer, which seems to add delay to the video when audio encoding is enabled. This is to cancel audio delay introduced by audio encoding itself. The delay for ffmpeg native aac encoder is 1024 samples, so in 48kHz sample rate, this equals to 1024/48000 = 21ms.

**Comment by fireattack** [comment]
THis makes sense. 

But this makes seeking to chapter mark very slow because it now has to decode the previous whole GOP and seek to the timestamp.

Is there anyway to make the two match, either by adjusting timestamp of chapter marks by the same delay, or make audio ahead?

For example, make the timestamp of chapters to always match with closest keyframe *after muxing*.

**Comment by rigaya** [comment]
> For example, make the timestamp of chapters to always match the closest keyframe after muxing.

Actually, this is difficult as adding the delay is done internally in the muxer side after nvencc passes the timestamp to the muxer.

Have you tried writing in mp4 format? The audio delay is handled differently in mp4 container and might not have this kind of issue.

**Comment by fireattack** [comment]
MP4 seems to work fine.

Yeah I agree it probably is hard to fix it on our end. 

I'm closing the ticket I guess, thanks for your time to investigate this.
