### ISSUE TITLE
Setting general_progressive_source_flag

### ISSUE THREAD

**Issue by psisis** [rigaya/NVEnc#348]
One issue that prevents encodes from being UHD compliant is the general_progressive_source_flag which should be set to 1. The nvencc64 option `--interlace progressive` has no effect on this flag. x265 does set this flag though with `--no-interlace` as a comparison.

OK, I found the flag in both VPS ans SPS. After I set it another issue was 'general_frame_only_constraint_flag' though it was within the same hex. But then there is 'fixed_pic_rate_general_flag' in HRD parameters need to be 1. I can't even find this one, so I assume there are a lot of issues right now making the HEVC encoder compliant?

I saw this post on the Intel forums about the requirements https://community.intel.com/t5/Media-Intel-oneAPI-Video/Add-SPS-and-VPS-Information-UltraHD-compatible/td-p/1139785

**Comment by rigaya** [comment]
There is a flag in NVENC SDK called [frameFieldMode](https://github.com/rigaya/NVEnc/blob/master/NVEncSDK/Common/inc/nvEncodeAPI.h#L1623) to set whether the video is progressive or interlace. I have tested this option, but had no effect to "general_progressive_source_flag" output in VPS, so it is not possible to change this flag to 1.

There are few options provided to control the VPS and the SPS in NVENC SDK, so I think it is difficult to make HEVC encoder UHD compliant.

**Comment by rigaya** [comment]
I'll close the issue as the topic has been answered.
