### ISSUE TITLE
NVEnc gives an error when encoding any UHD-BD/Remux using --avhw reader

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#35]
Error "[hevc @ 00000000xxxxxxxx] Invalid NAL unit 19, skipping" appears very often, if i use -avhw (Native, CUDA) when encoding UHD HDR BD/Remux. The encoding process reaches the end, a completely normal h265 file is created, but its size is always much smaller, than when encoding with the same parameters using Avisynth/Vapoursynth. This error appears from at least version 3.23.
(if using software reader (Avisynth/VapourSyth - this error never occurs!)

------------------------------ log -------------------------------

C:\Temp\StaxRip\Apps\NVEnc\NVEncC64.exe --avhw cuda --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --bframes 0 --ref 5 --gop-len 12 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto --output-buf 32 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --mv-precision q-pel --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) --max-cll 1529,380 --crop 0,278,0,278 -i "D:\PASSENGERS_(2016)_UHD_HDR_RMX-BLUEBIRD.mkv" -o "D:\PASSENGERS_(2016)_UHD_HDR_RMX-BLUEBIRD_new.h265"

NVEncC (x64) 3.29 (r714) by rigaya, Feb 19 2018 23:18:08 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (16299)
CPU            Intel Core i7-3930K @ 3.20GHz [TB: 4.07GHz] (6C/12T)
GPU            #0: GeForce GTX 1080 (20 EU) @ 1835 MHz (390.77)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 41 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 24000/1001 fps
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main10 @ Level auto
3840x1604p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        160000 kbps (Max: 160000 kbps)
Target Quality 21.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames
GOP length     12 frames
B frames       0 frames
Ref frames     5 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:Q-pel
encoded 167137 frames, 54.54 fps, 29473.16 kbps, 24492.45 MB
encode time 0:51:04, CPU: 1.2, GPU: 17.1, VE: 36.8, GPUClock: 1997MHz, VEClock: 1792MHz
frame type IDR  13929
frame type I    13929,  total size   3429.89 MB
frame type P   153208,  total size  21062.56 MB
[hevc @ 0000000011a2f600] Invalid NAL unit 19, skipping            <-- ERROR

**Comment by drSHLEFF** [comment]
NVEnc 3.30: If encode h265 video track extracted from remux (PASSENGERS_(2016)UHD_HDR_RMX-BLUEBIRD.mkv) the error changed, but still occured.

C:\Temp\StaxRip\Apps\NVEnc\NVEncC64.exe --avhw cuda --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --bframes 0 --ref 5 --gop-len 12 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto --output-buf 32 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --mv-precision q-pel --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) --max-cll 1529,380 --crop 0,278,0,278 -i "D:\T1_Video - English.h265" -o "D:\T1_Video - English_new.h265"

NVEncC (x64) 3.30 (r717) by rigaya, Feb 20 2018 22:25:35 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (16299)
CPU            Intel Core i7-3930K @ 3.20GHz [TB: 4.07GHz] (6C/12T)
GPU            #0: GeForce GTX 1080 (20 EU) @ 1835 MHz (390.77)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 41 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 24000/1001 fps
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main10 @ Level auto
3840x1604p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        160000 kbps (Max: 160000 kbps)
Target Quality 21.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames
GOP length     12 frames
B frames       0 frames
Ref frames     5 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:Q-pel
encoded 167137 frames, 68.92 fps, 29473.16 kbps, 24492.45 MB
encode time 0:40:24, CPU: 1.5, GPU: 7.0, VE: 46.6, GPUClock: 2012MHz, VEClock: 1800MHz
frame type IDR  13929
frame type I    13929,  total size   3429.89 MB
frame type P   153208,  total size  21062.56 MB
[NULL @ 00000000126e05c0] missing picture in access unit                   <-- ERROR CHANGED

**Comment by rigaya** [comment]
[hevc @ 00000000xxxxxxxx] or [NULL @ 00000000126e05c0] is error message from the libavformat parser, and not message from NVEnc, so I can do nothing for it.
If encode runs successfully anyway, can't we just ignore it?

**Comment by drSHLEFF** [comment]
As you say. We can certainly ignore it. That's just why the size of the final video varies so much between avisynth and avhw? When coding HEVC, the size of the destination file when using "--avhw cuda" is always much less than using Avisynth. (If encode h264, then the files are completely identical: avisynth = avhw, byte to byte)

**Comment by rigaya** [comment]
I have tested with avs, avsw & avhw readers. As you have told me, there was some change in error messages, but the output was almost the same.

There is slight change, but it is accepted, as this source video is a extracted video.


**source**
PASSENGERS_UHD_HDR_RMX_error.mkv


**avs**
```
FFVideoSource("PASSENGERS_UHD_HDR_RMX_error.mkv")
```


**avs reader**
```
--avs -i "PASSENGERS_UHD_HDR_RMX_error.mkv.avs" -o F:\temp\test.mp4 --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --bframes 0 --ref 5 --gop-len 12 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto
NVEncC (x64) 3.31 (r728) by rigaya, Mar  6 2018 09:58:05 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (16299)
CPU            Intel Core i9-7980XE @ 2.60GHz (18C/36T)
GPU            #0: GeForce GTX 1060 6GB (10 EU) @ 1708 MHz (390.77)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 41 frames
Input Info     Avisynth+ 2.60(yv12(10bit))->p010 [AVX2], 3840x2160, 24000/1001 fps
Vpp Filters    copyHtoD
Output Info    H.265/HEVC main10 @ Level auto
               3840x2160p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc => mp4
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        160000 kbps (Max: 160000 kbps)
Target Quality 21.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames
GOP length     12 frames
B frames       0 frames
Ref frames     5 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto


encoded 1922 frames, 51.36 fps, 36319.45 kbps, 347.08 MB
encode time 0:00:37, CPU: 27.3%, GPU: 18.4%, VE: 75.2%, GPUClock: 1875MHz, VEClock: 1686MHz
frame type IDR  161
frame type I    161,  avgQP  16.66,  total size   44.08 MB
frame type P   1761,  avgQP  16.67,  total size  303.00 MB
```


**avsw reader**
```
--avsw -i "PASSENGERS_UHD_HDR_RMX_error.mkv" -o F:\temp\test.mp4 --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --bframes 0 --ref 5 --gop-len 12 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto
[hevc @ 000001d114e380c0] Invalid NAL unit 19, skipping.
[hevc @ 000001d12601f640] Invalid NAL unit 19, skipping.
NVEncC (x64) 3.31 (r728) by rigaya, Mar  6 2018 09:58:05 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (16299)
CPU            Intel Core i9-7980XE @ 2.60GHz (18C/36T)
GPU            #0: GeForce GTX 1060 6GB (10 EU) @ 1708 MHz (390.77)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 41 frames
Input Info     avsw: hevc(yv12(10bit))->p010 [AVX2], 3840x2160, 24000/1001 fps
Vpp Filters    copyHtoD
Output Info    H.265/HEVC main10 @ Level auto
               3840x2160p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc => mp4
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        160000 kbps (Max: 160000 kbps)
Target Quality 21.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames
GOP length     12 frames
B frames       0 frames
Ref frames     5 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto
[hevc @ 000001d127b06240] First slice in a frame missing.
[hevc @ 000001d127b06240] First slice in a frame missing.
[hevc @ 000001d127b06240] First slice in a frame missing.
[hevc @ 000001d127b06240] First slice in a frame missing.
[hevc @ 000001d127b06240] First slice in a frame missing.
[hevc @ 000001d127b06240] First slice in a frame missing.
[hevc @ 000001d127b06240] First slice in a frame missing.
[hevc @ 000001d1292a4020] First slice in a frame missing.
[hevc @ 000001d1292a4020] First slice in a frame missing.
[hevc @ 000001d1292a4020] First slice in a frame missing.
[hevc @ 000001d1292a4020] First slice in a frame missing.
[hevc @ 000001d1292a4020] First slice in a frame missing.
[hevc @ 000001d1292a4020] First slice in a frame missing.
[hevc @ 000001d1292a4020] First slice in a frame missing.


encoded 1920 frames, 67.12 fps, 36288.61 kbps, 346.42 MB
encode time 0:00:28, CPU: 19.5%, GPU: 23.0%, VE: 92.2%, GPUClock: 1864MHz, VEClock: 1676MHz
frame type IDR  160
frame type I    160,  avgQP  16.66,  total size   40.57 MB
frame type P   1760,  avgQP  16.66,  total size  305.85 MB
```


**avhw reader**
```
--avhw -i "PASSENGERS_UHD_HDR_RMX_error.mkv" -o F:\temp\test.mp4 --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --bframes 0 --ref 5 --gop-len 12 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto
[hevc @ 000001d5128780c0] Invalid NAL unit 19, skipping.
NVEncC (x64) 3.31 (r728) by rigaya, Mar  6 2018 09:58:05 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (16299)
CPU            Intel Core i9-7980XE @ 2.60GHz (18C/36T)
GPU            #0: GeForce GTX 1060 6GB (10 EU) @ 1708 MHz (390.77)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 41 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 24000/1001 fps
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main10 @ Level auto
               3840x2160p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc => mp4
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        160000 kbps (Max: 160000 kbps)
Target Quality 21.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames
GOP length     12 frames
B frames       0 frames
Ref frames     5 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:auto


encoded 1921 frames, 67.39 fps, 36286.48 kbps, 346.58 MB
encode time 0:00:28, CPU: 0.2%, GPU: 14.1%, VE: 97.1%, GPUClock: 1870MHz, VEClock: 1681MHz
frame type IDR  161
frame type I    161,  avgQP  16.65,  total size   40.79 MB
frame type P   1760,  avgQP  16.66,  total size  305.80 MB
```

**Comment by drSHLEFF** [comment]
347.08 MB = 346.42 MB = 346.58 MB - almost the same)
Rigaya, the difference in the 1 min 20 sec fragment is insignificant (but even it, raises questions), but on the whole two-hours film, the difference in the final dimensions reaches 10-15% (~2Gb). This remux: http://bluebird-hd.org/details.php?id=7593 - try by youself.
**Moreover, when using H.264, whatever the reader (avhw cuda, avisynth, raw, y4m),  is using, the size and parameters of the final files, and even its checksums(!) - are the same byte-to-byte.**




P.S: "i9-7980XE" - black envy!)

**Comment by rigaya** [comment]
I can't reproduce getting more than 10% difference, as I don't have so long sample movie.

Does this occur when you use --cqp instead of --vbrhq?

**Comment by drSHLEFF** [comment]
--vbrhq

**Comment by pwacooijmans** [comment]
Mastering display color primaries: R: x=0.680000 y=0.320000, G: x=0.265000 y=0.690000, B: x=0.150000 y=0.060000, White point: x=0.312700 y=0.329000
Mastering display luminance: min: 0.0050 cd/m2, max: 4000.0000 cd/m2
Maximum Content Light Level: 1529 cd/m2
Maximum Frame-Average Light Level: 380 cd/m2

Please check this to be 100% sure the values are correct

**Comment by drSHLEFF** [comment]
In version 4.18 the problem is solved. The topic can be closed. **Thank you)**

**The interesting point is:** When using **avhw** reader with h265 UHD source, the size of the resulting file is always 10-15% less than when using **avisynth** as a reader.
If the source video uses the h264 codec, there is no difference in the size of the target file: avhw = avisynth.
