### ISSUE TITLE
having issue with HDR conversion

### ISSUE THREAD

**Issue by alenknight** [rigaya/NVEnc#351]
trying to get a basic 4k hdr file to convert to 1080p HDR hevc.  i'm not sure what i'm missing... i can convert to SDR fine... but i'm having trouble retaining the HDR.... i'm sure i'm mixing up the parameters, but i'm a bit lost where.... 

NVEncC64.exe -i E:\trimmed_test.mkv --output-res 1920x-2 --codec hevc --avhw --vpp-colorspace range=full:full -pix_fmt yuv420p10  --tier main --profile main10 --input-csp p010 --output-depth 10 --videoformat auto --colorprim auto --colormatrix auto --transfer auto --chromaloc auto --colorrange auto --sub-copy --audio-copy -o E:\output.mkv

**Comment by rigaya** [comment]
Looks like there are some options which NVEncC does not support...
```-pix_fmt yuv420p10```
```--input-csp p010```
are not supported and shall be removed.

Also "auto" in ```--videoformat``` is not supported, needs to select the [actual value](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--videoformat-string).

I also think ```--vpp-colorspace range=full:full``` is not required and can be removed.

If you want to preserve HDR, you will additionally need to specify [--master-display](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--master-display-string-or-copy-hevc-only), [--max-cll](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--max-cll-intint-or-copy-hevc-only), and if the input is HLG [--atc-sei](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--atc-sei-string-or-int-hevc-only) will also be required.

**Comment by alenknight** [comment]
ahh that's why! thanks!  i was mixing up my ffmpeg params with nvenc.... thanks for the clarification.
took those out and it worked like a charm.  
thanks!  
one question i couldn't quite understand - what's --master-display do? (i got the others) - but that one confuses me a bit.

**Comment by ValZapod** [comment]
> --input-csp p010



> --master-display

This is MDCV SEI. Mastering display metadata, THE only metadata that is mandatory for HDR10.
