### ISSUE TITLE
Colorspace conversion not working despite library being installed

### ISSUE THREAD

**Issue by norbusan** [rigaya/NVEnc#352]
When trying to do HDR2SDR via `--vpp-colorspace=mobius` I get 
```
colorspace: Failed to get ColorspaceFunc.h.
colorspace_conv: failed to build program source.
colorspace_conv: Source not found: 
colorspace: failed to setup custom filter.
```
That sounds somehow like I need to compile some more programs?

According to the README for `-vpp-colorspace` one needs `libnvrtc.so` which is available in `/usr/lib/x86_64-linux-gnu/libnvrtc.so`

Am I missing something more?

Thanks

**Comment by rigaya** [comment]
Thank you for reporting the issue, the problem was that "ColorspaceFunc.h" was not included in the binary in the Linux version.

I've made a commit to fix this, the issue shall be fixed by pulling the latest master branch. (e0d4517 and 40d2ea1 is the fix)

**Comment by norbusan** [comment]
Thanks a lot for the fix, I can confirm that with the latest state of master all works as expected (as far as I see now!).

(Sorry for the late feedback, I was out in the mountains)
