### ISSUE TITLE
no missing fonts error/warn for --vpp-subburn

### ISSUE THREAD

**Issue by somerendoguy** [rigaya/NVEnc#353]
When encoding with --vpp-subburn and if font is missing from mkv system fonts folder/attachments/custom fonts folder NVEnc silently replace font. Can you add warning about replacing fonts to system default like ffmpeg while using --vpp-subburn?

**Comment by rigaya** [comment]
Previously the log from libass were not shown by default (required --log-level debug).

Now [NVEnc 5.35](https://github.com/rigaya/NVEnc/releases/tag/5.35) shall show up the log from libass by default, including the font replacement warning you have mentioned.
