### ISSUE TITLE
5.35 64 bit version

### ISSUE THREAD

**Issue by alenknight** [rigaya/NVEnc#354]
for the latest updated - https://github.com/rigaya/NVEnc/releases/tag/5.35 - is there a 64 bit version? (i only see the 32 bit one out there)

**Comment by rigaya** [comment]
I've made the old tag of 5.35 by mistake, I have created the new [NVEnc 5.35](https://github.com/rigaya/NVEnc/releases/tag/5.35) release now, with the x64 bit version.

**Comment by alenknight** [comment]
awesome thanks!
