### ISSUE TITLE
Compilation error: v 5.35 + gcc 9.3.0 + cuda 11.4

### ISSUE THREAD

**Issue by babiulep** [rigaya/NVEnc#355]
Hello, with NVEnc 5.35 and gcc 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) I'm getting the following error when trying to compile NVEnc, I just upgraded to cuda 11.4 (11.3 was working fine)

NVEncCore/NVEncFilterNnedi.cu(90): error: identifier "__HALF2_TO_UI" is undefined

**Comment by rigaya** [comment]
Thank you for letting me know the error with the latest cuda.

I've made a workaround for this in e4b70ae, shall this fix the issue?

**Comment by babiulep** [comment]
Thanx for the fast reply!
It looks like it worked, when not using lto...

NVEnc (x64) 5.35 (r1991) by rigaya, Jul 25 2021 13:02:51 (gcc 9.3.0/Linux)
[NVENC API v11.0, CUDA 11.4]
reader: raw, y4m, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]

When using lto with gcc 9.3.0 I get several assembler messages: Error: symbol `fatbinData' is already defined

But without lto it works fine! I also tested the binary after compilation...
[nvenc.txt](https://github.com/rigaya/NVEnc/files/6873776/nvenc.txt)

**Comment by rigaya** [comment]
Nice to hear it works without lto.

lto seems to be difficult when compiling cuda sources (fatbinData seems to be related with cuda). Please compile without lto.
