### ISSUE TITLE
prores 422 not supported?

### ISSUE THREAD

**Issue by alenknight** [rigaya/NVEnc#356]
getting an error stating that ProRes 422 not supported in NVenc.... is that correct?
i' m using an .mov file container 
and output error 

`avcuvid: codec prores(yuv422p10le) unable to decode by cuvid.
failed to initialize file reader(s).
Failed to open input file.`

`C:\NVEncC\NVEncC64.exe -i E:\ConversionSource\Sloan_skydio2.mov --avhw --codec hevc --profile main --preset p7 --transfer auto --cqp 21 --output-depth 10 --audio-copy -o E:\TempMedia\Sloan_SkyDio2_07242021.mkv`

**Comment by rigaya** [comment]
ProRes 422 is not supported by hardware decoder, so you shall need to remove "--avhw". The software decoder shall be automatically selected which should work fine.

**Comment by alenknight** [comment]
awesome thanks.  that's unfortunate.  but makes sense given apple's history with nvidia.  thanks again!

**Comment by ValZapod** [comment]
> apple's history with nvidia

Prores is very simple and old, i.e. does not need HW decoder...
