### ISSUE TITLE
NVEnc crashing immediately if file name contains % character

### ISSUE THREAD

**Issue by jeryll7** [rigaya/NVEnc#36]
I noticed this while doing direct re-encode from various URLs. If URL does not contains + character, NVEnc has no problem re-encode media directly from URL to local HDD.

If URL contains + character in file name (which is for whatever reason in win 8.1 interpreted as %2B while pasting URL into NVEnc command line) NVEnc crashes immediately.

NVEnc also crash if you try to re-encode local media with simple file name %.mkv, so this is extra easy to reproduce.

**Comment by rigaya** [comment]
Thanks for reporting, now fixed with NVEnc 3.31.

**Comment by jeryll7** [comment]
Hi, thanks for the new version, after thorough testing, NVEnc 3.31 can successfully re-encode files with % character in file name, but there is also **--log** option, which is unfortunately crashing NVEnc 3.31 too - if log file name contains % character...

**Comment by rigaya** [comment]
Thanks, now fixed with [NVEnc 3.32](https://github.com/rigaya/NVEnc/releases/tag/3.32).

**Comment by jeryll7** [comment]
Thank you, tested the --log option, no longer crashing...
