### ISSUE TITLE
--level 5.1 issue in encode 4K HDR video

### ISSUE THREAD

**Issue by madey83** [rigaya/NVEnc#360]
hi,

when i try encode video with ref 16 i got error:

nvenc : Failed to Initialize the encoder
nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

Max ref value in which encode works is 7.

Full command
NVEncC64.exe" --avsdll "E:\apps\StaxRip-v2.8.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --cqp 18:21:23 --codec h265 --preset P7 --output-depth 10 --profile main10 --tier high --level 5.1 --aq --aq-strength 2 --bref-mode middle --ref 16 --gop-len 250 --lookahead 32 --strict-gop --nonrefp --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,0)" --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --chromaloc 1 --aud --repeat-headers --output-buf 128 --mv-precision q-pel --cabac -i "E:\video.avs" -o "E:\video_out.h265"

**Comment by madey83** [comment]
due to poblem with set --level 5.1. when it is set to unrestricted --ref 16 works

**Comment by madey83** [comment]
i re-open it due to fact that this should not be the problem to set level 5.1 beacuse lots of 4K HDR video has this level.
When i use unrestricted level video after encode has level L6.

**Comment by rigaya** [comment]
I think on 4K encoding, --ref 16 requires --level 6.

Please refer to MaxDpbSize in the table below.
https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding#Tiers_and_levels

Level 5.1 → 3,840×2,160@64 (**6**) 
Level 6    → 3,840×2,160@128 (**16**)

**Comment by madey83** [comment]
hi,

thank you for the answer. You were right. when i set Level 5 with ref 6 encoder do not crashed. 
Issue is solved.
