### ISSUE TITLE
--vpp-colorspace incorrect output colorimetry for bt2020nc SDR -> bt709

### ISSUE THREAD

**Issue by nomakewan** [rigaya/NVEnc#361]
I have a source file that is from a 4K UHD SDR bluray. The source material is limited color range, BT.2020 color primaries, BT.2020 (10-bit) transfer, BT.2020 non-constant matrix and SDR. Regardless of whether I use an AVIsynth script as input and manually specify the colorimetry or use AVHW input and use auto, attempting to use NVEncC64 to do the matrix changes results in poor output. If I use the HDRTools AVIsynth plugin with [ConvertYUVtoXYZ(Color=1),ConvertXYZtoYUV(pColor=1),ConvertBits(8),ConvertToYV12()] the result is correct, but as this plugin is entirely in software, it's a massive bottleneck (30 FPS encode on a 23.976 FPS source, as opposed to the ~400 FPS I usually get with my GTX1070). I would much rather let NVEncC64 handle the color matrix if possible.

Here is a screenshot of what the output looks like if I use HDRTools in AVIsynth:
![hdrtoolsresult](https://user-images.githubusercontent.com/11485516/132143486-4c42ed37-9e3f-4654-8afe-df0c0a7ea1ca.png)

As to the NVencC64 settings I've tried, here are the two:

--vpp-colorspace matrix=bt2020nc:bt709,colorprim=bt2020:bt709,transfer=bt2020-10:bt709
Output is way too bright, blacks look green, just looks horrible all around.
![fullresult](https://user-images.githubusercontent.com/11485516/132143509-204e1654-7ebe-458e-939f-ec36eee91bf2.png)

--vpp-colorspace matrix=bt2020nc:bt709
Output colors are dull and slightly too dark, though they are slightly richer colors than displaying the raw BT.2020 content on my ancient montior with no processing.
![matrixresult](https://user-images.githubusercontent.com/11485516/132143512-cc46cf30-867f-4d8a-906d-28afa5516ae4.png)

It doesn't matter if I use AVIsynth input or if I use AVHW and replace all the bt2020 with 'auto', the end result is the same.

Any assistance is greatly appreciated, the speed boost from using NVencC is amazing.

**Comment by rigaya** [comment]
I'm afraid there is no function in --vpp-colorspace which is completely equivalent to HDRTools, as --vpp-colorspace does not support XYZ colorspace.

Have you tried ```--vpp-colorspace matrix=bt2020nc:bt709,colorprim=bt2020:bt709,transfer=bt709:bt709```?

I think this might work for bt2020nc SDR to bt709.

**Comment by nomakewan** [comment]
Wow!! Yes, just changing the transfer to bt709:bt709 seems to have fixed the issue! The colors aren't exactly the same as the HDRTools result, but they're so close and the gamma is correct as well, so to tell which was actually most correct I'd have to test with an HDR-capable TV or monitor that I don't yet have. Either way, these results are acceptable considering the massive encode speed increase. I'll post a screenshot here for reference:

![newoutput](https://user-images.githubusercontent.com/11485516/132237144-8427f430-6993-4802-ad31-23ce752873f0.png)

Thank you for the tip! Great work!

**Comment by ValZapod** [comment]
> BT.2020 (10-bit) transfer

This transfer is ABSOLUTELY 100% the same as in BT.709. BT.2020 (12 bit) uses higher precision, but that does not matter with ffmpeg, it always uses highest precision anyway.

> exactly the same as the HDRTools result,

They should be. It is a bug in HDRtools then, since XYZ handling is complicated.

> HDR-capable TV

This is not HDR /facepalm. This is all SDR. HDR is PQ or HLG transfer, LOL.

**Comment by ValZapod** [comment]
>since I have that 1080p bluray handy, I compared a scene with deep reds that was present in both films. 

Can you give mediano here??

**Comment by nomakewan** [comment]
> Can you give mediano here??
Sure. I did confuse bluray for digital release, however. I have the digital release of the sequel film, not the bluray. But here is the mediainfo for that:

`Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 2 h 35 min
Bit rate mode                            : Constant
Bit rate                                 : 4 660 kb/s
Nominal bit rate                         : 10 000 kb/s
Width                                    : 1 920 pixels
Height                                   : 816 pixels
Display aspect ratio                     : 2.35:1
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.124
Stream size                              : 5.07 GiB (88%)
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709`

As for your comments about HDR and all that, my monitor is an ancient model from 2005 that is only TN film with a 6-bit panel. I understand fully that bt.2020 is not HDR, my point is just that if I had an HDR TV or monitor, I would be able to display the native images properly. But I don't, so my media players all display the native film "desaturated."

**Comment by ValZapod** [comment]
> I would be able to display the native images properly

Actually, you will still need a TV (LG C9, CX, C1) that supports BT.1886 which is gamma 2.4, not 2.2 or 1.961. That is how BT.709 is supposed to be watched. 

> Matrix coefficients : BT.709

Where did you get bt2020nc matrix then??

**Comment by nomakewan** [comment]
> Where did you get bt2020nc matrix then??

Perhaps you did not understand what I was saying earlier. The mediainfo you requested is for the _sequel film_, the start of which contains a flashback to several scenes in the film that has the issue being discussed here. The _sequel film_ is BT.709 and 1080p. When comparing the same scene as depicted in the _sequel film_ to that scene in the film discussed in this issue, the output from NVEnc with the settings rigaya suggested match the reds perfectly. That was how I confirmed that his settings are the correct ones to use to convert the bt2020nc to bt709.
