### ISSUE TITLE
General question regarding VBR

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#362]
Hello, 

I got a general question regarding VBR, and I am not sure if I misunderstood something or something is going wrong.

I am using the below setting to encode the video

`--avhw -i "test.mp4" --codec hevc -u quality  --output-depth 10 --vbr  500 --max-bitrate 3500 --multipass 2pass-full --qp-min 20 --qp-max 28 --lookahead 32 --bframes 5 --ref 8 --bref-mode each --mv-precision Q-pel --aq --aq-temporal --aq-strength 0 --audio-codec aac --audio-bitrate 128 --audio-stream :stereo -o "test.mkv"`

I was under the impression that the bitrate should fluctuate between 500 to 3500, or did I misunderstand this?

I am using qp-min and qp-max to achieve the best possible bitrate if I understood their usage correctly.

Is there somewhere a mistake I made in my thinking about how this works?

```
NVEncC (x64) 5.37 (r2015) by rigaya, Aug 10 2021 16:20:04 (VC 1929/Win)
OS Version     Windows 10 x64 (19043) [UTF-8]
CPU            Intel Core i9-9900K @ 3.60GHz [TB: 4.71GHz] (8C/16T)
GPU            #0: NVIDIA GeForce RTX 2060 (1920 cores, 1680 MHz)[PCIe3x16][471.96]
NVENC / CUDA   NVENC API 11.1, CUDA 11.4, schedule mode: auto
```

**Comment by rigaya** [comment]
I think it's almost correct, but the bitrate should go between **0** - 3500 kbps, and the average should be around 500 kbps.

Here is the bitrate distribution in 1.2sec notch at 720p encoding with ```--codec hevc -u quality --output-depth 10 --vbr 500 --max-bitrate 3500 --multipass 2pass-full```, and the final avg bitrate is 502 kbps.

![image](https://user-images.githubusercontent.com/815947/132922855-60d400bc-9896-4d60-9e70-fa995efcf354.png)

With qp min/max, as the qp range is limited, there might be a case that the bitrate cannot go to the specified value. For example, adding ```--qp-min 20 --qp-max 28``` to the same input file, you'll get bitrate distribution like below. The avg bitrate went up to 1410 kbps.

![image](https://user-images.githubusercontent.com/815947/132923019-cc052696-faab-41a6-89aa-7a05fe20e64c.png)

Please note that the bitrate shown on the log during encoding is equivalent to "kbps(avg)" in the graph.

**Comment by quamt** [comment]
@rigaya 

Ok, understand. 
Thank you.
BTW. Which program did you use to generate the graphs?

**Comment by rigaya** [comment]
The data for the graph is generated by [CheckBitrate](https://github.com/rigaya/CheckBitrate). The data is written in csv, and made it to graphs by excel.

**Comment by quamt** [comment]
Ok. Thank you very much.
I will close the ticket now.
