### ISSUE TITLE
Opus Multichannel

### ISSUE THREAD

**Issue by agressiv** [rigaya/NVEnc#363]
I know opus doesn't support 5.1(side), but I was hoping it would remap to regular 5.1.  I can't seem to force it regardless.

`avwriter: hevc, #1:flac/5.1 -> opus/mono/192kbps => matroska`

Someone else raised the issue as well a couple of years ago but closed it the next day. 

Attempting `--audio-codec opus`, and tried `--audio-stream :5.1` to force it to 5.1:

`[opus @ 000002157f8615c0] Specified channel layout '5.1' is not supported`

I can force --audio-stream :stereo but looking to preserve multichannel.  Thanks!

**Comment by rigaya** [comment]
Would you have a try with ```--audio-codec libopus``` instead of ```--audio-codec opus```?

```libopus``` uses [external library](https://opus-codec.org/downloads/) which supports more features.

**Comment by agressiv** [comment]
Ahh yes, much better!  Thanks!
