### ISSUE TITLE
DTS-HDMAやTRUE-HDをコアへと削る機能

### ISSUE THREAD

**Issue by waokitsunezaru** [rigaya/NVEnc#364]
こんにちは。
いつも有り難く使わせてもらっています。

表題の件ですが、DTS-HDMAやTRUE-HDをコピーする際、コアへ削る機能を実装して頂けないでしょうか。
ffmpegだと、下記コマンドのように実装されています。
　_ffmpeg -i DTS-HD_MA.dts -bsf:a dca_core -c:a copy TS-Core.dts_

同様の機能としては、MKVToolNixの「コアへと削る」や、tsMuxerRの「Downconvert TRUE-HD to AC3」等があります。

現状ではコアを削った一時ファイルを別途用意する必要があるので、NVEncCに実装して頂ければとても助かります。

**Comment by rigaya** [comment]
コアへ削る機能についてですが、実はffmpegのbsfで指定可能なbitstream filterを適用可能な ```--audio-bsf```という隠し(?)オプションがあります。(実験用に作ったものですが…)

```--audio-copy --audio-bsf dca_core```

で所望の動作とならないか、一度お試しいただけますでしょうか。

**Comment by waokitsunezaru** [comment]
返信ありがとうございます。
早速試してみたところ、上手く動作しました。

TrueHDの場合でも動作するのかなと思い、
m2tsに格納されているTrueHD音声トラックに対して
同じ要領で`truehd_core`を指定してみたところ、こちらは上手く行きませんでした。
ffmpegの`-bsf:a dca_core -c:a copy`も動作しなかったので、ffprobeで調べてみると、
どうも仮想的？にTrueHDトラックとは別に、AC3トラックが存在するようです。
(このAC3トラックはMediaInfoやtsMuxerRでは表示されません)

_Input #0, mpegts, from 'input.m2ts':
  Duration: 00:00:09.96, start: 4200.000000, bitrate: 36888 kb/s
  Program 1
  Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p(top first), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 59.94 tbr, 90k tbn
  Stream #0:1[0x1100]: Audio: truehd (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), s32 (24 bit)
  Stream #0:2[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 640 kb/s_

ffmpegではこの仮想AC3トラックをコピーすることで、コアに削ることが可能なようです。
NVEncCでも仮想AC3トラックが存在するようなので、下記コマンドで削ることができました。

`NVEncC.exe --avhw -i input.m2ts --audio-copy 2 -o output.mkv`

以上、お目汚し失礼しました。

**Comment by rigaya** [comment]
確認ありがとうございました。DTS-HDMAについて無事動作したとのこと、安心しました。

また、TrueHDでの方法についても共有いただきありがとうございました。
