### ISSUE TITLE
Subtitle problems

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#365]
Hello,

I got some problems with subtitles.

1. Subtitles and no subtitles
When I convert several files that have subtitles and some don't have the program aborts the encoding. 
Is there any workaround to ignore the missing subtitle? As there is no subtitle for that file.

2. Subtitles in the option-file
In the normal CMD I use 

`for %i in (*.mp4) do "D:\rigaya\NVEncC\NVEncC64.exe" --avhw -i "%i"` ......
`--sub-source "%~ni.forced.srt":disposition=forced;metadata=language=eng`

Using this in the option-file,  it won't work as it can't find the subtitle it seems.

My current workaround is to put it into the CMD line with the option-file.

`for %i in (*.mp4) do "D:\rigaya\NVEncC\NVEncC64.exe" -i "%i" --option-file "nvidia.txt" --sub-source "%~ni.forced.srt":disposition=forced;metadata=language=eng -o "%~ni.mkv"`

**Comment by rigaya** [comment]
I would like to show error when specified input file is missing, so I can only some up of a workaround creating a bat file like below, but it might not be what you want...

```Batchfile
@echo off
setlocal enabledelayedexpansion
for %%i in (*.mp4) do (
    set SUB_CMD=
    if exist "%%~ni.forced.srt" set SUB_CMD=--sub-source "%%~ni.forced.srt":disposition=forced;metadata=language=eng
    NVEncC64.exe -i "%%i" --option-file "nvidia.txt" !SUB_CMD! -o "%%~ni.mkv"
)
```

**Comment by quamt** [comment]
@rigaya 
That's good enough for my purpose. 
Thank you very much.
