### ISSUE TITLE
Segmentation fault with 5.38 (r2031)

### ISSUE THREAD

**Issue by babiulep** [rigaya/NVEnc#366]
Hi rigaya, I get a segmentation fault with the latest version of nvencc:
segfault at 38 ip 00007f2fd290ad51 sp 00007ffe4a11cf30 error 4

Compiler: gcc 9.3.0/Linux.
Command: nvencc --check-hw
NVENC API v11.1, CUDA 11.4
NVIDIA GeForce RTX 2060 SUPER

Let me know if you need any more info!

**Comment by rigaya** [comment]
Thank you for reporting the issue, shall be fixed with [NVEnc 5.39](https://github.com/rigaya/NVEnc/releases/tag/5.39).

**Comment by babiulep** [comment]
Thank you rigaya! It's working again with 5.39.
