### ISSUE TITLE
Chroma-qp-offset settings ???

### ISSUE THREAD

**Issue by JibsouX** [rigaya/NVEnc#368]
Hello @rigaya !
First of all, thank you for your work!
Then i would like to have more information about the "chroma-qp-offset" settings, namely, does it work like the x265 "--cbqpoffs" & "--crqpoffs" settings https://x265.readthedocs.io/en/master/cli.html#cmdoption-cbqpoffs ?
I.e. if negative setting more bits are allocated and vice versa?

Thanks in advance !

**Comment by rigaya** [comment]
Yes, it should be the same as
x265: "--cbqpoffs" & "--crqpoffs"
x264: "--chroma-qp-offset"

 Negative settings should allocate more bitrate in CQP or QVBR mode.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
