### ISSUE TITLE
How can I set keyframe?

### ISSUE THREAD

**Issue by legion7298** [rigaya/NVEnc#370]
First of all, I'm impressed by your NVENCC Project.
Really thx :D.

I have one question.
How can I set the keyframe like h264 option ?
Or are there corresponding options in NVENCC?

**Comment by rigaya** [comment]
If you want to set a keyframe to a specified frame ID, [--keyfile](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--keyfile-string) option might help you.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
