### ISSUE TITLE
Dolby Vision metadata support?

### ISSUE THREAD

**Issue by TomMettam** [rigaya/NVEnc#371]
Is it possible to add support for adding Dolby Vision metadata into an x265 bitstream? (I'm mostly interested in profile 8.1)

Here's a sample RPU dump

[RPU.zip](https://github.com/rigaya/NVEnc/files/7455305/RPU.zip)

**Comment by TomMettam** [comment]
Just realised I can inject it after encoding with NVenc using dovi_tool. Would still be nice to have in this tool though.

**Comment by quamt** [comment]
@TomMettam 
Would be nice to know how you managed to do that.
I am sure that other users would be interested as well.

**Comment by TomMettam** [comment]
@quamt 

dovi_tool inject-rpu -i video.hevc --rpu-in RPU.bin -o injected_output.hevc

**Comment by quamt** [comment]
@TomMettam
Thank you for the info.
I was curious on how you got the RPU from the file, the settings you used for nvenc to be compliant to standard. As well on how you put the files together after you injected the RPU into the hevc. Putting files together meaning audio and video into a container.

**Comment by TomMettam** [comment]
dovi_tool can extract the rpu from your source video, and convert it to profile 8 (the best choice, single layer, HDR10 compatible). 

You don't do anything special with NVenc, but once you have the encoded video you can extract the h265 annex B bitstream with ffmpeg, inject the RPU with dovi_tool and then merge it back in with mkvtoolnix.

**Comment by quamt** [comment]
@TomMettam
I tried that but doesnt work for me.
Unable to extract the RPU.

**Comment by TomMettam** [comment]
See the example on the dovi tool page, you have to work on the raw annex b HEVC bitstream

**Comment by rigaya** [comment]
I have added new option [--dolby-vision-rpu](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--dolby-vision-rpu-string) which can insert RPU file like x265, but it seems like it requires to be remuxed by tsMuxer to be detected as Dolby Vision by MediaInfo.

**Comment by quamt** [comment]
@rigaya
How did you achieve that?
I tried and the dolbyvision is not regocnised.
Somewhere along the way, there must be a mistake I do.

**Comment by Genine-Collin** [comment]
@quamt if you look  @t the mediainfo that it's notice dolbyvision than it should work and diplaying DV 
Second if you add the command you also need to set path where it is for example --dolby-vision-rpu c:\xxxxx\xxx.rpu or .bin depents what extention you have exported to

**Comment by rigaya** [comment]
NVEnc 7.58/7.59 adds support for copying dolby vision rpu metadata and setting dolby vision profile, so I’ll close this issue.
