### ISSUE TITLE
Process freezes when cuvidParseVideoData() fails

### ISSUE THREAD

**Issue by xtne6f** [rigaya/NVEnc#373]
`CuvidDecode::DecodePacket()`, and `NVEncCore.cpp` that uses it seem not to expect the case the `cuvidParseVideoData()` API fails with CUDA_ERROR_UNKNOWN etc.
When `L500: result = cuvidParseVideoData(..` in `CuvidDecode.cpp` does not return with CUDA_SUCCESS, `th_input` thread in the `NVEncCore.cpp` ends immediately. However, `m_cuvidDec->GetError()` remains false. Therefore, `L4052: for (..` loop in the `NVEncCore.cpp` becomes an infinite loop.
Actually, NVEncC --avhw freezes with outputting the message "Error in DecodePacket: 999 (CUDA_ERROR_UNKNOWN)." after inputting some wrong MPEG-2 stream.

All I just want is NVEncC simply exits without freezing when the API fails.
For example, adding an `if (..` statement like the following (for `CuvidDecode::FlushParser()` and `CuvidDecode::DecodePacket()`) will solve this problem:

```diff
         result = cuvidParseVideoData(m_videoParser, &pCuvidPacket);
+        if (result != CUDA_SUCCESS) {
+            m_bError = true;
+        }
      } catch(...) {
```

Sorry, I don't know whether `CuvidDecode::InitDecode()` (also calls the API) should add it, because I don't understand in detail the condition to set the `m_bError`.
Then, it seems that `CuvidDecode::DecVideoData()` (also calls the API) is not used at all, so I ignore it.

Please consider... Let me know if you need additional information.
Thank you.

**Comment by rigaya** [comment]
Thank you for the comments.

I have applied your comments to the code in [NVEnc 5.42](https://github.com/rigaya/NVEnc/releases/tag/5.42). Unfortunately, I have not been able to check this error flow, as I have no such broken input files which causes errors. Please have a try if you have a file causing problems.

**Comment by xtne6f** [comment]
Thank you for your quick commit!
This issue has been completely resolved now. I will close this.

![nvencc-541-542](https://user-images.githubusercontent.com/2673799/145684463-16d47ff4-a6ca-4b3f-b6ac-cf7fce155b0f.png)

Though `cuvidParseVideoData()` could fail for a variety of reasons, one way to reproduce this error is to input an MPEG-TS that changes the video resolution. For example, when switching to multi-channel. Multi-channel is often encountered on ETV (NHK高校講座, etc.), please try it.
PID (TS packet ID) change might happen at the same time, then NVEncC would exit for the PID change. In this case, try `--input-option merge_pmt_versions:1` option.
