### ISSUE TITLE
Depth 10 bits hevc encoding

### ISSUE THREAD

**Issue by ArturAlekseev** [rigaya/NVEnc#38]
Hello,

I'm using NVEncC x64 in staxrip.
I'm setting output bit depth to 10 bits for HEVC (nvidia h.265).
When NVEncC is started I always get this error:

> Failed to Initialize the encoder
> .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

Default settings are:
--cqp 20:23:25 --codec h265 --preset quality --output-depth 10 --lookahead 32

Without --output-depth 10 it works fine.
Does not matter if source is 10 bit or 8. Result is the same.

**Comment by hydra3333** [comment]
Just out of interest, what's your video card ?

**Comment by ArturAlekseev** [comment]
Nvidia 970 gtx asus strix

5 мар. 2018 г. 5:10 ПП пользователь "hydra3333" <notifications@github.com>
написал:

**Comment by jeryll7** [comment]
If you run **NVEncC_feature_test.bat** what is the last line in created **nvenc_features.txt**?
If your video card support encoding into 10bit HEVC, last line in **nvenc_features.txt** should be
**10bit depth               yes**

**Comment by ArturAlekseev** [comment]
Ah.
I'v got: 10bit depth               no
GPU: GeForce GTX 970 (13 EU) @ 1253 MHz (391.01)
How can it does not support 10bit?

**Comment by ArturAlekseev** [comment]
I see. Thanks. Strange thou...
