### ISSUE TITLE
MPLS no chapter import

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#380]
Hello I am using the option
`-i bluray:D:\ --input-option palylist:1`
To open an MPLS, which works.
Is it possible to import the chapter markers too?
Audio, Video, Subtitle works.
Please let me know if more info is needed.

**Comment by rigaya** [comment]
It seems like the "bluray:" input (by libavformat) does not support chapters. It was the same in ffmpeg/ffprobe.

This might be the limitation of the bluray input of libavformat (or libbluray).

**normal file**
With normal file, the chapters were parsed without problem.
ffprobe -i test.mp4  -show_chapters -of xml
```
    <chapters>
        <chapter id="0" time_base="1/10000000" start="0" start_time="0.000000" end="520520000" end_time="52.052000">
            <tag key="title" value="chapter-1"/>
        </chapter>
        <chapter id="1" time_base="1/10000000" start="520520000" start_time="52.052000" end="1420090000" end_time="142.009000">
            <tag key="title" value="chapter-2"/>
        </chapter>
        <chapter id="2" time_base="1/10000000" start="1420090000" start_time="142.009000" end="7160150000" end_time="716.015000">
            <tag key="title" value="chapter-3"/>
        </chapter>
        <chapter id="3" time_base="1/10000000" start="7160150000" start_time="716.015000" end="13349670000" end_time="1334.967000">
            <tag key="title" value="chapter-4"/>
        </chapter>
        <chapter id="4" time_base="1/10000000" start="13349670000" start_time="1334.967000" end="14250240000" end_time="1425.024000">
            <tag key="title" value="chapter-5"/>
        </chapter>
        <chapter id="5" time_base="1/10000000" start="14250240000" start_time="1425.024000" end="14400216670" end_time="1440.021667">
            <tag key="title" value="chapter-6"/>
        </chapter>
    </chapters>
```

**bluray MPLS**
However, for bluray MPLS, chapters were not parsed.
ffprobe -i bluray:D:\ -show_chapters -of xml
```
    <chapters>
    </chapters>
```

**Comment by quamt** [comment]
@rigaya
Ok. So in that case its best to extract the chapters into a NVENC readable format and import them via command to import chapters.
