### ISSUE TITLE
Skip audio stream

### ISSUE THREAD

**Issue by Jisevind** [rigaya/NVEnc#382]
My input file has 2 audio streams and I just want the first one for my output file, now it puts both tracks in the output.

I use these arguments, is this how I'm supposed to do it, if so it might be broken?

--codec hevc --audio-codec 1?aac --audio-bitrate 1?192 --audio-stream 1:stereo --chapter-copy --preset P7 --output-depth 10 --colormatrix auto --colorprim auto --transfer auto --chromaloc auto --tier main -i "C:\Videos\input.mkv" -o "C:\Videos\output.mkv"

**Comment by rigaya** [comment]
Would you please try with changing ```--audio-stream``` option as below?

original: ```--audio-stream 1:stereo```
changed: ```--audio-stream 1?:stereo```

**Comment by Jisevind** [comment]
Beautyful! That works like a charm, was driving me crazy :)
