### ISSUE TITLE
vpp filters apply order

### ISSUE THREAD

**Issue by laserfoxcn** [rigaya/NVEnc#384]
First of all, thank you very much for providing this tool.
Found that the vpp-pad filter is always applied to the movie after the vpp-subburn, even though I wrote the vpp-pad before the vpp-subburn in the commandline, the text wasn't in the padded border.
If I want to burn-in subtitle onto the padded border, how could i use it?
thanks again!

**Comment by rigaya** [comment]
Unfortunately, current implementation only allows filters to be applied in fixed order, vpp-pad and then vpp-subburn.

Currently I don't have a good idea to change this implementation.

**Comment by laserfoxcn** [comment]
ok, thanks for replying.

**Comment by laserfoxcn** [comment]
ok, thanks for replying.
