### ISSUE TITLE
MediaInfo video parameters

### ISSUE THREAD

**Issue by sweetngx** [rigaya/NVEnc#385]
When I use Handbrake or FFMPeg, the following parameters are available with mediainfo, but these parameters are not added after converting with any encoding method with NVEnc. Is this a problem ? What should I do to make it possible?

"BitRate_Mode": "",
"BitRate": "",
"BitRate_Maximum": "",

**Comment by rigaya** [comment]
I'm not thinking this as a problem now, the bitrate is not set as the actual bitrate is not known when starting encoding.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
