### ISSUE TITLE
unable to transcode "Main 10@L5@Main" stream to "Main 10@L5@Main" stream with lower bitrate

### ISSUE THREAD

**Issue by jeryll7** [rigaya/NVEnc#387]
Hi, as the title says, I'm unable to transcode "Main 10@L5@Main" input stream to "Main 10@L5@Main" output stream with lower bitrate with NVEncC64.exe. When I set "--output-depth 10 --profile main10 --level 5 --tier main" the program throws an error:
nvenc : Failed to Initialize the encoder
nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

When level is set to auto NVEncC64 transcode "Main 10@L5@Main" to L6, but my android TV can't play such stream with HW acceleration ... please check this and fix this if possible (should be, because ffmpeg can do this (tested))...

Thank you.

**Comment by rigaya** [comment]
I've tested simply running options below run successfully.

Y:\Encoders>x64\NVEncC64.exe -i Y:\input.ts -o F:\temp\test.mp4 -c hevc --output-depth 10 --profile main10 --level 5 --tier main

```
--------------------------------------------------------------------------------
F:\temp\test.mp4
--------------------------------------------------------------------------------
NVEncC (x64) 6.00 (r2153) by rigaya, Apr 17 2022 13:06:00 (VC 1929/Win)
OS Version     Windows 11 x64 (22000) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [5.12GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 2070 (2304 cores, 1710 MHz)[PCIe3x16][512.15]
NVENC / CUDA   NVENC API 11.1, CUDA 11.6, schedule mode: auto
Input Buffers  CUDA, 16 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 30/1 fps
AVSync         vfr
Vpp Filters    cspconv(nv12 -> p010)
Output Info    H.265/HEVC main10 @ Level 5
               3840x2160p 1:1 30.000fps (30/1fps)
               avwriter: hevc => mp4
Encoder Preset default
Rate Control   CQP  I:20  P:23  B:25
ChromaQPOffset cb:0  cr:0
Lookahead      off
GOP length     300 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             off
CU max / min   auto / auto
Others         mv:auto

encoded 600 frames, 104.18 fps, 17489.50 kbps, 41.70 MB
encode time 0:00:05, CPU: 4.3%, GPU: 4.1%, VE: 66.3%, VD: 18.7%, GPUClock: 1725MHz, VEClock: 1597MHz
frame type IDR   2
frame type I     2,  avgQP  20.00,  total size   0.85 MB
frame type P   150,  avgQP  23.00,  total size  28.93 MB
frame type B   448,  avgQP  25.00,  total size  11.92 MB
```

It might depend on other options and the input resolution and the framerate.

Would you please share the full command line options and the input resolution and the framerate?

**Comment by jeryll7** [comment]
Hi, you can test the issue with this test file [https://enchantedleathersocks-sto.energycdn.com/dl/3sEmNCD7iXbsWenZkj6g7Q/1650894612/857577240/625d6c93121b31.13427301/test_Main_10%40L5%40High.mkv](url), and the command line is this:

NVEncC64.exe -i input.mkv -o output.mkv --avhw --audio-copy --sub-copy --chapter-copy --codec hevc --output-depth 10 --profile main10 --level 5 --tier main --qvbr 33 --vbv-bufsize 17500 --max-bitrate 17500 --qp-init 1 --multipass 2pass-full --preset P7 --lookahead 32 --ref 7 --aq --aq-strength 15 --mv-precision Q-pel --weightp --master-display copy --max-cll copy --colorprim auto --transfer auto --colormatrix auto

Thanks...

**Comment by rigaya** [comment]
Thanks for sharing the sample file and the full command line.

It seems like --ref is over the limit of Level5. Changing "--ref 7" to "--ref 5" will make it run fine.

**Comment by jeryll7** [comment]
... interesting ... the only thing that I couldn't set in similar command line to ffmpeg were reference frames (ffmpeg says it isn't supported by HW (but it probably sets it internally by existing HEVC standard (or it didn't set at all ... or the support for reference frames isn't implemented in ffmpeg for whatever reason ... IDK))) ... so the issue was not present while transcoding my media files with ffmpeg ...
... anyway, thank you again ... problem solved ...
