### ISSUE TITLE
vpp options order?

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#388]
Is there a fixed filter order in which the vpp options are applied or does the order in which they are in the command line matter?
If there is a fixed order would be nice if the order could be added to the NVEncC_Options.en.md
Thanks!

**Comment by rigaya** [comment]
The vpp options are applied in fixed order, regardless of the order in the command line.

The orders are now added to the NVEncC_Options.en.md.
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#vpp-filtering-order

**Comment by Selur** [comment]
Nice! Thanks!
