### ISSUE TITLE
hevc 10bit input for avhw

### ISSUE THREAD

**Issue by om-user** [rigaya/NVEnc#389]
When I read in avhw for a hevc 10bit file, I get the following many error messages and it creates an output with few frames. when I read in avsw, it is processed correctly. is this not supported in avhw?
[hevc @ 000001d33fc0e1c0] PPS id out of range: 2
[hevc @ 000001d33fc0e1c0] PPS id out of range: 1

---------------
Below is the command.
NVEncC64.exe --avhw --codec hevc -i input.mov --vpp-colorspace lut3d="OMSYSTEM_OM-Log400_BT.2020_to_WDR_BT.709_v1.0.cube",lut3d_interp=trilinear --output-res 1920x-2 --audio-codec aac:aac_coder=twoloop --audio-bitrate 128 --preset P5 --lookahead 32 --bref-mode each -b 5 --ref 10 --qvbr 31 --max-bitrate 8192 -o "output.mp4"

---------------
The output when read by avsw is as follows.
NVEncC (x64) 6.00 (r2153) by rigaya, Apr 17 2022 04:14:29 (VC 1929/Win)
OS Version     Windows 10 x64 (19043) [UTF-8]
CPU            AMD Ryzen 7 4800HS with Radeon Graphics [4.30GHz] (8C/16T)
GPU            #0: NVIDIA GeForce RTX 2060 with Max-Q Design (1920 cores, 1185 MHz)[PCIe3x16][512.15]
NVENC / CUDA   NVENC API 11.1, CUDA 11.6, schedule mode: auto
Input Buffers  CUDA, 46 frames
Input Info     avsw: hevc(yv12(10bit))->p010 [AVX2], 3840x2160, 60000/1001 fps
AVSync         vfr
Vpp Filters    copyHtoD
               colorspace: cspconv(p010 -> yuv444(16bit))
                           matrix:bt709->GBR
                           lut3d: table=OMSYSTEM_OM-Log400_BT.2020_to_WDR_BT.709_v1.0.cube
                                  size=33, interp=trilinear
                           matrix:GBR->bt709
               cspconv(yuv444(16bit) -> yv12)
               resize(spline36): 3840x2160 -> 1920x1080
               cspconv(yv12 -> nv12)
Output Info    H.265/HEVC main @ Level auto
               1920x1080p 1:1 59.940fps (60000/1001fps)
               avwriter: hevc, #1:pcm_s16le/2ch -> aac/stereo/128kbps => mp4
Encoder Preset P5
Rate Control   VBR
Multipass      none
Bitrate        0 kbps (Max: 8192 kbps)
Target Quality 31.00
Initial QP     I:20  P:23  B:25
QP Offset      cb:0  cr:0
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     600 frames
B frames       5 frames [ref mode: each]
Ref frames     10 frames, MultiRef L0:auto L1:auto
AQ             off
CU max / min   auto / auto
Others         mv:auto

encoded 1260 frames, 77.37 fps, 3605.53 kbps, 9.04 MB
encode time 0:00:16, CPU: 86.7%, GPU: 51.7%, VE: 27.1%, GPUClock: 1648MHz, VEClock: 1545MHz
frame type IDR    3
frame type I      3,  avgQP  25.33,  total size  0.24 MB
frame type P    246,  avgQP  25.96,  total size  6.11 MB
frame type B   1011,  avgQP  27.90,  total size  2.69 MB

---------------
Below is output of ffprobe for same kind of  input MOV file.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'P4240837.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 537986816
    compatible_brands: qt
    creation_time   : 2022-04-24T10:27:18.000000Z
  Duration: 00:02:54.67, start: 0.000000, bitrate: 116535 kb/s
  Stream #0:0[0x1](jpn): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(pc, bt2020nc/bt2020/bt2020-10), 3840x2160 [SAR 1:1 DAR 16:9], 114513 kb/s, 59.94 fps, 59.94 tbr, 180k tbn (default)
    Metadata:
      creation_time   : 2022-04-24T10:27:18.000000Z
      vendor_id       : [0][0][0][0]
      timecode        : 01:06:25;55
  Stream #0:1[0x2](jpn): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2022-04-24T10:27:18.000000Z
      vendor_id       : [0][0][0][0]
      timecode        : 01:06:25;55
  Stream #0:2[0x3](jpn): Data: none (tmcd / 0x64636D74), 1 kb/s (default)
    Metadata:
      creation_time   : 2022-04-24T10:27:18.000000Z
      timecode        : 01:06:25;55

**Comment by rigaya** [comment]
ffprobe output seems OK, but ```PPS id out of range: ``` is an error in the codec parser, but it's hard to say the cause of this problem without reproducing the issue.

**Comment by om-user** [comment]
It is possible to provide a sample input file for you.
Could you review it?
If OK, please let me know if you have a convenient place to store the files.

**Comment by rigaya** [comment]
I would appreciate if I can take a look at a sample input file.

I have no request for where to store the files, so it would be nice if you can let me know the place of the file via e-mail (rigaya34589@live.jp).

**Comment by om-user** [comment]
I sent a e-mail to you with a download link of input sample file.
Please check it.

**Comment by rigaya** [comment]
Thank you for providing the sample input file.
I was able to reproduce the issue by the file.

I'll check if I can avoid this error.

**Comment by om-user** [comment]
Great!
I'll wait for your reply.

**Comment by rigaya** [comment]
Thank you again for sharing the sample, it helped very much.

[NVEnc 6.01](https://github.com/rigaya/NVEnc/releases/tag/6.01) will try avoid this error, and should have no problem with --avhw. Please have a try.

**Comment by om-user** [comment]
I tried Ver 6.01.
Issue was solved.
Thank you for quick great action!

**Comment by rigaya** [comment]
Thank you for confirming, I'm glad to hear the problem has been resolved.
