### ISSUE TITLE
"interlaced output is not supported for HEVC codec"

### ISSUE THREAD

**Issue by hydra3333** [rigaya/NVEnc#39]
Hello.

A fair amount of my material is mpeg2 interlaced. 

I could deinterlace with ffmpeg's yadif and pipe it and worry about how to use "--audio-source <string>" [and hoping I can just say to use the same input file :)], or deinterlace with one of nvenc's deinterlacers, however I'd prefer to keep the interlaced original format if possible ...

Would you please be able to clarify if the "interlaced output is not supported for HEVC codec"error message  is a temporary or permanent thing ?

PS which nvencc internal deinterlacer do you recommend for PAL 25fps interlaced 1080i and 576i material ?  

Of interest, note that Donald Graft's DGDecNV tool http://rationalqm.us/dgdecnv/dgdecnv.html is said to somehow use NVidia's inbuilt hardware "purevideo deinterlacer" which I suppose is also available to you to implement ... I am not at all sure of the facts about that one though.

**Comment by rigaya** [comment]
For HEVC, currently NVENC does not support interlaced encoding. You can check the supported features by the driver by "--chek-features", and "Field Encoding" property shows the ability of interlaced encoding.

Currently HEVC interlaced encoding is not supported by the driver even on Pascal(GP104/GP107), and I can't tell whether NVENC will support it in the future, it's up to NVIDIA.

So currently, using H.264 will be the answer for keeping the original interlace.

I don't know much about "pure video", but when using hw decoding you are also able to use "--vpp-deinterlace" as hw de-interlacer.

If you are not satisfied with it, you can try "--tff --vpp-afs preset=30fps,level=4".

```
Y:\QSVTest>x64\NVEncC64.exe --check-features
Environment Info
OS : Windows 10 x64 (16299)
CPU: Intel Core i9-7980XE @ 2.60GHz [TB: 4.21GHz] (18C/36T)
RAM: Used 5869 MB, Total 16079 MB
GPU: GeForce GTX 1060 6GB (10 EU) @ 1708 MHz (390.77)

List of available features.
Codec: H.264/AVC
Max Bframes               4
RC Modes                  63
Field Encoding            yes
MonoChrome                no
FMO                       no
Quater-Pel MV             yes
B Direct Mode             yes
CABAC                     yes
Adaptive Transform        yes
Max Temporal Layers       0
Hierarchial P Frames      no
Hierarchial B Frames      no
Max Level                 51
Min Level                 1
4:4:4                     yes
Max Width                 4096
Max Height                4096
Dynamic Resolution Change yes
Dynamic Bitrate Change    yes
Forced constant QP        yes
Dynamic RC Mode Change    no
Subframe Readback         yes
Constrained Encoding      yes
Intra Refresh             yes
Custom VBV Bufsize        yes
Dynamic Slice Mode        yes
Ref Pic Invalidiation     yes
PreProcess                no
Async Encoding            yes
Max MBs                   65536
MAX MB per sec            983040
Lossless                  yes
SAO                       no
Me Only Mode              yes
Lookahead                 yes
AQ (temporal)             yes
Weighted Prediction       yes
Max LTR Frames            8
10bit depth               no

Codec: H.265/HEVC
Max Bframes               0
RC Modes                  63
Field Encoding            no
MonoChrome                no
Quater-Pel MV             yes
B Direct Mode             no
Max Temporal Layers       0
Hierarchial P Frames      no
Hierarchial B Frames      no
Max Level                 62
Min Level                 1
4:4:4                     yes
Max Width                 8192
Max Height                8192
Dynamic Resolution Change yes
Dynamic Bitrate Change    yes
Forced constant QP        yes
Dynamic RC Mode Change    no
Subframe Readback         yes
Constrained Encoding      no
Intra Refresh             yes
Custom VBV Bufsize        yes
Dynamic Slice Mode        yes
Ref Pic Invalidiation     yes
PreProcess                no
Async Encoding            yes
Max MBs                   262144
MAX MB per sec            983040
Lossless                  yes
SAO                       yes
Me Only Mode              yes
Lookahead                 yes
AQ (temporal)             no
Weighted Prediction       yes
Max LTR Frames            7
10bit depth               yes
```

**Comment by hydra3333** [comment]
Thank you for your good work !
