### ISSUE TITLE
Resize to specific square

### ISSUE THREAD

**Issue by seiya-git** [rigaya/NVEnc#391]
Can I set resize using "--output-res <int>x<int>" with desired square, forcing original aspect ratio?

for example:
input 1000x800
--output-res 100x100,force_original_aspect_ratio=decrease
will be result in 100x80

**Comment by rigaya** [comment]
I have added a new option in [NVEnc 6.02](https://github.com/rigaya/NVEnc/releases/tag/6.02) to preserve input aspect ratio as you have mentioned.
[--output-res](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--output-res-intxintstringstring) &lt;w&gt;x&lt;h&gt;,preserve_aspect_ratio=&lt;string&gt;

Please have a try.

**Comment by seiya-git** [comment]
@rigaya thanks!
