### ISSUE TITLE
Shortcut for Quit

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#392]
It would be nice to implement a shortcut to quit the program
like Q = Quit in ffmpeg.

**Comment by rigaya** [comment]
I've been using "Ctrl+C" to quit NVEncC.

Please let me know we have any problems using "Ctrl+C".

**Comment by fzold** [comment]
Yes, I know Ctrl+C, and NVencC works like in any CMD.
But it is a form of habit. :-)
For years I use ffmpeg and there you have Q (only 1 finger) to quit.
Now I'm using both and often forget that NVEncC needs Ctrl+C.

**Comment by rigaya** [comment]
I see, I'll have 'q' or 'Q' key to quit the program in the next release.

**Comment by rigaya** [comment]
Now [NVEnc 6.02](https://github.com/rigaya/NVEnc/releases/tag/6.02) will accept 'q' or 'Q' key to quit encoding from console.

Please have a try.
