### ISSUE TITLE
 Version 6.02 fails to build colorspace_conv on git clone on Linux 5.13.0-41-generic #46~20.04.1-Ubuntu SMP

### ISSUE THREAD

**Issue by Shanghai-Tom** [rigaya/NVEnc#395]
**Command issued is**
--vpp-colorspace transfer=smpte2084:bt709,matrix=bt2020nc:bt709,colorprim=bt2020:bt709,hdr2sdr=bt2390,source_peak=252,ldr_nits=0 --colorrange limited --mv-precision Q-pel --colorprim bt709 --transfer bt709 --colormatrix bt709

**I performed git clone
then ./configure
then make**

**Executing command gives error**

**colorspace_conv: colorspace_conv(707): error: identifier "inff" is undefined**

>>>> **colorspace_conv: 707         const float desat_scale = inff;**

**some minor warnings in compile**

NVEncCore/NVEncFilterColorspace.cpp: In member function ‘RGY_ERR ColorspaceOpLUT3D::parseCube(std::vector<unsigned char>&)’:
NVEncCore/NVEncFilterColorspace.cpp:691:19: warning: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘int’ [-Wsign-compare]
  691 |             if (b >= m_tableSize0 || g >= m_tableSize0 || r >= m_tableSize0) {
      |                 ~~^~~~~~~~~~~~~~~

NVEncCore/NVEncFilterColorspace.cpp:691:40: warning: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘int’ [-Wsign-compare]
  691 |             if (b >= m_tableSize0 || g >= m_tableSize0 || r >= m_tableSize0) {
      |                                      ~~^~~~~~~~~~~~~~~

NVEncCore/NVEncFilterColorspace.cpp:691:61: warning: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘int’ [-Wsign-compare]
  691 |             if (b >= m_tableSize0 || g >= m_tableSize0 || r >= m_tableSize0) {
      |                                                           ~~^~~~~~~~~~~~~~~

NVEncCore/rgy_output_avcodec.cpp: In member function ‘RGY_ERR RGYOutputAvcodec::WriteNextFrameInternal(RGYBitstream*, int64_t*)’:
NVEncCore/rgy_output_avcodec.cpp:2379:34: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<nal_info>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
 2379 |                         && i + 1 < nal_list.size()
      |                            ~~~~~~^~~~~~~~~~~~~~~~~

**Version information:**

NVEnc (x64) 6.02 (r2191) by rigaya, May 17 2022 13:25:50 (gcc 9.4.0/Linux)
[NVENC API v11.1, CUDA 10.1]
reader: raw, y4m, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]

**The conversion command shown here has been used previously and has succeeded to convert HDR to BT709**

**Executed command:**
-i "filename" --video-metadata 1?language=eng **--vpp-colorspace transfer=smpte2084:bt709,matrix=bt2020nc:bt709,colorprim=bt2020:bt709,hdr2sdr=bt2390,source_peak=252,ldr_nits=0 --colorrange limited --mv-precision Q-pel --colorprim bt709 --transfer bt709 --colormatrix bt709** --avsync forcecfr --avhw -c hevc --cqp 27 --lookahead 30 --output-depth 10 --output-thread 1 --cuda-schedule sync --output-res 2560x-2 --vpp-resize spline64 --audio-copy 1 -u P7

**Gives error:**

colorspace_conv: failed to build program source.
colorspace_conv: Runtime compilation failed
colorspace_conv: ---------------------------------------
colorspace_conv: --- Source of colorspace_conv ---
colorspace_conv: ---------------------------------------
colorspace_conv:   1 #ifndef _JITIFY_INCLUDE_GUARD_EE7F8CAD3E73EA82
colorspace_conv:   2 #define _JITIFY_INCLUDE_GUARD_EE7F8CAD3E73EA82
colorspace_conv:   3 #ifdef __CUDACC_RTC__
colorspace_conv:   4 #define COLORSPACE_FUNC __device__ __inline__
colorspace_conv:   5 #else
colorspace_conv:   6 #define COLORSPACE_FUNC static
colorspace_conv:   7 #include <cmath>
colorspace_conv:   8 #include <cfloat>
colorspace_conv:   9 _Pragma("warning") (push)
colorspace_conv:  10 _Pragma("warning") (disable: 4819)
colorspace_conv:  11 #include <cuda_runtime.h>
colorspace_conv:  12 _Pragma("warning") (pop)
colorspace_conv:  13 #endif
...
colorspace_conv:  44 const float MP_REF_WHITE = 203.0f;
colorspace_conv:  45 const float **MP_REF_WHITE_HLG** = 3.17955f;
colorspace_conv:  46 
...
colorspace_conv: 705         const float mul = out_max / in_max;
colorspace_conv: 706 
**colorspace_conv: 707         const float desat_scale = inff;**
colorspace_conv: 708         const float desat_base = 1.7999999999999999e-01f;
colorspace_conv: 709         const float desat_strength = 7.5000000000000000e-01f;
colorspace_conv: 710         const float desat_exp = 1.5000000000000000e+00f;
colorspace_conv: 711         // in coeff calculation, "out_max" should be in normalized scale
colorspace_conv: 712         const float coeff = fmaxf(out_max * desat_scale - desat_base, 1e-6f) / fmaxf(out_max * desat_scale, 1.0f);
colorspace_conv: 713         const float mixcoeff = desat_strength * powf(coeff, desat_exp);
...
colorspace_conv: 762 
colorspace_conv: 763 static const int **PIX_PER_THREAD** = 4;
colorspace_conv: 764 

**remainder of source not included in this error report**

colorspace_conv: 807 
colorspace_conv: 808 #endif // _JITIFY_INCLUDE_GUARD_EE7F8CAD3E73EA82
colorspace_conv: ---------------------------------------
colorspace_conv: Compiler options: --use_fast_math -DTYPE4=ushort4 -arch=compute_61 
colorspace_conv: ---------------------------------------------------
colorspace_conv: --- JIT compile log for colorspace_conv ---
colorspace_conv: ---------------------------------------------------
**colorspace_conv: colorspace_conv(707): error: identifier "inff" is undefined**
colorspace_conv: colorspace_conv(45): warning: variable "MP_REF_WHITE_HLG" was declared but never referenced
colorspace_conv: colorspace_conv(763): warning: variable "PIX_PER_THREAD" was declared but never referenced
colorspace_conv: 1 error detected in the compilation of "colorspace_conv".
colorspace: failed to setup custom filter.

**cosmetic error - Cpu info not correct [ not important ]**

CPU AMD Ryzen Threadripper 2990WX 32-Core Processor (8C/64T)

It is amd 32 core 64 Thread, but the bracket info says 8C/64T

**Comment by Shanghai-Tom** [comment]
Similar errors occur when I try and compile 5.46 - which I did compile several weeks ago, perhaps the jitify code is now incorrect ??

Now I can't compile and convert ANY HDR film to BT709 with any version of nvencc :-(

**Comment by rigaya** [comment]
It seems like that the direct cause of the error comes from identifier "inff", which is the inverse value of ldr_nits. 

desat_scale = 1.0 / ldr_nits;

Please use positive non-zero value for ldr_nits when using hdr2sdr=bt2390. I'll add error message for this in the future release.

For the first step, would you please try leaving ldr_nits default and check if it works?

**Comment by Shanghai-Tom** [comment]
Many thanks for your very prompt response, the use of your program has saved me many hours, 
and storage space in my video library, and I highly appreciate your continued work on these tools.

**Now that I know a value of 0 (zero) is not acceptable I can check for this 
and over-ride it, the issue does not need an urgent fix.**

I amended the avg-cll to be 1 if it is defined as 0 and the file processes successfully
and the converted video displays with good brightness levels compared to the original HDR file.

**If you have any suggestion as to my method of using the values in the HDR video to
set the source_peak and ldr_nits I would be pleased to receive them.**

The original video file shows the following values of **maxcll 252 avgcll 0**

I used these 2 values automatically in the conversion from hdr.

HDR  : Colour Primaries values detected, colour range limited
HDR  : G(13250,34500) B(7500,3000) R(34000,16000) WP(15635,16450) L(40000000,50) **max-cll=252,0**

These values are extracted using ffprobe:

ffprobe -hide_banner -loglevel error -select_streams v:0  
-show_frames -read_intervals "%+#1"  /* reads just one frame */
-show_entries "frame=color_space,color_primaries,color_transfer,color_range,side_data_list,pix_fmt" 
-of default=noprint_wrappers=1'

The values are encoded in the side_data_list

side_data_type=Content light level metadata
max_content=252
max_average=0

These are also shown by mediainfo, no Maximum Frame-Average Light Level value is shown.

Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 252 cd/m2

A value of 0 (zero) when a peak brightness is specified possibly indicates the 
file was not corectly processed to HDR format, and the resulting display on the equipment
would be as defined by the manufacturer, and not as defined by the video studio that created it.

**This is the output log of using a value of 1, and not 0 (zero)**

Vpp Filters    colorspace: cspconv(p010 -> yuv444(16bit))
                           matrix:bt2020nc->GBR
                           transfer:smpte2084->linear
                           hdr2sdr(bt2390): source_peak=252.00 **ldr_nits=1.00**
                             desat base 0.18, strength 0.75, exp 1.50
                           prim:bt2020->bt709
                           transfer:linear->bt709
                           matrix:GBR->bt709
               cspconv(yuv444(16bit) -> yv12(16bit))
               resize(spline64): 3840x1600 -> 2560x1066
               cspconv(yv12(16bit) -> p010)


Setting the values to 1000,100 gives me a video that is too bright
on white areas compared to the original

I have amended my scripting to use a minimum of 500,50 and if the resulting video
is not acceptable I can manually over-ride these values and convert it again using 
the values from the ffprobe query ( but not allow 0 (zero ).

Once again, many thanks for your tools and dedicated work.

Please close this item at your convenience, or add a comment to ask me to close it if necessary.

Best Regards, Tom ( in the UK )

**Comment by Shanghai-Tom** [comment]
Thank you for the feedback, I think my best option is to attempt a first conversion using the values in the HDR parameters and then examine the new video.

If it is not at a brightness level I consider acceptable I can then manually over-ride ldr_nits and convert it again.

Thanks :+1:

**Comment by rigaya** [comment]
Yes, adjusting the parameters like that might be better, as the brightness differs between videos.

Now I'll close this issue.
