### ISSUE TITLE
feature request: encode two outputs simultaneously from one input?

### ISSUE THREAD

**Issue by jeryll7** [rigaya/NVEnc#396]
for example ffmpeg can do this (using one source input making two outputs simultaneously (with nvenc)):
ffmpeg.exe -i **input.mov** -encoding parameters for first output **output.mkv** -another encoding parameters for second output **output.mp4**

so is it possible to add this feature to nvencc64?
nvencc64.exe -i **input.mov** -encoding parameters for first output -o1 **output.mkv** -another encoding parameters for second output -o2 **output.mp4**

right now I'm using ffmpeg for making two versions of input material at once (one for my TV (4K) and the other for my mobile devices (1080p)) and liked to do it with nvencc64 (because ffmpeg nvenc implementation is missing some nvenc features that nvencc64 can set)

thanks for the answer and for this (almost) perfect trans-coding tool

**Comment by rigaya** [comment]
I'm sorry, but I must say that I'm thinking this feature difficult to implement, as NVEnc is designed for single output only.

Two or multiple outputs introduces too much complexity, and will need to re-design the whole pipeline.
