### ISSUE TITLE
vpp-afs使用時、二重化するフレームで縞模様が発生する

### ISSUE THREAD

**Issue by eW4txrR** [rigaya/NVEnc#398]
こんにちは。いつも利用させて頂いてます。

"H.264 YUV420 8bit"のインターレース動画を、コマンドラインからNVEncC64 ver6.02を利用してvpp-afsで処理すると、
二重化するフレームで縞模様が現れます。
こちらですが、同じ動画をAviUtlやAvisynthを経由して、
ログに"sm(yuv444(16bit))->yuv444(16bit)"や"AviSynth+ 3.7.2 r3661(yuv444)->yuv444"と出るように処理してやると
縞模様が発生しないことから、afsの処理をyuv444以外で行うときに発生する問題かと思われます。

使用コマンド:
NVEncC64.exe -i 入力ファイル.mp4 --interlace tff --vpp-afs preset=anime -c hevc --profile main10 -o 出力ファイル.mp4

念のため、元動画をアップさせて頂きました。
https://dotup.org/uploda/dotup.org2820517.mp4.html
パス：zxcv

変換後の32フレーム目に問題のフレームが現れます。

※似たような内容を何日か前にメールしましたが、迷惑メールに入ってしまったかもしれないので、
失礼ながら情報を追加してこちらに記載させて頂きます。

**Comment by rigaya** [comment]
vpp-afsのYUV420処理時の問題点をご指摘いただきありがとうございます。また回答が遅れ、申し訳ありません。

また、サンプルの入力ファイルもありがとうございました。おかげでスムーズに原因を突き止め、修正の確認をすることができました。

今回の問題はご指摘のようにyuv420処理時の固有の問題で、[NVEnc 6.03](https://github.com/rigaya/NVEnc/releases/tag/6.03)ではyuv420時の処理を修正しました。

ご確認いただけますと幸いです。よろしくお願いいたします。

**Comment by eW4txrR** [comment]
縞模様が出ないことを確認しました。
ご対応ありがとうございます。
