### ISSUE TITLE
Audio output is only supported with transcoding (avhw reader).

### ISSUE THREAD

**Issue by hydra3333** [rigaya/NVEnc#40]
Hello again. I tried to use your example for ffmpeg piping however am receiving an error.  A suggestion of where I'm going wrong would be most appreciated.

`"C:\SOFTWARE\ffmpeg\0-homebuilt-x64\ffmpeg.exe" -hide_banner -v verbose  -threads 0 -i "G:\HDTV\0nvencc\test-mp4-02\ABC HD interlaced.aac.mp4"  
-threads 0 -an 
-sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp 
-filter_complex "[0:v]yadif=0:0:0" -pix_fmt yuv420p -f yuv4mpegpipe -   | "C:\SOFTWARE\NVEncC\NVEncC64.exe" --y4m -i -  --codec h265 
--profile auto --level auto --output-depth 8 --vbr-quality 18 
--lookahead 32 --aq --aq-strength 0 --mv-precision auto --aq-temporal 
--dar 16:9 --log-level info --perf-monitor --perf-monitor-interval 1000 
--chapter-copy --sub-copy     --max-cll "400,1000"  
-o "G:\HDTV\0nvencc\test-mp4-02\converted_mp4_henc\ABC HD interlaced.aac.mp4.nvencc.h265.mp4"`

yields

```
Audio output is only supported with transcoding (avhw reader).
Failed to open output file: "G:\HDTV\0nvencc\test-mp4-02\converted_mp4_henc\ABC HD interlaced.aac.mp4.nvencc.h265.mp4"
av_interleaved_write_frame(): Broken pipe
No more output streams to write to, finishing.
Error writing trailer of pipe:: Broken pipe
```

![audio-error](https://user-images.githubusercontent.com/10749357/37006870-5f295a6a-212a-11e8-93e4-b2880702cfdd.png)

**Comment by rigaya** [comment]
You are using pipe input to send video frames, so only video is sent to NVEncC, you can't copy audio from nothing...

Below is the minimum commandline to send raw frame and audio stream together from ffmpeg to NVEncC.

ffmpeg.exe -y -i "<input>" -codec:a copy -codec:v rawvideo -pix_fmt yuv420p -f nut - | NVEncC64.exe --avsw -i - --audio-copy -c hevc -o "<output>"

**Comment by hydra3333** [comment]
OK thank you.
