### ISSUE TITLE
HDR + Dolby Vision

### ISSUE THREAD

**Issue by jriker1** [rigaya/NVEnc#402]
I have some footage that seems to contain both HDR10 and Dolby Vision.  Does this look accurate?

HDR format                               : Dolby Vision / SMPTE ST 2086
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
HDR_Format_Commercial                    : HDR10 / HDR10

Or is this just Dolby Vision and if the device doesn't support it can look at the info like HDR10?  If they both are in this file, can they be re-encoded into a new file with nvencc?

**Comment by rigaya** [comment]
I suppose this is an output of MediaInfo, but it's not possible for me to tell if it is accurate or not.

Dolby Vision support in nvencc is limited and can handle only single-layer profiles. As it seems like it is single-layer (dovi rpu metadata + HDR10 static metadata), it might be possible to handle it.

**Comment by jriker1** [comment]
Here is what I ended up doing to get both the HDR10 and Dolby Vision content.  Seems to work and the data is there:

demux video track to HEVC
Run: dovi_tool extract-rpu <video>.h265

NVEncC64.exe --avhw --input input.mkv --output output.hevc --codec h265 --tier high --level 5.1 --output-depth 10 --cqp 19 --preset quality --vbv-bufsize 15000 --lookahead 32 --bframes 4 --aq-temporal --aud --repeat-headers --chromaloc 2 --colorprim bt2020 --transfer smpte2084 --colormatrix bt2020nc --colorrange limited --max-cll 413,65 --master-display copy --video-metadata copy --crop 0,280,0,280 --gop-len 0 --ref 3 --profile main10 --bref-mode middle --mv-precision Q-pel

(Note I manually set the max-cll info as don't know that copying the master-display info includes that.  Don't think so.)

On final video run: dovi_tool inject-rpu -i video.hevc --rpu-in RPU.bin -o injected_output.hevc

Then mux to MKV and good to go plus adding in the audio and stuff.

**Comment by Gedeon90** [comment]
Thanks for the info and the insight about max-cll. I'll check it.

This tool (https://forum.doom9.org/showthread.php?t=183479) seems to do it in  a more automated way. Mkvmerge seems to do the "magic" in parsing the DV metadata and adding the headers to the hevc stream  in a way mediainfo, ffprobe and players admit.

I'm also curious about "--ref 3" and "--bref-mode middle" ¿ Have you observed improvements in saving space/increasing quality ?

These are my current "high quality" constant parameters
 --mv-precision Q-pel --preset p7 --bref-mode each --multipass 2pass-full --bframes 4 --ref 16 --gop-len 120

**Comment by jriker1** [comment]
Never thought about that if understanding.  Do we think if you like crop black bars on the top and bottom that the dolby vision data exported isn't valid when injecting back into the final video?  I don't honestly know a lot about some of the attributes I use, just researching online a compilation of similar recommendations and where there were a lot of synergies went with them.  

Right now I'm struggling with encoding settings.  Have another issue open that contains images of that.  I like to have a keep for watching and a keep for I love this video setting.  Before it was my CRF value.  Now looking at CQP.  CRF was always odd to me that the value suggested was lower (higher number) for 4k than 1080p.  not sure if that's because of the presumption 4k content is cleaner so less pixelation.   In my other post here it's hard for me to see in the actual video differences form 16 up to 28 for CQP.  I do see smoothing in the background but hard to see differences in people in the video.  For me anyway but that's on a small screen.

**Comment by lgoncal** [comment]
> Do we think if you like crop black bars on the top and bottom that the dolby vision data exported isn't valid
That is correct.
If you crop the video you must adjust (crop) the DoVi metadata

**Comment by rigaya** [comment]
NVEnc 7.58/7.59 adds support for copying dolby vision rpu metadata and setting dolby vision profile, so I’ll close this issue.
