### ISSUE TITLE
Could not find sync byte

### ISSUE THREAD

**Issue by jriker1** [rigaya/NVEnc#403]
Trying to use nvencc64 in Windows and been fine.  Have one file that I'm getting the below any thoughts?

[mpegts @ 000001f63a059240] max resync size reached, could not find sync byte VD 18%, est out size 7973.5MB
[mpegts @ 000001f63a059240] max resync size reached, could not find sync byte
[mpegts @ 000001f63a059240] max resync size reached, could not find sync byte
[mpegts @ 000001f63a059240] max resync size reached, could not find sync byte
[mpegts @ 000001f63a059240] max resync size reached, could not find sync byte
avcuvid: error occured while reading file: 111271 frames, Resource temporarily unavailable

This is a local file to the computer.

Also not a bigger deal but occurred is spelled incorrectly.

**Comment by rigaya** [comment]
As the mpegts demuxer is failing to find sync byte in mpegts, it a trouble in libavformat mpegts demuxer or simply the file is corrupted, and difficult to find a solution for this.
