### ISSUE TITLE
8 bit coming out 10

### ISSUE THREAD

**Issue by jriker1** [rigaya/NVEnc#404]
I have been converting lately 4k content so everything I'm doing is 10 bit.  Went back to play with some 1080p content and not sure what I'm setting officially yet but stripped out part of my 4k commands and came up with this:

`NVEncC64.exe --avhw --input "input.mkv" --output "output.mkv" --codec h265 --tier high --level 5.1 --output-depth 8 --cqp 19 --preset quality --vbv-bufsize 12500 --lookahead 32 --bframes 4 --aq-temporal --aud --repeat-headers --chromaloc 0 --colorprim bt709 --transfer bt709 --input-csp yuv420p --video-metadata copy --crop 0,132,0,132 --gop-len 0 --ref 3 --profile main10 --bref-mode middle --mv-precision Q-pel`

The resulting file is 8 bit and also pixel format yuv420p10le instead of the original yuv420p.  What am I missing to set?

**Comment by rigaya** [comment]
Please remove ```--profile main10```, and the output will be 8bit.

**Comment by jriker1** [comment]
Thanks I'll give that a try.  I'm finding a real hard time seeing the differences between these for the most part to figure out a good CQP value.  Any thoughts?

Original:
![image](https://user-images.githubusercontent.com/1495536/178089329-ce52a271-b735-407c-805e-cb36be62222f.png)

CQP19:
![image](https://user-images.githubusercontent.com/1495536/178089335-4ca469e7-f060-4590-847a-6ed60c55a059.png)

CQP22:
![image](https://user-images.githubusercontent.com/1495536/178089341-ae795f4e-b3c7-4a0a-99e8-c4fa3e8b27f4.png)

CQP25:
![image](https://user-images.githubusercontent.com/1495536/178089345-76571db8-32dd-42f7-a943-761e85ae6dcb.png)

CQP28:
![image](https://user-images.githubusercontent.com/1495536/178089349-656378f8-fc51-4f42-ac16-a8c0de11d02b.png)

Not sure if I should treat my preferred CQP values for storage (CQP 19) and I love this movie (CQP 16) for my 4k content vs what I'm now trying to figure out for 1080p content.

**Comment by rigaya** [comment]
I cannot advise about CQP value as it's a tradeoff between size and quality, please find your suitable value yourself.

I'll close this issue as the main topic has been answered.
