### ISSUE TITLE
AVC artifacts using preset quality on 3090

### ISSUE THREAD

**Issue by euan-droid** [rigaya/NVEnc#405]
Hello!

I am getting visual artifacts when encoding anything to AVC using "--preset quality" on my new 3090. Everything works fine on my old 1080 Ti. Default preset works on 3090 fine too.

NVEncC (x64) 6.05 (r2215) by rigaya, Jun 16 2022 13:01:48 (VC 1929/Win)

`NVEncC64.exe  --avhw --codec avc --preset quality --input "F:\big_buck_bunny_1080p_h264.mov" --output "F:\big_buck_bunny_1080p_h264.mp4"`

![avsw default](https://user-images.githubusercontent.com/26905461/179231571-74323686-f07b-4f87-9091-7b5bffb3c35b.png)
![avsw quality](https://user-images.githubusercontent.com/26905461/179231597-0ee28959-8a40-4dd9-a963-2cef85a247d6.png)
![avhw default](https://user-images.githubusercontent.com/26905461/179231637-122d6db2-634a-4b0e-8ce9-bed77ed29baa.png)
![avhw quality](https://user-images.githubusercontent.com/26905461/179231615-e790e2b0-c33f-49bb-8253-9e2a3b7b489b.png)

Best regards.

**Comment by rigaya** [comment]
Thanks for reporting the issue, but feels very strange...

I tested with the same options but had no problem with AVC ```--preset quality``` using both RTX2070 or GTX1060, so looks like it's specific to RTX3xxx series?

Problem I have is that I have no RTX3xxx series to test, making difficult to reproduce the issue.

May I have some questions?

1. Does this artifact show up with both software decode and hardware decode on the player side? (I mean not avsw/avhw switch on encode time).
1. Does things change by adding ```--bframes 2``` or ```--bframes 0```?
1. Does things change by adding ```--ref 4```?
1. Does things change by adding ```--multiref-l0 1 --multiref-l1 1```?

**Comment by euan-droid** [comment]
Hello!!!

It would be sad enough if this is specific to RTX3xxx :) 

1. You are right, there's no artifacts when hardware decoding on! Tested on mpv 0.34.0 x64. Strange, but there are artifacts when I play video on TV, directly from flash-drive.
![sw](https://user-images.githubusercontent.com/26905461/179342066-795071fc-d39f-4c6c-9f38-81af70fd37ed.png)
![hw](https://user-images.githubusercontent.com/26905461/179342071-4db66579-648a-4956-9d8a-32cf57e0233d.png)
2. There are no artifacts with `--bframes 0`.
3. There are no artifacts with `--ref 4`.
4. There are no artifacts with `--multiref-l0 1 --multiref-l1 1`.

Well as for me I am totally satisfied with `--ref 4`. But I would be glad to do more tests, if you need it. (By the way, I _love_ NVEncC64, thank you very much!!!)

**Comment by Gedeon90** [comment]
Try to "underclock/undervolt" the gpu.

I've read similar issues with high-end cards.

**Comment by euan-droid** [comment]
> 

Yes, Gedeon90, I've tried undervolt my GPU. It now works under 0.875 V @ 1860MHz, which passed stability test with 98,4%, but artifacts appear in any case.

**Comment by Gedeon90** [comment]
¿ And the VRAM ? Just for discard.

**Comment by euan-droid** [comment]
Gedeon90, and VRAM _this time_ :) Artifacts are still here. And `--bluray` changes nothing.

**Comment by Gedeon90** [comment]
Oops... My last bullet ...

Try to force  --level 4.1 since is usually the accepted/expected standard for most AVC/H264 players

**Comment by euan-droid** [comment]
> Oops... My last bullet ...
> 
> Try to force --level 4.1 since it is usually the accepted/expected standard for most AVC/H264 players

I am sorry, but that changed nothing...

**Comment by rigaya** [comment]
@euan-droid 
Thank you for your tests. This seems very strange but glad to hear it can be avoided by --ref 4, or by using hardware decoder. (also weird the behavior changes by the decoder)

Seems to be related to reference frames and also specific to RTX30xx, but I find it difficult to avoid this automatically from the app.
