### ISSUE TITLE
Missing first frames

### ISSUE THREAD

**Issue by Gygun** [rigaya/NVEnc#408]
Hello Rigaya

I'm using avhw to transcode a video, but for some reason the output is missing the first frames (4 secs) of the original video. When using ffmpeg the error is not present. Is there any option/parameters I could use to avoid that? Amazing work btw, Thank you!

`NVEncC --avhw -i "input.mp4" -o "output.mp4"`

My guess is that the video I'm using has the first keyframe missing.

**Comment by rigaya** [comment]
Yes, I also think there might be first keyframe missing.

NVEncC start encoding from the first keyframe, so the start point might differ from other applications. Unfortunately, there is no option to avoid this, as I think it'll be difficult to start decode from non-keyframe. (I'm not sure how ffmpeg is doing)

**Comment by Gygun** [comment]
Thank you for the answer! In other videos works just fine. I'm sure it's the keyframe then. I'll report if I find anything else.
