### ISSUE TITLE
Issue or change?

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#409]
When encoding video material with the following settings:

`for %i in (*.mp4) do "E:\rigaya\NVEncC\NVEncC64.exe" -d 0 -i "%i" --avhw --codec h265 --preset P7 --output-depth 10 --profile main10 --tier high --max-bitrate 2500 --vbv-bufsize 2500 --bref-mode each --ref 5 --vpp-deband rand_each_frame --vpp-edgelevel  --vpp-warpsharp  --mv-precision q-pel --lookahead 32 --audio-copy --sub-source "%~ni.ass":disposition=forced;metadata=language=eng -o "D:\TEST_9_%~ni.mkv"`

The subtitle is listed as audio in the input? 
```
NVEncC (x64) 6.05 (r2215) by rigaya, Jun 16 2022 13:01:48 (VC 1929/Win)
OS Version     Windows 11 x64 (22000) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [5.00GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 3080 (8704 cores, 1725 MHz)[PCIe4x16][516.59]
NVENC / CUDA   NVENC API 11.1, CUDA 11.7, schedule mode: auto
Input Buffers  CUDA, 44 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
               avcodec audio: ass
AVSync         vfr
Vpp Filters    cspconv(nv12 -> yv12(16bit))
               edgelevel: strength 5.0, threshold 20.0, black 0.0, white 0.0
               warpsharp: threshold 128.0, blur 2, type 0, depth 16.0, chroma 0
               deband: mode 1, range 15, threY 15, threCb 15, threCr 15
                       ditherY 15, ditherC 15, blurFirst no, randEachFrame yes
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc, aac, subtitle#1 => matroska
Encoder Preset quality
Rate Control   CQP  I:20  P:23  B:25
ChromaQPOffset cb:0  cr:0
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       3 frames [ref mode: each]
Ref frames     5 frames, MultiRef L0:auto L1:auto
AQ             on
CU max / min   auto / auto
Others         mv:Q-pel
```

Are there any changes?
Or a mistake on my site?

**Comment by rigaya** [comment]
I exppect the subtitle is handled properly as it is written properly on the output side.
```avwriter: hevc, aac, subtitle#1 => matroska```

Do you have any problem with the actual output mkv file?

**Comment by quamt** [comment]
The output seems to be fine.
I was just perplexed the way it showed the audio and the subtitle.
In this case was a mistake / misunderstanding on my side.
Closing this.
Thank you.
