### ISSUE TITLE
10 bit ffmpeg pipe example

### ISSUE THREAD

**Issue by hydra3333** [rigaya/NVEnc#41]
At the moment the example for pipe usage from ffmpeg is
`ffmpeg -y -i "<inputfile>" -an -pix_fmt yuv420p -f yuv4mpegpipe - | NVEncC --y4m -i - -o "<outfilename.264>"`

May I assume that's for 8-bit ? And for 10-bit would that be this ?
`ffmpeg -y -i "<inputfile>" -an -pix_fmt yuv420p10le -f yuv4mpegpipe - | NVEncC --y4m -i - -o "<outfilename.264>"`

**Comment by rigaya** [comment]
Yes, command line above is for 8bit, and below will be for 10bit.

**Comment by hydra3333** [comment]
thank you.
