### ISSUE TITLE
HDR10+ and cropping?

### ISSUE THREAD

**Issue by jriker1** [rigaya/NVEnc#410]
I learned with Dolby Vision if I cropped the black bars during encoding that I had to deal with that with the Dolby Vision data exported from the source.  Is there something similar that has to be done with the metadata for HDR10+ content?

**Comment by rigaya** [comment]
I’m sorry but I’m not sure about the details of the metadata, and I won’t be able to answer this.

**Comment by fzold** [comment]
HDR10+ has no EL layer, only metadata. Nothing to deal with.
