### ISSUE TITLE
AC3 to AAC Conversion speed

### ISSUE THREAD

**Issue by x901c963s** [rigaya/NVEnc#411]
Wondering if I can solve the following problem with NVEnc!

While I don't actually have a problem with conversion, I do have a direct problem with Conversion speed. With FFMpeg, I convert ac3 (175 mb) audio files to aac (70mb) format in about 2 minutes by consuming very little cpu (5%). I couldn't find a way to achieve this even though it's really great on my computer, I guess the problem is software... Do you think there is a way to achieve this? I have a lot of questions in my mind, why can't FFMPeg speed up this process at the expense of consuming more cpu, What is the obstacle?

I think I found someone having similar issue at the link below... Anyone have a better idea? https://forums.developer.nvidia.com/t/nvenc-with-audio-conversion-best-practice-advice/40759

`ffmpeg.exe -threads 32  -i "en.ac3" -map a:0 -c:a aac -b:a 128k -vn -y output.aac`

**Comment by x901c963s** [comment]
So can NVENC only convert a audio file? Is there a method for the command line ?

**Comment by rigaya** [comment]
No, NVEnc targets video encoding by NVENC hw encoder.
