### ISSUE TITLE
HDR2SDR with DisplayP3 Colorspace

### ISSUE THREAD

**Issue by holmy88** [rigaya/NVEnc#412]
Is it possible to add support for hdr2sdr to be able to convert from DisplayP3 (smpte432) to BT709 instead of BT2020 to BT709 primary colorspace? I have found many if not most HDR files are actually mastered in DisplayP3 colorspace and converting from BT2020 causes the colors to go weird in some videos. For my DisplayP3 files, I'm currently having to use ffmpeg (example below) to convert from smpte432 to BT2020 which is very slow and then piping the rawvideo into NVENCC to then do the tonemapping. My script checks the masterdisplay metadata to determine if the file is DisplayP3 or BT2020.

`ffmpeg -i input.mkv -vf scale=1920:1080:force_original_aspect_ratio=decrease:force_divisible_by=2,zscale=pin=smpte432:p=bt2020 -c:v rawvideo -f nut - | nvencc64 --avsw -i - --codec hevc --device 1 --output-depth 10 --vpp-colorspace hdr2sdr=reinhard,source_peak=4000 --preset p6 --vbr 3500k --max-bitrate 3850k --vbv-bufsize 3850k --qp-min 20 --lookahead 32 --gop-len 50 --bframes 4 --bref-mode each --aq -o video.mkv`

**Comment by rigaya** [comment]
As you have mentioned, hdr2sdr was always converting bt2020 to bt709 primary colorspace.

I have updated to [NVEnc 6.06](https://github.com/rigaya/NVEnc/releases/tag/6.06), which will allow conversion from primary other than bt2020.
Would you please try ```--vpp-colorspace hdr2sdr=reinhard,colorprim=st432-1:bt709```, which will convert from DisplayP3 to bt709 primary colorspace.

**Comment by holmy88** [comment]
It works thank you.

**Comment by rigaya** [comment]
Thank you for confirming.
