### ISSUE TITLE
HDR2HDR

### ISSUE THREAD

**Issue by wsx958191** [rigaya/NVEnc#413]
hi：
     How to support HDR coding ?

**Comment by rigaya** [comment]
I’m sorry but I’m not able to get what you mean.

Would you please provide more details and examples?

**Comment by wsx958191** [comment]
Hello, maybe I didn't make it clear. I want to provide HDR video conversion from high bit rate to low bit rate, but I don't know whether it can be realized if the HDR content of the video should be maintained

**Comment by GabeBlincoln** [comment]
Just don't change the colorspace or mastering data and you're fine.   HDR can be reencoded to any bit rate you want, or resized and left as HDR.  I've converted old SD 30fps 480i videos to 60fps 480p HDR10 w/ Dolby Vision and don't have any issues playing them back.  It's much easier when your source is already HDR, I'm just giving an extreme example.

The only caveat is that if you want seeking to work well on TVs and devices with less memory you'll probably want to set a fixed GOP length that's relatively short.   

If the video has HDR10+ metadata or Dolby Vision there are other things that need to be done to preserve those (unless NVEnc handles them automatically) that you'll have to google around for.

**Comment by rigaya** [comment]
NVEnc now supports copying HDR10 metadata (mastering display, max FALL/CLL), HDR10+ dynamic metadata copy and dolby vision rpu copy, so HDR conversion could be done using those features.
