### ISSUE TITLE
7.1ch audio use --audio-stream  downmix to 2ch with libopus will lose some volume

### ISSUE THREAD

**Issue by Lincutt** [rigaya/NVEnc#415]
Input audio is 7.1ch FLAC, when I use below options to downmix it
`--audio-codec libopus --audio-stream 7.1:stereo`
the output 2ch opus audio will lose some volume.

FFMPEG use the same input with:
`-c:a libopus -ac 2`
will keep the original volume.
(Louder than NVEncC made.)

**Comment by rigaya** [comment]
Thank you for reporting the issue.

I've changed audio sample format used in down mixing, and should have been fixed with [NVEnc 6.07](https://github.com/rigaya/NVEnc/releases/tag/6.07).

**Comment by Lincutt** [comment]
Thank you very much!
I've tested with v6.07 and everything is good.
now I can remove staxrip and all other things from my laptop! lol

Thank you again for you make all these GREAT stuff!!!
