### ISSUE TITLE
Conversion to BT709: vpp-colorspace error

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#416]
I'm converting movies from PAL DVDs into h264 mkv or mp4 and BT709 for streaming.
With
`--vpp-colorspace matrix=bt470bg:bt709`
you get a lot red lines and
`colorspace_conv: 10 errors detected in the compilation of "colorspace_conv".
colorspace: failed to setup custom filter.`
And with
`--vpp-colorspace matrix=smpte170m:bt709`
or another source you get no error lines but the result is unusable. Wrong colors and the lower half of the image is colored green.

-----------
Intel Tiger Lake + NVIDIA GeForce RTX 3050 Ti, W10 Pro

**Comment by rigaya** [comment]
Thank you for sharing the issue.

I was able to reproduce the problem with --vpp-colorspace matrix=bt470bg:bt709, however was not able to find problem just with --vpp-colorspace matrix=smpte170m:bt709.

It might be related with other conditions. Would you please share the full options and log when the problem occurred with --vpp-colorspace matrix=smpte170m:bt709?

**Comment by fzold** [comment]
Thank you, the first issue is solved. 👍

I have searched for the second problem: It has to do with INTERLACED encoding. Every DVD has mpeg2 interlaced encoded content. I use MakeMKV to build mkv files from DVD.
If you feed interlaced mkv to NVEncC and vpp-colorspace then you get that unusable frames.
When does colorspace work? Before or after deinterlacing?

`Input Info     avcuvid: MPEG2, 720x576, 25/1 fps`
`Deinterlace    adaptive`
`AVSync         vfr`
`Vpp Filters    colorspace: cspconv(nv12 -> yuv444)`
  `matrix:bt470bg->bt709`
   `cspconv(yuv444 -> yv12)`
    `cspconv(yv12 -> nv12)`
I think colorspace (yuv444) must work on a frame - not on a fiekd. So first you have to deinterlace to frame and then comes the colorspace conversion.

You'll get the colorspace issue -> green colored lower half of frames only with interlaced content.
Hope that helps.

**Comment by rigaya** [comment]
Thank you for the log and explanation about the interlaced input.

The error was caused by wrong handling of interlaced flags and wrong yuv444 -> yv12 conversion.

[NVEnc 6.09](https://github.com/rigaya/NVEnc/releases/tag/6.09) shall fix this issue, which has corrected these problems.

**Comment by fzold** [comment]
Great!  👍 Many thanks.
