### ISSUE TITLE
feature request: include libplacebo filter in NVEnc

### ISSUE THREAD

**Issue by jeryll7** [rigaya/NVEnc#418]
Hi, could you perhaps consider to include this filter in NVEncc?
[https://code.videolan.org/videolan/libplacebo](url)
[http://ffmpeg.org/ffmpeg-all.html#libplacebo](url)
Not sure how difficult it will be to implement/support, but if it can be done, we will get this:
```

High-quality, optimized upscaling and downscaling including support for
polar filters ("Jinc"), anti-aliasing, anti-ringing and gamma correct
scaling.

Color management and format conversions for a wide variety of HDR or
wide gamut color spaces. This includes support for ICC profiles, ITU-R
BT.1886 emulation, colorimetrically accurate clipping, custom 1D/3D LUTs,
scene-referred OOTFs (such as HLG), constant luminance formats including
ICtCp and a variety of film industry formats ranging from XYZ to Sony's
S-Log or Panasonic's V-Gamut.
Tunable debanding shader. This is based on flash3kyuu, expanded to
provide high quality by combining multiple debanding passes.
Dynamic HDR tone mapping, including shaders for real-time peak and
scene-change detection, chroma-preserving (luma-only) tone mapping,
highlight desaturation, dynamic exposure control and a variety of
industry-standard EETFs including BT.2390.
High performance film grain synthesis for AV1 and H.274, allowing media
players to offload this part of decoding from the CPU to the GPU.
A pluggable, extensible custom shader syntax, equivalent to an improved
version of mpv's .hook
syntax. This can be
used to arbitrarily extend the range of custom shaders to include popular
user shaders like RAVU, FSRCNNX, or Anime4K. See the mpv wiki on user
scripts
for more information.
```

I tested current implementation in latest ffmpeg and I want this to use in NVEnc if possible. Thank you very much for your hard work.

**Comment by Lincutt** [comment]
> libplacebo says it supports D3D11, so I think it can be added to NVEncC, at least in Windows.
> 
> I'll think about this, but I'm not sure how much time it will take, and how much time I can spend too...

rigaya's hwenc is better than ffmpeg's in any way(quality/size/speed), whatever nv/qsv/vce.
I was wondering if you could make something like librigya.dll or implement them into libavcodec...etc
that will be great I thought!

such GREAT encoders should let more people know and use!

**Comment by jeryll7** [comment]
No longer relevant to me, since I managed to find how use libplacebo filters through Avisynth (in staxrip) and with basic knowledge of avs scripts this can be AFAIK done with nvencc64 through --avs option.
