### ISSUE TITLE
突然使えなくなりました

### ISSUE THREAD

**Issue by Luluria** [rigaya/NVEnc#419]
二週間ほど前まで普通に使えていましたが、先ほどAviutlを使ったら出力できなくなっており、プラグインの最新版を入れたりいろいろ試しましたがこの画像の通りです。
NODEVICEとありますがこれはこのプラグインがGPUを認識していないということですか？？
ゲーム等は普通にできており、出力できていた二週間前から変わっていることはGPUのドライバーくらいです。
GPUのドライバーも一応正常だった時のバージョンを入れてみましたが結果は変わりませんでした。
GPUはRTX3060です。

![Desktop Screenshot 2022 08 22 - 08 22 10 82](https://user-images.githubusercontent.com/111712614/185815793-60b3f0eb-3c0a-43db-a67b-e3e0a1edd253.png)

**Comment by rigaya** [comment]
> NODEVICEとありますがこれはこのプラグインがGPUを認識していないということですか？？

そうですね。GPUを見つけられなかったというエラーになります。

可能であれば、コマンドプロンプトを起動して、```nvidia-smi```と入れてEnterで起動して、このコマンドでGPUが認識されるか確認いただけますでしょうか?

![image](https://user-images.githubusercontent.com/815947/185928652-933971b3-90f1-4a07-a1bb-0e356809bf53.png)

**Comment by Luluria** [comment]
![Desktop Screenshot 2022 08 23 - 11 33 28 04](https://user-images.githubusercontent.com/111712614/186056268-a6de2192-0ab9-4d08-b500-13cc17d46a31.png

あんまり見てもよくわからないんですが認識されているのでしょうか？？？

ゲームとかちゃんとできてるので3060動いているとは思うのですが……

**Comment by Luluria** [comment]
と思っていたのですがどうやらGPU怪しいかもしれないです。
OBSで録画しようとするとNVENCコーデックを開けませんと出ました。
どうもエンコードの件と無関係ではなさそうですね
NVIDIA関連のものをすべてアンストして入れなおしましたが改善しません。
何かした覚えは全くないですがこれはGPUに何らかのエラーというかダメージ的なものを与えてしまったのでしょうか…？

**Comment by rigaya** [comment]
いただいたScreenshotでは、認識されているようですが、どうもアプリケーションからは見えていない状況になっていそうです。

ただ、思い当たる点が少なく、思い当たる点としては環境変数 ```CUDA_VISIBLE_DEVICES``` におかしな値が設定されているとこういう症状が出たりします。

ただ、普通設定しないと思うので違うかもしれないです。

環境変数は [設定アプリ] > [システム] > [バージョン情報] > [システムの詳細設定] から

以下の画面の下のほう、環境変数をクリックして確認できます。
![image](https://user-images.githubusercontent.com/815947/186188599-95ca1431-b52b-4617-ab40-ae8a4e427482.png)

**Comment by Luluria** [comment]
![Desktop Screenshot 2022 08 24 - 07 25 13 25](https://user-images.githubusercontent.com/111712614/186276915-cb85d5df-9556-47a7-9500-7e0dabbbeb41.png)
そのような変数は見られないですね……
ほんとに何かした覚えがないんですけどいつの間にかこうなってしまうものなんですかねぇ？
ハードウェア的なこともおそらくありえませんし(PCのお掃除をしたくらい)

**Comment by Luluria** [comment]
CUDA_VISIBLE_DEVICESという変数がそもそもないのですがこれは異常ですか？

**Comment by rigaya** [comment]
いえ、ないのが普通で、なければ特に問題ないです。

ただ、そうなってくると、ドライバの再インストールも試されてもOBSでもエンコードできないということですので、すみませんが私のほうでも思い当たることがありません…

**Comment by Luluria** [comment]
わかりました
対応いただきありがとうございました！
もう少し自力で頑張ります！

**Comment by Luluria** [comment]
わかりました
ご対応いただきありがとうございました！
自力で頑張ります！
とはいえおんなじ事例がないのか検索かけても一ミリもヒットしないんですよね…

**Comment by Luluria** [comment]
治りました！
レジストリエディターそういえばいじったなと思いHKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDriversにあるTdrLEVELというものを消したら治りました。
友人から教えてもらったものだったので怪しんでいませんでした…
今後レジストリいじるのはやめときます…
OBSも同様に動かせます！
ご対応いただき本当にありがとうございました！
ご迷惑おかけしました。

**Comment by rigaya** [comment]
無事解決されたとのことで安心しました。

レジストリの設定が原因だったのですね、私もこの設定については知りませんでした。問題となったレジストリについて共有いただき、ありがとうございました。
