### ISSUE TITLE
ERROR : The number of fields...

### ISSUE THREAD

**Issue by bbcby** [rigaya/NVEnc#424]
Blu-ray authoring software (**Sonic Scenarist**) - Import file to project.
ERROR : The number of fields(frames) displayed in a GOP exceeds the limit.

`NVEncC64 -i Untitled-01.avs --codec h264 --preset quality --bluray --qp-min 0 --aq --aq-temporal --pic-struct --aud --vbr 20000 --vbv-bufsize 30000 --max-bitrate 30000 --gop-len 24 --sar 1:1 -o Untitled-01.264`

**Comment by rigaya** [comment]
> ERROR : The number of fields(frames) displayed in a GOP exceeds the limit.

I've run with your command line options, and checked the keyframe position in the video by ffprobe with the following command.

x64\ffprobe.exe -show_frames -select_streams v test_output.264 | find "key_frame" | find /N "key_frame=1"

Output is attached at the link below, and there was one keyframe in 24 frames, which shows ```--gop-len 24``` is working.
[sample_movie_1080p.264.txt](https://github.com/rigaya/NVEnc/files/9495519/sample_movie_1080p.264.txt)

Therefore, GOP length is 24 frames, and should be within the limit.

Below is the result of the "TMPGEnc MPEG Smart Renderer 4", which is a software I've been using to test bluray compatibility, shows the file is suitable for BDMV (as BDMV is highlighted in yellow).
![image](https://user-images.githubusercontent.com/815947/188605102-a577c69c-4597-4dcf-92d5-97c19215d2f3.png)

**Comment by bbcby** [comment]
It seems to me that the problem is not in the GOP at all.
The file does not pass validation MUI Generator of Scenarist.

**TMPGEnc Authoring Works 6**:
Track criterias for Smart Render (Blu-ray BDMV) shows 100%.
Automatic insert of chapters (18 chapters) for a 40-minute movie takes approximately 5 minutes.
After the start of the mux - re-encoding 100%. Smart Render only audio track.

**TSMUXER** (Blu-ray folder):
Mux Ok. During playback, when clicking on the next chapter, for example 2, the movie plays from the beginning, but the mark shows chapter 2, and so on.
The same reaction to the seek.

**Blu-Disc Studio** (Blu-ray authoring software).
The file in the project is opened, but chapters cannot be set. Impossible.
After mux - result the same like TSMUXER.

**KITe UHD Authoring Suite**:
Mux is failed.
Part of log
```
...
Elementary stream Buffer underflow: : PID = 4113, Frame PTS = 667856, Time PTS = 667858
...
```

**Comment by rigaya** [comment]
> problem is not in the GOP at all.

As it is difficult to find out what the program is complaining, I find it difficult to improve further.
