### ISSUE TITLE
Error while compiling  with ffmpeg  5.1

### ISSUE THREAD

**Issue by divyam234** [rigaya/NVEnc#425]
https://hastebin.com/odacobacuf

![Screenshot from 2022-09-16 14-02-29](https://user-images.githubusercontent.com/47589864/190594262-de00f70e-666b-4536-9ff3-55bd382003d3.png)

Compilation process is failing at this step.I have attached logs above. Currently I am trying to integrate  Nvenc with https://github.com/BtbN/FFmpeg-Builds  repo which compiles all the libraries needed for Nvenc.

**Comment by rigaya** [comment]
```
/usr/bin/ld: /opt/ffbuild/lib/libavcodec.a(libx264.o): in function `X264_init':
libx264.c:(.text.unlikely+0xc7c): undefined reference to `x264_encoder_open_164'
```

This is simply failing to link to libavcodec.a (static link?) by "undefined reference", so you need to add link options and pass where the libraries are via ```--extra-ldflags``` for other dependencies of libavcodec.a. This should depend on your build, system, or environment.
