### ISSUE TITLE
Forced only subtitle flag for PGS subtitles when hard coding to video

### ISSUE THREAD

**Issue by MartyMcNuts** [rigaya/NVEnc#426]
Hi, I have been using -vpp-subburn quite often to hard code the subs from PGS into the video (4K UHD & 1080p bluray) but occasionally come across a movie where the PGS subs contain both full and forced subtitles.

I was wondering if you could add a "forced-only" flag so that just the forced subs in the PGS file can be hard coded in the video. I think FFMPEG has something like this.

I have zipped and attached a PGS sub file from "A Quiet Place" 4K UHD. This PGS file contains the both full and forced subs.

Cheers,
MM

[A QUIET PLACE_F1_T15_Subtitle - English.zip](https://github.com/rigaya/NVEnc/files/9595966/A.QUIET.PLACE_F1_T15_Subtitle.-.English.zip)

**Comment by rigaya** [comment]
I'm sorry but I could not get the point.

I might bot be able to understand by what it means by "full and forced subs". There are 2 types subtitles in one subtitle track?

> I was wondering if you could add a "forced-only" flag so that just the forced subs in the PGS file can be hard coded in the video. I think FFMPEG has something like this.

Would you let me know the actual command line for ffmpeg? I would like to check as it might be a great hint.

**Comment by MartyMcNuts** [comment]
Hi rigaya,

If you open the PGS subtitle file in BDSup2Sub you can see that the file contains 165 subtitles and 114 of those are flagged as forced.

What I would like is for an option to be able to burn in only those forced subtitles from the file.

In FFMPEG, the -forced_subs_only flag tells the PGS decoder to only delcode those subtitles in the file marked as forced. An example FFMPEG command can be found here: [https://superuser.com/questions/1458297/ffmpeg-using-forced-subs-only-does-not-burn-in-forced-subs](url)

Cheers,
MM

**Comment by rigaya** [comment]
Thank you for the detailed explanation and the usage of the option in ffmpeg! That helped me a lot.

[NVEnc 7.03](https://github.com/rigaya/NVEnc/releases/tag/7.03) will have new parameter "forced_subs_only" for --vpp-subburn to render forced only subs in PGS subtitles.

```
--vpp-subburn filename="A QUIET PLACE_F1_T15_Subtitle - English.sup",forced_subs_only=on
```

**Comment by MartyMcNuts** [comment]
Tested and yes it works! Thanks heaps!!

**Comment by rigaya** [comment]
Thank you for confirming!
