### ISSUE TITLE
About AV1 and HDR

### ISSUE THREAD

**Issue by draco1544** [rigaya/NVEnc#428]
The rtx 4000 series has been announced with an av1 hardware encoder. This new encoder will support Av1 in HDR ? I know this is to early to answer this question but I open this topic for keeping a track of the progress of av1 nvenc

**Comment by draco1544** [comment]
HDR seems to be supported

**Comment by rigaya** [comment]
[NVEnc 7.02](https://github.com/rigaya/NVEnc/releases/tag/7.02) shall be able to handle AV1 encoding with HDR options.
