### ISSUE TITLE
Aviutl NVEnc 6.12 > > > Virus

### ISSUE THREAD

**Issue by Baka-Neko-Hime** [rigaya/NVEnc#430]
Hello, seem like "auo_setup.exe" is infected by a suspicious.mystic !

**Comment by rigaya** [comment]
I'm not sure which anti-virus detects it as virus, but it is false-positive if the hash matches the link below.

https://www.virustotal.com/gui/file/c7e6ae1fe2ad11e54d8d0e884f888511de1a8ce0e3bee3505321d0d482dac9bb

**Comment by rigaya** [comment]
I’ll close this issue as the topic has been answered.
