### ISSUE TITLE
Error in JIT compile using --vpp-colorspace matrix=bt470bg:bt709,colorprim=bt470bg:bt709,transfer=bt470bg:bt709

### ISSUE THREAD

**Issue by Shanghai-Tom** [rigaya/NVEnc#432]
BT.601 cannot be used for video greater than 720p and I am up-scaling the video size to 1080p, and therefore 1080p should be bt709 

My input file is:

```
1. Matrix:     BT.470 System B/G 
2. Primaries:  BT.601 PAL 
3. Transfer:   BT.470 System B/G
```

According to documentation on the internet BT.601 PAL should be specified as  bt470bg, as nvencc does not recognise BT.601  in any of it's options

```
--vpp-colorspace matrix=bt470bg:bt709,colorprim=bt470bg:bt709,transfer=bt470bg:bt709
                     bt470bg                    bt601  PAL              bt470bg
```

I amended the command to use `colorprim=auto:bt709` but it still fails

- _My query is to ask if this conversion is possible and what parameters should I use ?_

I am using NVEnc (x64) 6.02 (r2191)

Extract from error Log, if you need all of it please let me know

colorspace_conv: failed to build program source.
colorspace_conv: Runtime compilation failed
colorspace_conv: ---------------------------------------
colorspace_conv: --- Source of colorspace_conv ---
colorspace_conv: ---------------------------------------

[ full log not included ]

colorspace_conv: ---------------------------------------
colorspace_conv: Compiler options: --use_fast_math -DTYPE4=uchar4 -arch=compute_61 
colorspace_conv: ---------------------------------------------------
colorspace_conv: --- JIT compile log for colorspace_conv ---
colorspace_conv: ---------------------------------------------------
colorspace_conv: colorspace_conv(661): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(661): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(661): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(662): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(662): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(662): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(663): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(663): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(663): error: expression must have arithmetic or enum type
colorspace_conv: colorspace_conv(45): warning: variable "MP_REF_WHITE_HLG" was declared but never referenced
colorspace_conv: colorspace_conv(715): warning: variable "PIX_PER_THREAD" was declared but never referenced
colorspace_conv: 9 errors detected in the compilation of "colorspace_conv".
colorspace: failed to setup custom filter.

```
Code referenced in error messages:

colorspace_conv: 660         float m[3][3] = {
colorspace_conv: 661             { -nanf, -nanf, -nanf },
colorspace_conv: 662             { -nanf, -nanf, -nanf },
colorspace_conv: 663             { -nanf, -nanf, -nanf }
colorspace_conv: 664         };
colorspace_conv: 665         x = matrix_mul(m, x);
```

Many thanks for any assistance,
 Regards Tom

**Comment by Shanghai-Tom** [comment]
Update: First part of log confirms the file is bt470bg

Input #0, matroska,webm, 
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-10-15T12:19:46.000000Z
  Duration: 00:23:59.92, start: 0.000000, bitrate: 2320 kb/s
    **Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt470bg, progressive)**, 1024x576 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)

**Comment by rigaya** [comment]
Conversion from bt470bg was unspported, but support was added in NVEnc 6.09. ( #416 )

Please update to the latest version and try again.

**Comment by Shanghai-Tom** [comment]
Thank you for your prompt response, I have upgraded to version 7.02 and the conversion is successful :-)
