### ISSUE TITLE
 Information about nvenc h.264 presets

### ISSUE THREAD

**Issue by sandr1x** [rigaya/NVEnc#436]
Please tell me, I can find somewhere a more detailed description of the nvenc_h264 presets, as described for [x264](http://dev.beandog.org/x264_preset_reference.html)?
Interested in presets P1-P7

**Comment by rigaya** [comment]
I've gone through documents of NVIDIA VIDEO CODEC SDK, but there were not detailed documentation about presets there.

You can simply think it as a performance/quality knob.
