### ISSUE TITLE
I need help to Crop Video and remove sound please!

### ISSUE THREAD

**Issue by rezpower** [rigaya/NVEnc#441]
Sorry for the trouble but I am totally ignorant on settings to use and need help to rectify a scrip shared with me by a friend!

What I am doing is simply Fast encoding 7K, 8K SBS 3D videos to a light proxy, so I can edit them fast in Adobe premiere.
I would like to achieve the most possible encoding speed as the quality is of no importance and proxy is only needed to make few cuts. 

here is the setting that I am using right now:

for %%i in (*.mp4 *.avi *.mov *.wmv *.ts *.m2ts *.mkv) do if not exist "%ProxyDir%\%%~ni_proxy.mp4" (
    if /I not "%%~xi" == ".avi" (
        "%~dp0nvencc\NVEncC64.exe" -i "%%i" -o "%ProxyDir%\%%~ni_proxy.mp4" --output-res 960x-2 -c h264 --preset quality --cqp 23:25:28 --aq-strength 10 --ref 1 --bframes 0 --gop-len 15 --lookahead 15 --qp-max 30 --aq --cabac --mv-precision q-pel --audio-codec aac --audio-bitrate 384 --avsync cfr --colorprim auto --transfer auto --colormatrix auto --colorrange auto

This is giving me a sufficiently good result and I am able to do my job already with this.

But I am hoping for two things here is you can help me please:
1- These videos are SBS (Side by side) and I want to know if there is a way I can crop half of the video (no matter which side) So that the exported proxy would be only one full side.

2- How can I set the encoding to only encode video "without sound" ? For now I changed the audio part to "--audio-copy" as this will probably use less resource as I don't need the sound at all.

Also my pc has an i7 12800HX CPU and Nvidia RTX3070 Ti), but I see that the bottleneck is the video decoding. (only 2 % cpu usage). Is there anyway I can speed up the encode ? Any modification to my settings that can achieve a faster encode would be appreciated.

**Comment by rigaya** [comment]
1. You might go try for [--crop](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--crop-intintintint) for cropping half of the video.

2. To encode without sound, please remove **all** audio related options (such as --audio-codec, --audio-copy, --audio-bitrate), and no audio will be processed.

3. If hw decode is working, CPU usage will be low.

Below is an example, with only ``` --output-res 960x-2 -c h264```.
```
NVEncC (x64) 7.04 (r2374) by rigaya, Nov 12 2022 18:44:58 (VC 1929/Win)
OS Version     Windows 11 x64 (22000) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [4.89GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 4080 (9728 cores, 2505 MHz)[PCIe4x16][526.98]
NVENC / CUDA   NVENC API 12.0, CUDA 12.0, schedule mode: auto
Input Buffers  CUDA, 20 frames
Input Info     avcuvid: VP9, 7680x4320, 24000/1001 fps
Vpp Filters    copyDtoD
Output Info    H.264/AVC high @ Level auto
               960x540p 1:1 23.976fps (24000/1001fps)
               avwriter: h264 => mp4
Encoder Preset default
Rate Control   CQP  I:20  P:23  B:25
ChromaQPOffset cb:0  cr:0
Lookahead      off
GOP length     240 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             off
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto

encoded 6570 frames, 102.73 fps, 4464.45 kbps, 145.84 MB
encode time 0:01:03, CPU: 0.6%, GPU: 81.0%, VE: 5.5%, VD: 82.6%, GPUClock: 2768MHz, VEClock: 2157MHz
frame type IDR   28
frame type I     28,  avgQP  20.00,  total size   3.60 MB
frame type P   1643,  avgQP  23.00,  total size  63.74 MB
frame type B   4899,  avgQP  25.00,  total size  78.50 MB
```

- Input Info "avcuvid" shows hw decode working. (avsw for sw decoding)
- CPU usage is low.
- GPU usage is GPU ALU/FPU usage, mainly used in filtering (resize here).
- VE is hw encoder usage.
- VD is hw decoder usage. Around 80-100% is high enough, it will be difficult to get more performance.

I think it is difficult to avoid decode bottleneck in this case...

**Comment by rezpower** [comment]
Thanks a lot for your help and your reply. Got the audio out of the way! (didn't know I should remove entries but thought have to add something like audio=off etc ) .
I already looked at the crop commands before posting this question. But could not understand what to do exactly as what I need with these side by side videos is to remove exact half of the video from left side OR right side (only keep the video from laft to middle of the screen) each video has different resolution (5k 6k 8k etc) . would you know how to do this?

**Comment by rigaya** [comment]
Unfortunately, NVEncC does not have option to crop "half" of the video, we need to set pixels to crop manually.

If you are using bat file, I think this can be set automatically, combining with MediaInfo CLI.

Simple example is shown below. (%1 is for input file)

```
set MEDIAINFO_PATH=Y:\Encoders\x64\MediaInfo\MediaInfo.exe
set NVENCC_PATH=Y:\Encoders\x64\NVEncC64.exe

"%MEDIAINFO_PATH%" "--Inform=Video;%%Width%%" %1 > "%~1.width.txt"
for /f "usebackq delims=" %%A in ("%~1.width.txt") do set WIDTH=%%A
set /a WIDTH_HALF=%WIDTH%/2
del "%~1.width.txt"

"%NVENCC_PATH%" -i %1 -o "%~1.out.mp4" --crop %WIDTH_HALF%,0,0,0
```

**Comment by rezpower** [comment]
thanks a lot rigaya. Impressive support :)
