### ISSUE TITLE
feature request:specify end time of input file

### ISSUE THREAD

**Issue by 4D094DC081** [rigaya/NVEnc#442]
when I want to encode specified range of a video with NVEncC avsw

--seek is specify start time,but it do not specify end time.

use ffmpeg pipe solve it

"E:\ffmpeg.exe" -loglevel fatal -ss 02:00:00.000 -to 02:30:00.000 -i "E:\1.mkv -fps_mode passthrough -c:a copy -c:v rawvideo -f nut - | "E:\NVEncC64.exe" --codec h265 --preset P7 --output-depth 10 --tier high --multipass 2pass-full --aq-temporal --bref-mode each --gop-len 90 --lookahead 32 --ref 7 --bframes 3 --sar 1:1 --colorrange auto --colorprim auto --transfer auto --colormatrix auto --qvbr 26 --audio-codec copy --output-res 1280x720 --avsw -i - -o "E:\2.mp4"

looks like --seek is like doing -ss funtion of ffmpeg , why not add something like --seekto doing ffmpeg's -to funtion

**Comment by rigaya** [comment]
[--seekto](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--seekto-intintintint) option has been added in [NVEnc 7.07](https://github.com/rigaya/NVEnc/releases/tag/7.07).

Please note that --seek, --seekto in not so accurate, when accuracy is required, --trim shall be used in NVEnc. Also, it might not be completely equivalent compared to ffmpeg as the implementation differs.

**Comment by 4D094DC081** [comment]
Thanks rigaya, great job.
