### ISSUE TITLE
Deactivate in-loop-deblocking at h265 / HEVC codec

### ISSUE THREAD

**Issue by mogobime** [rigaya/NVEnc#446]
When downscaling from 4K to 1080p I sometimes deactivate in-loop-deblocking at NVEnc h264 to get a maximum sharp and detailed image. But at h265 deactivating the deblocker isn't possible, and I prefer 10 bit encoding.
Is it possible to realize a --no-deblock option for h265, too?
I think weakening the deblock isn't supported by Nvidia, right?

**Comment by rigaya** [comment]
I checked through the NVENC API, but it seems that there are no option provided for deblock filters in HEVC encoding.

**Comment by rigaya** [comment]
I'll now close this issue, as the question has been answered.
