### ISSUE TITLE
Is it  possible to include compiled binary  along with  rpm and deb packages  in releases?

### ISSUE THREAD

**Issue by divyam234** [rigaya/NVEnc#447]
I am using nvenc  in aws sagemaker instance which  doesn't allow  installation of deb  and rpm packages. Although I was compiling  nvenc executable ealier but it would be nice if its already  included in releases.

**Comment by rigaya** [comment]
I might have misunderstood the point, but I think compiled binary will not work alone, as it depends on many other packages. (so you need to install packages anyway)
```
rigaya@rigaya2-pc:~$ dpkg -x nvencc_7.08_Ubuntu22.04_amd64.deb out
rigaya@rigaya2-pc:~$ ls out/usr/bin/
nvencc
rigaya@rigaya2-pc:~$ ldd out/usr/bin/nvencc
        linux-vdso.so.1 (0x00007ffd8e46a000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f263208e000)
        libcuda.so.1 => /usr/lib/wsl/lib/libcuda.so.1 (0x00007f2631e69000)
        libswresample.so.3 => /lib/x86_64-linux-gnu/libswresample.so.3 (0x00007f2631e47000)
        libavutil.so.56 => /lib/x86_64-linux-gnu/libavutil.so.56 (0x00007f2631d1e000)
        libavcodec.so.58 => /lib/x86_64-linux-gnu/libavcodec.so.58 (0x00007f2630758000)
        libavformat.so.58 => /lib/x86_64-linux-gnu/libavformat.so.58 (0x00007f26304de000)
        libavfilter.so.7 => /lib/x86_64-linux-gnu/libavfilter.so.7 (0x00007f263015b000)
        libass.so.9 => /lib/x86_64-linux-gnu/libass.so.9 (0x00007f262ff28000)
  ... and so many other libraries ...
```

**Comment by divyam234** [comment]
All Nvencc version works well with  https://github.com/BtbN/FFmpeg-Builds  dynamic builds  so  I don't  have to install these
dependencies separately via  apt or yum  . In my case the only problem with sagemaker studio  instances is that they don't provide sudo access  so I can't  install any package with dpkg ,yum or apt etc. That why I was wondering if its possible to include only  nvencc binary that is packaged with deb and rpm packages in releases.

**Comment by rigaya** [comment]
I see, I've understood the dependencies could be installed by other ffmpeg lib builds.

May I have one more question? If you want only nvencc binary in the package, you could extract it from deb file to local directory by dpkg command **without sudo**. Would this not work? (or dpkg command not available?)

```
dpkg -x nvencc_7.08_Ubuntu22.04_amd64.deb <outdir>
# nvencc could be found "<outdir>/usr/bin/nvencc"
```

It is possible to simply add the nvencc binary only archive (like nvencc_7.xx_Ubuntu22.04_amd64.tar.gz or something), but I think it might be confusing for some users to have many choices/options to download.

**Comment by divyam234** [comment]
Sure I will try if this works.Thanks for quick response.
