### ISSUE TITLE
Side by Side / Split Screen comparison, possible?

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#448]
Hello,

I want to ask if it is possible to implement and Side by Side / Split Screen comparison?

When filters are applied and encoded it would be nice to have this feature to compare the output result with a result where the filters have not been applied. Like a top/bottom or left/right comparison. 

I did not see this in the options or did I miss it?

**Comment by rigaya** [comment]
Unfortunately, NVEnc does not have that kind of feature, and no plan to implement, as we can easily compare using Avisynth in that case.

Example is shown below.
```
v1 = LWLibavVideoSource("output_without_filter.mp4")
v2 = LWLibavVideoSource("output_with_filter.mp4")
a = LWLibavAudioSource("output_without_filter.mp4")
v = StackHorizontal(v1,v2) # Horizontal for left/right, StackVertical can be used for top/bottom
audiodub(v,a)
```

**Comment by quamt** [comment]
Ok. Thank you for the AviSynth solution.
