### ISSUE TITLE
Color desaturation on AV1 encodes (HDR metadata not preserved with NVEncC AV1)

### ISSUE THREAD

**Issue by Vrael0n** [rigaya/NVEnc#453]
Colors become desaturated when encoding av1, this does not occur when encoding h265.

Source:
![source](https://user-images.githubusercontent.com/61518774/213883357-2a92b0fd-8b5c-4dc6-8c1c-2ef8ad33b59c.jpg)

NVEncC AV1:
![av1](https://user-images.githubusercontent.com/61518774/213883365-aaf52b28-6a81-45bf-8d0f-f1f555a88b09.jpg)

NVEncC H265:
![h265](https://user-images.githubusercontent.com/61518774/213883370-d5c322ce-0f0f-4c08-9120-b1bb11c4b890.jpg)

It's easier to see the difference using the "Slider" compare mode on https://www.diffchecker.com/image-compare/

Environment Info:
NVEncC (x64) 7.12 (r2406) by rigaya, Jan 21 2023 09:23:36 (VC 1929/Win)
OS Version     Windows 10 x64 (19044) [UTF-8]
CPU            13th Gen Intel Core i5-13600K [5.43GHz] (6C/12T)
GPU            #0: NVIDIA GeForce RTX 4090 (16384 cores, 2520 MHz)[PCIe4x16][527.56]
NVENC / CUDA   NVENC API 12.0, CUDA 12.0, schedule mode: auto

Colorimetry:
VUI            matrix:bt2020nc,colorprim:bt2020,transfer:smpte2084,range:full,chromaloc:topleft
MasteringDisp  G(0.265000 0.690000) B(0.150000 0.060000) R(0.680000 0.320000)
               WP(0.312700 0.329000) L(1000.000000 0.000000)
MaxCLL/MaxFALL 1000/1000

HDR format: SMPTE ST 2086, HDR10

AV1 command:
`NVEncC64.exe --avhw --codec av1 --preset P7 --profile main --tier 1 --output-depth 10 --qvbr 20 --max-bitrate 800000 --aq --aq-temporal --mv-precision Q-pel --lookahead 32 --output-buf 32 --colorrange auto --colormatrix auto --colorprim auto --transfer auto --chromaloc auto --max-cll copy --master-display copy --audio-copy -i "E:\OBS Capture\Enctest\2022-12-29 05-55-38 (1) 2s trim.mkv" -o "E:\OBS Capture\Enctest\2022-12-29 05-55-38 (1) 2s trim NVEncC av1.mkv"`

H265 Command:
`NVEncC64.exe --avhw --codec h265 --preset P7 --profile main10 --tier high --output-depth 10 --qvbr 20 --max-bitrate 800000 --aq --aq-temporal --mv-precision Q-pel --lookahead 32 --output-buf 32 --colorrange auto --colormatrix auto --colorprim auto --transfer auto --chromaloc auto --max-cll copy --master-display copy --audio-copy -i "E:\OBS Capture\Enctest\2022-12-29 05-55-38 (1) 2s trim.mkv" -o "E:\OBS Capture\Enctest\2022-12-29 05-55-38 (1) 2s trim NVEncC h265.mkv"`

Source video:
https://drive.google.com/file/d/1GrFbfpnjIr8wt6MoDUgPgKOz7SNi3Oh0/view?usp=share_link

Debug log:
[log.txt](https://github.com/rigaya/NVEnc/files/10472817/log.txt)

**Comment by Vrael0n** [comment]
Split image, Source and H265 look like left side, AV1 on right side:
![image](https://user-images.githubusercontent.com/61518774/213884264-4004eac3-c5de-4b49-828f-6554633d4171.png)

**Comment by Vrael0n** [comment]
I believe the problem is related to HDR, Mastering display, and MaxCLL/MaxFall not being signaled when encoding NVEncC AV1 because the source AV1 and the NVEncC H256 encode have the metadata.

AV1 source:
> HDR format: SMPTE ST 2086, HDR10 compatible
---and---
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0000 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000
Maximum Frame-Average Light Level        : 1000

NVEncC H265:
> HDR format: SMPTE ST 2086, HDR10 compatible
---and---
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0000 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 1000 cd/m2

NVEncC AV1:
No HDR format
No Mastering display color primaries/luminance
No MaxCLL and MaxFall

Source (AV1):
![image](https://user-images.githubusercontent.com/61518774/213894879-1018e2e8-5c3f-44d2-9ca6-ff895bcfc7db.png)

NVEncC H265:
![image](https://user-images.githubusercontent.com/61518774/213894892-5e3a35fc-9098-4673-a8c4-0cab68bb0b15.png)

NVEncC AV1:
![image](https://user-images.githubusercontent.com/61518774/213894899-771914b4-3084-43ad-9576-f4e69f46f227.png)

**Comment by rigaya** [comment]
Thank you fro the details and the input file.

However, I must say I'm not being able to find out the cause.

Although I've used your input file and the same command line options, I don't seem to be able to reproduce this issue, MediaInfo (22.12) shows HDR metadata copied properly, and I've also debugged internal behavior but MaxCLL/MasteringDisplay was read, generated and inserted correctly. I've also compared the log, but there was no hint.

Very weird...

![image](https://user-images.githubusercontent.com/815947/213897355-6f87331a-956d-483a-b04d-05eb40316fa0.png)

```
NVEncC (x64) 7.12 (r2406) by rigaya, Jan 21 2023 09:23:36 (VC 1929/Win)
OS Version     Windows 11 x64 (22621) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [5.00GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 4080 (9728 cores, 2505 MHz)[PCIe4x16][528.02]
NVENC / CUDA   NVENC API 12.0, CUDA 12.0, schedule mode: auto
Input Buffers  CUDA, 44 frames
Input Info     avcuvid: AV1, 3840x2160, 60/1 fps
AVSync         vfr
Vpp Filters    copyDtoD
Output Info    AV1 main 10bit @ Level auto
               3840x2160p 1:1 60.000fps (60/1fps)
               avwriter: av1, aac => matroska
Encoder Preset quality
Rate Control   VBR
Multipass      none
Bitrate        0 kbps (Max: 800000 kbps)
Target Quality 20.00
Initial QP     I:20  P:23  B:25
QP Offset      cb:0  cr:0
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     600 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on
Part size      max auto / min auto
Tile num       columns auto / rows auto
TemporalLayers max 1
Refs           forward auto, backward auto
VUI            matrix:bt2020nc,colorprim:bt2020,transfer:smpte2084,range:full,chromaloc:topleft
MasteringDisp  G(0.265000 0.690000) B(0.150000 0.060000) R(0.680000 0.320000)
               WP(0.312700 0.329000) L(1000.000000 0.000000)
MaxCLL/MaxFALL 1000/1000
Others         mv:Q-pel

encoded 130 frames, 56.23 fps, 206658.49 kbps, 53.38 MB
encode time 0:00:02, CPU: 0.3%, GPU: 63.0%, VE: 27.0%, VD: 98.5%, GPUClock: 2640MHz, VEClock: 2108MHz
frame type IDR   2
frame type I     2,  avgQP  50.00,  total size   1.77 MB
frame type P   128,  avgQP  42.15,  total size  51.60 MB
```

**Comment by Vrael0n** [comment]
I've managed to get the Mastering display color primaries\luminance and MaxCLL and MaxFall to show with the latest MediaInfo version and Nvidia driver which is odd since the source (also AV1, created by OBS-NVENC) shows the metadata fine. But HDR format is still missing. Your MediaInfo screenshot is also missing it.

![image](https://user-images.githubusercontent.com/61518774/213899077-1eb85f0a-93ca-4925-9500-1225912f8014.png)

AV1 source:
![image](https://user-images.githubusercontent.com/61518774/213899109-c28d6ee5-80ba-4e6d-9a28-e97d9afed98a.png)

NVEncC H265:
![image](https://user-images.githubusercontent.com/61518774/213899156-e4661e73-94b4-4229-ac4a-7e1d8cd22e68.png)

NVEncC AV1:
![image](https://user-images.githubusercontent.com/61518774/213899191-ddfa98f1-3948-4dca-beff-c8969b260181.png)

**Comment by rigaya** [comment]
I've improved HDR10 metadata handling in [NVEnc 7.13](https://github.com/rigaya/NVEnc/releases/tag/7.13), now adds metadata information also on the container side, and now HDR format shall show up.

**Comment by Vrael0n** [comment]
That fixed it thanks 👍

However metadata appears to be duplicated now with an `INFO` and `INFO_Original` copy of each type, but `HDR format: SMPTE ST 2086, HDR10 compatible` is now preserved and playback is fixed now visually matching the source.

You can close this issue if you think the metadata duplication is not a problem.

![image](https://user-images.githubusercontent.com/61518774/213919363-ab27131f-0171-4f2e-a4fb-5a029a9d35f3.png)

**Comment by rigaya** [comment]
Thank you for confirming, and nice to hear now visually matching the source.

Duplication is due to metadata in both container and av1 bitstream. The same duplication is shown when encoding by svt-av1 with HDR10 metadata and then muxing by mp4box to mp4, so I think it is not a problem.
