### ISSUE TITLE
Add black bar to encoded video

### ISSUE THREAD

**Issue by ysnist** [rigaya/NVEnc#454]
Greetings to Rigaya, the kindest developer on the planet. I have a problem that I think might be useful for other NVEnc users.

If I have a movie file with a resolution of 1920x800 and I want to encode it to 1920x1080, unfortunately it stretches my video from above and below, causing the image to distort. Actually ffmpeg does this as well. But other video encoders like wondershare keep the height 800 constant and add a 140px black bar at the top and bottom of the video (1080-800=280) and the video image is 1080 without distortion. I wonder if it is possible to do this with NVENC. This problem is a nightmare for movie encoders.

@rigaya

**Comment by quamt** [comment]
You can use --vpp-pad <int>,<int>,<int>,<int> to add black bars.
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-pad-intintintint

**Comment by rigaya** [comment]
@quamt Thank You!

Please not that --vpp-pad will be inserted as last filter of the pipeline. (filters are in fixed order)

**Comment by ysnist** [comment]
Oh. It's really interesting that I went through all the command lines one by one and missed this one. Thank you all.

**Comment by quamt** [comment]
You could try create a batch file with the below content, please adjust accordingly to your environment.

```
set MEDIAINFO_PATH=E:\rigaya\MediaInfo\MediaInfo.exe
set NVENCC_PATH=E:\rigaya\NVEncC\NVEncC64.exe

"%MEDIAINFO_PATH%" "--Inform=Video;%%Height%%" %1 > "%~1.Height.txt"
for /f "usebackq delims=" %%A in ("%~1.Height.txt") do set Height=%%A
set /a Height_ADJUST=(1080-%Height%)/2
del "%~1.Height.txt"

"%NVENCC_PATH%" -i %1 -o "%~1.out.mp4" --vpp-pad 0,%Height_ADJUST%,0,%Height_ADJUST%
```

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
