### ISSUE TITLE
Question: How to use --mux-option ?

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#455]
Hello I want to check on how to use the ` --mux-option`

For example I have a txt file with description of the video and want to add the information into the end result.

Example file name "Holiday_2002.txt" contains text: `Holiday 2002 in Europe from 20th to 30th January 2002`

I didn't se another option to add a description metadata, I suppose its via the `--mux-option` ?

And is it possible to add a picture as thumbnail via `--mux-option` ? for mp4 / mkv

**Comment by rigaya** [comment]
I think what you need is [--metadata](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--metadata-string-or-stringstring).

In your case following should work.
```
 --metadata description="Holiday 2002 in Europe from 20th to 30th January 2002"
```

> is it possible to add a picture as thumbnail 

Unfortunately adding picture is not available. I'm not sure how to do that...

**Comment by quamt** [comment]
I was looking at that, but didn't see how to import from a txt file.
In that case I might need create a batch script to read the txt file and add it as the metadata description.

Or combine it with the info I saw that for ffmpeg on how to add a picture as a thumbnail:

```
ffmpeg -i "input.mkv" -attach "cover.jpg" -map 0 -c copy -metadata:s:t mimetype="image/jpg" -metadata:s:t:0 filename="cover.jpg" "output_cover.mkv"
```

**Comment by quamt** [comment]
@rigaya Is there somewhere, where all the mux-options can be found/listed?

**Comment by rigaya** [comment]
```--mux-option``` is actually internally directed to [libavformat Format Options](https://ffmpeg.org/ffmpeg-formats.html#toc-Format-Options), so can be used like ```--mux-option max_delay:250000```.

It should take effect for output (mux) only.

**Comment by rigaya** [comment]
[NVEnc 7.14](https://github.com/rigaya/NVEnc/releases/tag/7.14) adds [--attachment-source](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--attachment-source-stringintparam1value1) which can adds attachments from file.

Example:
```
--attachment-source "<png_file>":metadata=mimetype=image/png
```

**Comment by quamt** [comment]
Thank you :-)
