### ISSUE TITLE
Avcuvid: Unknown FPS

### ISSUE THREAD

**Issue by ysnist** [rigaya/NVEnc#456]
When I want to change the frame rate of the video I coded using `--fps 25/1` or `--fps 25,000`, I get the following error. Do you have any idea why this is happening?

`avcuvid: Unknown input option: framerate=25/1, ignored.`

**Comment by rigaya** [comment]
There is no option to changing original frame rate in NVEnc, it is recommended required to use Avisynth or others in that case.

```--fps``` is intended to work for raw input or sequential image inputs, which originaly does not have information of frame rate.

**Comment by ysnist** [comment]
Oh. Oh. I never thought I'd hear that. So can you make this feature for nvenc? I don't know how difficult it is. But I think it's very important, it's a feature that almost all encoders have.

**Comment by rigaya** [comment]
Simply changing frame rate only should cause change in video duration and cause de-sync of video & audio, so it should be not useful.

Mean while, if you want to keep video duration **and** change frame rate, you shall need interpolation to create a frame which will com in between, which should require a complex algorithm I won't be able to implement.

If you simply want to duplicate or drop frame to change frame rate ```--fps 25/1 --avsync forcecfr``` will do, but might not be a smooth video, because there is no interpolation there. You can ignore the warning "Unknown input option" in that case because it's only a warning as it is in yellow (error should be shown in red).

**Comment by ysnist** [comment]
Now I understand better and you are right, but does this also apply to ffmpeg? If I need to encode my video with nvencc after first converting it with ffmpeg?

**Comment by rigaya** [comment]
There are multiple ways to change framerate in ffmpeg.
- input option ```-r``` → change video duration (cause de-sync)
- ```-vf fps``` or ouput option ```-r``` → duplicate or drop frame (same as NVEncC ```--fps n --avsync forcecfr```)
- ```-vf minterpolate``` → interpolation but slow

**Comment by ysnist** [comment]
Thank you for the valuable information you have provided.

**Comment by rigaya** [comment]
With simple duplicate or drop frame, there should be little discomfort if the source frame rate to target frame rate is very close, or multiple of integer, or can be divided by integer.

In other cases, there might be rather bigger discomfort without interpolation, so in those cases the best ways is to not change the frame rate when possible.

**Comment by ysnist** [comment]
Yes, it's actually my rtmp server that worries me. I send my movie archive to my rtmp server to convert it to live streaming, but I wonder how my rtmp server will handle this situation if the fps of both movies are different when one movie ends and switches to the next. Because the rtmp server I currently use can switch to the new movie without any interruption in movie transitions. But I don't know if it will show the same behavior when the fps are different. At least as long as the resolutions are the same, I don't think there will be a problem. But the difference in fps worries me. I guess it is not possible to understand without trying

**Comment by rigaya** [comment]
As long as I test on my local systems I haven't gone such corruptions, so it's hard to think it is problem of the encoder itself.
