### ISSUE TITLE
Picture jumps with h264 VBR encoding on Android TV

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#458]
When using variable bitrate encoding with "--vbr xxxx" or "--qvbr xx" the picture jumps on my Sony Android TV 2022 (Android 9).

It does not jump with h264 VBR on my phone with Android 12, not on Windows, and not with hevc VBR encoded video on the same Android TV.

Could it be that my TV, even though it's from 2022, doesn't support VBR with h264, or could that be a bug in the encoder?

Here is a test video which has the problem under Android TV:
https://user-images.githubusercontent.com/16306963/214855692-dc192ff9-f739-45c0-959b-9c1a616bc1e7.mp4

And this is what it looks like when it jumps:
https://user-images.githubusercontent.com/16306963/214856477-4486b978-e3c5-490d-b4f3-2f5fec47044a.mp4

**Comment by quamt** [comment]
Do you have the complete commands used for your encoding?
Which nvenc version do you use?
And which nvidia driver version?

**Comment by rainman74** [comment]
> Do you have the complete commands used for your encoding? Which nvenc version do you use? And which nvidia driver version?

`nvencc64.exe -i input.mkv -c h264 --profile high --level auto --preset quality --qvbr 23 --audio-copy -o output.mkv`

NVEncC (x64) 7.13 (r2413)

NVIDIA Driver 528.02 @ Geforce GTX 3080 and also tested on GTX 1080

**Comment by rainman74** [comment]
And there are no image errors with Constant Bitrate Enconding

`nvencc64.exe -i input.mkv -c h264 --profile high --level auto --preset quality --cqp 16:18:20 --audio-copy -o output.mkv`

or

`nvencc64.exe -i input.mkv -c h264 --profile high --level auto --preset quality --cbr 8000 --audio-copy -o output.mkv`

**Comment by rainman74** [comment]
There is also no problem with the h264 VBR in FFmpeg (current nightly build) on Android TV, so I guess the "bug" is probably in nvencc64 after all.

`ffmpeg -i "input.mkv" -c:v h264_nvenc -profile:v high -preset p7 -tune hq -cq:v 25 -rc:v vbr -rc-lookahead:v 32 -c:a copy "output.mkv"`

**Comment by rigaya** [comment]
It's natural that NVEncC and ffmpeg behavior differs as the default parameters seem to be different.

Please try for adding "[--bref-mode](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--bref-mode-string) middle" or swicthing to "[--preset](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#-u---preset) default".

**Comment by rainman74** [comment]
> "[--bref-mode](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--bref-mode-string) middle"

adding "--bref-mode middle" fixes the jumping of the picture at h264 VBR on Android TV.

Thanks a lot 👍👍👍

**Comment by rigaya** [comment]
[NVEnc 7.14](https://github.com/rigaya/NVEnc/releases/tag/7.14) enables --bref-mode by default when preset slower than default is selected, and therefore will be able to avoid this issue by default.

Thank you for reporting this issue, now I will close this issue.
