### ISSUE TITLE
SuperRes filter is great, but output-res option is not suitable for it

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#459]
Since many videos do not always have exact formats, the SuperRes filter usually does not work. Even if I calculate the size exactly according to the resize factor.

Example:
Input 720x404 --> --output-res=1440x808 --> Suitable ratio for nvvfx-superres not found!

```
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 1.5, retrying with other ratios...
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 2.0, retrying with other ratios...
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 3.0, retrying with other ratios...
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 4.0, retrying with other ratios...
resize: Suitable ratio for nvvfx-superres not found.
resize: Failed to init nvvfx filter.
```

Upscaling from 1280x720 to 1920x1080 (2x) works but I don't need that often.

Therefore, the following alternative option to --output-res would be better for SuperRes:
--output-scale <int>

Examples:
--output-scale 1.5
--output-scale 2
--output-scale 3
--output-scale 4

**Comment by quamt** [comment]
Hello @rigaya,

I get similar error messages with the new filters.
I am not sure if it is the resolution or the source material.
Its MPEG2 720x480

(The Upscaler feature supports any input resolution, and the following scaling factors: 4/3x (~1.33x), 1.5x, 2x, 3x and 4x.
https://github.com/NVIDIA/MAXINE-VFX-SDK)

Trying to denoise, upscale with superres and artefact reduction I get the error messages below.

`nvvfx-denoise: Failed to set input image: A CUDA pitch is not within the acceptable range..
`
`nvvfx-artifact-reduction: Failed to set input image: A CUDA pitch is not within the acceptable range..`

```
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 4.0, retrying with other ratios...
resize: Suitable ratio for nvvfx-superres not found.
resize: Failed to init nvvfx filter.
```

or 

```
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 3.0, retrying with other ratios...
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 4.0, retrying with other ratios...
resize: Suitable ratio for nvvfx-superres not found.
resize: Failed to init nvvfx filter.
```

or 

```
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 2.0, retrying with other ratios...
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 3.0, retrying with other ratios...
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 4.0, retrying with other ratios...
resize: Suitable ratio for nvvfx-superres not found.
resize: Failed to init nvvfx filter.
```

**Comment by quamt** [comment]
I did some more testing and it is the resolution that seem to give the problem.
Upscaling in Handbrake to 720p and reencode with denoise, upscale with superres and artefact reduction works without problem.

**Comment by rigaya** [comment]
@quamt The line artifact showing up was due to spline16 bug in NVEnc 7.15, shall be fixed in [NVEnc 7.16](https://github.com/rigaya/NVEnc/releases/tag/7.16).

I also think "A CUDA pitch is not within the acceptable range" problem is due to input resolution. as I have no problem with at least 720p and 1080p. The problem is that I could not find from the documents which is the acceptable range (or value).

vpp-resize nvvfx-superres is using "Super Resolution" and not "Upscaler" from the [MAXINE-VFX-SDK](https://github.com/NVIDIA/MAXINE-VFX-SDK). As scaling factor is limited to 4/3x (~1.33x), 1.5x, 2x, 3x and 4x, NVEnc will try using these ratios to starting from the ratio near --output-res, and then resize to the exact --output-res value. Therefore, I think --output-res will be enough and adding another --output-scale option will be more confusing.

**Comment by rainman74** [comment]
@rigaya Then SuperRes is unfortunately not usable for me with nvencc, because even a simple resize from a 720x400 video fails :-(

nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 3.0, retrying with other ratios...
nvvfx-superres: Failed to set input image: A CUDA pitch is not within the acceptable range..
resize: Failed to init nvvfx-superres with ratio 4.0, retrying with other ratios...
resize: Suitable ratio for nvvfx-superres not found.
resize: Failed to init nvvfx filter.

Magnifying a 720p or 1080p with SuperRes is relatively useless, but yes, I can also confirm that it works.

**Comment by quamt** [comment]
@rigaya 

The Super Resolution feature supports between 90p to 2160p as input resolutions.
https://github.com/NVIDIA/MAXINE-VFX-SDK

So it seems only Progressive material is supported.
But even after deinterlaced in handbrake it gave the error.

Testet 640x480p and it works.

**Comment by Alex-Balay** [comment]
It seems the length must be a multiple of 128.

**Comment by rainman74** [comment]
> MAXINE-VFX-SDK

yes looks like it! But this doesn't seem to be a limitation of the MAXINE-VFX-SDK, it's up to NVenC. Reason unknown...

**Comment by rigaya** [comment]
@Alex-Balay Thanks, I've did some tests and can confirm width must be multiple of 128, and height seems to have no restriction.

Below is result for --vpp-nvvfx-denoise, "Y" was fine, but "N" went into error. 

| Input Resolution | Result |
|:--:       |:--:|
| 320x180   | N  |
| 320x240   | N  |
| 384x288   | Y  |
| 384x216   | Y  |
| 480x360   | N  |
| 512x288   | Y  |
| 512x384   | Y  |
| 640x360   | Y  |
| 640x480   | Y  |
| 704x396   | N  |
| 704x480   | N  |
| 720x480   | N  |
| 768x432   | Y  |
| 768x576   | Y  |
| 800x600   | N  |
| 832x468   | N  |
| 896x504   | Y  |
| 896x672   | Y  |
| 960x720   | N  |
| 1024x576  | Y  |
| 1024x768  | Y  |
| 1152x648  | Y  |
| 1152x864  | Y  |
| 1280x720  | Y  |
| 1280x960  | Y  |
| 1408x792  | Y  |
| 1408x1056 | Y  |
| 1440x810  | N  |
| 1440x1080 | N  |
| 1536x864  | Y  |
| 1920x1080 | Y  |

**Comment by rainman74** [comment]
@rigaya The fault lies with the SDK, I just tried it with the sample app and there are limitations here that were not mentioned.

![image](https://user-images.githubusercontent.com/16306963/217500150-d043936d-ef78-4813-ad02-5184bc46ffca.png)

**Comment by Alex-Balay** [comment]
> The fault lies with the SDK

No, try setting the output resolution to 2x height of the input.

VideoEffectsApp.exe --in_file=000000244.png --out_file=000000244-1.png --effect=SuperRes --resolution=1152 --mode=1 --show

where 000000244.png is 720x576

**Comment by rainman74** [comment]
> 

@Alex-Balay oh shit, I had overlooked that, you're right! 

With the SDK it works. So the error lies with NVEnc :-(

![image](https://user-images.githubusercontent.com/16306963/217540507-c9a6b7bc-4f3f-4282-b3a8-6e59b59a4e87.png)

**Comment by rainman74** [comment]
![image](https://user-images.githubusercontent.com/16306963/217626350-7917e039-4668-425f-95f2-1de555c1200e.png)

**Comment by rigaya** [comment]
[NVEnc 7.17](https://github.com/rigaya/NVEnc/releases/tag/7.17) should input width which cannot be divided by 128.

What I changed is very simple...

MAXINE-VFX-SDK used NvCVImage as filter input and it's memory can be allocated in 2 ways, one ways is to use NvCVImage C++ constructer and another is to use NvCVImage_Alloc function.

[NVEnc 7.17](https://github.com/rigaya/NVEnc/releases/tag/7.17) switches to use NvCVImage_Alloc function instead of C++ constructer as same as in the sample code, and that seems to avoid the error.

I was successfully able to resize 720x480 → 1920x1080.

![image](https://user-images.githubusercontent.com/815947/217818249-f2900d8b-62b2-4545-95d7-bf1c251aa449.png)

**Comment by rainman74** [comment]
@rigaya Thank you! :-)
