### ISSUE TITLE
Colour correction 

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#460]
Hello,

I want to check if it is possible to implement colour correction?

I see that there is a tweak option but that one doesnt allow me to change the colours to adjust the white balance.

Is it possible to implement colour correction ?

**Comment by rigaya** [comment]
I'm sorry but I'm not able to get what exactly is "color correction", as I thought color correction is something to adjust brightness, contrast, gamma and saturation, just like --vpp-tweak does.

Are there filter in ffmpeg which I can get hint of?

**Comment by quamt** [comment]
I think this one might be one option to do it.

Curves
https://ffmpeg.org/ffmpeg-filters.html#toc-curves-1

**Comment by rigaya** [comment]
Thank you for letting me know the filter. I've gone through the Curves filter, it seems like the actual processing can be returned by 1D curve interpolation and simple LUT, so I think I'll be able to implement it.

I cannot say when I can take time, but I'll try adding it in the near future.

**Comment by quamt** [comment]
Sure, no rush :-)
Thank you.

**Comment by rigaya** [comment]
[NVEnc 7.18](https://github.com/rigaya/NVEnc/releases/tag/7.18) adds [--vpp-curves](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-curves-param1value1param2value2) which enables color adjustment.

Please note that not all options in the original curves filter is supported.

**Comment by quamt** [comment]
Thank you.

I will test it. Will report back.

**Comment by quamt** [comment]
Thank you again.
Works great.
If any issues Ill report it, but so far all good.
