### ISSUE TITLE
preserve the film grain and custom keyframes?

### ISSUE THREAD

**Issue by Schmaenks** [rigaya/NVEnc#461]
I use AV1 NVEncC.

Is there a command line to preserve the film grain?

Even with the best settings, the codec smooths everything too much for me. Especially movies with film grain look soft in places.
Especially clouds, walls, smoke, smooth objects.
Examples - Sucker Punch, Black Hawk Down etc.
With x265 you can keep the grain well by optimizations.

And command lines like x265´s --- keyint=24:open-gop=0 --- would be nice.

Would like to switch because the speed advantage is enormous.

SP_Original Blu Ray
https://ibb.co/b5KHcK4

SP_x265_encode
https://ibb.co/r6y26K7

SP_AV1_encode
https://ibb.co/0CtDGNY

**Comment by rigaya** [comment]
Unfortunately, there is no option in this app to preserve film grain, and no option for ```open-gop``` either.

For ```keyint```, please try for [--gop-len](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--gop-len-int).

**Comment by Schmaenks** [comment]
Tried --gop-len 24
Degrades the image quality.

Will stay with x265 (even if it takes a lot longer with cpu encoding).
I just don't get the quality I want with AV1.
