### ISSUE TITLE
nppi64_10.dll in resizing algorithm

### ISSUE THREAD

**Issue by euan-droid** [rigaya/NVEnc#463]
Hello, rigaya!
Thank you for your amazing work!
New resizing algorithms, such as "super", require nppi64_10.dll and such. Links you provided [NPP library (https://developer.nvidia.com/npp)](https://developer.nvidia.com/npp) and [Video Effect models and runtime dependencies (https://www.nvidia.com/broadcast-sdk-resources)](https://www.nvidia.com/broadcast-sdk-resources) deliver nppi64_12.dll and nppi64_11.dll (and such) respectively (is it CUDA version, idk?) at the time. Renaming won't help, NVEncC either could'n see "...11.dll" and "...12.dll" files, or just returnes nothing when I rename them to "...10.dll". I found "...10.dll" files in your old post: [CUDA 10.1 - nppc64_101.dll nppi64_101.dll needed](https://github.com/rigaya/NVEnc/issues/110). These work fine, but... :[

**Comment by rigaya** [comment]
Runtime required for NPP library algorithms (```nn```, ```npp_linear```, ```cubic```, ```super```, and ```lanczos```) and nvvfx algorithm (```nvvfx-superres```) is different, so should not be mixed up.

Current Windows x64 binary is build against CUDA 10.1 and so it requires NPP library (nppc64_10.dll, nppif64_10.dll and nppig64_10.dll) for CUDA 10.1 to run ```nn```, ```npp_linear```, ```cubic```, ```super```, and ```lanczos```. It is actually listed as dependencies. Renaming should not work and you'll need dlls from the [link](https://drive.google.com/folderview?id=0BzA4dIFteM2dS1ZUT1FjTnF3Q0E&usp=sharing).

![image](https://user-images.githubusercontent.com/815947/217501494-4e69106f-474a-4657-a009-c45a8fd4fe79.png)

```nvvfx-superres``` is another thing and has different modules required, requires install of  Video Effect models and runtime dependencies.

**Comment by Alex-Balay** [comment]
> Renaming should not work

It works )

![image](https://user-images.githubusercontent.com/124720358/217574464-c3ef2b73-1fa6-4eb4-8322-5d5cce407a9c.png)
![image](https://user-images.githubusercontent.com/124720358/217574760-5151b33c-9975-4760-8705-236ff2ebfb3e.png)

np*10.dll  are renamed from  npp*12.dll

Current CUDA Toolkit is v12, could you build x64 binary against it?

**Comment by rigaya** [comment]
I don't recommend renaming as I'm not sure what happens.

The problem for new CUDA version is that it requires driver update. NVEncC is built intentionally against old CUDA to support old drivers possible, as NVEncC does not requires new features in CUDA 11 or 12 (no reason to update CUDA version).

**Comment by euan-droid** [comment]
@Alex-Balay lucky you! Renaming does not work for me.
@rigaya thank you very much for explanation! Everything is clear now! Will use CUDA 10 libraries!
