### ISSUE TITLE
crop as first

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#465]
On conversion the crop filter is set after colorspace in the order of vpp-filters. That greatly reduces the speed!
I'm using colorspace with lut3d for HLG transcoding.

crop is not a vpp filter but a NVIDIA nvdec feature. (cuvid in ffmpeg)
Please put it first in the filter chain. So we don't convert parts that not be used after cropping.

**Comment by fzold** [comment]
No, GPU utilization is lower.
I'm using resizing 4k to 1080p, because most UHDs have not that sharpness or are upscaled (CGI has 2k). So I get  about 200fps on my Dell notebook.

Small resizing to 70mm format looks much better on tv:
```
-i "movie.uhd.mkv" ^
--vpp-colorspace matrix=bt2020nc:bt2020nc,lut3d=1000nit.cube,lut3d_interp=tetrahedral ^
--crop 124,264,124,264 --output-res 1920x1080 --vpp-pad 0,104,0,104 ^
```
Because of working NVIDIA hardware I never use --avsw. 
One question: Does it save the chromaloc 2 in lut3d conversion?

**Comment by rigaya** [comment]
If VE(=Encoder) utilization is near 100%, it is difficult to get significantly higher performance.

> Does it save the chromaloc 2 in lut3d conversion?

No, ```--chromaloc``` is only an option to add chromaloc flag in the output bitstream.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.

**Comment by fzold** [comment]
thanks.
