### ISSUE TITLE
--fps option ignored

### ISSUE THREAD

**Issue by kliffgomel** [rigaya/NVEnc#466]
In the following example, the option --fps is not used.
There is also something wrong with the --level option. If the value is 4.0, it works, but is not used. Values of 4 or 4.1 result in an error.

d:_out>d:\SOFT\NVEncC\NVEncC64.exe -i "d:_out\title_t00.mkv" -o e:_out\Malboro.mkv --avhw --fps 24000/1001 -c hevc --profile main10 --level 4.0 --output-depth 10 --sar 1:1 --vbr 8000 --preset quality --multipass 2pass-full --max-bitrate 12000 --vbv-bufsize 24000 --qp-init 18:18:18 --gop-len 240 --lookahead 32 --strict-gop --bframes 4 --ref 5 --mv-precision Q-pel --aq --aq-temporal --bref-mode middle --chromaloc 0 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange tv --audio-copy 4 --audio-metadata 1?clear --audio-disposition 1?default --audio-source d:_out\rus.m4a --sub-copy --chapter-copy --avsync cfr --input-format matroska --output-format matroska

**avcuvid: Unknown input option: framerate=24000/1001, ignored.**
NVEncC (x64) 7.18 (r2465) by rigaya, Feb 13 2023 12:40:13 (VC 1929/Win)
OS Version     Windows 10 x64 (19045) [UTF-8]
CPU            AMD Ryzen 5 3600X 6-Core Processor [4.39GHz] (6C/12T)
GPU            #0: NVIDIA GeForce GTX 1660 (1408 cores, 1830 MHz)[PCIe3x16][528.49]
NVENC / CUDA   NVENC API 12.0, CUDA 12.0, schedule mode: auto
Input Buffers  CUDA, 45 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
               avcodec: aac
AVSync         vfr
Vpp Filters    cspconv(nv12 -> p010)
Output Info    **H.265/HEVC main10 @ Level auto**
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc, dts, ac3, aac, subtitle#1, subtitle#2,
                subtitle#3, subtitle#4, chap => matroska
Encoder Preset quality
Rate Control   VBR
Multipass      2pass-full
Bitrate        8000 kbps (Max: 12000 kbps)
Target Quality auto
Initial QP     I:18  P:18  B:18
QP Offset      cb:0  cr:0
VBV buf size   24000 kbit
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       4 frames [ref mode: middle]
Ref frames     5 frames, MultiRef L0:auto L1:auto
AQ             on
CU max / min   auto / auto
VUI            matrix:bt709,colorprim:bt709,transfer:bt709,range:limited,chromaloc:left
Others         mv:Q-pel

**Comment by rigaya** [comment]
--fps is only for inputs which does not have framerate information in the container, will not work for mkv format inputs.

Please check for the list available for [--level](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--level-string), ```--level 4``` should work fine.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
