### ISSUE TITLE
--vpp-pad and --vpp-overlay encoding priority

### ISSUE THREAD

**Issue by ysnist** [rigaya/NVEnc#467]
I use `--vpp-pad` to add a black bar to my `1920x800` videos to make them `1920x1080`. But I also use `--vpp-overlay` to add a logo to my movies. The problem is that the logo is not in the position I want because the logo is added first and then the black bar is added. If there is a sorting priority between filters, how can I implement it. Can I add the black bar first and then apply the other filters according to the new resolution?

**Comment by rigaya** [comment]
Filtering on NVEncC is in fixed order and cannot be changed.

I might change the order of ```--vpp-overlay``` and ```--vpp-pad``` in the future release.

**Comment by ysnist** [comment]
Actually just adding sorting property for `--vpp-pad` can solve the whole problem
Looking forward to the new version
Thank you so much.
