### ISSUE TITLE
NVPlay - Recommendation

### ISSUE THREAD

**Issue by ysnist** [rigaya/NVEnc#469]
I know you are in love with your project, so are you thinking of making nvplay like ffplay is? I think it would be very useful... As you are aware there are hundreds of filters and encode options...

`nvplay.exe -i source.mp4 --codec h264 --preset p4.....`

**Comment by rigaya** [comment]
The same can be done using ffplay by command line below fro example.

```
NVEncC64.exe -i input --audio-codec aac -f mpegts -o - | ffplay.exe -
```
