### ISSUE TITLE
[Enhancement] Please Add new features from Video Effects SDK

### ISSUE THREAD

**Issue by Wontell** [rigaya/NVEnc#472]
Hello,
Thank you for all the hard work done on the codec and implementation of Video Effects SDK.

Nvidia added [new?] a number of options [beta] that look like useful for video encoding, can you please consider adding them?

1] **Encoder Artifact Reduction (Beta)**, which reduces the blocking and noisy artifacts that are produced from encoding while preserving the details of the original video.
The ArtifactReduction effect has the following modes:

    Strength 0, which applies a weak effect.
    Strength 1, which applies a strong effect.

2] **Upscale (Beta),** which is a fast and light-weight method to upscale for an input video and sharpen the resulting output.

This filter can optionally be pipelined with encoder artifact reduction to enhance the scale while reducing the video artifacts.

3] I see that Super Resolution is already implemented: nvvfx-superres 

https://docs.nvidia.com/deeplearning/maxine/vfx-sdk-system-guide/index.html

Best Regards

**Comment by quamt** [comment]
I think they already all implementent 
https://github.com/rigaya/NVEnc/releases/tag/7.15

**Comment by rigaya** [comment]
@quamt  Thank you. Yes, they are already added to vpp filters.

Please have a try with
- [--vpp-nvvfx-denoise](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-nvvfx-denoise-param1value1param2value2)
-  [--vpp-nvvfx-artifact-reduction](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-nvvfx-artifact-reduction-param1value1param2value2)
- [--vpp-resize](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-resize-string-or-param1value1param2value2) nvvfx-superres

"Upscale" is not added as we already have Super Resolution.

**Comment by quamt** [comment]
@rigaya 
Is that Upscale (Beta) different from the super resolution?
Comparable with Intel internal upscaler?
Or still AI based?

**Comment by rigaya** [comment]
I don't know anything more than the documents, but it seems more focused on performance, as it mentions "light weight".

However, super resolution was also able to achieve high performance, so I decided to just skip upscale filter for simplification.

**Comment by rigaya** [comment]
> in your settings page says that --vpp-nvvfx-artifact-reduction and --vpp-nvvfx-denoise limited to 1080p?

It is noted on the following link.
https://github.com/NVIDIA/MAXINE-VFX-SDK

> The Artifact Reduction feature supports between 90p to 1080p as input resolutions.
> The Super Resolution feature supports between 90p to 2160p as input resolutions.
> The Video Noise Removal feature supports between 80p to 1080p as input resolutions.
