### ISSUE TITLE
[BUG] Encoder asks for nppc64_10.dll, while current/latest version is nppc64_12.dll

### ISSUE THREAD

**Issue by Wontell** [rigaya/NVEnc#473]
Hello,
Current cuda package comes with version 12 of NPP files.

P.S. As temp measure I tried renaming just the nppc64_12.dll to nppc64_10.dll, didn't helped
I renamed all NPP files from 12 to 10 and so far it encodes fine, no idea if it actually works but at least it started to encode.

Regards

**Comment by rigaya** [comment]
I have uploaded archive containing these dlls [here](https://drive.google.com/folderview?id=0BzA4dIFteM2dS1ZUT1FjTnF3Q0E&usp=sharing)(npp64_10_dll.zip) if you need.

NVEncC is built intentionally against old CUDA 10 to support old drivers possible, as NVEncC does not requires new features in CUDA 11 or 12 (no reason to update CUDA version).

**Comment by Wontell** [comment]
> I already have uploaded archive containing these dlls [here](https://drive.google.com/folderview?id=0BzA4dIFteM2dS1ZUT1FjTnF3Q0E&usp=sharing)(npp64_10_dll.zip) if you need.
> 
> This is nothing like a bug, as NVEncC is built intentionally against old CUDA 10 to support old drivers possible, as NVEncC does not requires new features in CUDA 11 or 12 (no reason to update CUDA version).

Thank you for the link.
Is it possible that updated version is faster on rtx4XXX cards or it has something needed for these cards to work properly?

**Comment by rigaya** [comment]
>  Is it possible that updated version is faster on rtx4XXX cards or it has something needed for these cards to work properly?

I’m not sure with the performance difference, but generally it will require rebuild with CUDA 12. However, I don’t think NVEncC can be built with CUDA12.

Renaming dlls might work but it might cause unexpected reusults.

**Comment by rigaya** [comment]
I have added the [download link for npp dlls](https://github.com/rigaya/NVEnc/releases/tag/7.00) (npp64_10_dll_7zip.7z) in the documents for [--vpp-resize](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-resize-string-or-param1value1param2value2) and [--vpp-gauss](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-gauss-int) so you need not to look around for the dlls.

**Comment by rigaya** [comment]
I'll close this issue, as the question has been answered and the documents have been improved.
