### ISSUE TITLE
4090 Dual Encoders Always Show Exact 50% Utilization Each

### ISSUE THREAD

**Issue by Wontell** [rigaya/NVEnc#474]
Hello,
How are you doing everybody?

So im encoding 4K BluRay Remuxes into HEVC 12mb or AV1 10MB.
Before I had 3090 and 3060, both cards have single encoder and same speed [actually for some unknown reason 3060 encodes video tad faster than 3090]
Now with 4090, the card has dual encoders.
What i see in HWNFO is 50-51% utilization per encoder.

This is form encode info:
[10.1%] 18290 frames: 47.94 fps, 12783 kb/s, remain 0:56:29, GPU 17%, VE 50%, VD 6%, est out size 11487.7MB
[10.1%] 18321 frames: 47.92 fps, 12786 kb/s, remain 0:56:30, GPU 17%, VE 50%, VD 5%, est out size 11490.0MB

Is there anything that can be done to speed up the encode? 
When i do P7 4K encode im averaging 45FPS, when I do P5 4K im averaging 108FPS, and in both cases the encoders do 50-51% utilization each.
If the encoders could work at full speed i can almost double the encode speed.

I tried opening two FastFlix instances and do 2 encodes, and on AV1 4K P5 it did on average 80FPS per video [so in theory its better to encode two videos than one]

Also I find it strange that both encoders work in tandem but only 50% each, why not use one to 100% and leave the second one asleep or use it for second encode?

Regards

**Comment by rigaya** [comment]
Current NVENC SDK 12.0 does not provide method to select or handle the 2 encoders.

On the documents on the link below, it is said that the SDK 12.1 in the furture might come with “improved flexibility with multiple encoders”.
https://www.nvidia.com/en-us/on-demand/session/gtcfall22-A41806/

**Comment by rigaya** [comment]
The [--split-enc](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--split-enc-string) switch will allow to use the dual encoders, added in NVEnc 7.26.
