### ISSUE TITLE
Strategy adopeted for Auto resizer 

### ISSUE THREAD

**Issue by dan64** [rigaya/NVEnc#475]
Hello Rigaya,

Could you explain the strategy used by NVEnc to select the resizer to be used when is used the "auto" resizer option ?

Thanks.

**Comment by rigaya** [comment]
If using avhw reader and none of below is used, then cuvid resizer will be used.
- any vpp filter
- crop
- vpp-deinterlace bob
- interlaced encoding

Else, spline36 resize will be used.

**Comment by rigaya** [comment]
I'll close this issue, as the question has been answered.
