### ISSUE TITLE
Blu-ray compatibility with authoring apps

### ISSUE THREAD

**Issue by AlekseyKolesnikov** [rigaya/NVEnc#476]
Hello!

I checked the command line provided in the https://github.com/rigaya/NVEnc/issues/424 with KITe and it says:

Field value more then must be by BD specification
Field name: Numbers of fields in GOP
Field value: 7550
Maximum value: 24
GOP number: 1
NameValuesStr: video_format = 6 (1080p), frame_rate = 2 (24 Hz), bit_rate = 30000000

ffmpeg sees I-frames every 24th frame, but KITe sees only the first one

I noticed that ffmpeg and KITe see different frame sizes, except the first one:
```
KITe:   832, 140, 129, 128, ...
ffmpeg: 832, 128, 129, 129, ...
```
ffmpeg log: https://blu-disc.net/test/test.csv
KITe MOMReader screenshot: https://blu-disc.net/test/test_264_frame_list.png

PS: Panasonic verifier says: slice_type shall be set to 7, 5 or 6. But actually 2

**Comment by rigaya** [comment]
I’m not sure but the the KITe is not being able to search the key frame as expected, as ffmpeg is able to see the actual key frame inserted every 24 frames.

**Comment by AlekseyKolesnikov** [comment]
The problem is that Scenarist does not see keyframes as well. And chapter searching issue mentioned by bbcby in https://github.com/rigaya/NVEnc/issues/424 means the same - keyframes are not visible by player.

**Comment by rigaya** [comment]
As same as #424, I find it difficult to improve further.
