### ISSUE TITLE
Multiple audio streams encoding

### ISSUE THREAD

**Issue by Eduard90** [rigaya/NVEnc#478]
Hello!

I like NVEnc software. NVEnc faster and provide better quality than ffmpeg.
But I have question about videos (mkv, h264) with multiple audio streams (10 or more) - I think one thread for encode 10 audio streams is not enough.

Hardware & software:

- Server with 2xCPU Xeon 2695v4
- 192GB RAM
- NVIDIA RTX A2000 (6GB)
- Linux

Input video:
- mkv, h264, 1920x1080, video bitrate: 12000kbps, 10 audio streams (with bitrate ~192kbps)

Output video (I need):
- mp4, h264, 240p, video bitrate: 600kbps, 10 audio streams (codec AAC, bitrate 192kbps)

When I tried to encode this video file (with all audio streams to AAC 192kbps) to 240p I got (speed) only ~150fps, encoder util: 10%, decoder util: 20%, CPU (one core) util: 100% .
But if I remove all audio streams from the file (or leave 1-2 audio streams) and run nvencc I get 600fps, encoder util: 100%, decoder util: 100% .
If I leave 3 audio streams in video - I get performance ~500fps.

Then I found the option ``--thread-audio`` in source code. I tried ``--thread-audio 2`` and I got +25fps (175fps) and two CPU cores util (100% and ~50%). And ~590fps with 3 audio streams (instead 500fps without this arguments).
It's very good :-)

What do you think about this case? Can you add separate threads (or thread pool) for parallel encoding audio streams, maybe?

Regards

**Comment by Eduard90** [comment]
I changed CPU Xeon 2695v4@2.10GHz -> Xeon 2690v4@2.60GHz and got 200fps (instead 175fps) on video with 10 audio streams

**Comment by Eduard90** [comment]
I have changed CPU Xeon 2695v4 @ 2.10GHz -> Xeon 2690v4 @ 2.60GHz and got 200fps (instead 175fps) on video with 10 audio streams

**Comment by rigaya** [comment]
Yes, I think in your case encode speed is limited by audio encoding on the CPU side.

I think I'll be able to change the code to create threads for each audio streams.

However, I must say that it might take time, as I need to work on bug ( #479 ) fix of NVEnc 7.22 first.

**Comment by rigaya** [comment]
I have attached the test build which can create threads for each audio streams by ```--thread-audio 3```. The mode number is "3", but 10 threads will be running if you have 10 audio streams with this mode.
[NVEncC64_7.25beta1.exe.zip](https://github.com/rigaya/NVEnc/files/11321433/NVEncC64_7.25beta1.exe.zip)

Please have a test, and would you please let me know if it can speed up your encoding?

**Comment by Eduard90** [comment]
@rigaya it works! :-) I got performance boost and 100% CPU usage.
Can you add this code to sources ? I use OS Linux (nvencc in docker in Linux) :-)

**Comment by rigaya** [comment]
Thank you for confirming, nice to hear it works fine!

Actually I had problem with Linux build. b840c9b1 should have ```--thread-audio 3``` and will be able to be build on Linux.

**Comment by rigaya** [comment]
The new [NVEnc 7.25](https://github.com/rigaya/NVEnc/releases/tag/7.25) has this audio parallel encode mode as default.
