### ISSUE TITLE
Parameter -fps is displayed as error but executed

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#480]
Parameter -fps is displayed as error but executed

`nvencc64.exe --avhw -i input.mkv -c hevc --profile main --level auto --preset quality --qvbr 28 --fps 30.000 --aq-temporal --aq-strength 0 --lookahead 32 --bref-mode middle --audio-codec ac3 --audio-bitrate 384 --sub-copy --chapter-copy -o output.mkv`

Input file is 23.98 fps!

![image](https://user-images.githubusercontent.com/16306963/233392780-cbf9c057-de88-44e5-a3a6-756271130bdb.png)

**Comment by rigaya** [comment]
> Input file is 23.98 fps!

For mkv inputs, just remove --fps option and you should be fine.

**Comment by rigaya** [comment]
NVEnc does not and will not support frame rate conversion.
