### ISSUE TITLE
No more HLG afther version 5.43

### ISSUE THREAD

**Issue by Genine-Collin** [rigaya/NVEnc#483]
@rigaya  It"s  holding me down to update to an later version because i'm losing the HLG option.
I'm using your program together with Fastflix of cdgriffith and stumbled an a problem with fastflix using the seek to option and the solution  was to update nvencc.
cdgriffit ask me kindly to report this issue to you
Normal when i'm using the command of nvenc dolby vision 8.4 it's getting the HLG option and then i add the atc-sei bt2020-10 witch works perfect
When updating to a newer one it won't work anymore 
The left image is the newer 7.22 i think all the version afther 5.40 won't work

![hlg prob](https://user-images.githubusercontent.com/99371909/234994780-9e6fa279-b7a6-46cf-846f-cbde8f26214d.png)
![hlg Prob2](https://user-images.githubusercontent.com/99371909/234994864-dcb9311d-888d-42e0-97fa-5894bcced20e.png)

**Comment by rigaya** [comment]
Would you please let me know the whole commnand line?

When using dolby vision profile 8.4, parameters below should be used (or these three can be omitted when ```--dolby-vision-profile 8.4``` is set).
```
--colorprim bt2020 --colormatrix bt2020nc --transfer arib-std-b67
```

Would you please check again if you have set these properly?

**Comment by Genine-Collin** [comment]
Sorry this is the whole command as fastflix use it's autgenerated commands
like i mention it this worked for version 5.40 but not after later versions but will do the test don't see if the  -transfer arib-std-b67 will make the change 
i'll be back afther the new encoding test and see if it makes any deferences with version 7.22

"C:\nvenc\NVEncC64.exe" --avsw --device 0 -i "C:\test.mkv" --seekto 6642.5 --video-metadata clear --metadata clear --chapter-copy -c hevc --vbr 10000 --bref-mode disabled --preset quality --tier high --lookahead 32 --aq-temporal --aq-strength 0 --level 5.1 --chromaloc auto --colorrange auto --colormatrix bt2020nc --transfer smpte2084 --colorprim bt2020 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)" --max-cll "1000,567" --output-depth 10 --multipass 2pass-full --mv-precision Auto --avsync cfr  --audio-copy 1 --audio-metadata 1?language=eng --audio-disposition 1?default   -m default_mode:infer_no_subs --preset P3 --level 5.1 --dolby-vision-rpu d:\movies\bat.bin --dolby-vision-profile 8.4 --atc-sei bt2020-10 -o "C:\fastflix-146f.mkv"

**Comment by rigaya** [comment]
[NVEnc 7.13](https://github.com/rigaya/NVEnc/releases/tag/7.13) changes behavior handling --dolby-vision-profile.

Previously --dolby-vision-profile has overwritten values of --colormatrix, --colorprim, and --transfer, but now it is the opposite due to user request. Now, --colormatrix, --colorprim, and --transfer will overwrite --dolby-vision-profile.

Therefore, you need to specify the correct values (  --colorprim bt2020 --colormatrix bt2020nc --transfer arib-std-b67) or simply omit those.

Actually, one weird thing is that NVEnc 5.40 you have mentioned even does not have --dolby-vision-profile option, it has been added in NVEnc 5.43.

**Comment by Genine-Collin** [comment]
indeed it's version 5.43 :-)  ok still encoding din't know there was any changes that i needed to do afther v5.43

**Comment by Genine-Collin** [comment]
Glad to say it work thanks for clearing it out din't know about the changes that dolbyvision broke the hlg option glad it work and that i can do futures updates simply added the  --transfer arib-std-b67 (Hybrid Log-Gamma ) 
BTW love your work and glad to see that there is an good uptodate nvenc encoder
Sorry for that false positive but your faster in fixing than I in updating :-)
![HLG test](https://user-images.githubusercontent.com/99371909/235328549-e92bf615-fa4b-40f5-83ae-b20b396156cb.jpg)
