### ISSUE TITLE
QVBR ratecontrol hits a hard bitrate limit, and no way to increase it?

### ISSUE THREAD

**Issue by Orum** [rigaya/NVEnc#486]
I'm trying to use QVBR RC for a UHD/30p encode, but it seems to be bumping into a bitrate limit, after which lowering the `--qvbr` QP will no longer increase quality.  The full command I'm using is:
`NVEncC.exe --y4m -i - -c av1 --output-depth 10 --qvbr %1 -u quality --lookahead 32 -b 7 --ref 16 --mv-precision Q-pel --aq --aq-temporal --max-temporal-layers 5 --refs-forward 4 --refs-backward 3 --colorprim bt709 --transfer bt709 --colorrange full -o "%1.mkv"`
...and when encoding, file sizes & bitrates look like this:
```
51.mkv:  6.4 MiB /  5.4 Mb/s
45.mkv: 11.3 MiB /  9.4 Mb/s
39.mkv: 19.7 MiB / 16.5 Mb/s
33.mkv: 32.2 MiB / 27.0 Mb/s
27.mkv: 35.7 MiB / 30.0 Mb/s
21.mkv: 35.6 MiB / 29.9 Mb/s
```
As you can see, it appears to be bumping into a 30 Mb/s bitrate limitation.  I thought that using the `--max-bitrate` option with a very high number (e.g. `--max-bitrate 2000000`) would eliminate the problem, but then the value given to `--qvbr` is totally ignored, and the encode will be the same size regardless of what is used there.

I've thought of some ways to work around the problem, such as giving a fake FPS value much lower than the actual FPS of the clip during the encode (and adjusting it back to the correct speed by remuxing), but this could potentially affect RC, and is inconvenient to say the least.  Is there some other way I can raise the maximum bitrate for QVBR RC without having to resort to such workarounds?

**Comment by rigaya** [comment]
I think ```--max-bitrate``` will solve the problem, and works out fine. (Win11/RTX4080/531.68 driver)

Options tested is below fro simplification.

NVEncC64.exe -c av1 --output-depth 10 --qvbr n --max-bitrate 200000 -i input -o output

Result
![image](https://user-images.githubusercontent.com/815947/236833181-ae1714db-8f88-487b-8b9d-95d5dd1d7aeb.png)

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.

**Comment by Orum** [comment]
Sorry for the late reply, but I cannot repeat this on my end.  The moment I set max-bitrate, the qvbr parameter ceases to change the output size.  For example, running:
`nvencc --y4m -i src.y4m -c av1 --output-depth 10 --qvbr 1 -o "1.mkv" --max-bitrate 2000000000`
and
`nvencc --y4m -i src.y4m -c av1 --output-depth 10 --qvbr 51 -o "51.mkv" --max-bitrate 2000000000`
results in files with identical output size:
```
1160501067      1.mkv
1160501067      51.mkv
```

Any chance this can be reopened?

**Comment by rigaya** [comment]
Too big max-bitrate seem to get unexpected result. [NVEnc 7.82](https://github.com/rigaya/NVEnc/releases/tag/7.82) adds limit to max-bitrate and can avoid the weird behavior.

**Comment by Orum** [comment]
Thanks, I'll give that a try.
