### ISSUE TITLE
QVBR Help Question

### ISSUE THREAD

**Issue by wwaag76** [rigaya/NVEnc#487]
The following comes from the help file:

 --qvbr <float>               set bitrate for QVBR mode (kbps)
                                  same as "--vbr 0 --vbr-quality <float>"

Just to be certain, the <float> value should be target quality (0-51) and not bitrate as shown.  Correct?

Thanks.

Wayne

**Comment by rigaya** [comment]
Yes, --qvbr sets target quality and not bitrate.

**Comment by wwaag76** [comment]
Does is work the same way for vce encoding?  There are 2 lines in the help file.
--qvbr <int>                 set bitrate in QVBR mode (kbps)
 --qvbr-quality <int>         set QVBR level (0 - 51)

So what is the correct way to encode at quality level 23?
--qvbr-quality 23  or --qvbr 23  ??
Sorry for my confusion.  
Thank you.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
