### ISSUE TITLE
--fps 29.97 is  Variable Frame rate 59.758 FPS ?

### ISSUE THREAD

**Issue by godmd5** [rigaya/NVEnc#488]
--codec hevc --profile main10 --fps 29.97 --output-depth 10 --tier high --preset P7 --vbr 2048 --multipass 2pass-full --audio-copy 1 --audio-stream 1?:stereo --chapter-copy --colormatrix bt2020c --transfer bt2020-10 --lookahead 32 --colorprim bt2020 --chromaloc 2 -i "C:\Users\godmd5\Documents\230429 CIGNATURE- AURORA  Focus.JIWONMoving Cam Boseong World Car Expo Opening Ceremony_cut.mp4" -o "C:\Users\godmd5\Documents\230429 CIGNATURE- AURORA  Focus.JIWONMoving Cam Boseong World Car Expo Opening Ceremony_cut (2).mp4"

file
General
Complete name                  : C:\Users\godmd5\Documents\230429 CIGNATURE- AURORA  Focus.JIWONMoving Cam Boseong World Car Expo Opening Ceremony_cut (2).mp4
Format                         : MPEG-4
Format profile                 : Base Media / Version 2
Codec ID                       : mp42 (mp42/iso2/mp41)
File size                      : 5.81 MiB
Duration                       : 10 s 945 ms
Overall bit rate               : 4 453 kb/s
Writing application            : NVEncC (x64) 7.24

Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L4@High
Codec ID                       : hev1
Codec ID/Info                  : High Efficiency Video Coding
Duration                       : 10 s 945 ms
Source duration                : 10 s 978 ms
Bit rate                       : 4 186 kb/s
Width                          : 720 pixels
Height                         : 1 280 pixels
Display aspect ratio           : 0.562
Frame rate mode                : Variable
Frame rate                     : 59.758 FPS
Minimum frame rate             : 29.970 FPS
Maximum frame rate             : 59.940 FPS
Original frame rate            : 29.970 (30000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0 (Type 2)
Bit depth                      : 10 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.076
Stream size                    : 5.46 MiB (94%)
Source stream size             : 5.48 MiB (94%)
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : BT.2020 (10-bit)
Matrix coefficients            : BT.2020 constant
mdhd_Duration                  : 10944
Codec configuration box        : hvcC

**Comment by rigaya** [comment]
--fps only framerate sets input for raw inputs, and for other input it is only a hint when the reader cannot detect the framerate of the input file. In most cases, the timestamp from the input file is used regardless of the --fps settings. Therefore, if the input file is VFR, the output will also be VFR.

NVEnc does not and will not support frame rate conversion, as mentioned in #480.

For frame rate conversion, please consider using Avisynth/VapourSynth filters.

**Comment by godmd5** [comment]
ok ,thank
