### ISSUE TITLE
UHD blu-ray compliant

### ISSUE THREAD

**Issue by lderynck** [rigaya/NVEnc#489]
Hi,
I have done many, many tests to encode with nvencc64 to have
a hevc blu-ray UHD compliant file.
In all the case, when I import wih MUIGENERATOR from scenarist UHD, I have always
the same error : 
fixed_pic_rate_general_flag in HRD parameters shall be set to 1

I have used chatGPT to search more about "how it's possible to correct that".
Do you think nvidia codecs SDK with apis can provide a hevc UHD blu-ray compliant file?
What information nvenc needs to become compliant ?
Whatever, I salute the jop you have made with nvenc, congratulations Rigaya!!

**Comment by rigaya** [comment]
I've checked through the API, but was not able to find an option to set fixed_pic_rate_general_flag.

There is another problem for UHD compliant output, seems like general_progressive_source_flag is also necessary but not set ( #348 ). Therefore, it seems to be difficult to make HEVC encoder UHD compliant.

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
