### ISSUE TITLE
--dhdr10-info copy Doesnt work

### ISSUE THREAD

**Issue by Wontell** [rigaya/NVEnc#491]
Source file is a BD HEVC REMUX with HDR10+
Using FastFlix, i enabled software Decoder and HDR10+ copy
The target file doesn't have any HDR10+ metdata

Tested again with hardware decoder, same result
Tested without Crop just in case, same result.

Encode is HEVC to AV1 10Mb/s, using 4090

Original file
![image](https://user-images.githubusercontent.com/36778216/236698052-f6ff0125-da7c-42c1-a157-3aa5f0c1da47.png)

from the log file:
Dynamic HDR10  copy
Input Info avsw

Result:
![image](https://user-images.githubusercontent.com/36778216/236698099-c887db65-3fdf-4596-b0e3-aab97f9c20ec.png)

EDIT: did more testing, the option works fine if the target is HEVC, if the target is AV1 it doesn't work.
It doesn't even work the old way when you extract metadata with hdr10plus_tool.exe

**Comment by rigaya** [comment]
NVEnc 7.59 has added support for AV1 encoding to --dhdr10-info, so the issue should has been fixed.
