### ISSUE TITLE
top/bottom field first

### ISSUE THREAD

**Issue by Discograp** [rigaya/NVEnc#492]
when specifying - hardware encoder or software encoder = top/bottom field first

then different software reports different errors

Why?

**Comment by rigaya** [comment]
Sorry, but there is too little information here, and I'm not able to understand what is mentioned here.

**Comment by Discograp** [comment]
Nvidia graphics cards can't deinterlace properly?

using fields? = top/bottom field first or progressive type scan = with 'BoB'

**Comment by Discograp** [comment]
Thanks for the answer

Where can I read info about this, Nvidia's errors?

my GPU 3060-12.

**Comment by godmd5** [comment]
you can run command --check-features 

#0: NVIDIA GeForce GTX 1060 6GB (1280 cores, 1759 MHz)[PCIe2x16][531.29]
NVEnc features
Codec: H.264/AVC
Encoder Engines           1
Max Bframes               4
B Ref Mode                3 (each + only middle)
RC Modes                  63 (CQP, CBR, CBRHQ, VBR, VBRHQ)
Field Encoding            1 (field mode)                 <-here
MonoChrome                no
FMO                       no
Quater-Pel MV             yes
B Direct Mode             yes
CABAC                     yes
Adaptive Transform        yes
Max Temporal Layers       4
Hierarchial P Frames      yes
Hierarchial B Frames      yes
Max Level                 62 (6.2)
Min Level                 10 (1)
4:4:4                     yes
Min Width                 33
Max Width                 4096
Min Height                17
Max Height                4096
Multiple Refs             no
Max LTR Frames            8
Dynamic Resolution Change yes
Dynamic Bitrate Change    yes
Forced constant QP        yes
Dynamic RC Mode Change    no
Subframe Readback         yes
Constrained Encoding      yes
Intra Refresh             yes
Custom VBV Bufsize        yes
Dynamic Slice Mode        yes
Ref Pic Invalidiation     yes
PreProcess                no
Async Encoding            yes
Max MBs                   65536
Lossless                  yes
SAO                       no
Me Only Mode              1 (I,P frames)
Lookahead                 yes
AQ (temporal)             yes
Weighted Prediction       yes
10bit depth               no
==============
#0: NVIDIA GeForce RTX 4070 (5888 cores, 2475 MHz)[PCIe2x16][531.61]
NVEnc features
Codec: H.264/AVC
Encoder Engines           1
Max Bframes               4
B Ref Mode                3 (each + only middle)
RC Modes                  63 (CQP, CBR, CBRHQ, VBR, VBRHQ)
Field Encoding            0 (no)  <---no here
MonoChrome                no
FMO                       no
Quater-Pel MV             yes
B Direct Mode             yes
CABAC                     yes
Adaptive Transform        yes
Max Temporal Layers       4
Hierarchial P Frames      yes
Hierarchial B Frames      yes
Max Level                 62 (6.2)
Min Level                 10 (1)
4:4:4                     yes
Min Width                 145
Max Width                 4096
Min Height                49
Max Height                4096
Multiple Refs             yes
Max LTR Frames            8
Dynamic Resolution Change yes
Dynamic Bitrate Change    yes
Forced constant QP        yes
Dynamic RC Mode Change    no
Subframe Readback         yes
Constrained Encoding      yes
Intra Refresh             yes
Custom VBV Bufsize        yes
Dynamic Slice Mode        yes
Ref Pic Invalidiation     yes
PreProcess                no
Async Encoding            yes
Max MBs                   65536
Lossless                  yes
SAO                       no
Me Only Mode              1 (I,P frames)
Lookahead                 yes
AQ (temporal)             yes
Weighted Prediction       yes
10bit depth               no

**Comment by Discograp** [comment]
OMG ! Thanks!

**Comment by Discograp** [comment]
Please ! How to enter this command?

![123](https://github.com/rigaya/NVEnc/assets/95682410/499ae187-4340-4b65-99c8-8e94da8eeb5c)

**Comment by Discograp** [comment]
very weird

deinterlacing - H.265 - video speeds up and color is distorted
deinterlacing - H.264 - everything is fine, color adds HDR

**Comment by godmd5** [comment]
how to you deinterlacing, use -tff + vpp ? you can try staxrip "qtgmc" deinterlace, 8bit color output 
https://github.com/staxrip/staxrip

**Comment by godmd5** [comment]
NVEncC64.exe --check-features

**Comment by Discograp** [comment]
> how to you deinterlacing, use -tff + vpp ? you can try staxrip "qtgmc" deinterlace, 8bit color output https://github.com/staxrip/staxrip

(v.326) Topaz Video Enhance with fake AI

deinterlacing footage and upscale to HD - H.265 - video speeds up and color is distorted < FHD or upscale(720*480i)x2 with (default)Dione DV x2 fps

deinterlacing footage and upscale to HD - H.264 - everything is fine, color adds HDR < FHD or upscale(720*480i)x2 with (default)Dione DV x2 fps

**Comment by godmd5** [comment]
this is topaz video ai Problem !
if you need deinterlace ,use staxrip or ripbot264 is bestest, if you need ai upscale ,deinterlace file first and use(finetune or arterus) and the prores output 
,topaz dv deinterlace is only deinterlace and fake ai upscale, and color is not change ,not have HDR!
HERE is for "nvenc"!

**Comment by Discograp** [comment]
for me

"deinterlace" - mpeg2/4 or QSVEnc264 or ProRes(Standard/Normal)
resize/upscale+"deinterlace"= Nvidia better < new RTX VSR tech. (Topaz Video Enhance)
