### ISSUE TITLE
--sub-source with --trim did not sync

### ISSUE THREAD

**Issue by patpatqu** [rigaya/NVEnc#493]
When I included --sub-source option together with the --trim option, the subtitle of the outfile is out of sync. The arguments I used are:-

             --sub-source "sub_file.srt":disposition=default;metadata=language=eng --trim 154:0

Frame rate is 23.976 and I extracted the output files SRT and noticed that 9 milliseconds instead of 154 frames worth of time had been subtracted from the original time.

ORIGINAL:

     1
     00:00:01,697 --> 00:00:08,530

     2
     00:00:33,250 --> 00:00:34,556
     Wait!

     3
     00:00:34,643 --> 00:00:38,342
     Wait, just wait.

OUTPUT:

     1
     00:00:33,241 --> 00:00:34,547
     Wait!

     2
     00:00:34,634 --> 00:00:38,333
     Wait, just wait.

     3
     00:00:38,420 --> 00:00:41,249
     Hell is where you'll go
     if you do this, ma'am.

**Comment by rigaya** [comment]
--audio-source/--sub-source with --trim will not work properly. I'll add warning message for this in the future.

To apply --trim to the subtitle, you can first mux the subtitle track and then encode.

**Comment by rigaya** [comment]
I’ll close the issue as the topic has been answered.
