### ISSUE TITLE
Have an GUI software for NVEnc ?

### ISSUE THREAD

**Issue by Augusto7743** [rigaya/NVEnc#494]
Hello.
Have an converter GUI for NVEnc available ?

Thanks for reading my topic.

**Comment by bitspyer** [comment]
Try Hybrid 
It's a GUI for several Encoders.

**Comment by godmd5** [comment]
staxrip ,CudaCoder ,FastFlix

**Comment by Discograp** [comment]
modified = vapoursynth - Hybrid software - (old)avisynth

latest = vapour/avisynth - StaxRip software

**Comment by waeart** [comment]
FastFlix is easy.

**Comment by Augusto7743** [comment]
Thanks for all replies.
OS is Linux.
Hybrid and FastFlix have an GUI simple ...
Only tested FastFlix using NVENCC having errors in some files being xvid+mp3 in avi.
FastFlix running in an monitor 720P not have space to show all options in main window.
Have an nice next week.

**Comment by Discograp** [comment]
> Thanks for all replies. OS is Linux. Hybrid and FastFlix have an GUI simple ... Only tested FastFlix using NVENCC having errors in some files being xvid+mp3 in avi. FastFlix running in an monitor 720P not have space to show all options in main window. Have an nice next week.

try it - special downloads for Linux https://www.selur.de/downloads

**Comment by rigaya** [comment]
I’ll close this issue as I must say this topic is out of scope of my project.

**Comment by Augusto7743** [comment]
Thanks Rigaya
