### ISSUE TITLE
--audio-filter volume

### ISSUE THREAD

**Issue by Damundai** [rigaya/NVEnc#495]
While using the "example" in the NVEncC_Options.en.md, I recieve an error.

I use:
--audio-filter 2?volume=-4db  (I've tried going to the positive side of volume as well...  "volume=+2.7db")

I get the error:
avout: Failed to parse filter description: Invalid argument: "volume=-4db": volume=-4db,aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=0x3
failed to initialize file reader(s).
Failed to open output file: "D:\Completed Movies\ **movie title here**.mkv"
[Parsed_volume_0 @ 000002305e1ac440] [Eval @ 0000003d01913250] Invalid chars 'b' at the end of expression '-4db'
[Parsed_volume_0 @ 000002305e1ac440] Error when evaluating the volume expression '-4db'
[AVFilterGraph @ 000002305e66d3c0] Error initializing filter 'volume' with args '-4db'

**Comment by babiulep** [comment]
I think the 'b' should be a capital... I.e.: volume=7dB

**Comment by rigaya** [comment]
Thanks you for pointing out the cause, changed 'b' to capital in the document.
