### ISSUE TITLE
What files from repository to find the command line output information when encoding?

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/NVEnc#497]
Hello, i would like to know the file/s to edit from the repository clone, where's the output information when it's encoding?

I want to edit this command line output information being shown when encoding begins.

Thanks.

**Comment by rigaya** [comment]
You mean the actual source code?

You can check the code below for log output of encoding information.
https://github.com/rigaya/NVEnc/blob/master/NVEncCore/NVEncCore.cpp#L4696

**Comment by VisionHDR** [comment]
Nevermind, i found the lines to edit :)

**Comment by VisionHDR** [comment]
> You mean the actual source code?
> 
> You can check the code below for log output of encoding information. https://github.com/rigaya/NVEnc/blob/master/NVEncCore/NVEncCore.cpp#L4696

I installed everything to compile it with Visual Studio 2019, but i get this error when i build x64 solution?

3>------ Build started: Project: NVEncC, Configuration: Debug x64 ------
3>NVEncC.cpp
\NVEnc\NVEncC\NVEncC.cpp(265,8): error C2664: 'BOOL UpdateResourceW(HANDLE,LPCWSTR,LPCWSTR,WORD,LPVOID,DWORD)': cannot convert argument 2 from 'LPSTR' to 'LPCWSTR'
\NVEnc\NVEncC\NVEncC.cpp(265,34): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\winbase.h(4070,1): message : see declaration of 'UpdateResourceW'
\NVEnc\NVEncC\NVEncC.cpp(277,30): error C2665: 'str_replace': none of the 2 overloads could convert all the argument types
\NVEnc\NVEncCore\rgy_util.h(642,13): message : could be 'std::string str_replace(std::string,const std::string &,const std::string &)'
\NVEnc\NVEncCore\rgy_util.h(607,14): message : or       'std::wstring str_replace(std::wstring,const std::wstring &,const std::wstring &)'
\NVEnc\NVEncC\NVEncC.cpp(279,49): message : while trying to match the argument list '(std::wstring, const char *const , const char *const )'
\NVEnc\NVEncC\NVEncC.cpp(277,16): error C2737: 'commandline': const object must be initialized
\NVEnc\NVEncC\NVEncC.cpp(310,12): error C3536: 'commandline': cannot be used before it is initialized
\NVEnc\NVEncC\NVEncC.cpp(310,12): error C2660: 'CreateProcessA': function does not take 9 arguments
>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\processthreadsapi.h(361,1): message : see declaration of 'CreateProcessA'
3>Done building project "NVEncC.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 3 up-to-date, 1 skipped ==========

**Comment by rigaya** [comment]
I think you need to try Configuration: DebugStatic, not Debug.
https://github.com/rigaya/NVEnc/blob/master/Build.en.md#3-build-nvenccexe--nvencauo

**Comment by rigaya** [comment]
I won't be able to help much with compilation, but you may be not properly downloaded source code, as you seem to not have dtl , cppcodec and avisynth, which has nothing to do with the edited part.

Please check again for the build instructions.
https://github.com/rigaya/NVEnc/blob/master/Build.en.md#windows

**Comment by VisionHDR** [comment]
> I won't be able to help much with compilation, but you may be not properly downloaded source code, as you seem to not have dtl , cppcodec and avisynth, which has nothing to do with the edited part.
> 
> Please check again for the build instructions. https://github.com/rigaya/NVEnc/blob/master/Build.en.md#windows

yes i figured that out :) but then when i open the project in VS 2019, i get this weird error:

error: Designtime build failed for project '\NVEnc\NVEnc\NVEnc.vcxproj', configuration 'RelStatic|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME=true and restart Visual Studio to investigate.



Happens for Debug-Static and all configurations i set.

**Comment by rigaya** [comment]
I haven’t got that kind of error, so I won’t be able to help you with that.

**Comment by VisionHDR** [comment]
> I haven’t got that kind of error, so I won’t be able to help you with that.

I see, could you compile just NvEncc64.exe for me with the command line only showing the encoding speed/remaining and the GPU info/CUDA. Nothing else? No VPP, no filters used, no functions. I can of course pay for this task. Please let me know how this can be done. Thanks!

**Comment by rigaya** [comment]
NVEncC 7.27beta1 (for Win64) is attached, which adds options to show only the encoding speed/remaining time.
[NVEncC64_7.27beta1.zip](https://github.com/rigaya/NVEnc/files/11614058/NVEncC64_7.27beta1.zip)

Please replace the original exe file, and add ``` --log-level error,core_progress=info``` to the original command line.

Please have a try and let me know if you have any problems or not. If there are no problems, it will be released later as NVEnc 7.27.

> i will pay what you need

Although donations are welcome from https://paypal.me/rigaya34589, pay for this is not required, as it didn't require a big change, and actually it didn't take much time. ( [7367669](https://github.com/rigaya/NVEnc/commit/73676692c9afb99115facd9a24ab17d32dcf42b6) )

**Comment by VisionHDR** [comment]
> NVEncC 7.27beta1 (for Win64) is attached, which adds options to show only the encoding speed/remaining time. [NVEncC64_7.27beta1.zip](https://github.com/rigaya/NVEnc/files/11614058/NVEncC64_7.27beta1.zip)
> 
> Please replace the original exe file, and add ` --log-level error,core_progress=info` to the original command line.
> 
> Please have a try and let me know if you have any problems or not. If there are no problems, it will be released later as NVEnc 7.27.
> 
> > i will pay what you need
> 
> Although donations are welcome from https://paypal.me/rigaya34589, pay for this is not needed, as it didn't require a big change, and actually it didn't take much time. ( [7367669](https://github.com/rigaya/NVEnc/commit/73676692c9afb99115facd9a24ab17d32dcf42b6) )

Hello, testing and so far it seems to work well. Thanks, you are awesome!

**Comment by VisionHDR** [comment]
> NVEncC 7.27beta1 (for Win64) is attached, which adds options to show only the encoding speed/remaining time. [NVEncC64_7.27beta1.zip](https://github.com/rigaya/NVEnc/files/11614058/NVEncC64_7.27beta1.zip)
> 
> Please replace the original exe file, and add ` --log-level error,core_progress=info` to the original command line.
> 
> Please have a try and let me know if you have any problems or not. If there are no problems, it will be released later as NVEnc 7.27.
> 
> > i will pay what you need
> 
> Although donations are welcome from https://paypal.me/rigaya34589, pay for this is not needed, as it didn't require a big change, and actually it didn't take much time. ( [7367669](https://github.com/rigaya/NVEnc/commit/73676692c9afb99115facd9a24ab17d32dcf42b6) )

You know what i would need? A way to add "Film Grain" with the GPU, a high-quality grain with different styles e.g., 35mm, 4k 35mm and so on. Are you able to implement it? If so, as i know that is indeed more work, please tell me how much would be. I always wanted to add it for some videos, even for my personal taste or to remove possible banding using few film grain in the back moving (it works for this, trust me). 

If you can add this feature, let me know. Thanks again!

**Comment by VisionHDR** [comment]
I also need the possibility to add an image logo (png) with transparency/alpha feature too.

**Comment by rigaya** [comment]
> Hello, testing and so far it seems to work well.

Nice to hear that.

> A way to add "Film Grain" 

I have no knowledge about them, so will be difficult to implement.

I recommend to use Avisynth/Vapoursynth filters for complicated filtering.

**Comment by VisionHDR** [comment]
> > Hello, testing and so far it seems to work well.
> 
> Nice to hear that.
> 
> > A way to add "Film Grain"
> 
> I have no knowledge about them, so will be difficult to implement.
> 
> I recommend to use Avisynth/Vapoursynth filters for complicated filtering.

Yes, but that would involve re-encoding the NvEncc output. Or adding it to the source before encoding, which is worse.

Is possible to combine Avisynth/Vapoursynth filters with NvEncc64? So it adds the filter when encoding? Not sure if that's actually possible.

**Comment by rigaya** [comment]
> Is possible to combine Avisynth/Vapoursynth filters with NvEncc64?

NVEncC can directly read avs/vpy files.

**Comment by VisionHDR** [comment]
> > Is possible to combine Avisynth/Vapoursynth filters with NvEncc64?
> 
> NVEncC can directly read avs/vpy files.

yes, but it works as an "input", how to read the avs/vpy filter script and also use a "file input" in the same command? Sorry maybe it's easy and i didn't know yet.

**Comment by rigaya** [comment]
When reading avs/vpy file, the actual file will be read by Avisynth/Vapoursynth file reader.

**Comment by VisionHDR** [comment]
> When reading avs/vpy file, the actual file will be read by Avisynth/Vapoursynth file reader.

Yes, you are right. I don't run the command by itself though, it runs inside a script and later in a package for windows. So it's hard sometimes to deal with a filter that inputs a file that way.

**Comment by rigaya** [comment]
The new release [NVEnc 7.27](https://github.com/rigaya/NVEnc/releases/tag/7.27) also adds only showing the encoding speed/remaining.

I'll close this issue as the initial topic has been solved.
