### ISSUE TITLE
Hls time

### ISSUE THREAD

**Issue by DarkstaIkers** [rigaya/NVEnc#499]
When I do set -m hls_time:4 video does not split at 4 seconds, it splits at 10 seconds for any changes I do below than 10.

**Comment by rigaya** [comment]
The default GOP len is 10 seconds, so the minimum split is also limited to 10 seconds.

Please try lower --gop-len, for example ```--gop-len 30```.

**Comment by DarkstaIkers** [comment]
> The default GOP len is 10 seconds, so the minimum split is also limited to 10 seconds.
> 
> Please try lower --gop-len, for example `--gop-len 30`.

So, I did set --gop-len 4 and I got this error: nvenc : **Failed to Initialize the encoder
nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)**

I can set it up til 8 only. I'd like to set it up 4. Could you check this out?

**Comment by rigaya** [comment]
The unit of --gop-len is "frames" and not "seconds", so you need not to go little like 4.

If your video is 30fps, ```--gop-len 30``` shall be 1 seconds, which will be low enough to be split in 4 seconds.

**Comment by DarkstaIkers** [comment]
> The unit of --gop-len is "frames" and not "seconds", so you need not to go little like 4.
> 
> If your video is 30fps, `--gop-len 30` shall be 1 seconds, which will be low enough to be split in 4 seconds.

Now I've got it . Thank you, rigaya.
