### ISSUE TITLE
Only 1 frame is encoded when using Amatsukaze 0.9.4.0+ and NVEnc 7.18+ together

### ISSUE THREAD

**Issue by bN2DhXKD** [rigaya/NVEnc#500]
Amatsukaze+NVEncの組み合わせで便利に使っているのですが、
最近のバージョンで、1フレームしかエンコードされない事象が発生するようになりました。
お手すきの際に見ていただけると幸いです。

1. 事象発生する組み合わせ：Amatsukaze 0.9.4.0 or later + NVEnc 7.18 or later
2. 事象発生しない組み合わせ：Amatsukaze 0.9.3.1 + NVEnc 7.17

Amatsukazeのプロファイル(1, 2共通)
- エンコーダ：NVEnc
- エンコーダ追加オプション：--codec hevc --qvbr 25 --preset quality --output-depth 10 --lookahead 32 --aq --aq-temporal --aq-strength 0 --bref-mode each --tier high --vpp-afs preset=anime,rff=true
- フィルタ設定：フィルタなし

Amatsukazeのログ抜粋：1, 2共通の部分

NVEncに渡される引数にファイル名以外の差異はなさそうです。
`AMT [info] "D:/Programs/NVEncC/NVEncC64.exe" --colorprim bt709 --transfer bt709 --colormatrix bt709 --tff --codec hevc --qvbr 25 --preset quality --output-depth 10 --lookahead 32 --aq --aq-temporal --aq-strength 0 --bref-mode each --tier high --vpp-afs preset=anime,rff=true --frames 911 -o "C:/Users/xxxx/AppData/Local/Temp/amt8132706/v0-0-0.raw" --output-format mp4 --y4m -i -
`

Amatsukazeのログ抜粋：1, 2で差異のある部分

NVEncのログ出力に差異があります。
[1.log](https://github.com/rigaya/NVEnc/files/11644826/A.log) "encoded 1 frames"となっている
[2.log](https://github.com/rigaya/NVEnc/files/11644827/B.log) "encoded 911 frames"となっている(渡された引数と一致)

他、不足している情報などありましたらお知らせください。

**Comment by rigaya** [comment]
ご報告ありがとうございます。

```--vpp-afs```で'''rff'''を使用した時に発生する問題でした。[NVEnc 7.27](https://github.com/rigaya/NVEnc/releases/tag/7.27)で修正できていると思います。

**Comment by rigaya** [comment]
無事解消できてよかったです。ご確認ありがとうございました！
