### ISSUE TITLE
Codec info ?

### ISSUE THREAD

**Issue by turbomund** [rigaya/NVEnc#501]
NVEncC (x64) 7.28 (r2570) by rigaya, Jun  7 2023 12:50:33 (VC 1929/Win)
  [NVENC API v12.1, CUDA 10.1]
 reader: raw, y4m, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]
#0: NVIDIA GeForce GTX 1070 (1920 cores, 1683 MHz)[PCIe3x16][535.98]
Avaliable Codec(s)
H.264/AVC
H.265/HEVC

check profiles ->
Failed to find codec name "H.264/AVC"

?????

**Comment by rigaya** [comment]
--check-profiles is check for audio codec.

You already have list for video codecs [here](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--profile-string).

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
