### ISSUE TITLE
VPP: AvisynthフィルターのKNLMeansCLの移植を希望します

### ISSUE THREAD

**Issue by s-andro** [rigaya/NVEnc#502]
ノイズ低減フィルターを色々試しまして
くすまず、にじまず、一定の効果が出せるのがKNLMeansCLだったのですが
Avisynthでは呼び出しのオーバーヘッドが大きいのかFPSの落ち込みが大きいのが難点です
VPPフィルターに組み込まれれば高速に処理できるのではと思います

自分で挑戦しようかと思いましたがハードルが高いようでした

**Comment by rigaya** [comment]
KNLMeansはもともと非常に重いフィルタ処理(演算量がとにかく多い)のため、fpsの落ち込みが大きいのはAvisynthの呼び出しというよりフィルタ処理自体の重さに起因する可能性が高いと思います。そのため、vppフィルタとして組み込んでも高速化が見込めるかは微妙と思います。

また、KNLMeansCLはオプションが多く、すべて実装するのは難しいと思います。d=0, channels="Y", wmode=0 固定でよろしければ、なんとか時間をかければ実装可能かもしれません。

**Comment by s-andro** [comment]
改めてGPUの状態を見ると確かに重かったのはフィルター処理のようです
電力に余裕があったのでもう少し頑張れるんじゃ？って思ってましたが、諸々の制限でもう無理なのでしょう

提示されたオプションの固定は自分はその通りに使用していたので問題ないです
検討していただきありがとうございました

**Comment by rigaya** [comment]
確認ありがとうございました。

やはりフィルター処理が重そうということで、VPPへの実装は見送りたいと思いますので、本件Closeさせていただきます。
