### ISSUE TITLE
Overlay function does not have a timing option? I need image overlay for first seconds of the video

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/NVEnc#503]
Hello, i was wondering why the overlay image function doesn't have any timing option. I just want to add an image/logo for the first 5 seconds of the video, because now it just makes it on for the entire video length. 

Is it possible to include this command for the --vpp-overlay?

Thanks a lot!

**Comment by rigaya** [comment]
> why the overlay image function doesn't have any timing option

There is not timing option for --vpp-overlay in order to simplify implementation.

--vpp-overlay can take not only image, but movie as input file.

Therefore, you can create a movie file 5 seconds logo movie file and set it as --vpp-overlay source file.
