### ISSUE TITLE
NVIDIA Superresolution

### ISSUE THREAD

**Issue by sven-pke** [rigaya/NVEnc#504]
Hi,
As far as I understand the Superreolution filter is identical to the upscale filter in NVIDIA Maxine with its strengh parameter from 0-1.
Is there a big difference with Maxine's superresolution that seems to be different, and can this filter be implemented?

Greetings

**Comment by rigaya** [comment]
--vpp-resize nvvfx-superres utilizes NVIDIA Maxine Super Resolution filter. (so it is already implemented)

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
