### ISSUE TITLE
Subtitle fonts auto retrieval for *.ASS when font in subtitle "mentioned"

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#506]
Hello,

When using the subtitle burn-in function, the fonts get auto-retrieved if it is an *.ASS subtitle.
Would it be possible to implement this for add-on subtitles, the auto-retrieval of the fonts and the addon to the newly encoded file?

Example when using the burn-in function with *.ASS subtitle:

`fontselect: (Trebuchet MS, 400, 0) -> TrebuchetMS, 0, TrebuchetMSVE
fontselect: (Arial, 700, 0) -> Arial-BoldMT, 0, Arial-BoldMT
fontselect: (Verdana, 400, 0) -> Verdana, 0, Verdana
fontselect: (Trebuchet MS, 400, 100) -> TrebuchetMS-Italic, 0, TrebuchetMS-Italic`

**Comment by rigaya** [comment]
Does "add-on subtitles" means ass included in mkv, and try to burn in by ```--vpp-subburn 1``` for example?

I think this should already work fine, I tested myself creating a mkv with ass by mkvtoolnix, and was able to get the same font related message between ```--vpp-subburn <filename>.ass``` and ```--vpp-subburn 1```.

**Comment by rigaya** [comment]
Now I think I've got what you mean. However, the font auto retrieval is done inside libass (font rendering library), so it seems to be difficult to expose this feature to use it to embed fonts.
