### ISSUE TITLE
AVS plugin

### ISSUE THREAD

**Issue by tormento** [rigaya/NVEnc#507]
I am playing with NVEnc and it's fast and awesome.

I'd like to insert it's capabilities in an AVS script.

Could you create an AVS plugin to expose its functions to the frame server?

Thank you in advance! ;)

**Comment by rigaya** [comment]
NVEnc is developed as a transcoder, it'll be difficult to make it as a AVS plugin.

Also, the performance advantage of NVEnc filter comes from the implementation of NVEnc vpp filters that it is tightly combined with decode and encode stage, which enable the frames kept in GPU, not transferring between CPU and GPU. Developing the filters as an AVS plugin would remove that advantage.

Further more, I think there exists equivalent filters to most of the features NVEnc has.

**Comment by DTL2020** [comment]
It was idea to offload most of NVenc filters to accelerator and left more CPU time to software MPEG encoder. If all Vpp filters implemented inside GPU memory as fixed filterchain - it is required only 1 upload and 1 download frame for any of used filters in filtergraph. So as simple implementation it may be single AVS filter with 1 input and 1 output and accept standard NVenc text string as params (for all active filters in the filterchain used). What is required to implement - download ready to encode frame after all Vpp processing and before hardware encoder (if possible), or somehow bypass hardware encoder and download uncompressed frame and output as data of GetFrame() AVS filter function.

**Comment by tormento** [comment]
Isn't possible to transfer whole chunks of frames (up to available memory or barsize) to reduce overhead and, perhaps, using https://github.com/keylase/nvidia-patch to have multiple frames at the same time too?

**Comment by rigaya** [comment]
I'm not bright in crating AVS plugins, so as I have mentioned earlier, I will not focus in creating avs plugins.
