### ISSUE TITLE
There's no way to choose a part of the video to encode?

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/NVEnc#508]
I think there's no way to choose a part of the video to encode? Like ffmpeg -ss ? i would like not to use ffmpeg and only use nvencc64 to do this task. Is there a way to do this with just nvencc64? Or maybe, you could implement the feature in a beta? Thank you.

**Comment by rigaya** [comment]
Please have a try with [--seek](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--seek-intintintint) and [--seekto](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--seekto-intintintint) to encode part of video.

**Comment by VisionHDR** [comment]
Awesome, i totally missed this. Thanks, it worked perfectly.
