### ISSUE TITLE
DTS audio conversion fails with v7.30

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#510]
I have tested several videos and with all of them the following error message appears towards the end of the conversion process and the video is not written correctly (there are always a few seconds missing at the end and the index - e.g. length information - is also missing).

Command line:
nvencc64.exe --avhw -i "in.mkv" -c hevc --profile main --level auto --preset quality --qvbr 28 --aq-temporal --aq-strength 0 --lookahead 32 --bref-mode middle --audio-codec ac3 --audio-bitrate 384 --sub-copy --chapter-copy -o "out.mkv"

Output with error:
avcuvid: --sub-copy/--vpp-subburn is set, but no subtitle stream found.
NVEncC (x64) 7.30 (r2572) by rigaya, Jun 24 2023 02:43:35 (VC 1929/Win)
OS Version     Windows 11 x64 (22621) [UTF-8]
CPU            11th Gen Intel Core i9-11900K @ 3.50GHz [TB: 5.33GHz] (8C/16T)
GPU            #0: NVIDIA GeForce RTX 3080 (8704 cores, 1800 MHz)[PCIe4x16][536.40]
NVENC / CUDA   NVENC API 12.1, CUDA 12.2, schedule mode: auto
Input Buffers  CUDA, 44 frames
Input Info     avcuvid: H.264/AVC, 1920x800, 25/1 fps
AVSync         vfr
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main @ Level auto
               1920x800p 1:1 25.000fps (25/1fps)
               avwriter: hevc, #1:dca/5.1(side) -> ac3/5.1(side)/384kbps,
                #2:dca/5.1(side) -> ac3/5.1(side)/384kbps => matroska
Encoder Preset quality
Rate Control   VBR
Multipass      none
Bitrate        0 kbps (Max: 11520 kbps)
Target Quality 28.00
Initial QP     I:20  P:23  B:25
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     250 frames
B frames       3 frames [ref mode: middle]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on
CU max / min   auto / auto
Others         mv:auto
avout: failed to feed the audio filtergraphs, remain 0:00:45, GPU 74%, VE 99%, VD 19%, est out size 1390.4MB
avout: failed to feed the audio filtergraph
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error FlushEncoder: 20.

encoded 133075 frames, 197.12 fps, 2053.53 kbps, 1303.07 MB
encode time 0:11:15, CPU: 0.3%, GPU: 89.9%, VE: 97.8%, VD: 22.2%, GPUClock: 1980MHz, VEClock: 1740MHz
frame type IDR   838
frame type I     838,  avgQP  22.20,  total size   41.99 MB
frame type P   37187,  avgQP  22.29,  total size  702.74 MB
frame type B   95050,  avgQP  24.27,  total size  558.35 MB

**Comment by rainman74** [comment]
Mediainfo:
General
Unique ID                      : 228399411545074098565031868919344104975 (0xABD42068B1BD7435BFB1BD21DBD5860F)
Complete name                  : in.mkv
Format                         : Matroska
Format version                 : Version 1
File size                      : 8.50 GiB
Duration                       : 1 h 28 min
Overall bit rate               : 13.7 Mb/s
Frame rate                     : 25.000 FPS
Encoded date                   : 2008-10-27 16:10:53 UTC
Writing application            : mkvmerge v2.3.0 ('Freak U') built on Sep  8 2008 18:32:16
Writing library                : libebml v0.7.7 + libmatroska v0.8.1

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.1
Format settings                : CABAC / 5 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 5 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 1 h 28 min
Bit rate                       : 10.7 Mb/s
Width                          : 1 920 pixels
Height                         : 800 pixels
Display aspect ratio           : 2.40:1
Frame rate mode                : Constant
Frame rate                     : 25.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.278
Stream size                    : 6.46 GiB (76%)
Writing library                : x264 core 65 r998M 6768543
Encoding settings              : cabac=1 / ref=5 / deblock=1:0:0 / analyse=0x3:0x113 / me=umh / subme=7 / psy_rd=1.0:0.0 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / chroma_qp_offset=-2 / threads=6 / nr=0 / decimate=1 / mbaff=0 / bframes=3 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=3 / wpredb=1 / keyint=250 / keyint_min=25 / scenecut=40(pre) / rc=2pass / bitrate=10678 / ratetol=1.0 / qcomp=0.50 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.10 / pb_ratio=1.10 / aq=1:1.00
Language                       : English
Default                        : Yes
Forced                         : No

Audio #1
ID                             : 2
Format                         : DTS
Format/Info                    : Digital Theater Systems
Codec ID                       : A_DTS
Duration                       : 1 h 28 min
Bit rate mode                  : Constant
Bit rate                       : 1 509 kb/s
Channel(s)                     : 6 channels
Channel layout                 : C L R Ls Rs LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 93.750 FPS (512 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Stream size                    : 959 MiB (11%)
Language                       : German
Default                        : Yes
Forced                         : No

Audio #2
ID                             : 3
Format                         : DTS
Format/Info                    : Digital Theater Systems
Codec ID                       : A_DTS
Duration                       : 1 h 28 min
Bit rate mode                  : Constant
Bit rate                       : 1 509 kb/s
Channel(s)                     : 6 channels
Channel layout                 : C L R Ls Rs LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 93.750 FPS (512 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossy
Stream size                    : 959 MiB (11%)
Language                       : English
Default                        : No
Forced                         : No

**Comment by rigaya** [comment]
This kind of problem is due to the input file or the filter used, will be difficult to solve without reproducing the issue.
