### ISSUE TITLE
CQP value strange

### ISSUE THREAD

**Issue by deathvenom-369** [rigaya/NVEnc#511]
v. 7.30
when ruining:
 "--avhw --input-analyze 30 --input-probesize 64M -i "/media/Test/(6).mp4" --video-metadata copy --metadata copy --chapter-copy --audio-copy -c av1 --video-tag nvenc **--cqp 66** --aq-temporal --aq-strength 8 --lookahead 30 -u P5 --colorrange auto --colormatrix auto --colorprim auto --transfer auto --chromaloc auto --chromaloc auto --max-cll copy --master-display copy -o "/temp/(6)-TdarrCacheFile-36byPvhks.mkv" 
files come out larger. Is there a scaling factor I'm missing? I have it set to 75 now and that seems to be what would normally be about 24

**Comment by rigaya** [comment]
CQP range of AV1 seems to differ from H.264/HEVC, it takes value of 0 - 255. Therefore, you may need to set a larger value comapred to the value use in H.264/HEVC.

**Comment by deathvenom-369** [comment]
ok I think I did read something to that effect for one of the software encoders. Thank you
