### ISSUE TITLE
--vpp-pad invalid parameter (but it seems to be right)? 

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/NVEnc#516]
Hi, 

I get "invalid parameter" 

Even when i use minimal options just for testing:

>nvencc64.exe -i m.mkv --vpp-pad 0:67:0:67 -o m2.mkv
--------------------------------------------------------------------------------
m2.mkv
--------------------------------------------------------------------------------
pad: Invalid parameter.

The input video has a resolution of 3840x2026 pixels.
Display aspect ratio: 1.895

It doesn't appear to be a fix for this particular video input resolution, and i tried everything. --vpp-pad always fails. Same happens for videos with similar aspect ratios (of course all are cropped, that's the reason i want to use --vpp-pad)

Any help would be appreciated.

**Comment by VisionHDR** [comment]
I had to do: 0,66,0,68.

Looks like it wasn't hitting the proper 2160.

**Comment by rigaya** [comment]
--vpp-pad requires values which are multiple of 2, as chroma has half the resolution of luma.

**Comment by VisionHDR** [comment]
Thanks!
