### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Discograp** [rigaya/NVEnc#518]
Hello! Can you add 265 main 422 10-bits?

**Comment by rigaya** [comment]
NVENC hardware does not support yuv422 encoding, so it is not able to add yuv422 encoding feature.

**Comment by Discograp** [comment]
ok - and QSVENC also does not support 422, it is strange that it is available for selection in the settings.

when encoding 10/8bit 422 = outputs 10/8bit 420

I thought it was a bug and Nvidia just forgot to add...?
