### ISSUE TITLE
 Possibility of integration NVEncC in OBS Studio

### ISSUE THREAD

**Issue by sandr1x** [rigaya/NVEnc#522]
Hi! Perhaps this question has already been asked. But why hasn't NVEncC been added to OBS Studio yet, at least as a separate plugin? I like the capabilities of NVEncC, so I would really like to process an uncompressed stream using NVEncC. We ran tests and were amazed by the results of `--vpp-nvvfx-artifact-reduction`. I even managed to stream with OBS+NGINX using NVEncC, but the main problem is that we have to process the compressed stream from OBS.
![image](https://github.com/rigaya/NVEnc/assets/113405680/5dd7d07c-aff1-4428-a718-fd4e7db19732)

In general, I don't know how to get an uncompressed stream from OBS for NVEncC, as is done in the Multiple RTMP outputs plugin. I hope you understand what I mean.

I'm using NVEncC on Windows 10

upd: Everything worked out. We used OBS Virtual Camera for video and VB-Audio Virtual Cable for audio. Media interception was carried out via ffmpeg, after which the stream was encoded via NVEnc

**Comment by sandr1x** [comment]
I found one of your answers where you said that you can grab a camera. We managed to capture OBS Virtual Camera, transcode the stream and send it to rtmp

`NVEncC64.exe --avsw --input-format dshow -i video="OBS Virtual Camera" `

**Comment by rigaya** [comment]
I’ll close this issue as I must say this topic is out of scope of my project.
