### ISSUE TITLE
FFmpeg raw output vs NVEncC raw output

### ISSUE THREAD

**Issue by dan64** [rigaya/NVEnc#524]
I'd like to use your last version 7.33, which support raw output, to write a Vapoursynth script that will allow to see the preview of NVEnC encoded video. For this purpose I wrote the following script:

--------------------------------------------------------------------------------------------------------------------
import vapoursynth as vs
from vapoursynth import core
import subprocess
import ctypes

NVEnc = r'E:\VideoTest\TestSubs\NVEncC64.exe'
ffmpeg = r'E:\VideoTest\TestSubs\ffmpeg.exe'
source_path=r'E:\VideoTest\TestSubs\TestVideo.mp4'
#Loading Plugins
core.std.LoadPlugin(path="E:/VideoTest/TestSubs/BestSource.dll") #from https://forum.doom9.org/showthread.php?t=184255 
#current color space: YUV420P8, bit depth: 8
#resolution: 1280x536, fps: 25, color matrix: 470bg, yuv luminance scale: limited, scanorder: progressive

#this clip is not not needed, just to get width and height
clip = core.bs.VideoSource(source=source_path) 
#Setting detected color matrix (470bg).
clip = core.std.SetFrameProps(clip, _Matrix=5)
#Setting color transfer info (470bg), when it is not set
clip = clip if not core.text.FrameProps(clip,'_Transfer') else core.std.SetFrameProps(clip, _Transfer=5)
#Setting color primaries info (BT.709), when it is not set
clip = clip if not core.text.FrameProps(clip,'_Primaries') else core.std.SetFrameProps(clip, _Primaries=1)
#Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
clip = core.std.SetFrameProp(clip=clip, prop="_FieldBased", intval=0) # progressive
#set output frame rate to 25fps (progressive)
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)

clip = core.std.BlankClip(clip)

w = clip.width
h = clip.height
Ysize  = w * h
Usize = w * h//4
Vsize = w * h//4
frame_len = Ysize + Usize + Vsize #YUV420

command = [ ffmpeg, '-i', source_path,'-vcodec', 'rawvideo', '-pix_fmt', 'yuv420p',  '-f', 'rawvideo', '-']
#command = [NVEnc, '--avhw','--input', source_path, '-c raw', '-output-csp yuv420', '--output-depth 8', '--output-format raw', '--output -'] 

pipe = subprocess.Popen(command, stdout = subprocess.PIPE, bufsize=100*frame_len)

def load_frame_from_pipe(n,f):
    vs_frame = f.copy() 
    try:
        for plane, size in enumerate([Ysize, Usize, Vsize]):
            ctypes.memmove(vs_frame.get_write_ptr(plane), pipe.stdout.read(size),  size)
        pipe.stdout.flush()
    except Exception as e:
        raise ValueError(repr(e))    
    return vs_frame

try:
    clip = core.std.ModifyFrame(clip, clip, load_frame_from_pipe)
except ValueError as e:
    pipe.terminate()
    print(e)

clip.set_output()

--------------------------------------------------------------------------------------------------------------------

this script is working well using ffmpeg raw output. If you comment the "command" row using ffmpeg and uncomment the "command" row using NVEnc, which should provide the same output, the preview is not working anymore. If I save the output of 2 process the generated file has the same size, so the problem is not related to the raw video produced, but in the way how the file is produced in output. 
The way used by ffmpeg is working inside Vapoursynth script, the way implemented in NVEnc not.
I hope that you will be able to fix this issue.

P.S.
The video used for the test is available here: https://filebin.net/trb7yof9h0g335e0
The script used for the test is available here: https://filebin.net/qm5ihxuwiejacumh

**Comment by rigaya** [comment]
Please check the NVEnc log, you can write it to file by "--log log.txt". I suppose NVEnc doesn't have problem here, the command line is wrong there...

```-output-csp yuv420``` → ```--output-csp yuv420```

**Comment by dan64** [comment]
You are right I forgot to add "--output-res", but the real problem is that Popen() has problem with array input. Passing to Popen() a command string generated with **' '.join(command)** , solved the problem. 
Thanks,
Dan
