### ISSUE TITLE
nvvfx-superres 4x upscale don't work for 1080p sources

### ISSUE THREAD

**Issue by valujin** [rigaya/NVEnc#526]
NVEnc version: 7.33 (x64)

Upscaling from 1080p to 2160p works.
Upscaling from 2160p to 4320p works.
Upscaling from 1080p to 4320p doesn't work.

Since MAXINE VFX SDK states support for 4x upscaling for sources up to 1080p and 2x upscaling for 2160p sources it's expected to have the ability to upscale 1080p source to 4320p.

**Comment by rigaya** [comment]
It is said in [MAXINE VFX SDK](https://github.com/NVIDIA/MAXINE-VFX-SDK) that 2160p to 4320p is not supported.

_2160p input is only supported for the following scaling factors: 4/3x (~1.33x), 1.5x and 2x._

**Comment by valujin** [comment]
2160p x2 = 4320p and it works, but 1080p x4 = 4320p don't.
<img width="707" alt="image" src="https://github.com/rigaya/NVEnc/assets/130094817/e4247240-b394-4494-9c2a-7e4707ff45d7">

**Comment by rigaya** [comment]
Yes, it is expected as it is written in the documents.

**Comment by valujin** [comment]
> Super Resolution supports the following scaling factors: 4/3x (~1.33x), 1.5x, 2x, 3x and 4x.
> The maximum output resolution for the Super Resolution feature is 4320p.

Which means that 1080p can be upscaled to 4320p, but with current version of NVEnc I can only do 2x scaling for 1080p videos, instead of allowed maximum of 4x.

> 2160p input is only supported for the following scaling factors: 4/3x (~1.33x), 1.5x and 2x

2160p to 4320p is working fine.

**Comment by rigaya** [comment]
I’m not sure but I’m not going further into nvvfx errors.
