### ISSUE TITLE
--log-level for just encoding status without error logs?

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/NVEnc#527]
Hello, I was wondering if you could add a log level for just the encoding status (nothing else) just like the new one you have added:

--log-level error,core_progress=info

But without the errors showing up. 

Something like

--log-level core_progress=info

I haven't tried this one yet since I'm heading back home and I was informed one of my apps would need this command. 

Would that work that way or maybe there's another command that can do what I need? 

Thanks!

**Comment by rigaya** [comment]
```quiet``` mode was added to [--log-level](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--log-level-param1valueparam2value) in [NVEnc 7.34](https://github.com/rigaya/NVEnc/releases/tag/7.34).

You might try ```--log-level quiet,core_progress=info``` for encoding status without error logs.

**Comment by rigaya** [comment]
I'll close the issue as it should have been improved in NVEnc 7.34.
