### ISSUE TITLE
How disable --qvbr in V7.35?

### ISSUE THREAD

**Issue by Kapiroto** [rigaya/NVEnc#528]
`Make --qvbr mode default encode mode.`
In this version 7.35, the --qvbr parameter is the default, and with that, before my encodes from H264 (1.5G) to H265 (~300MB) were always small, but now with the addition of this parameter as default there is no longer any difference in the size of the encoded file.

**Comment by rigaya** [comment]
You can switch back to previous default by adding ```--cqp 20:23:25```.

One more way is to change --qvbr value, it is ```--qvbr 25``` by default so you can use larger --qvbr values (such as ```--qvbr 30```) for smaller size.
