### ISSUE TITLE
For everyone who uses mediainfo from mediaarea.net

### ISSUE THREAD

**Issue by pwacooijmans** [rigaya/NVEnc#53]
I personally payed mediainfo to make an update to detect missing trailbits in the nvenc stream while encoding h265 with master-display settings. The issue has been fixed today in mediainfo, so watch out for the next update of mediainfo to check the nvenc streams yourself. You will see in a lot of cases the trailing bit is missing in version 4.05 AND before. Now what does this mean: the short version: less compatibility with mediaplayers/tvs. It does NOT mean your old streams will NOT play on ANY tv, it just means there ARE SOME models on which they don't. The issue is being looked at by Rigaya so nothing to worry about...but probably the first 100% compatible release will be 4.06 for hdr info.

**Comment by rigaya** [comment]
I have changed output for this in NVEnc 4.06, it should work with MediaInfo now, so I think you can just update NVEnc without changing anything about MediaInfo.

**Comment by pwacooijmans** [comment]
Awesome work thanks a lot...you have no idea how much people you just
helped. :)

Op za 2 jun. 2018 11:21 schreef rigaya <notifications@github.com>:

**Comment by pwacooijmans** [comment]
https://www.youtube.com/watch?v=uwWLAxc9WZ8
is all that I have to say about it :)
