### ISSUE TITLE
Estimation accuracy issue w/ seek parameters

### ISSUE THREAD

**Issue by eriforce** [rigaya/NVEnc#530]
Looks like skipped frames are treated as encoded in no time when using with `--seek` and `--seekto` parameters, which makes estimated remaining time and output size inaccurate. Is it possible to improve this?

Thanks.

**Comment by rigaya** [comment]
This might be improved in [NVEnc 7.39](https://github.com/rigaya/NVEnc/releases/tag/7.39).

**Comment by rigaya** [comment]
I'll close the issue as it should have been improved in NVEnc 7.39.
