### ISSUE TITLE
An EAC3 7.1 audio track is converted as mono to AC3 by default

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#531]
An EAC3 7.1 audio track is converted as mono to AC3 by default if --audio-stream 5.1 is not specified.

It would make more sense to convert to 5.1 by default.

`Output Info    H.265/HEVC main @ Level auto`
`   1920x1038p 1:1 23.976fps (24000/1001fps)`
`   avwriter: hevc, #1:eac3/7.1 -> ac3/mono/384kbps,`
`   #2:eac3/5.1(side) -> ac3/5.1(side)/384kbps => matroska`

Test file:
[EAC_7.1_convert-to-ac3_Test.zip](https://github.com/rigaya/NVEnc/files/13256723/EAC_7.1_convert-to-ac3_Test.zip)

**Comment by rainman74** [comment]
[EAC_7.1_convert-to-ac3_Test.zip](https://github.com/rigaya/NVEnc/files/13256721/EAC_7.1_convert-to-ac3_Test.zip)

**Comment by rainman74** [comment]
@rigaya Wouldn't it make more sense to always convert DTS-HS & EAC3 7.1 audio tracks to 5.1 by default when converting to e.g. AC3 or an audio format that does not support 7.1 channels?

Converting to mono in the default here is rather suboptimal.

**Comment by rigaya** [comment]
I've changed audio channel selection when output codec does not support the same audio channels as the input audio in [NVEnc 7.51](https://github.com/rigaya/NVEnc/releases/tag/7.51), now should select 5.1ch by default in this case.

Please have a try.
