### ISSUE TITLE
Default

### ISSUE THREAD

**Issue by Discograp** [rigaya/NVEnc#534]
StaxRip v.2.29.0 NVenc v.7.35 H.264/Avc

Please change automatic selection by default

![изображение](https://github.com/rigaya/NVEnc/assets/95682410/5a2dc5ca-c316-420b-b470-693d4df65cd1)

**Comment by rigaya** [comment]
I am not developer of Staxrip. Furthermore, you can simply just change it and save the settings, so you need not to change the default.
