### ISSUE TITLE
Failure in Audio Encoding with DCA (DTS) Codec using NVEncC

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#536]
I am encountering a problem while encoding audio using the DCA (DTS Coherent Acoustics) codec with NVEncC. 
The process is failing specifically when using the DCA codec, although encoding with AC-3 and E-AC-3 codecs was successful.

Options used:
```
--avhw
--codec h264
--qvbr 26
--preset quality 
--multipass 2pass-full 
--max-bitrate 8000
--vbv-bufsize 10000
--ref 5
--bref-mode each
--aq
--aq-temporal
--lookahead 24
--mv-precision Q-pel
--bluray 
--audio-codec dca
```

Intended Outcome: Encoding an audio track using the DCA codec for Blu-ray compliance.
Note: Same options were successfully executed for AC-3 and E-AC-3 codecs.

Error Messages Received:

```
failed to open encoder(dca) for audio track 1: Invalid argument
failed to initialize file reader(s).
Failed to open output file: "test.m2ts"
```

Encoder and Profile Checks:

Output of --check-encoders confirms the availability of the DCA encoder.
`dca             : DCA (DTS Coherent Acoustics)`

Output of --check-profiles dca shows the following profiles available for DCA:
```
DTS
DTS-ES
DTS 96/24
DTS-HD HRA
DTS-HD MA
DTS Express
```

Troubleshooting Attempts:

Attempts to encode using AC-3 and E-AC-3 codecs were successful, indicating the issue is specific to the DCA (DTS) codec.

Input audio is E-AC3.
Output of --check-decoders confirms the availability of the EAC3 decoder.
`eac3            : ATSC A/52 E-AC-3`

Something I am missing? 
I used NVEnc 7.33 for this encode

**Comment by babiulep** [comment]
Try adding (audio-)bitrate i.e.:  --audio-bitrate 1?1510. Then it works for me, without it I get the same error you describe.

I am currently using 7.37.

Perharps there is a default minimum audio bitrate already defined (within nvencc)?
Because DCA requires a much higher minimum bitrate and libdcaenc will refuse to encode if the bitrate value is considered *too low*...

**Comment by quamt** [comment]
Yes, audio bitrate works when set to --audio-bitrate 768
which is the lowest for DTS.
So I wonder, for the other codecs like AC3 or EAC3 for example, it sets them to a specified bitrate when none is provided.

**Comment by quamt** [comment]
I am closing this for now, as it works when the value is manually set.
Just wonder why other codecs had a predefined setting.
