### ISSUE TITLE
Default --max-bitrate sets low number: 17500, Doesnt allow High bitrate encodes

### ISSUE THREAD

**Issue by Wontell** [rigaya/NVEnc#538]
Hello,
I think this is recent bug, because i remember encoding 25Mb files and they coming as 25mb.
Yesterday all my 25Mb/s files came as 15 and 16mb/s
Apparently now the encoder sets automatically a very low max bitrate --max-bitrate 17500

Please fix it like it was, make the default 200000 kbps.

I know this can be fixed manually like this: --max-bitrate 200000
But most people have no idea about that, and i personally never had to set --max-bitrate ever before, i just set my the bitrate to 25000 and files came up as 25MB/s

Right now im on 7.36

**Comment by quamt** [comment]
@Wontell 
You might want to try the latest version 7.37 if that fixes your issue.

**Comment by Wontell** [comment]
> @Wontell You might want to try the latest version 7.37 if that fixes your issue.

That solves it, thanks
