### ISSUE TITLE
AV1 codec level not working

### ISSUE THREAD

**Issue by alonsofnr1** [rigaya/NVEnc#540]
Thanks a lot for the great software. 

I got a new RTX GPU and am experimenting with the AV1 codec. I run the following line:

NVEncC64.exe --avhw -c av1 --level 4.1 --vbr 1800 -i TEST.mp4 -o TEST2.mp4

but I get an error:
nvenc : Failed to Initialize the encoder
nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

I played around and it seems the problem is in the "level" parameter. It does work in H264 and HEVC however. 

When you have time, could you take a look? Thanks.

**Comment by rigaya** [comment]
Yes. actually I have never managed to make --level work with AV1 encoding.

I recommend to just remove --level option and keep it auto.

**Comment by alonsofnr1** [comment]
Thank you, not super important I guess.
