### ISSUE TITLE
convert audio stream only, copy video stream?

### ISSUE THREAD

**Issue by The4Apes** [rigaya/NVEnc#541]
Copy audio and sub is possible with "--audio-copy" and "--sub-copy", but i cant find a copy option for video stream.
How can i copy the video stream?

**Comment by rigaya** [comment]
NVEnc is developed fro video encoding, there is no feature to copy video stream.

**Comment by quamt** [comment]
> Many other programs for video encoding feature copy video stream. A function for copying the video stream would not be a contradiction. But if that is not desired, I did it differently now. I used NVEnc to recoded the video and audio stream and MKVToolNix to merged the original video stream with the recoded audio stream . Works too.



You can copy the video and only encode the audio to another format using FFmpeg.

Copying the Video Stream:
FFmpeg can copy a video stream without re-encoding it using the `-c:v copy` parameter. 
This means the video quality and characteristics will remain unchanged, and the process will be faster as it avoids re-encoding.

Re-encoding Audio: 
To re-encode the audio stream, perhaps to a different format or specifications, FFmpeg can do this with various audio codecs. For example, using `-c:a libmp3lame` to encode audio into MP3 format.

Merging Streams: 
FFmpeg can also mux the video and audio streams into various container formats like MKV, MP4, etc., effectively combining the original video stream with a newly encoded audio stream.

**Comment by rigaya** [comment]
I’m sorry but there is no plan to support video copy feature, so I’ll have this issue closed.
