### ISSUE TITLE
Unclear usage and explanation of --qvbr, --vbr and --multipass

### ISSUE THREAD

**Issue by Dendraspis** [rigaya/NVEnc#542]
Hello rigaya,

normally I would edit the docs and create a PR as usual, but in this case I'm not sure how to deal with it and additionally I cannot edit the Japanese version.

The doc says about the `--multipass`-parameter:
```
--multipass <string>
Multi pass mode. Available only for --vbr and --cbr. [API v10.0]
```
...but for `--qvbr` we have the following info:
```
--qvbr <float>
Encode using constant quality mode. (0.0-51.0, 0 = automatic)
This is equivalent to --vbr 0 --vbr-quality <float>.
```

So the question is:
Does `--multipass` also apply to `--qvbr` as this is (internally) also a `--vbr` mode combined with `--vbr-quality` or does `--multipass` only apply for `--vbr` ***without*** `--vbr-quality` as it seems to be a bitrate related process like indicated through the explanation of the `--multipass` parameter: `"[..] can reach closer to the target bitrate [..]"`?

Hope to read soon from you. Keep up the good work.

Referring to the English docs:
[--multipass](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--multipass-string)
[--qvbr](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--qvbr--float)

Related issue on my side:
https://github.com/staxrip/staxrip/issues/1162

**Comment by rigaya** [comment]
I think it's very clear, just simply think that ```--qvbr [x]``` is mapped to ```--vbr 0 --vbr-quality [x]```.

For ```--vbr 0 --vbr-quality [x]```, ```--multipass``` will take effect as it can be used with ```--vbr```.

**Comment by Dendraspis** [comment]
Thanks for the quick response and the confirmation.
At that time both handlings looked valid, so I just wanted to make sure how it works.

Have a nice day. 👍
