### ISSUE TITLE
vmaf has cuda support now

### ISSUE THREAD

**Issue by bavdevc** [rigaya/NVEnc#543]
Hello @rigaya,

vmaf(Netflix) and cuda(Nvidia) implemented some kind of feature extraction that really speeds up the vmaf process.

Could we have that with nvencc? ffmpeg got it:

https://github.com/FFmpeg/FFmpeg/commit/7f685d0f493bbfa44cf1b3b65f9347291e23872b

and

https://github.com/Netflix/vmaf/commit/3071d7eeaa055696f8fc3ffbb3f6abb640ed5505

kind regards

**Comment by rigaya** [comment]
I actually gave up, as I could not build libvmaf with cuda on Windows. (I'm not really interested with Linux only features.)

Is libvmaf able to be build with cuda on Windows now?

**Comment by bavdevc** [comment]
very true - Netflix devs didn't test it on Windows - just read that comment from their devs.

ok, I think we can forget about it - I'm testing it with ffmpeg linux build atm. it's working only with AV_PIX_FMT_YUV420P and AV_PIX_FMT_YUV444P16 atm. but it's not easy to get it working at all
