### ISSUE TITLE
Can add vmaf cuda?

### ISSUE THREAD

**Issue by claudiomarassi** [rigaya/NVEnc#546]
https://github.com/Netflix/vmaf/tree/master/libvmaf

add -Denable_cuda=true to build with CUDA support, which requires nvcc for compilation (tested with CUDA >= 11)

https://github.com/Netflix/vmaf/releases/tag/v3.0.0

First release to include vmaf_cuda_* APIs, header file vmaf_cuda.h

**Comment by rigaya** [comment]
This seems to be a duplicate of ＃543.

**Comment by claudiomarassi** [comment]
Sorry.
Thanks!
