### ISSUE TITLE
Add feature Explicit Split Frame Encoding

### ISSUE THREAD

**Issue by claudiomarassi** [rigaya/NVEnc#547]
https://docs.nvidia.com/video-technologies/video-codec-sdk/12.1/nvenc-application-note/index.html

Table 2. What’s new in Video Codec SDK 12.1?

Explicit Split Frame Encoding 

Client applications have explicit control to enable or disable split frame encoding along with specifying the number of NVENCs to split the frame across or use default automatic mode.

**Comment by rigaya** [comment]
SDK 12.1 feature has already been added and can be set by [--split-enc](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--split-enc-string).

**Comment by claudiomarassi** [comment]
It worked! Thank you very much!
