### ISSUE TITLE
[Feature Request] Screenshot Output

### ISSUE THREAD

**Issue by tazlord** [rigaya/NVEnc#551]
Is it possible to output a single video frame (screenshot) to a standard photo format, like JPEG or PNG (or both)?
This would be helpful when creating large quantities of screenshots from a video source, especially when including vpp functions like tone mapping.

**Comment by rigaya** [comment]
Unfortunately, it's not possible in current implementation, and will be also difficult as it is not  supported in current NVENC SDK feature.

**Comment by tazlord** [comment]
Thank you for your quick reply.
