### ISSUE TITLE
Ho to limit max bitrate?

### ISSUE THREAD

**Issue by Einst1969** [rigaya/NVEnc#554]
I think I have a problem with the wifi transmitting to my TV and I think the max bitrate is too high. 

How can I put a maximum limit on the bitrate?

I tried "maxrate" and " "vbv-bufsize" but it doesn't seem to work. I don't understand what values to put.

**Comment by rigaya** [comment]
I think ```--max-bitrate``` (the unit is in kbps) should work, but only with ```--qvbr```, ```--vbr``` or ```--cbr```.

If using ```--cqp```, it is not possible to limit bitrate, so please consider using other modes.

**Comment by Einst1969** [comment]
It doesn't work with the CBR. Or am I doing something wrong?

**Comment by rigaya** [comment]
I've tested but it seems to work fine with command line below.
```x64\NVEncC64.exe -i input.ts -o output.mp4 --cbr 6000 --max-bitrate 6000```

```
NVEncC (x64) 7.41 (r2681) by rigaya, Jan 22 2024 13:02:15 (VC 1929/Win)
OS Version     Windows 11 x64 (22631) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [5.19GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 4080 (9728 cores, 2505 MHz)[PCIe4x16][551.23]
NVENC / CUDA   NVENC API 12.1, CUDA 12.4, schedule mode: auto
```

![image](https://github.com/rigaya/NVEnc/assets/815947/ce650911-96ac-4900-a021-42334764c11d)

It's not exact but shall be enough.

**Comment by Einst1969** [comment]
What program do you use to see the bitrate over time?

**Comment by qwe7989199** [comment]
> What program do you use to see the bitrate over time?

[This](https://github.com/rigaya/CheckBitrate) will help to extract bitrate distribution as a csv file, so that you can visulize it in MS Excel or other tools.

**Comment by Einst1969** [comment]
Hello and thanks for the reply.

I saw that Handbrake manages the maxbitrate in CQ mode NVENC h265. Do you think that in the future it will also be possible for your codec (what I use on Staxrip)?

**Comment by rigaya** [comment]
I’ll close this issue as the topic has been answered.
