### ISSUE TITLE
Request: add audio-quality

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/NVEnc#558]
With ffmpeg it's possible to set an audio quality target with `-aq` in the range 0-9 instead of a set bitrate for most codecs. 

The only codec I tested so far that doesn't support it is `libvorbis` but most others do. 

Would be nice to be able to mirror that ability in your encoders. Thanks for the consideration either way!

**Comment by rigaya** [comment]
I think it'll be able to add something like --audio-quality for NVEnc also (equivalent to ffmpeg -aq).

I'll check and try adding it.

**Comment by rigaya** [comment]
--audio-quality has been added in [NVEnc 7.42](https://github.com/rigaya/NVEnc/releases/tag/7.42), which should work the same as ffmpeg -aq (or -qscale:a).
