### ISSUE TITLE
The transcoding file and source file screens are not synchronized？

### ISSUE THREAD

**Issue by staxrip727** [rigaya/NVEnc#562]
The same frame is different after transcoding, Why?
QSV is also like this.

**Comment by rigaya** [comment]
Timestamps might be changed if the first frame of your input file is not a keyframe, as video can be decoded only from a keyframe. 

NVEnc/QSVEnc will change timestamp in such cases, therefore comparing on the same time might not result in the same frame.

**Comment by staxrip727** [comment]
> Timestamps might be changed if the first frame of your input file is not a keyframe, as video can be decoded only from a keyframe.
> 
> NVEnc/QSVEnc will change timestamp in such cases, therefore comparing on the same time might not result in the same frame.

How to solve it? FFMPEG+NVENC is normal, but I want to use this one as it has a wide range of adjustable parameters.

**Comment by staxrip727** [comment]
Not only this file, but almost all of them are in this situation.

**Comment by rigaya** [comment]
I don’t really think you need to “solve” it, as it is just changing the first keyframe to the start point of the video.

However, adding “--timestamp-passthrough” might work if avhw or avsw reader is used.

**Comment by staxrip727** [comment]
> I don’t really think you need to “solve” it, as it is just changing the first keyframe to the start point of the video.
> 
> However, adding “--timestamp-passthrough” might work if avhw or avsw reader is used.

It's still the same after adding it.

How can VMAF score correctly if frames cannot be synchronized?

**Comment by rigaya** [comment]
If --timestamp-passthrough does not work, there will be no way to change this.

**Comment by staxrip727** [comment]
Another question, about -- avsync

"--avsync" [https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--avsync-string](url)

--avsync cfr encoding window displays vfr???
--avsync vfr encoding window displays vfr OK
--avsync forcecfr encoding window displays force cfr OK

**Comment by rigaya** [comment]
Actually, --avsync cfr was an old option and now does not reflect the actual behavior as it acts nearly like vfr, I've changed the option name to "auto" in NVEnc 7.43.

If you need cfr, please use --avsync forcecfr.
