### ISSUE TITLE
crop and resize issue since v7.42

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#568]
Resizing shows a vertical shifted and damaged picture beginnng from v7.42. I didnt test v7.41.
Version 7.40 is working ok.

Some code:
`-i thephysician.rmx.mkv ^

--crop 62,128,62,136 --output-res 1920x1080 --vpp-pad 0,104,0,104 ^

--avhw -c h264 --profile high -u p5 --qvbr 24 ^`

System info
OS Version     Windows 10 x64 (19045) [UTF-8]
CPU            11th Gen Intel Core i7-11800H @ 2.30GHz [TB: 4.50GHz] (8C/16T)
GPU            #0: NVIDIA GeForce RTX 3050 Ti Laptop GPU (2560 cores, 1223 MHz)[PCIe4x16][546.09]

**Comment by rigaya** [comment]
Thank you for reporting the issue, [NVEnc 7.45](https://rigaya34589.blog.fc2.com/blog-entry-1796.html) should have fixed --crop issue from 7.42, please have try.

**Comment by fzold** [comment]
v7.45 is working again.
Thank you very much.
