### ISSUE TITLE
isit possible to do artifact reduction with nvencC

### ISSUE THREAD

**Issue by chowderhead** [rigaya/NVEnc#569]
artifact reduction came with maxine.  be nice to know how to use it with nvencC or staxrip
Randy K.

**Comment by rigaya** [comment]
Please checkout the documents below.
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-nvvfx-artifact-reduction-param1value1param2value2

**Comment by rigaya** [comment]
I'll close the issue as the question has been answered.
