### ISSUE TITLE
Application provided invalid, non monotonically increasing dts to muxer in stream.

### ISSUE THREAD

**Issue by acsway878787** [rigaya/NVEnc#57]
Hi, I tried to convert an mp4 video from 1080p to 720p but this error occurred, is there any solution?
I'm sorry if this question is stupid, I'm really a newbie to this.
Here's the log:

>  C:\NVEnc_4.07\NVEncC\x64> .\nvencc64 -i in.mp4 --output-res 1280x720 --audio-copy --avhw -o out.mp4
NVEncC (x64) 4.07 (r788) by rigaya, Jun  5 2018 22:18:56 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (17134)
CPU            Intel Core i7-6700HQ @ 2.60GHz [TB: 3.50GHz] (4C/8T)
GPU            #0: GeForce GTX 1060 (10 EU) @ 1670 MHz (398.11)
NVENC / CUDA   NVENC API 8.1, CUDA 9.2, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 2100504995/70076543 fps
Vpp Filters    copyDtoD
Output Info    H.264/AVC high @ Level auto
               1280x720p 1:1 29.974fps (2100504995/70076543fps)
               avwriter: h264, aac => mp4
Encoder Preset default
Rate Control   CQP  I:20  P:23  B:25
Lookahead      off
GOP length     300 frames
B frames       3 frames
Ref frames     3 frames, LTR: off
AQ             off
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto
[mp4 @ 00000209a5a45680] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 9223372036854775807 >= 9223372036854775807
[mp4 @ 00000209a5a45680] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 9223372036854775807 >= 9223372036854775807
[mp4 @ 00000209a5a45680] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 9223372036854775807 >= 9223372036854775807
[mp4 @ 00000209a5a45680] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 9223372036854775807 >= 9223372036854775807
[mp4 @ 00000209a5a45680] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 9223372036854775807 >= 9223372036854775807
[mp4 @ 00000209a5a45680] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 9223372036854775807 >= 9223372036854775807
(A lot of same messages)
encoded 72 frames, 321.43 fps, 3129.05 kbps, 0.90 MB
encode time 0:00:00, CPU: 6.1%, GPU: 0.0%, GPUClock: 1404MHz
frame type IDR  1
frame type I    1,  avgQP  20.00,  total size  0.00 MB
frame type P   18,  avgQP  23.00,  total size  0.34 MB
frame type B   53,  avgQP  25.00,  total size  0.56 MB

**Comment by rigaya** [comment]
Problem might be caused by incorrect fps detection. Please try adding --fps 30000/1001 to specify proper fps.

**Comment by acsway878787** [comment]
It works, thank you very much.
