### ISSUE TITLE
Is 7.45 Safe - Virus False Positive?

### ISSUE THREAD

**Issue by AYColumbia** [rigaya/NVEnc#570]
Hi,
I just wanted to be sure that the current 7.45 x64 package is safe as prior versions were not detected by Windows Defender as problematic.  Upon scanning the 7.45 7z file, Defender flagged it with: Trojan:Script/Wacatac.B!ml.

I just wanted to be sure before assuming it's safe and allowing it.  Thank you.

**Comment by quamt** [comment]
> Hi, I just wanted to be sure that the current 7.45 x64 package is safe as prior versions were not detected by Windows Defender as problematic. Upon scanning the 7.45 7z file, Defender flagged it with: Trojan:Script/Wacatac.B!ml.
> 
> I just wanted to be sure before assuming it's safe and allowing it. Thank you.

[VirusTotal](https://www.virustotal.com/) is a recommended resource for file verification. 
Windows Defender can sometimes generate false positive results.

The attached images display the outcomes of the most recent version analysis.
![image](https://github.com/rigaya/NVEnc/assets/64795789/dedbb277-b305-4d0f-a540-dc7ab7e6bff0)

The scan results for the latest executable file are also provided below:
![image](https://github.com/rigaya/NVEnc/assets/64795789/907bb7e4-49bd-4651-818a-80d7b101d05d)

The findings indicate that only 1 out of 72 antivirus engines identified a potential issue, suggesting a minimal likelihood of actual risk. For peace of mind, consider using additional tools like VirusTotal for further verification.

**Comment by AYColumbia** [comment]
Thanks and yes, you're right about Windows Defender.  Thank you for the info for VirusTotal.
