### ISSUE TITLE
Alpha support (YUVA) for hevc codec?

### ISSUE THREAD

**Issue by qwe7989199** [rigaya/NVEnc#571]
It seems that NVIDIA's official SDK explicitly supports hevc hardware encoding with an alpha channel in the [following note](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.1/nvenc-video-encoder-api-prog-guide/index.html#hevc-alpha-encoding).  

Although the applications for this technique are very limited.  
Could you consider adding this feature in future version of nvenc.

**Comment by rigaya** [comment]
I'm sorry, but I'm not sure what kind of use case we have for supporting alpha channel. 

I know it would be useful in a video editor software, but NVEncC is mainly a transcoder. Also, does video players support this alpha channel in HEVC?

**Comment by qwe7989199** [comment]
In fact on the production side, HEVC with alpha channel has been limited to Apple devices in recent years. FFmpeg on macOS can call the videotoolbox hardware encoder for transparent HEVC output, and there is some application like [this](https://engineering.dena.com/blog/2022/07/hevcplayerview).  

And by browsing [this page](https://kitcross.net/hevc-web-video-alpha-channel/) with my Windows PC, I confirmed that at least Chrome can render HEVC with alpha correctly. This is the [sample file](https://kitcross.net/videos/hevc-bounce-5319b8308f.mov).

Probably the most significant point of adding this feature is to make windows also have a way to output transparent HEVC.

On the application side, I think the biggest significance may be that when used in conjunction with lossless YUV444, it is possible to store image sequences containing alpha channel in a more efficient way.
For example, compared to ProRes4444XQ (which is an Apple exclusive and can't be hw-decoded),  HEVC is much smaller and more compatible with other platforms.

The above is based on my incomplete understanding.
This feature is "better to have", and in fact few people care.

**Comment by rigaya** [comment]
On Windows, ffmpeg seems to not being able to decode the alpha channel even with sw decode, and therefore its use will be greatly limited on a Windows environment.

I'll consider to add this feature in the future, but the functionality will be limited, for example, I think the filters will not be supported when using alpha channel encoding.

**Comment by EliotRagueneau** [comment]
I would need such type of support in my project, as I am embedding transparent videos within a web page, and to support Safari, the only encoder that seems to work so far with alpha channels is hevc_videotoolbox, but this one is only available on M1/2 chips, nd so cannot be encoded on a server

**Comment by rigaya** [comment]
[NVEnc 7.61](https://github.com/rigaya/NVEnc/releases/tag/7.61) adds experimental YUVA420 support for HEVC.

Unfortunately I were not able to the decode the output, ffmpeg on Windows or Linux does not seem to support HEVC alpha channel decoding.

I would appreciate it if you would have a test and check whether it can be decoded properly.

**Comment by qwe7989199** [comment]
It could be that I haven't found the right way to use it yet
But I tried the following two commands and neither of them encode properly

1. I prepared argb's qtrle (quicktime animation) using the mov container
`nvencc64 -i -i alpha.mov -c hevc --output-csp yuva420 -o hevc_alpha.mov
`
which returns
```
avsw: Invalid pixel format "argb" from input file.
failed to initialize file reader(s).
Failed to initialize file reader(s).
```
2. I prepared a vp9 of yuva420 with the same content, using the webm container
`NVEncC64 -i alpha.webm -c hevc --output-depth 8 --output-csp yuva420 -o hevc_alpha.mov
`
which returns

```
Input file does not have alpha channel.
```

So I guess I first need to figure out what kind of alpha channel format I need for encoding to yuva420 hevc.


https://github.com/user-attachments/assets/1ad790df-ab9a-4d20-9178-df003fef9fee

[alpha.webm](https://github.com/user-attachments/assets/c36f819e-93cc-41ec-bbbf-79e661f41f16)

**Comment by qwe7989199** [comment]
In fact, I'm stuck at the step of creating the valid input file.
My sample alpha channel hevc file was produced under macOS, and the browser under macOS renders the alpha channel correctly.

https://github.com/user-attachments/assets/2b59c7d3-34e0-4bc0-8f49-3553481a5da5

But nvencc doesn't consider it a correct video with alpha channel: 
```
NVEncC64 -i "movie-hevc.mov" -c hevc --output-csp yuva420 -o nv_hevc_alpha.mp4
--------------------------------------------------------------------------------
nv_hevc_alpha.mp4
--------------------------------------------------------------------------------
Input file does not have alpha channel.
```

If only hevc files with alpha produced by nvidia's encoder can be recognized correctly, it becomes a chicken or egg problem.

At the moment, I don't think this solution is compatible with the macOS one.

**Comment by rigaya** [comment]
Unfortunately, both software decoder (by libavcodec) or hardware decoder of NVEnc does not support HEVC alpha channel.

Therefore, input files needs to be in other format, so I was testing using ProRes YUVA444 input file and huffyuv rgba input files.

I got sample file from UsingHEVCVideoWithAlpha.zip which can be downloaded from this [url](https://developer.apple.com/documentation/avfoundation/media_playback/using_hevc_video_with_alpha). There was a ProRes 4444 sample file "HEVC-Videos-With-Alpha-Exports\Resources\puppets_with_alpha_prores.mov".

It can be encoded by
```
NVEncC64 -i puppets_with_alpha_prores.mov -o test.mp4 -c hevc --output-csp yuva420
```

Also, I also tested other input format like below (only for test purpose).
```
ffmpeg -i puppets_with_alpha_prores.mov -c:v huffyuv -pix_fmt bgra test_huffyuv_bgra.mkv
NVEncC64 -i test_huffyuv_bgra.mkv -o test.mp4 -c hevc --output-csp yuva420
```

**Comment by qwe7989199** [comment]
As far as I know, Davinci Resolve (the free version) can handle hevc with alpha channel. 

I tried with `movie-hevc.mov` above, and it was recognized as moive with alpha channel successfully, cuz we can set alpha mode in "Clip Attributes". 

But I can not render correctly in windows (But correct in macOS).

![check_alpha_in_win](https://github.com/user-attachments/assets/3d60a837-2313-4bdd-b9ef-2c79703d4280)


When I import the nvencc output of hevc with alpha channel, Davinci Resolve show only one alpha mode "Premultiply", which is consistent with the behavior of the video without alpha channel. 
![only_one_mode](https://github.com/user-attachments/assets/eaf5037f-31ff-4471-b3c6-3283d82d91bb)


I'm not sure what condition the extra alpha mode in "Clip Attributes" is triggered, but it could be seen as one of the signs for success alpha or not.
As for how to get the correct rendering results on windows, I have no idea at the moment. 

Here is the correct result by Davinci Resolve on macOS, alpha channel(the outline of phone) can be splitted and rendered stand alone.
![截屏2024-08-08 10 42 34](https://github.com/user-attachments/assets/4bff7019-87c5-416e-b4d3-2c3cd948453b)

**Comment by rigaya** [comment]
Thank you for sharing the information of Davinci Resolve.

I have improved muxer handling in [NVEnc 7.62](https://github.com/rigaya/NVEnc/releases/tag/7.62), although the file cannot be rendered (as I'm using Windows version), now other alpha modes can be shown.

![image](https://github.com/user-attachments/assets/e6d52991-bc29-479d-84e6-23af4efbc437)

Would you please have a try?

**Comment by qwe7989199** [comment]
Thank you for your great work. 
I can be sure we are not far from success.

Now I am using a simpler validation process: 
1. Start an HTTP server on Windows that holds the nvenc encoded hevc with alpha (.mp4) file. 
2. Use an apple device, either safari on iphone or safari/chrome on macos, access the file address. 
3. Check the result of web browser playback. 

In Chrome (macOS), we can see that the alpha channel is rendered but seems to be almost twice as wide as the content of the other channels.
<img width="1564" alt="截屏2024-08-12 11 05 14" src="https://github.com/user-attachments/assets/6e7c1fe6-8f04-40a4-a49f-6d896a50e5b9">

In Safari (iOS), we can still recognize the presence of the alpha channel on the left side of the video, but it's still offset from the content, causing the effect to be unnormal.

![793c5ead-57e1-41f8-92cf-904b6b6f24b2](https://github.com/user-attachments/assets/98e227df-9258-45cc-bdac-8e3ef196932c)

**Comment by rigaya** [comment]
Thank you so much for sharing the validation process using the web server.

It really helps me much, as I can now check using my iPhone!

I was able to find out the bug of handling alpha channel which has caused the width error of alpha channel, [NVEnc 7.63](https://github.com/rigaya/NVEnc/releases/tag/7.63) shall fix this, and I think we are now able to get proper playback now.

Below is a check on Safari (iOS).

![nvencc_hevc_alpha_iphone_capture_571](https://github.com/user-attachments/assets/1983a554-1817-4dc3-ab0e-0f1ddf44dac5)

**Comment by qwe7989199** [comment]
Browser validation on the macOS side also proved successful.
<img width="600" alt="截屏2024-08-12 17 08 34" src="https://github.com/user-attachments/assets/f1753099-5b6a-41a7-a6a1-774276a48b67">

But Davinci Resolve still couldn't render a alpha channel.  
Also I noticed that when using the official `puppets_with_alpha_hevc.mov`, the alpha mode in the Clip Attribute is recognized by default as "premultiplied", while the nvenc output is recognized as " straight".
I don't know if there is a correlation between this and being able to render correctly.
<img width="600" alt="截屏2024-08-12 17 21 04" src="https://github.com/user-attachments/assets/8a37ac90-ae65-4fd9-9d2d-920eac0eac52">

Actually it's enough for hevc to be rendered correctly on the web side as the final distributed format.
Thanks again for the great work!

**Comment by rigaya** [comment]
Thank you for your tests!

> the alpha mode in the Clip Attribute is recognized by default as "premultiplied", while the nvenc output is recognized as " straight".

[NVEnc 7.64](https://github.com/rigaya/NVEnc/releases/tag/7.64) adds option to change alpha channel mode ([--alpha-channel-mode](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--alpha-channel-mode-string-hevc)). By adding ```--alpha-channel-mode premultiplied```, I was able to get Davinci Resolve to recognized as "premultiplied" (but not rendered as I've checked on Windows). It also was shown properly on iOS Safari.

Also, [NVEnc 7.64](https://github.com/rigaya/NVEnc/releases/tag/7.64) fixed wrong alpha channel related headers.

Will you please have a try on macOS version?

> Actually it's enough for hevc to be rendered correctly on the web side as the final distributed format.

Thank you, I think NVEnc 7.64 will be last try, as I'm not being able to come up of other points to be improved.

**Comment by qwe7989199** [comment]
Thank you for your hard work.

On Safari macOS, all things behave normally.
But when it comes to Chrome (macOS), translucent values (0<alpha<1) behaves strangely.
You can see the "blurtest" part.
<img width="600" alt="截屏2024-08-13 18 52 33" src="https://github.com/user-attachments/assets/274c2268-ab9f-4e48-b44f-b9c5dc018e1b">

And I changed the border color of "blurtest" from red to black, Chrome also becames normal.
<img width="600" alt="截屏2024-08-13 18 59 38" src="https://github.com/user-attachments/assets/41d0d751-b4c0-431c-b72f-775c58bbea82">

I don't know why this is happening. I think there's something about compatibility that's missing.
