### ISSUE TITLE
Low transcoding performance with the latest release (v7.49)

### ISSUE THREAD

**Issue by otuncelli** [rigaya/NVEnc#577]
I'm getting about 70% GPU Video Encoding engine utilization on my 1050 ti while transcoding a video with the latest version (v7.49)

7.48 doesn't have this problem. Everything else is the same.

Comparison 7.49 vs 7.48

![comparison](https://github.com/rigaya/NVEnc/assets/5532796/faa847c2-093c-48d1-8e28-20326e57aa89)

More info: 
* The input file is 8 bit
* Adding  `--avsw` didn't make any difference
* Same problem with older driver (551.76)
* Turning `lookahead` off seems to be fixing the issue.

**Comment by bitspyer** [comment]
can confirmed this issue. with 7.49 there is a frame drop of aprox 40%

**Comment by Jigsawbg** [comment]
@otuncelli
`--tune uhq` -> "Tune presets for latency tolerant encoding for higher quality. Only supported for HEVC on Turing+ architectures" from SDK. You use Pascal architectures (GTX 1050 Ti)
For `--lossless` I don't know.

**Comment by otuncelli** [comment]
> @otuncelli `--tune uhq` -> "Tune presets for latency tolerant encoding for higher quality. Only supported for HEVC on Turing+ architectures" from SDK. You use Pascal architecture (GTX 1050 Ti). You need at least GTX 1630 which is Turing.

Ah, I see. Thank you for the info.

**Comment by rigaya** [comment]
The performance drop was due to the new ```--lookahead-level``` option added in NVEnc 7.49, defaulted to auto.
 
I've changed the default to 0 in NVEnc 7.50, and will remove the performance drop.

**Comment by otuncelli** [comment]
Awesome! I can confirm the issue has been fixed.
