### ISSUE TITLE
Question new Options tune and lookahead -level

### ISSUE THREAD

**Issue by bitspyer** [rigaya/NVEnc#578]
Hi,

can you explain what the benefits of the options tune and lookahead-level are?

I made some tests and i got now diffrences in size and bitrate, when i encode a UHD Sample to hevc.

Greetz,
Bitspyer

**Comment by rigaya** [comment]
--lookahead-level
It is described in the NVENC SDK as below.

_< [in]: Specifies the lookahead level. Higher level may improve quality at the expense of performance._

**Comment by quamt** [comment]
> Hi,
> 
> can you explain what the benefits of the options tune and lookahead-level are?
> 
> I made some tests and i got now diffrences in size and bitrate, when i encode a UHD Sample to hevc.
> 
> Greetz, Bitspyer

What are your encoding parameters?
How did you verify the difference in "quality"?
Certain settings in video encoding can improve the perceived quality of a video without significantly changing the file size.

**Comment by bitspyer** [comment]
For testing I first used very few options:

--y4m --preset quality --qvbr 20 --max-bitrate 50000 

second run with extra option --lookahead 32 --lookahead-level 3 --tune uhq

checked both runs with vmaf and the diffrence was little and i think because the second run with the new options made the file with higher bitrate.

Another Test was with a "fixed" bitrate :
made 2 runs with --vbr 5000  and now there was a small advantage for lookahead-level and tune at smaller filesize

Maybe the new options may be usefull for low bitrates and not if you use qvbr with high bitrates
