### ISSUE TITLE
feature request: pad/letterbox

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#58]
Would be nice if one could pad/letterbox a source to add black borders.
Unless I'm overlocking something this isn't possible atm., is it?
What I would like to do to be able to is to for example use a 3840x2000 source, resize it to 1920x1000 and then add borders to get 1920x1080. (Or a 1920x960 source, resize to 1280x668 and then add border so get 1280x720.)

Atm. I can crop (--crop ..) , and resize (--resize + --output-res), but I can't add borders as far as I know.

It would especially nice if this could be used with avhw.

**Comment by rigaya** [comment]
[NVEnc 4.09](https://github.com/rigaya/NVEnc/releases/tag/4.09) adds --vpp-pad for video padding.

In your case,
_3840x2000 source, resize it to 1920x1000 and then add borders to get 1920x1080,_
```
--output-res 1920x1080 --vpp-pad 0,40,0,40
```
should do. It will work with both avhw/avsw.

**Comment by Selur** [comment]
Nice ! Thanks a lot!
