### ISSUE TITLE
fastdecode tuning alternative

### ISSUE THREAD

**Issue by couleurm** [rigaya/NVEnc#581]
hello, i am looking for alternatives to x264 fastdecode that encode faster, what would be some NVEncC arguments that replicate or get close to it

**Comment by bitspyer** [comment]
Depending on your Nvidia Card (check with --check-features  Option)

--preset quality 
--lookahead 32 
--ref 6 (depends on Card)
--bframes 5 (depends on Card)
--mv-precision Q-pel
--aq
--aq-strength 0
--aq-temporal

than you can try 2-pass Encoding with vbr:
--multipass 2pass-full
--vbr 5000  (depends on Source, HD, UHD...maybe u need higher bitrate)

or use
--qvbr 20 (depends on source)

nvencc often needs more bitrate for same quality as x264, but for this its fast!

And read the Docs....

**Comment by rigaya** [comment]
Unfortunately there is no option for x264 "fastdecode" in nvencc.

**Comment by bitspyer** [comment]
ah, as i see, i miss understood the question...  sorry for that. It was for the x264 tune parameter fastdecode

**Comment by rigaya** [comment]
I'll close the issue as the question has been answered.
