### ISSUE TITLE
info on HEVC temporal filtering.

### ISSUE THREAD

**Issue by Einst1969** [rigaya/NVEnc#582]
I'm looking in the documentation and in the code (I downloaded the 12.2 SDK and the 12.2 headers) why 4 or more bframes are required. But unfortunately I'm not succeeding. You can help me. Do you know why more than 3 bframes are required? Also, can you tell me where it is written in the documentation or in the code?

**Comment by rigaya** [comment]
Al I know is what is written in the header, it says in the link below that temporal filtering requires "frameIntervalP >= 5" which means "bframes >= 4", as "frameIntervalP" is equal to "bframes+1".
https://github.com/rigaya/NVEnc/blob/master/NVEncSDK/Common/inc/nvEncodeAPI.h#L1899-L1902

**Comment by Einst1969** [comment]
thanks, I missed it!
