### ISSUE TITLE
When the input is an avs script, it seems that GPU accelerated decoding cannot be used?

### ISSUE THREAD

**Issue by mojie126** [rigaya/NVEnc#584]

**Comment by qwe7989199** [comment]
AviSynth is a frame server that mixes CPU and GPU processing, what it gives to NVEnc is already uncompressed YUV/RGB data, so the concept of decoding doesn't exist between AVS and NVEnc.  

In other words, decoding is finished by AviSynth itself, if you want to make use of your GPU to decode the video, [LSMASHVideoSource for ISO based media](http://www.avisynth.nl/index.php/LSMASHSource) or [LWLibavVideoSource for other formats](http://www.avisynth.nl/index.php/LSMASHSource/LWLibavVideoSource) both with `prefer_hw=3` will try hardware decoder in the order of CUVID->QSV.   

It is possible for normal video codecs to use the power of the GPU to accelerate the decoding based on my practice.
![image](https://github.com/rigaya/NVEnc/assets/10990771/41db1593-7e98-4fcf-856d-24ccd3bc444d)

**Comment by rigaya** [comment]
@qwe7989199 Thank you for answering and sharing ways to use hw decode via Avisynth.

I'll close the issue as the question has been answered.
