### ISSUE TITLE
libopus:  Please support mapping_family as well as recommended/default bitrates

### ISSUE THREAD

**Issue by agressiv** [rigaya/NVEnc#585]
When encoding libopus audio, please consider adding support for [mapping_family](https://opus-codec.org/docs/opusfile_api-0.7/structOpusHead.html) argument that the encoder supports.  [ffmpeg supports](https://ffmpeg.org/ffmpeg-codecs.html#Option-Mapping) it via **-mapping_family** 1 as a parameter.  In addition, the bitrates NVEnc (and QSVEnc) default to are very low for multi-channel audio.

As an example, a 7.1 channel audio from a movie:

When encoded with NVEnc/QSVEnc (forced to 416k) or ffmpeg WITHOUT -mapping_family 1:
- The movie is encoded at 293Mbyte.
- LFE channel is not optimized

When encoded via opusenc.exe (via piping from ffmpeg or eac3to), or ffmpeg with -mapping_family 1:
- Bitrate is automatically set to 416k if it's not overridden
- LFE channel is optimized.
- The same movie is encoded at 246.5Mbyte.

NVEnc/QSVEnc would otherwise default to 192kilobit/sec, regardless of channels.  It would be great if it they both used a bitrate that was proportional to the number of channels:

7.1 = 416k
6.1 = 352k
5.1 = 320k
2.0 = 96k
1.0 = 64k

Thanks!

**Comment by rigaya** [comment]
Setting "mapping_family" for libopus should be already available by ```--audio-codec libopus:mapping_family=1```.

I'll think about the default audio bitrate in the next release. NVEnc defaults 192kbps if not set as you have mentioned, but it might be better to let audio codec itself to decide as same as ffmpeg.

**Comment by rigaya** [comment]
[NVEnc 7.53](https://github.com/rigaya/NVEnc/releases/tag/7.53) will let codecs (like libopus) to set bitrate automatically when --audio-bitrate is not set, allowing the default bitrate to change according to the number of channels.

**Comment by agressiv** [comment]
Thanks for this change!
