### ISSUE TITLE
nvencc: Darker Images After Color Space Conversion with vpp-colorspace

### ISSUE THREAD

**Issue by Demicro** [rigaya/NVEnc#587]
## **FFMPEG**
<img src="https://github.com/rigaya/NVEnc/assets/17597833/7b97016f-5437-4753-ba8b-7ac43b1a6299" width="400" height="250">

-vf "scale=w=3840:h=2160:flags=lanczos:threads=0:force_original_aspect_ratio=decrease, colormatrix=bt709:bt2020, format=pix_fmts=yuv420p10"

## **NVENCC**
<img src="https://github.com/rigaya/NVEnc/assets/17597833/76c47c3b-403c-4ec9-9291-dfe514375bc1" width="400" height="250">

--vpp-colorspace "matrix=auto:bt2020nc,colorprim=auto:bt2020,transfer=auto:bt2020-10,range=auto:limited"

**Comment by rigaya** [comment]
The difference here is cause by the difference in the options.

For nvencc, you shall just use --vpp-colorspace "matrix=auto:bt2020nc" to match the ffmpeg command line options.
