### ISSUE TITLE
4.08 --audio-copy doesn't copy the audio track DELAY value

### ISSUE THREAD

**Issue by yturbe** [rigaya/NVEnc#59]
### DESCRIPTION:
My audio track 1 has a delay of -497ms but it has been lost during remux and I get 0ms. It fails with both h264 and h265 codecs.

### RESOURCES:
https://drive.google.com/open?id=1ZFjZw1mTjUB-UadZkFnJ3yovci4EkeUx
( 240 Mb, recorded by myself, free to use)

### COMMAND LINE:
NVEncC64.exe -i qc_record.mkv --codec h264 --cbrhq 4000  --audio-copy 1 -o qc_record_H264.mkv

### LOG FILE:
NVEncC (x64) 4.08 (r795) by rigaya, Jul  5 2018 20:50:40 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (17134)
CPU            Intel Core i7-6700K @ 4.00GHz (4C/8T)
GPU            #0: GeForce GTX 1080 Ti (28 EU) @ 1657 MHz (398.36)
NVENC / CUDA   NVENC API 8.1, CUDA 9.2, schedule mode: auto
Input Buffers  CUDA, 36 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 5284/91 fps
Vpp Filters    copyDtoD
Output Info    H.264/AVC high @ Level auto
               1920x1080p 1:1 58.066fps (5284/91fps)
               avwriter: h264, aac => matroska
Encoder Preset default
Rate Control   CBRHQ
Bitrate        4000 kbps (Max: 4000 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      off
GOP length     580 frames
B frames       3 frames
Ref frames     3 frames, LTR: off
AQ             off
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto

encoded 2411 frames, 311.62 fps, 3922.29 kbps, 19.41 MB
encode time 0:00:07, CPU: 22.7%, GPU: 2.6%, VE: 43.9%, GPUClock: 1910MHz, VEClock: 1653MHz
frame type IDR    5
frame type I      5,  avgQP  32.60,  total size   0.29 MB
frame type P    603,  avgQP  32.87,  total size  12.54 MB
frame type B   1803,  avgQP  39.09,  total size   6.58 MB

**Comment by rigaya** [comment]
Thank you for letting me know the issue, and also providing the source.

[NVEnc 4.09](https://github.com/rigaya/NVEnc/releases/tag/4.09) has improved syncronization between audio & video, now the delay will be internally resolved.

As your input file seems to be VFR (variable frame rate), you might want to add "--avsync vfr" for more accurate synchronization, because NVEncC assumes CFR by default.

**Comment by yturbe** [comment]
Thanks for your feedback and your reactivity!
