### ISSUE TITLE
 --vpp-nlmeans explanation

### ISSUE THREAD

**Issue by dan64** [rigaya/NVEnc#592]
NLMeans is a very useful denoise filter. Thanks for having included it in NVEnc.

This filter was already available in ffmpeg and Handbrake. 

There is an interesting explanation of this filter here: [NLMeans denoise filter](https://forum.handbrake.fr/viewtopic.php?p=139077)

The problem is that I'm unable to reconcile the parameters described in the above post, with the parameters defined in NVEnc.

The NLMeans parameters described in the above posts are:

- Strength
- Origin Weight
- Patch Size (context width)
- Range (spatial search window width)
- Frames (temporal search depth)
- Prefilter Mode
 

Could you provide the mapping between the 2 implementations ?

Thanks,
Dan

**Comment by rigaya** [comment]
Unfortunately, I know nothing about handbrake implementation of nlmeans, so I can say nothing about it.

All I can say is that the implementation seems to be different, as at least the implementation of nlmeans in NVEnc does not and will not have temporal mode.

**Comment by dan64** [comment]
Looking to the ffmpeg implementation, the main parameters are:

- s:  denoising strength. Default is 1.0. Must be in range [1.0, 30.0].
- p: patch size. Default is 7. Must be odd number in range [0, 99].
- r: research size. Default is 15. Must be odd number in range [0, 99].

So it seems that a possible mapping could be:

s -> sigma  (default=0.005, 0.0 -), h (default=0.05, 0.0 <)
p -> patch  (default=5, 3 - 21)
r -> search (default=11, 3 - 21)

The values for "p" and "r" are compatible with the values used in NVEnc.
It is not clear the range (0.0 -) for sigma what represent, the same for h, is not clear what represent the range (0.0 <).

By looking to the function [vf_nlmeans.c](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_nlmeans.c)

h is calculated as: `h = s->sigma * 10.0;`

but as you said the problem for "sigma" and "h" is that the range of values is different.

While even in NVEnc the ratio h/sigma is equal to 10, the default value for "s" in ffmpeg is 1.0 while in NVEnc is 0.005

Maybe the strength in ffmpeg is expressed in bit, so that 0.005*255 is about 1.

Dan

**Comment by dan64** [comment]
Doing some tests on NLMeans the sensitivity to Sigma is very high.

See a comparison: [NLMeans](https://imgsli.com/MjcyNjE2)

PMD is able to retain better the details 

See a comparison: [PMD](https://imgsli.com/MjcyNjE4) 

PMD=4 provides the same bit rate and denoise of NLMeans with Sigma = 0.002
but is able to retain better the details, see: [PMD vs NLMeans](https://imgsli.com/MjcyNjE5)

I think that the default S=0.005 is too high because is removing too many details and should be lowered to S=0.002.

Dan

**Comment by rigaya** [comment]
vpp-nlmeans is not implemted to be equivalent to other implementations.

I disagree to change the default parameter, please set the sigma parameter to lower the strength of it, as that is why the parameter can be changed by command line option.
