### ISSUE TITLE
HDDの接続が妙に切れたりする

### ISSUE THREAD

**Issue by YKefasu** [rigaya/NVEnc#595]
主にエンコード用のデータはSSDにおいてあるんですが、別の用件に使うHDDが接続してるんです。
エンコードしてる時に途中でHDDが妙にカチャッと鳴って接続切れたりされるんです。デバイスマネージャにもたまに消えたりします。使用が0％でもそのようなんです。もう年取ってるかと思って最近新しくもう1つのHDDを買ったんですけど、また新品のHDDにも起こっています。ウィンドウズも再インストールしましたがダメでした。

自分は英語より日本語のほうが書きやすいと思ってまだ独学してるんですけど、わかりにくい言葉があればすみません…

**Comment by YKefasu** [comment]
以下の解決策を試したけど結果はダメでした
1. ウィンドウズも再インストール
2. 新品のHDD
3. NVIDIAドライバー537.58、555.85、555.99

環境はStaxRip v2.40
NVEncC (x64) 7.54 (r2867) by rigaya, May 28 2024 12:36:06 (VC 1929/Win)
OS Version     Windows 11 x64 (22631) [UTF-8]
CPU            Intel Core i3-10100 @ 3.60GHz [TB: 4.10GHz] (4C/8T)
GPU            #0: NVIDIA GeForce RTX 2060 (2176 cores, 1650 MHz)[PCIe3x16][537.58]
NVENC / CUDA   NVENC API 12.1, CUDA 12.2, schedule mode: auto

**Comment by rigaya** [comment]
HDD搭載のシステムで試したことが最近ないのではっきりとはいえませんが、エンコーダがHDDの挙動に影響することは考えにくく、申し訳ないですが思い当たることがありまん。

個人的には、Windowsの電源オプションの詳細でハードディスクの欄に「次の時間が経過後、ハードディスクの電源を切る」の項目がありますが(多言語でどういう表記かわかりませんが)、これを「なし」などにすると改善するかもとは思いました。

**Comment by YKefasu** [comment]
原因がわかりました。
storport.sysはGPUが使用中のCPUコアを乗っけようとして、DPC遅延がはねちゃってHDDが落ちたんです。
![スクリーンショット 2024-06-24 041139](https://github.com/rigaya/NVEnc/assets/129555908/495dc4b0-1dad-4977-ad12-29cff7634eae)

Intel(R) 400 Series Chipset Family SATA AHCI Controllerドライバーの不具合らしいです。
対策はHDDを一旦無効にするしかないです😓
