### ISSUE TITLE
CQP Value does not appear to scale correctly with large input videos

### ISSUE THREAD

**Issue by Kim2091** [rigaya/NVEnc#597]
When re-encoding large videos, CQP does not appear to scale properly past a certain point.

For example, with a 1.6 GB FFV1 lossless video, I attempted to re-encode it down to 25 MB. Doing so is impossible with CQP in your encoder.

Setting CQP 21 or CQP 48 does not matter, as it yields nearly the exact same video size and quality (of about 480 MB). I cannot get it lower. Switching to VBR does allow it to function properly however.

This also applies to QSVEnc. I will open a separate issue there

**Comment by rigaya** [comment]
Unfortuantely, I’m not able to find problem with CQP.

I've tested below in bat file, and scales perfectly well.

for %%i in (10 15 20 25 30 35 40 45 50) do NVEncC64.exe -i input.mp4 -o test_%%i.mp4 --log test_%%i.log --cqp %%i

CPU            12th Gen Intel Core i9-12900K [4.97GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 4080 (9728 cores, 2505 MHz)[PCIe4x16][555.85]

![image](https://github.com/rigaya/NVEnc/assets/815947/6338e482-ceb8-40c3-b592-8e9ca5620c20)

**Comment by Kim2091** [comment]
I appreciate your response. I will get back to you with a sample test clip that I know has been problematic, and some results.

**Comment by Kim2091** [comment]
Of course, right after I open the issue on GitHub I am unable to reproduce it...

My tests are now aligning with yours for NVEnc. I tested HEVC and AV1. They all scale properly. I will close this issue, thank you

**Comment by rigaya** [comment]
Thank you for your update and closing the issue.

Bit weird, but nice that now you don't have the problem
