### ISSUE TITLE
New --vpp-fft3d filter doesn't seem to do much?

### ISSUE THREAD

**Issue by agressiv** [rigaya/NVEnc#598]
--vpp-fft3d doesn't seem to actually denoise anything.  Even with maximum denoising on a grainy video, it's hardly doing anything.   When I compare stills, I have a hard time finding anything different, even in noisy scenes.

Amount = 1 (default) doesn't seem to degrain at all.  In some cases the file size is _**larger**_ than a video without any filters.
Amount = 0 degrains a bit?  But it's hardly measurable or noticeable.   

I was really hoping for a high quality denoiser that can be done in hardware so that I don't have to resort to (much slower) avisynth/vapoursynth scripts.

I loaded up neo_fft3d and it denoises quite a bit.  I wouldn't expect identical results but I'm wondering if something got missed?...

- Source Video size: 288MB
- Encoded Video w/out any denoiser:  51.6MB
- Encoded Video with --fft3d amount=1 (max denoise): 52.5MB
- Encoded Video with --fftd amount=0: 46.3MB
- Encoded Video with neo_fft3d() in Avisynth default settings: 21.7MB

**Comment by rigaya** [comment]
The first option to use when you want to adjust the strength of fft3d is ```sigma```, and not ```amount```.

I think you should let ```amount``` default, and try increasing value of ```sigma``` (default=1.0, 0.0 - 100.0).

**Comment by agressiv** [comment]
Adjusting sigma does nothing at all.  File sizes are all identical with sigma 10,20,30,40,50, all the way up to 100.

Looks like this parameter works in QSVEnc, but has no effect in NVEnc.

**Comment by rigaya** [comment]
Thanks for testing, it seems to be a bug of fft3d, I'll check and have it fixed.

**Comment by rigaya** [comment]
sigma not working shall be fixed with [NVEnc 7.56](https://github.com/rigaya/NVEnc/releases/tag/7.56), please have a try.

**Comment by agressiv** [comment]
thanks, this is now working!
