### ISSUE TITLE
Max Bitrate limited to ?

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#6]
`NVEncC --y4m -i - --fps 25.000 --codec h265 --profile main --level 5.1 --sar 1:1 --lookahead 16 --vbrhq 30000 --max-bitrate 40000 --gop-len 0 --bframes 0 --ref 3 --mv-precision Q-pel --cu-max 32 --cu-min 8 --output "H:\Temp\Test-AC3-5.1_16_30_58_7910_01.265"`
work fine, but 
when I use a higher max-bitrate in example 45000, I get:
`Failed to Initialize the encoder
.: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)`
Is this some limitation of the SDK or is this some limitation of NVEnc which could be changed.
 (HEVC itself should allow way higher datarates, see: https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding_tiers_and_levels)

**Comment by rigaya** [comment]
It is limited by the level, with level 5.1, the bitrate is limited to 40000kbps.

| Level | Max Btrate (kbps) |
|-------|-------------------|
| 5     | 25000             |
| 5.1   | 40000             |
| 5.2   | 60000             |
| 6     | 60000             |
| 6.1   | 120000            |
| 6.2   | 240000            |

For max bitrate 450000, please use --level 5.2, or just keep it auto.

**Comment by Selur** [comment]
Thanks
