### ISSUE TITLE
ngx vsr filter

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#605]
The NVIDIA programming guide shows that the filter ngx vsr (DLVSR) is for generation of high resolution videos from low resolution. Scale factor 2 or 3.
But in NVEncC we can use other scale factors, and downscaling too.
Is then the AI working? And what scaling algorithm is used?

**Comment by rigaya** [comment]
I don't get the point, is there any problem with the resizing? Please let me know the actual issue you are having, like errors or unexpected artifacts.

When --vpp-resize ngx-vsr is selected, resizing is done totally by calling ngx vsr function, and not other functions. It should be doing well internally, as I don't face any problems as far as I have tried.

**Comment by fzold** [comment]
No problem. I just doubt wether deep learning is working.
In their programming guide
[https://docs.nvidia.com/rtx/ngx/programming-guide/index.html]()
5.3. DLVSR (CUDA Only) they state:

```
The following parameters are supported by DLVSR:
...
Scale   -   Super-resolution scale factor (2 or 3).
```
Maybe there are updates to the function. I don't know.

**Comment by fzold** [comment]
Now I think you made the **rtx Video Super Resolution** implementation, not ngx vsr. You should rename the function.
[https://blogs.nvidia.com/blog/rtx-video-super-resolution/](https://blogs.nvidia.com/blog/rtx-video-super-resolution/)
Working with driver and RTX 40 or 30 Series GPU, and nearly all content.

I have a RTX 4060 laptop GPU.

**Comment by fzold** [comment]
Now I think you implemented the **RTX Video Super Resolution**, not ngx vsr. You should rename it.
[https://blogs.nvidia.com/blog/rtx-video-super-resolution/](https://blogs.nvidia.com/blog/rtx-video-super-resolution/)
It is working with driver and RTX 40 and 30 Series GPUs, and nearly all content.

I have a RTX 4060 Laptop GPU.

**Comment by rigaya** [comment]
RTX Video SDK is a wrapper of NGX SDK, as you can find writings below in the documents included in RTX Video SDK.

![image](https://github.com/user-attachments/assets/b20b2ba6-f329-4c2e-81d5-aafbc8f5d3fc)

Therefore, I think either naming can be fine. Moreover, now that it is already out named it as ```ngx-vsr```, I don't think it is worth renaming it, anyway it's function is VSR.

> No problem

I'll close the issue as the implementation seems to be fine.
