### ISSUE TITLE
v7.58: "cspconv: unsupported csp conversion: yv12(16bit) -> p010." when enabling vpp-ngx-truehdr filter

### ISSUE THREAD

**Issue by tazlord** [rigaya/NVEnc#606]
Hello,
First, thanks for this software. I have been using it for years and it's amazing!

The Problem:
I recently upgraded to v7.58 and started noticing a strange message being repeated when trying to encode a video with the `vpp-ngx-truehdr` filter enabled (see output below). This issue did not exist in v7.57 (tested and verified).

The source is media an MKV file that contains a raw rip of a blu-ray source (movie).
This has been tested on multiple sources of the same type.

Below is the command-line I am using that produces the message.
> nvencc64.exe --avhw --preset quality --codec hevc --vbr 49152 --vbr-quality 1 --multipass 2pass-full --qp-init 16 --lookahead 32 --lookahead-level 0 --aq-temporal --aq-strength 0 --mv-precision Q-pel --output-res 3840x2160 --vpp-resize algo=nvvfx-superres,superres-mode=1,superres-strength=1.0 --vpp-ngx-truehdr contrast=100,saturation=100,middlegray=50,maxluminance=1000 --vpp-nvvfx-model-dir [path-to-model-dir] --profile main10 --level 5.1 --tier high --input video.mkv --output output.mkv

Below is the output from running the command:
> NVEncC (x64) 7.58 (r2955) by rigaya, Aug  1 2024 09:23:01 (VC 1929/Win)
> OS Version     Windows 10 x64 (19045) [UTF-8]
> CPU            AMD Ryzen 9 5900X 12-Core Processor [4.91GHz] (12C/24T)
> GPU            #0: NVIDIA GeForce RTX 3080 Ti (10240 cores, 1695 MHz)[PCIe4x16][560.70]
> NVENC / CUDA   NVENC API 12.2, CUDA 12.6, schedule mode: auto
> Input Buffers  CUDA, 44 frames
> Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
> Vpp Filters    cspconv(nv12 -> yv12(16bit))
>                resize: nvvfx-superres 1920x1080 -> 3840x2160
>                            nvvfx-superres: cspconv(yv12(16bit) -> bgr(fp32))
>                                            nvvfx-superres: mode: 1 (aggressive), strength 1.00
>                                            cspconv(bgr(fp32) -> yv12(16bit))
>                ngx-truehdr: colorspace: cspconv(yv12(16bit) -> yuv444(16bit))
>                            matrix:bt709->GBR
>                             cspconv(rgb(fp32) -> rgb32)
>                             ngx-truehdr: contrast: 100, saturation: 100, middleGray: 50, maxLuminance: 1000
>                             cspconv(rgba(fp16) -> rgb(fp32))
>                             colorspace: prim:bt709->bt2020
>                            transfer:linear->smpte2084
>                            matrix:GBR->bt2020nc
>                cspconv(yuv444(16bit) -> p010)
> Output Info    H.265/HEVC main10 @ Level 5.1
>                3840x2160p 0:0 23.976fps (24000/1001fps)
>                avwriter: hevc => matroska
> Encoder Preset quality
> Rate Control   VBR
> Multipass      2pass-full
> Bitrate        49152 kbps (Max: 153600 kbps)
> Target Quality 1.00
> Initial QP     I:16  P:16  B:16
> QP range       I:0-63  P:0-63  B:0-63
> QP Offset      cb:0  cr:0
> VBV buf size   auto
> Split Enc Mode auto
> Lookahead      on, 32 frames, Level 0, Adaptive I, B Insert
> GOP length     240 frames
> B frames       3 frames [ref mode: middle]
> Ref frames     3 frames, MultiRef L0:auto L1:auto
> AQ             on (temporal, strength auto)
> CU max / min   auto / auto
> Others         mv:Q-pel
> cspconv: unsupported csp conversion: yv12(16bit) -> p010.
> cspconv: unsupported csp conversion: yv12(16bit) -> p010.
> cspconv: unsupported csp conversion: yv12(16bit) -> p010.

Please let me know if you need more information and I will be happy to provide it.

**Comment by rigaya** [comment]
I'll have the issue closed, as the problem should have been fixed in NVEnc 7.59.
