### ISSUE TITLE
Seeking Insights on Audio Encoder Channel Layouts

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#611]
Hello,

I've been using NVEncC for video encoding, and I'm trying to understand better the limitations of audio channel layouts for different encoders. 

```
NVEncC (x64) 7.59 (r2957) by rigaya, Aug  2 2024 12:45:34 (VC 1929/Win)
  [NVENC API v12.2, CUDA 10.1]
 reader: raw, y4m, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]

Environment Info
OS : Windows 11 x64 (22631) [UTF-8]
CPU: 12th Gen Intel Core i9-12900K [4.91GHz] (8P+8E,16C/24T)
```

I've encountered some constraints during my tests, and I'd like to inquire about these.

Observations and Limitations:

```
EAC3 Encoder:


Unsupported Layout: 7.1
Supported Layouts: mono, stereo, 3.0(back), 3.0, quad(side), quad, 4.0, 5.0(side), 5.0, 2 channels (FC+LFE), 2.1, 4 channels (FL+FR+LFE+BC), 3.1, 4.1, 5.1(side), 5.1

```

```
DCA Encoder:

Unsupported Layout: 7.1
Supported Layouts: mono, stereo, quad(side), 5.0(side), 5.1(side)
```

```
TrueHD Encoder:

Unsupported Layouts: 7.1 and 5.1
Supported Layouts: mono, stereo, 2.1, 3.0, 3.1, 4.0, 4.1, 5.0(side), 5.1(side)

```
During my testing, I attempted to use the 5.1(side) layout with the TrueHD encoder but received an error message indicating that it was unsupported.

My Inquiry
- Are these limitations inherent to the encoders, or are there specific configuration options that could support these layouts?
- Is there any way to enable support for the 7.1?

I'd appreciate any guidance or suggestions on better understanding these encoder constraints and optimising my use of NVEncC. 
Thank you so much for your help!

**Comment by rigaya** [comment]
I might have messed up with "5.1(side)" and "5.1", I'll have a check.

About 7.1ch support,

> Are these limitations inherent to the encoders, or are there specific configuration options that could support these layouts?

It is limitation of the encoder itself.

> Is there any way to enable support for the 7.1?

Please have a try with ```--audio-codec libopus```.

**Comment by quamt** [comment]
> I might have messed up with "5.1(side)" and "5.1", I'll have a check.

I will leave the ticket open in that case.


> About 7.1ch support,
> 
> > Are these limitations inherent to the encoders, or are there specific configuration options that could support these layouts?
> 
> It is limitation of the encoder itself.
> 
> > Is there any way to enable support for the 7.1?
> 
> Please have a try with `--audio-codec libopus`.

Thank you very much for the information.
I will check if this is supported by the player.

**Comment by rigaya** [comment]
I've improved handling of "5.1(side)" in [NVEnc 7.62](https://github.com/rigaya/NVEnc/releases/tag/7.62), now can be encoded with "5.1(side)".

**Comment by quamt** [comment]
Thank you :-)
