### ISSUE TITLE
Latest version is broken? All my encoding commands now get errors.

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/NVEnc#612]
Hello, the latest version seems to have broken all commands i use.

See the debug:

[matroska,webm @ 00000270f30fe540] Before avformat_find_stream_info() pos: 1773 bytes read:32768 seeks:0 nb_streams:3
[matroska,webm @ 00000270f30fe540] parser not found for codec prores, packets or times may be invalid.
[prores @ 00000270f3693a00] Auto bitdepth precision. Use 12b decoding based on codec tag.
[matroska,webm @ 00000270f30fe540] Non-increasing DTS in stream 1: packet 3 with DTS 39, packet 4 with DTS 39

This command for high bitrate testing used to work with the previous version and now fails.

--mv-precision q-pel --ref 5 --nonrefp --weightp --output-buf 2048 --lookahead 32 --gop-len 240 --multiref-l0 4 --multiref-l1 3 --vbr 285000 --vbr-quality 0.1 --vbv-bufsize 320000 --max-bitrate 285000 --qp-min 1 --qp-max 1

I get the same for everything now (ProRes 4444XQ HDR sources as always) with software decoder.

I don't understand, what changed? Thanks.

**Comment by VisionHDR** [comment]
I get errors:

Completely random but even more when i try --lookahead-level more than 0 (default) 2, 3 ... sometimes it encodes and sometimes i get:
nvenc : Failed to Initialize the encoder
nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

This version is broken, not sure what changed honestly.

I go back to the previous release and all works smooth.

**Comment by Jigsawbg** [comment]
I tried same settings and have no issue with encoding. But, I tried with m2ts, because don't have ProRes 4444XQ HDR source. If someone can link few seconds file for download. . . I will try. 
However, I don't get an encoding error, but I get the following message: `weighted prediction with B frames unsupported.`
I can't see `weighted prediction B frames` command. Which command of all refers to this?

**Comment by rigaya** [comment]
```weighted prediction with B frames unsupported``` means ```--weightp``` cannot be used with B frames (which is enabled by default). It is no problem that this message is shown.

**Comment by Jigsawbg** [comment]
Ah…Thank you Rigaya for your clarification! I just misunderstood the message.

**Comment by rigaya** [comment]
I'll close this issue as the topic seems to be resolved.
