### ISSUE TITLE
Encoder only retains Dolby Vision when video contains both Dolby Vision and HDR10+

### ISSUE THREAD

**Issue by Demicro** [rigaya/NVEnc#613]
Description:

When processing a video that contains both Dolby Vision and HDR10+ metadata, the encoder only retains the Dolby Vision stream and omits the HDR10+ metadata. As a result, the output file loses HDR10+ compatibility.

Comparison of HDR metadata in original and processed files:

Original file (DV + HDR10+):

```
HDR format                  : Dolby Vision, Version 1.0, Profile 7.6, dvhe.07.06, BL+EL+RPU, no metadata compression, Blu-ray compatible / SMPTE ST 2094 App 4, Version HDR10+ Profile B, HDR10+ Profile B compatible
```
Processed file (DV only, no HDR10+):

```
HDR format                  : Dolby Vision, Version 1.0, Profile 7.6, dvhe.07.06, BL+RPU, no metadata compression, Blu-ray compatible / SMPTE ST 2086, Version HDR10, HDR10 compatible
```
I have tried changing to profile 8.1 in case there are compatibility problems but that should not be the case if profile 7.6 can contain the hdr10+ along with the DV, I have also tried extracting the json and instead of using the copy mode I use the external file and this way it works.

**Comment by rigaya** [comment]
Thank you for pointing out the issue.

I've found that --dhdr10-info copy is not working when --dolby-vision-rpu copy is used. I'll have it fixed in the next release.
