### ISSUE TITLE
Another issue? Tag text incompatible with output codec error

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/NVEnc#615]
Hello,

I keep having issues with the last version, now when i try to encode a MOV ProRes , i get this error all the time no matter what i try to use in the commands...

[mov @ 0000017ae826e940] Tag text incompatible with output codec id '98314' ([0][0][0][0])
avout: failed to write header for output file: Invalid data found when processing input
[mov @ 0000017ae826e940] Tag text incompatible with output codec id '98314' ([0][0][0][0])
avout: failed to write header for output file: Invalid data found when processing input

What's wrong?

**Comment by rigaya** [comment]
The problem is the the muxer does not support the codec (probably for audio).

Please try encoding audio to other codec or try using other container such as mkv.

**Comment by VisionHDR** [comment]
> The problem is the the muxer does not support the codec (probably for audio).
> 
> Please try encoding audio to other codec or try using other container such as mkv.

I fixed it by removing "--data-copy" , strange as this was working in previous releases.

**Comment by rigaya** [comment]
Thank you for sharing ways to fix.
