### ISSUE TITLE
--vpp-smooth switch parameters usage

### ISSUE THREAD

**Issue by AYColumbia** [rigaya/NVEnc#620]
NVEncC (x64) 7.65 (r2991) by rigaya, Aug 22 2024 12:33:04 (VC 1929/Win)
  [NVENC API v12.2, CUDA 10.1]

I added the --vpp-smooth switch and tried to use some different values for its values but when I use both **qp** and **prec** the encoder fails with an invalid value for qp, e.g., `--vpp-smooth quality=6,qp=75.0,prec=fp32`

Here's a snippet from the help for the switch.
```
   --vpp-smooth [<param1>=<value>][,<param2>=<value>][...]
     enable smooth filter.
    params
      quality=<int>         quality of filter (high=higher quality but slow)
                             (default=3, 1-6)
      qp=<float>            strength of filter (default=0.00, 0.0-100.0)
      prec=<string>         Select calculation precision.
                              auto (default), fp16, fp32
```
Let me know if you need anything else.  Thanks much.

[UPDATE] After I posted this, it's now failing with "smooth: Invalid parameter (qp)." with just `--vpp-smooth qp=75.0`.  Here's a sample of my encoding command:

`"NVEncC64.exe" --device 0 --codec avc --bluray --vpp-colorspace hdr2sdr=hable,matrix=bt2020nc:bt709,colorprim=bt2020:bt709,transfer=smpte2084:bt709 --vbr 15000 --vpp-resize spline36 --output-res 1920x1080 --crop 0,264,0,264 --vpp-pad 0,132,0,132  --qp-init 18 --qp-min 14 --qp-max 32 --gop-len 12 --lookahead 32 --ref 2 --slices 4 --aq --vpp-fft3d --vpp-deband range=2,sample=2,thre=4,dither=31 --vpp-smooth quality=6,qp=100.0 --max-bitrate 18000 --vbv-bufsize 15000 --videoformat ntsc --colorprim bt709 --transfer bt709 --colorrange limited --colormatrix bt709  --log "clip.PEMLOG.txt" --input "d:\media\clip.mkv" --output "clip.avc" `

**Comment by rigaya** [comment]
I'm sorry, the --help show wrong range of qp.

The correct range of qp is 0 - 63, so lowering the value smaller than 63 will make it work.

**Comment by AYColumbia** [comment]
> I'm sorry, the --help of [--vpp-smooth](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-smooth-param1value1param2value2) shows wrong range of qp.
> 
> The correct range of qp is 0 - 63, so lowering the value smaller than 63 will make it work.

Okay, thank you.  I'll close this issue.  I'll try it later and if it still throws the error I can reopen or create another one.  Thanks again.
