### ISSUE TITLE
Question - Future Plans for libplacebo?

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#623]
@rigaya

I noticed you recently added support for libplacebo resize filters to the NVENC build (--vpp-resize), and I appreciate the new functionality! I was wondering if you have any plans to integrate other features from libplacebo in the future.

**Comment by rigaya** [comment]
Thanks, I'm planning to add "debanding" and "tone mapping" feature from libplacebo in the future.

But I must say that I'll first be trying to add libplacebo resize feature to QSVEnc (if I can) and it should take some time, so adding other features ("debanding" and "tone mapping") from libplacebo to NVEnc will be after that.

**Comment by quamt** [comment]
Thank you for the response and for the exciting news about adding debanding and tone mapping in the future.

I also wanted to ask if there are any plans to potentially add support for a pluggable, extensible custom shader system, similar to what libplacebo offers.

Do you think something like this might be feasible?

**Comment by rigaya** [comment]
For the custom shader system, I cannot say for sure that it is possible at this time, but it should be possible.

I also think it interesting, so I would like to try adding it in the future.

**Comment by Andrasolin** [comment]
how to activate YOUR OWN resize like QSVENC-Advance??? = StaxRip v.2.42.1 NVENC v.7.68

**Comment by quamt** [comment]
Thank you @rigaya l
