### ISSUE TITLE
Auto settings for --vpp-ngx-truehdr

### ISSUE THREAD

**Issue by Dendraspis** [rigaya/NVEnc#631]
Hello rigaya,

when using `--vpp-ngx-truehdr` there are no HDR settings made that are necessary for the result to be recognized and used as HDR material. A few values like the color space, transfer and color primaries are mentioned in the docs, but there are some missing.

Especially:
- `--master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)"`
- `--max-cll "1000,300"`

They are sort of special as they carry luminance values. I'm not sure how the implementation works and if it sets the sort of default 1000 fix for all videos or if it is sort of dynamically calculated, but it would be great to have that info.

In case the luminance values differ from video to video, it would be great if those 2 parameters could be set automatically as defaults and be used - if not overwritten. Maybe also if those values are fix? 🤔

Hope it was understandable.  🤦‍♂️

**Comment by rigaya** [comment]
Actually, this is duplicate of #610.

“maxluminance” option for --vpp-ngx-truehdr should match the equivalent part of the metadata, For other values, although general values for PQ shall be fine, but I’m not sure, so there will be no automatic settings.

Furthermore, --vpp-ngx-truehdr is only a vpp filter, which just converts pixel data as a image filter, just like other vpp filters. Therefore, it does nothing about metadata.

It is expected that command lines for color matrix, color primaries, transfer and other metadata are to be added manually as you have mentioned if necessary.

**Comment by Dendraspis** [comment]
Oh, somehow missed that issue.  🙄 

Okay, thank you, I guess all my questions are answered.  🙂
