### ISSUE TITLE
Build problems concerning libdovi

### ISSUE THREAD

**Issue by norbusan** [rigaya/NVEnc#632]
@rigaya さん

いつもお世話になっております。Archのnvencのmaintainerです。

うちには、nvencをビルドするとき、おかしいメッセージがでています：
```
hecking for cargo...OK
--2024-10-26 22:31:14--  https://github.com/quietvoid/dovi_tool/archive/refs/tags/2.1.2.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/quietvoid/dovi_tool/tar.gz/refs/tags/2.1.2 [following]
--2024-10-26 22:31:15--  https://codeload.github.com/quietvoid/dovi_tool/tar.gz/refs/tags/2.1.2
Resolving codeload.github.com (codeload.github.com)... 20.27.177.114
Connecting to codeload.github.com (codeload.github.com)|20.27.177.114|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘dovi_tool.tar.gz’

dovi_tool.tar.gz                        [ <=>                                                              ] 449.49K  --.-KB/s    in 0.07s   

2024-10-26 22:31:15 (6.70 MB/s) - ‘dovi_tool.tar.gz’ saved [460282]

error: no such command: `cinstall`

        Did you mean `install`?

        View all installed commands with `cargo --list`
        Find a package to install `cinstall` with `cargo search cargo-cinstall`
checking libdovi with pkg-config...Please specify at least one package name on the command line.
```
`configure`を確認しましたが、ちょっと曖昧な感じしちえます。

なにかの解決方法があれば、ぜひ教えてください。

よろしくお願いいたします。

**Comment by babiulep** [comment]
@norbusan:
1. you need to install the cargo package cinstall (check with cargo --list).
2. And you have to unpack the dovi_tool.tar.gz: the folder/directory should be "dovi_tool" immediately under the main NVEnc folder (at least that worked for me).

**Comment by rigaya** [comment]
Would you please have a check below?

1. If environment variable ```CARGO``` is set, it should point to a valid cargo path. (default is ```cargo```)
  ```CARGO``` should be passed to build_libdovi.sh [from configure script](https://github.com/rigaya/NVEnc/blob/master/configure#L559) and used [here](https://github.com/rigaya/NVEnc/blob/master/build_libdovi.sh#L21). It seems like somehow environment variable ```CARGO``` is not passed to build_libdovi.sh?

2. ```cargo-c``` needs to be installed, by ```cargo install cargo-c```.

**Comment by norbusan** [comment]
Thanks a lot @rigaya ,
the missing `cargo-c` was the problem!

I will release a new ARch build version with libdovi built in.

Thanks a lot

**Comment by rigaya** [comment]
Thank you.
Nice to have libdovi built in in your release!

**Comment by norbusan** [comment]
BTW @rigaya is the version of dovi in your source code different from upstream?
Arch has already a packaged version of libdovi, and I am testing a patch to `configure` of NVEnc to use the system-wide libdovi, if available, and if not, fall back to building it locally.

The Arch version has libdovi 3.3.1

**Comment by rigaya** [comment]
I'm using libdovi from [dovi_tools 2.1.2](https://github.com/quietvoid/dovi_tool/releases/tag/2.1.2), which seems to be the latest release for dovi_tools.

Seems to be libdovi and dovi_tools version number different?

**Comment by norbusan** [comment]
I think that is the same version ;-) The 3.3.1 comes from the `CHANGELOG` file in [`dovi_tool/dolby_vision/CHANGELOG.md`](https://github.com/quietvoid/dovi_tool/blob/main/dolby_vision/CHANGELOG.md)

**Comment by norbusan** [comment]
In fact, ffmpeg libraries on Arch already depend on libdovi, so I cannot get rid of it ;)
Here is a PR https://github.com/rigaya/NVEnc/pull/634
