### ISSUE TITLE
Tweak Filter with Default Settings Crashes Nvencc64

### ISSUE THREAD

**Issue by wwaag76** [rigaya/NVEnc#637]
If the Tweak filter is added with no changes to settings, Nvencc64 crashes.  Even the slightest change, e.g. "brightness=.000001", leads to a successful render.  Here's the command line I've used.  

nvencc64 -i <inAVS>  --codec hevc  --cqp 28 --preset default --vpp-tweak brightness=0.00,contrast=1.00,gamma=1.00,saturation=1.00,hue=0.00,swapuv=false --audio-source <inTempWav>:codec=aac;bitrate=128;delay=44 -o <outFile>.mp4

Here's the output from a simpliefied command line with  no audio.  No log is generated.

![tweak issue](https://github.com/user-attachments/assets/1689e496-801f-4875-b5b0-3a75a625d5ac)

**Comment by rigaya** [comment]
The default setting does not do anything (no changes is done by the filter), so please remove the whole "--vpp-tweak" option there, and you'll be fine.

I might fix the crush in the future.

**Comment by rigaya** [comment]
The crush when running vpp-tweak with no effect can be avoided in [NVEnc 7.73](https://github.com/rigaya/NVEnc/releases/tag/7.73).
