### ISSUE TITLE
When set option fps, master-display copy option doesnt work

### ISSUE THREAD

**Issue by bitspyer** [rigaya/NVEnc#640]
Dont know if this is a bug or a feature:

When using the 
**--fps**  option 
AND the option  
**--master-display copy** 
 the Master Display Value from the Source will not copied to the Encoded File.

**Comment by bitspyer** [comment]
ok... I thought so
would you please add this to the Documentation?

**Comment by rigaya** [comment]
I have updated the docs mentioning that --fps should be only used with --raw.
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--fps-intint-or-float

**Comment by bitspyer** [comment]
Great!
