### ISSUE TITLE
gpuinfo: Failed to init CUDA device #1 from DX11 device.

### ISSUE THREAD

**Issue by AYColumbia** [rigaya/NVEnc#641]
I had not noticed this prior to 7.73 so it looks like it's new.  The encoder moves on and encodes but wanted to report this since it may be a possible issue.  I've provided my encoding command and took a snapshot of the encoding process below.

`C:\Tools\NVEncC\NVEncC64.exe" --codec hevc --output-depth 8 --preset quality --vbr 3547 --vbr-quality 19 --qp-init 18 --qp-min 14 --qp-max 36 --max-bitrate 10000 --gop-len 69 --lookahead 32 --ref 4 --aq --vpp-pmd threshold=130.0 --vpp-deband range=4,thre=4,dither=31,rand_each_frame  --profile Main --level 5 --tier Main --videoformat ntsc  --colorrange limited  --log "video-log.txt" -i "uhd-title.mkv" -o "uhd-title.hevc"`

```
--------------------------------------------------------------------------------
uhd-title.hevc
--------------------------------------------------------------------------------
gpuinfo: Failed to init CUDA device #1 from DX11 device. <--- shown in RED
Max B frames are 0 frames. <--- shown in YELLOW
NVEncC (x64) 7.73 (r3066) by rigaya, Nov  2 2024 09:24:08 (VC 1929/Win)
OS Version     Windows 10 x64 (19045) [UTF-8]
CPU            Intel Core i7-7700K @ 4.20GHz [TB: 4.41GHz] (4C/8T)
GPU            #0: NVIDIA GeForce GTX 1060 3GB (1152 cores, 1835 MHz)[PCIe3x16][566.03]
NVENC / CUDA   NVENC API 12.2, CUDA 12.7, schedule mode: auto
Input Buffers  CUDA, 41 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 24000/1001 fps
Vpp Filters    cspconv(nv12 -> yv12)
               denoise(pmd): strength 100, threshold 130, apply 2, exp 1
               deband: mode 1, range 4, threY 4, threCb 4, threCr 4
                       ditherY 31, ditherC 31, blurFirst no, randEachFrame yes
               cspconv(yv12 -> nv12)
Output Info    H.265/HEVC main @ Level 5
               3840x2160p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   VBR
Multipass      none
Bitrate        3547 kbps (Max: 10000 kbps)
Target Quality 19.00
Initial QP     I:18  P:18  B:18
QP range       I:14-36  P:14-36  B:14-36
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 32 frames, Level 0, Adaptive I, B Insert
GOP length     69 frames
B frames       0 frames [ref mode: disabled]
Ref frames     4 frames
AQ             on (spatial, strength auto)
CU max / min   auto / auto
VUI            videoformat:ntsc,range:limited
Others         mv:auto
```
Let me know if you need any other info.  Thanks.

**Comment by simonpek88** [comment]
I noticed this error started in 7.72, 7.6x had no problem.

**Comment by rigaya** [comment]
You can just ignore the message if it is running fine.

The applications will try to go on even if the message is shown. Furthermore, error message is about device #1, but the #0 is used, so there is no problem at all.

**Comment by simonpek88** [comment]
Ok, thank you.

**Comment by AYColumbia** [comment]
> You can just ignore the message if it is running fine.
> 
> The applications will try to go on even if the message is shown. Furthermore, error message is about device #1, but the #0 is used, so there is no problem at all.

Okay thanks. Since I'm not specifying the device and only have the 1 Nvidia card, why would it try #1 at all (am assuming 0 index as you stated per #0)? Just curious. :)

**Comment by AYColumbia** [comment]
Just FYI, the error occurred when I did a device check, i.e.,

```
NVEncC64.exe --check-device

gpuinfo: Failed to init CUDA device #1 from DX11 device.
DeviceId #0: NVIDIA GeForce GTX 1060 3GB
```
