### ISSUE TITLE
--dynamic-rc cqp

### ISSUE THREAD

**Issue by raptorfx1980** [rigaya/NVEnc#642]
parsing issue --dynamic-rc

---------------------------------------------------------------------------------------------------
Parameter set in options file:
--dynamic-rc 0:498,vbr=0,multipass=2pass-full,vbr-quality=21.7
--dynamic-rc 499:997,cqp=23,multipass=2pass-full
--dynamic-rc 998:0,cqp=23:25:28,multipass=2pass-full

result in log:

DynamicRC      frame=0:498,VBR=0,vbr-quality=21.6992
               frame=499:997,CQP=998:0:0
               frame=998:end,CQP=499:997:997
settings appear correct, but the misinterpretation in the log (e.g., CQP=499:997:997,and CQP=998:0:0) suggests a parsing issue with cqp

Verbesserung:
 -vbr-quality <float>, -vbr-quality <float>:init i:init p:init b
 Bsp: -vbr-quality=23.0:23:25:25 (target -vbr-quality=23.0 with init qp i=23,init qp p=25, init qp b=25)

Verbesserung  -vbr-quality with init for i p b als Parameter for fine tuning init of qp in  -vbr-quality

**Comment by raptorfx1980** [comment]
cqp=<int> or cqp=<int>:<int>:<int>
wurde ja richtig gesetzt als value

**Comment by raptorfx1980** [comment]
value ist ja int

**Comment by rigaya** [comment]
Thank you for pointing out the issue.

The parsing of cqp in --dynamic-rc seems to be wrong, I'll have it fixed in the next release.

**Comment by raptorfx1980** [comment]
Thank you for your work on this project so far, I think that my suggestion for improvement in terms of extending the parameters for -vbr-quality could be helpful, if --dynamic-rc supports I P B init to be set , like --qp-init <int> or <int>:<int>:<int> in dynamic-rc environment

**Comment by rigaya** [comment]
Thank you for reporting, [NVEnc 7.74](https://github.com/rigaya/NVEnc/releases/tag/7.74) should have fixed the cqp issue.

> if --dynamic-rc supports I P B init to be set , like --qp-init but in dynamic-rc environment

Unfortunately not, it does not qp-init parameter.

**Comment by rigaya** [comment]
I’ll have this issue closed as the issue has been resolved.
