### ISSUE TITLE
Cannot write the subtitle streams from Blu-ray files

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#643]
When converting Blu-Rays, NVEnc very often aborts, saying it cannot write the subtitle stream.

FFmpeg has no problems with such files. What could be the reason for this?

```
[matroska @ 00000250c3686880] Application provided invalid, non monotonically increasing dts to muxer in stream 4: 415957 >= 411494
avout: Error: Failed to write subtitle stream 4 frame: Invalid argument.
[matroska @ 00000250c3686880] Application provided invalid, non monotonically increasing dts to muxer in stream 4: 416791 >= 411494
avout: Error: Failed to write subtitle stream 4 frame: Invalid argument.
[matroska @ 00000250c3686880] Application provided invalid, non monotonically increasing dts to muxer in stream 4: 418042 >= 412412
avout: Error: Failed to write subtitle stream 4 frame: Invalid argument.
[matroska @ 00000250c3686880] Application provided invalid, non monotonically increasing dts to muxer in stream 4: 418042 >= 412412
avout: Error: Failed to write subtitle stream 4 frame: Invalid argument.
[matroska @ 00000250c3686880] Application provided invalid, non monotonically increasing dts to muxer in stream 4: 418042 >= 413871
avout: Error: Failed to write subtitle stream 4 frame: Invalid argument.
[matroska @ 00000250c3686880] Application provided invalid, non monotonically increasing dts to muxer in stream 4: 418042 >= 413871
avout: Error: Failed to write subtitle stream 4 frame: Invalid argument.
[matroska @ 00000250c3686880] Application provided invalid, non monotonically increasing dts to muxer in stream 4: 418042 >= 415957
avout: Error: Failed to write subtitle stream 4 frame: Invalid argument.
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error occurred in ProcessOutput: 20
Error FlushEncoder: 20.
```

[Example Blu-Ray, which is then converted to an mkv file with DVDFab](https://moviehunterz.cc/threads/caligula-1979-remastered-uncut-kinofassung-dual-complete-bluray-mama.124007/)

Command
`nvencc64.exe --thread-priority all=lowest --avhw -i "Movie.mkv" -c hevc --profile main --tier high --level auto --preset quality --qvbr 26 --aq-temporal --aq-strength 0 --lookahead 20 --lookahead-level 0 --tf-level 0 --bframes 4 --ref 4 --bref-mode middle --audio-codec ac3 --audio-bitrate 384 --sub-copy --chapter-copy -o "Output.mkv"`

**Comment by rigaya** [comment]
The timestamp of the subtitle seems to be somehow messed up.

It seems difficult and I think I shouldn't download the whole file, so would you please add ```--log-packets input_packets.log``` and attach input_packets.log? (The log size might be big so it might be better to compress by zip)

**Comment by rainman74** [comment]
> --log-packets input_packets.log

[input_packets.zip](https://github.com/user-attachments/files/17691612/input_packets.zip)

and the subtitles as mks (from the same Blu-Ray to match the log):
[subtitles.zip](https://github.com/user-attachments/files/17691617/subtitles.zip)

**Comment by rigaya** [comment]
Thank you for the log and the input subtitle file, that helped me a lot. The input file had subtitle packets not in order as below.

```
stream  0,         h264,       478728,       478645,   41, 0,   1652290886
stream  0,         h264,       478687,       478687,   41, 0,   1652515539
stream  3, hdmv_pgs_subtitle,       470011,       470011,    0, 1,   1652637317
stream  3, hdmv_pgs_subtitle,       473890,       473890,    0, 1,   1652637354
stream  3, hdmv_pgs_subtitle,       471471,       471471,    0, 1,   1652652324
stream  0,         h264,       478853,       478728,   41, 0,   1652661400
stream  0,         h264,       478770,       478770,   41, 0,   1652912834
stream  0,         h264,       478812,       478812,   41, 0,   1652981337
stream  3, hdmv_pgs_subtitle,       473640,       473640,    0, 1,   1653049559
stream  3, hdmv_pgs_subtitle,       476726,       476726,    0, 1,   1653049595
stream  0,         h264,       478978,       478853,   41, 0,   1653077708
stream  0,         h264,       478895,       478895,   41, 0,   1653308162

```

This part, stream 3 has packets in time 470011, 473890, 471471, 473640, 476726. Somehow 473890 was coming in front of 471471, 473640, and that was causing the issue.

[NVEnc 7.74](https://github.com/rigaya/NVEnc/releases/tag/7.74) will now be able avoid the error, by sorting the subtitle packets not in order in the input file.

**Comment by rainman74** [comment]
Thank you @rigaya 👌

**Comment by rainman74** [comment]
@rigaya Just a small note: Could you perhaps avoid all the debug output and just show that PGS have been sorted? The current displays now make it rather confusing :-(

![image](https://github.com/user-attachments/assets/cdb64478-2caf-43e1-b860-7e756be88ca8)

**Comment by rigaya** [comment]
I originally thought this sorting was unnecessary and created it as a workaround, so I intentionally have shown this as a warning.

However, as it somehow seems to be so many of them, it would be better not to display them. I will change in next update to not be displayed.

**Comment by rainman74** [comment]
Fine, thank you!

**Comment by rigaya** [comment]
Now the warning logs will no show up in [NVEnc 7.75](https://github.com/rigaya/NVEnc/releases/tag/7.75).

**Comment by rigaya** [comment]
I've made a new test build addressing for the message, does the build below work?
https://nightly.link/rigaya/NVEnc/actions/runs/12008253627/NVEncC_release_r3098_x64.zip

**Comment by rainman74** [comment]
> I've made a new test build trying to silence the message, does the build below work? https://nightly.link/rigaya/NVEnc/actions/runs/12008253627/NVEncC_release_r3098_x64.zip

Looks very good 👌

![image](https://github.com/user-attachments/assets/21fa2f66-638c-4a55-9235-6411d3fe65ee)

**Comment by rigaya** [comment]
Great!

The change will be included in next release. Please use the test build untill the next release.
