### ISSUE TITLE
Remaining time display

### ISSUE THREAD

**Issue by Dendraspis** [rigaya/NVEnc#644]
Hello rigaya,

sorry for that one, but it seems like this code adding 500(ms?) to the remaining time...

https://github.com/rigaya/NVEnc/blob/ab4c3976072e00d21fe205381261ef98f34f25e0/NVEncCore/rgy_status.cpp#L261-L269

...leads sometimes to an output of something like:  `remain 0:10:60`, which can be pretty annoying.  Don't know if you want to improve it...
At least it has been reported to me twice already.

PS:  Don't beat me for that.  😅

**Comment by rigaya** [comment]
> which can be pretty annoying

really?

I might remove +500 in the future.

**Comment by Dendraspis** [comment]
I looks pretty weird, but absolute minor ... just wanted to report it anyway.  😅

**Comment by rigaya** [comment]
+500 has been removed in [NVEnc 7.75](https://github.com/rigaya/NVEnc/releases/tag/7.75).

**Comment by Dendraspis** [comment]
Then we can definitely close this issue...

Thank you.
