### ISSUE TITLE
dovi-profile copy noy supported in this build!

### ISSUE THREAD

**Issue by deathvenom-qvp** [rigaya/NVEnc#646]
Unsupported  build on 20.04

**Comment by rigaya** [comment]
--dovi-profile copy requires Ubuntu 24.04, as it requires libavformat60 (ffmpeg 6.x) or later, and is not supported in Ubuntu 20.04/22.04 build.

**Comment by rigaya** [comment]
I’ll have this issue closed as the question has been answered.
