### ISSUE TITLE
Parameters for vpp-libplacebo-deband broken

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#647]
The parameters for vpp-libplacebo-deband are broken. It works neither with the underscore according to the documentation nor without it.

```
--vpp-libplacebo-deband grainY=20.0,grainC=-1.0
--vpp-libplacebo-deband grain_y=20.0,grain_c=-1.0

```
![image](https://github.com/user-attachments/assets/b5777750-0a52-4fd0-8b3f-e462c2a399a3)

![image](https://github.com/user-attachments/assets/8ad2afc1-351b-47a7-b068-4fecec60e0bd)

**Comment by rigaya** [comment]
Thank you for reporting the isseu!

The command line parser for ```grain_y``` and ```grain_c``` has been fixed in [NVEnc 7.76](https://github.com/rigaya/NVEnc/releases/tag/7.76).
