### ISSUE TITLE
Failed to get DoVi RPU - Dolby Vision issue with v7.75

### ISSUE THREAD

**Issue by Dendraspis** [rigaya/NVEnc#648]
Hello rigaya,

with v7.75 there is an issue when using DoVi RPU with H265 codec::
![image](https://github.com/user-attachments/assets/4a139581-f883-4637-b8d9-9a8f549946ff)

```
bitstream: Failed to get dovi rpu for 1435.
bitstream: Failed to get dovi rpu for 1433.
bitstream: Failed to get dovi rpu for 1432.
bitstream: Failed to get dovi rpu for 1434.
bitstream: Failed to get dovi rpu for 1439.
bitstream: Failed to get dovi rpu for 1437.
bitstream: Failed to get dovi rpu for 1436.
bitstream: Failed to get dovi rpu for 1438.
encoded 1440 frames, 59.61 fps, 8776.46 kbps, 62.84 MB
```

The encode finishes after a while, but continues to print those messages.
With v7.74 there are no issues reported.

Command Line I have used for testing:
`--qvbr 28 --codec h265 --preset p7 --output-depth 10 --profile main10 --lookahead 10 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)" --dhdr10-info "A:\_StaxRip-Test\Hybrid HDR10Plus DV Sample.mkv_temp\HDR10PlusMetadata.json" --dolby-vision-profile 8.1 --dolby-vision-rpu "A:\_StaxRip-Test\Hybrid HDR10Plus DV Sample.mkv_temp\HDRDVmetadata.rpu" --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --max-cll "598,273" --chromaloc 2 --aud --repeat-headers`

**Comment by rigaya** [comment]
Thank you for reporting the issue, fix has been made for the error caused in NVEnc 7.75.

[NVEnc 7.76](https://github.com/rigaya/NVEnc/releases/tag/7.76) should have no problem and the error message will be removed. Also, using --dhdr10-info and --dolby-vision-rpu will be handled better.

**Comment by Dendraspis** [comment]
I confirm, that it is solved.  Thank you.
