### ISSUE TITLE
Negative int parameters for --vpp-ngx-truehdr 

### ISSUE THREAD

**Issue by k6G52m4Dz75W** [rigaya/NVEnc#649]
First of all, thanks for this amazing app!
Though it seems that this ngx-TrueHDR is not the same as RTX Video HDR, it really shares some similiar settings and according to the guide for RTX Video HDR here: https://www.reddit.com/r/nvidia/comments/1b03yfg/rtx_hdr_paper_white_gamma_reference_settings/ , the best default parameters for max luminence of 1000 should be +25 Contrast, -25 Saturation and +44 mid-gray. So would you please add negative int parameters support for this option and default them to the previous numbers?
Thanks in advance. And if I'm wrong, please share me more details on this.

**Comment by rigaya** [comment]
Thank you for your comments.
I'm using RTX Video SDK 1.0.2 header file to integrate NGX TrueHDR, and the value range for --vpp-ngx-truehdr is based on the  has definition in the header file, and it seems to have no negative value.

![image](https://github.com/user-attachments/assets/fb502fb7-07d3-492a-ae87-46fdbc22fa5f)

I'm pretty unsure if the parameter mapping is the same although it's name is the same.

**Comment by k6G52m4Dz75W** [comment]
Thanks for your quick response. I've compared the values in the panel of Nvidia app with the ones in the image you provided, I'm almost sure that they use identical algorithm except that they have different "base" numbers to count. The parameters in the sdk are based on 100 instead of 0, so the equivilant values for max luminence of 1000 should be 125 Contrast, 75 Saturation and 44 MiddleGray. And I've made an experiment with this combination whose result is fantastic. Please consider change the default values to these. Thanks again!

**Comment by rigaya** [comment]
Thank you for sharing the information.

I've applied the changed to the default value of contrast and saturation for --vpp-ngx-truehdr in [NVEnc 7.76](https://github.com/rigaya/NVEnc/releases/tag/7.76).

**Comment by rigaya** [comment]
I'll close the issue as the change has been applied in NVEnc 7.76.
