### ISSUE TITLE
Deinterlace video /  Analysing + Auto detecting interlacing

### ISSUE THREAD

**Issue by zenomag** [rigaya/NVEnc#650]
Hello, I would like to know if it **is** possible or if there is a way within the available options to detect the type of interlacing a video **has.** Many blurays have interlacing, some are fakes, some are hybrid, some are more complex. etc

**Analysing + Auto detecting interlacing type**

For those who will comment that the only optimal way to know and detect the type of interlacing in a video is to check it yourself and that your eye is the best detector ..... I already know that,  thanks :)

Please is there such an option or would it be possible to add it? I know that the Megui program has a source analyser and it detects the type of interlacing and also tells you which filter would be better to use, etc. Is there anything similar here? thanks.

![image](https://github.com/user-attachments/assets/c19cb469-bc8b-4a6e-9cb6-5b34c73041d6)
![image](https://github.com/user-attachments/assets/cc02aa41-aaab-4ef8-9433-361fce86df0f)

**And a second question, for example, what would be the equivalent of these Avisynth filters in NVEncc?**

tfm(order=1)             --------------------  (http://avisynth.nl/index.php/TIVTC/TFM)
tdecimate(hybrid=1) ---------------  (http://avisynth.nl/index.php/TIVTC/TDecimate)

Thanks for the help and I hope you can help me.

**Comment by rigaya** [comment]
I'll close the issue, as answer is provided and there are no plan for new implementation.
