### ISSUE TITLE
Question about Level 5.1 Limitation with HDR and 4K Upscaling

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#652]
Hello @rigaya,

I encountered an issue when attempting to upscale a 1920x1080 video to 4K while using `--level 5.1`. The encoder fails to initialize with the following error:

```
nvenc : Failed to Initialize the encoder
nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)
```

When I switch to `--level 6` or `--level auto`, the encoding works as expected. 

My configuration is:
```
--avhw
--vbr 50000
--ref 8
--bframes 5
--output-depth 10
--pic-struct
--audio-copy
--chapter-copy
--atc-sei auto
--vpp-ngx-truehdr contrast=100,saturation=100,middlegray=50,maxluminance=1000
--master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)
--colormatrix bt2020nc 
--colorprim bt2020 
--transfer smpte2084
--max-cll 1000,300
--codec hevc 
--level auto
--profile main10 
--tier high
--output-res -4x2160
--vpp-resize algo=ngx-vsr,vsr-quality=4
```

System Details:
```
NVEncC (x64) 7.77 (r3112) by rigaya, Dec 10 2024 09:44:50 (VC 1929/Win)
[NVENC API v12.2, CUDA 10.1]
reader: raw, y4m, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]
others
  nvml       : yes
  nvrtc      : yes
  nvvfx      : yes
  ngx        : yes
  nvof fruc  : yes
  libass     : yes
  libdovi    : yes
  d3d11      : yes
  vulkan     : no
  libplacebo : yes
  vmaf       : yes
#0: NVIDIA GeForce RTX 3060 (3584 cores, 1792 MHz)[PCIe4x16][566.36]
Avaliable Codec(s)
H.264/AVC
H.265/HEVC
```

Given my settings, the combined requirements of my configuration exceed the limits of Level 5.1 in terms of luma sample rate, bitrate, or frame rate. Switching to Level 6 resolves the issue, as it supports significantly higher limits.

Could you confirm if this is a known limitation of NVENC with Level 5.1, or if there’s a configuration I could adjust to make Level 5.1 work with this setup?

Thank you for your time and assistance.

**Comment by rigaya** [comment]
You can change as below and you'll be fine with --level 5.1 (or simply use --level auto).

```--ref 8``` → ```--ref 5```

You can always check the table below.
https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding#Tiers_and_levels

Here, you can see ```3,840×2,160@64 (6)``` for level 5.1, so MaxDpbSize <= 6 is required. Therefore, ref needs to be 5 or below (```ref = MaxDpbSize - 1```).

**Comment by quamt** [comment]
Thank you @rigaya 
Closing this as has been answered :-)
