### ISSUE TITLE
supporting mpls as input

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#69]
would be nice if .mpls files from blu-rays could be supported as input

**Comment by pwacooijmans** [comment]
would be nice if .mpls files from UHD blu-rays could be supported as input

**Comment by rigaya** [comment]
Sorry for leaving this issue, mpls should be accepted now using libbluray from bluray protocol, and [NVEnc 4.68](https://github.com/rigaya/NVEnc/releases/tag/4.68) adds --input-option so that you may select playlist to encode. Please check #209 .

**Comment by Selur** [comment]
Thanks, tested 'input-option' worked fine here :)

**Comment by rigaya** [comment]
Thanks, I'll close this issue, as mpls files are now supported.
