### ISSUE TITLE
How to set quality profiles? Can't find this option

### ISSUE THREAD

**Issue by techok** [rigaya/NVEnc#80]
4.19 added quality profiles as reading on the changelog:
· Added quality designation **profile**. 

· We removed weighted P frame from **profile** "HEVC bit rate specified high image quality". 

Can't seem to find this option? Any ideas? 

Thanks.

**Comment by rigaya** [comment]
Perhaps you are looking for the changelog of NVEnc.auo, an Aviutl plugin. ([Aviutl](http://spring-fragrance.mints.ne.jp/aviutl/) is Japanese video editting software)

For the commandline tool NVEncC, the change log is on [github releases](https://github.com/rigaya/NVEnc/releases).

**Comment by techok** [comment]
> Perhaps you are looking for the changelog of NVEnc.auo, an Aviutl plugin. ([Aviutl](http://spring-fragrance.mints.ne.jp/aviutl/) is Japanese video editting software)
> 
> For the commandline tool NVEncC, the change log is on [github releases](https://github.com/rigaya/NVEnc/releases).

Hello thanks for the reply! If it's not too much hassle,  Is it possible for you to then post here the nvencc64 commands for each of those profiles for me to try out? Would like to test the results against the commands i currently use. 

As it would be hard for me to understand Japanese. Thanks in advance!

**Comment by rigaya** [comment]
They are not something highly tuned, just a sample to show how to set the GUI. You'll also need to adjust the bitrate, it's actually rather low.

- H.264 CQP
 -c h264 --cqp 20:23:25 --qp-init 20:23:25 --lookahead 32 --gop-len auto

- H.264 bitrate mode
 -c h264 --vbr 6000 --max-bitrate 17500 --qp-init 20:23:25 --gop-len auto

- H.264 bitrate mode HQ
 -c h264 --vbrhq 6000 --max-bitrate 17500 --qp-init 20:23:25 --lookahead 32 --gop-len auto --weightp --aq --aq-temporal --aq-strength 7

- H.264 quality based mode HQ
 -c h264 --vbrhq 0 --vbr-quality 27 --max-bitrate 17500 --qp-init 20:23:25 --lookahead 32 --gop-len auto --weightp --aq --aq-temporal --aq-strength 7

- HEVC CQP
 -c hevc --cqp 20:23:25 --qp-init 20:23:25 --lookahead 32 --gop-len auto -b 0

- HEVC bitrate mode
 -c hevc --vbr 6000 --max-bitrate 17500 --qp-init 20:23:25 --gop-len auto -b 0

- HEVC bitrate mode HQ
 -c hevc --vbrhq 6000 --max-bitrate 17500 --qp-init 20:23:25 --lookahead 32 --gop-len auto -b 0 --aq --aq-temporal --aq-strength 7

- HEVC qulaity based mode HQ
 -c hevc --vbrhq 0 --vbr-quality 27 --max-bitrate 17500 --qp-init 20:23:25 --lookahead 32 --gop-len auto -b 0 --aq --aq-temporal --aq-strength 7

**Comment by techok** [comment]
Thanks a lot ! Will try and compare. ;)

**Comment by rigaya** [comment]
I'll close this issue now. Please reopen if you have any more related issues.
