### ISSUE TITLE
avcuvid: codec vc1(yuv420p) unable to decode by cuvid.

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#81]
I get the above when calling:

> "I:\Hybrid\64bit\NVEncC.exe" --avhw cuda  -i "F:\TestClips&Co\files\VC-1\00002_vc-1_24fps_1080p.m2ts" --fps 24.000 --codec h264 --profile high --level auto --sar 1:1 --lookahead 16 --cbrhq 1012 --max-bitrate 240000 --gop-len 0 --bframes 0 --ref 3 --mv-precision Q-pel --cabac --deblock --preset quality --videoformat undef --colorprim undef --transfer undef --colormatrix bt709 --vpp-resize lanczos --output-res 1920x1080 --vpp-gauss disabled --output "E:\Temp\00002_vc-1_24fps_1080p_20_20_12_4310_01.264"

but according to https://developer.nvidia.com/video-encode-decode-gpu-support-matrix my GTX 1070 ti (and a lot of other cards according to https://en.wikipedia.org/wiki/Nvidia_PureVideo) should be able to decode vc-1 without a problem. 

-> is this some framework limitation of just a missing feature?
If it's a missing feature, could VC-1 decoding be enabled in the next release?

**Comment by Selur** [comment]
Thanks!

**Comment by Truth1234** [comment]
> 
> 
> I've enabled VC-1 decoding in [NVEnc 4.20](https://github.com/rigaya/NVEnc/releases/tag/4.20). Please note there will be no support for WMV3.

Hello Rigaya!

There is some problems with the HW decoding of some VC1 videos. A header problem.

I cut out and uploaded a sample video (direct stream copy) Here is the download link: https://sendgb.com/Z7bBFzyv6h3


cuvid: Parsed header too large!
failed to init decoder.

Thank you!

**Comment by rigaya** [comment]
Thank you for your report and the sample file. 

Now it should be fixed with [NVEnc 4.23](https://github.com/rigaya/NVEnc/releases/tag/4.23).

**Comment by rigaya** [comment]
I'll close this issue as it has be resolved. Please reopen if you have any more related issues.
