### ISSUE TITLE
Is it possible there are no advantages by using more than a GTX 1060 6gb in Cuda NVEncc64 4K HEVC Encoding?

### ISSUE THREAD

**Issue by techok** [rigaya/NVEnc#82]
I'm wondering if Rigaya could reply and confirm, according to some tests made by YouTuber who use Davinci Resolve 15 in 4K , there is almost no diference at all by encoding H.264 using Cuda between the 1060 and a 2080ti.

Image: https://extraimage.net/images/2018/10/11/8a935d4fac19636073d1d444333e8088.jpg

But of course Resolve is not Nvencc64 , in this case will do improve or is still the same? 

Currently i'm getting around 60 fps encoding HEVC in 4K HDR using the nvencc64 hardware resizer to 4K ( without external filters just the resizing to 422 in vapoursynth then encoding by cuda. 

Would this actually improve using a better nvidia GPU or the 1060 Cuda is the tops?

When encoding the Video Engine is not always on 100% and the GPU is much less used of course.

**Comment by rigaya** [comment]
I've done simple benchmark using hw decode & encode with NVEncC. It seems like GTX1080 is only **slightly** better than GTX1060 6GB. Using GPU filters might show difference, but when you focus only encoding, it nearly the same.

When looking at GTX1080, video engine (VE) usage is only around 50%, there might be a chance to do 2 jobs in parallel.

I don't know about RTX20** series, might be as same as Resolve.

- Input file
HEVC 10bit / 3840x2160 / 23.976fps / 64.4Mbps / 3min21sec

- Decode (hw decode)
avcuvid: H.265/HEVC, 3840x2160, 24000/1001 fps

- Params
  - H.264 CQP
  default

  - H.264 VBRQ
   --vbrhq 0 --vbr-quality 26 --aq --aq-temporal --lookahead 32

  - HEVC CQP
   -c hevc

  - HEVC VBRQ
   -c hevc --vbrhq 0 --vbr-quality 26 --aq --lookahead 32

  - HEVC CQP
  -c hevc --output-depth 10

  - HEVC VBRQ
   -c hevc --output-depth 10 --vbrhq 0 --vbr-quality 26 --aq --lookahead 32

|      | GTX1060 6GB | GTX1080 |
| :--- | ----    | ----    |
| CPU  | i9 7980XE @ 4GHz | R7 1700 @ 3.2GHz |
| H.264 CQP | 106.43 fps, CPU: 2.9%, GPU: 10.5%, VE: 97.1% | 111.78 fps, CPU: 6.5%, GPU: 6.2%, VE: 47.8% |
| H.264 VBRQ | 78.97 fps, CPU: 2.9%, GPU: 10.9%, VE: 96.4% | 88.69 fps, CPU: 6.5%, GPU: 7.6%, VE: 52.3% |
| HEVC CQP | 90.54 fps, CPU: 2.9%, GPU: 8.7%, VE: 97.9% | 96.22 fps, CPU: 6.5%, GPU: 5.5%, VE: 49.0% |
| HEVC VBRQ | 80.95 fps, CPU: 0.5%, GPU: 12.4%, VE: 97.2% | 87.21 fps, CPU: 1.2%, GPU: 8.6%, VE: 48.9% |
| HEVC 10bit CQP | 88.21 fps, CPU: 2.9%, GPU: 10.0%, VE: 96.0% | 94.42 fps, CPU: 6.5%, GPU: 6.9%, VE: 49.0% |
| HEVC 10bit VBRQ | 75.81 fps, CPU: 0.4%, GPU: 17.1%, VE: 96.9% | 82.49 fps, CPU: 1.0%, GPU: 11.8%, VE: 49.5% |

**Comment by PhoO3nX** [comment]
Easy, 1060/1080 series do not support HEVC B Frame encoding when 2060/2080 series yes

https://developer.nvidia.com/video-encode-decode-gpu-support-matrix#Encoder

**Comment by hydra3333** [comment]
Also, https://github.com/rigaya/NVEnc/issues/114#event-2335179210 ... GTX 1650 uses Volta NVENC, and doesn't support HEVC B frame.

**Comment by pwacooijmans** [comment]
and some cards support multiple encodes at the same time just check the comment above.

**Comment by rigaya** [comment]
I’ll close the issue as the topic has been answered.
