### ISSUE TITLE
How to lower the video size by setting options?

### ISSUE THREAD

**Issue by acsway878787** [rigaya/NVEnc#83]
Hello there,
I'm really sorry for asking such stupid question, but until now I still can't figure out the way to reduce video size without changing its resolution...
Can some one give me some hints?
Sorry for this disturbing question again.

**Comment by rigaya** [comment]
Generally, lower video size (= lower bitrate) will result in lower quality.

When using --cqp, higher value for it will result lower bitrate (such as --cqp 30).

When using --vbr/--vbrhq you'll need to lower the bitrate (such as --vbrhq 5000).

So you'll just need to use options like below,
```
NVEncC64.exe -i input.mp4 -o output.mp4 --vbrhq 5000
```

Can this be an answer?

**Comment by acsway878787** [comment]
It works, thank you very much!
But can I lower the size by adding more B frames(--bframes 4)? I've searched some articles said this works.
And what's the difference between --vbr and --vbrhq?

**Comment by rigaya** [comment]
I'll close this issue now. Please reopen if you have any more related issues.
