### ISSUE TITLE
just wondering, is cuda 10 out now ?

### ISSUE THREAD

**Issue by hydra3333** [rigaya/NVEnc#84]
if so is there any advantage in migrating to use that ?

**Comment by rigaya** [comment]
CUDA version should have almost no advantage to NVEncC.

Also CUDA 10.0 does not support 32bit build, which is a problem for NVEncC, as I think there is still some need for 32bit version (for 32bit Avisynth support).

**Comment by hydra3333** [comment]
OK. Thank you.
