### ISSUE TITLE
Error "[NULL @ 0000025708e60140] missing picture in access unit" encoding UHD HDR with --avhw

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#85]
The same error when encoding h265 UHD HDR content ((
NVEnc 4.20
Driver 416.34

C:\Temp\StaxRip\Apps\NVEnc\NVEncC64.exe --avhw cuda --vbrhq 160000 --codec h265 --preset quality --output-depth 10 --ref 5 --lookahead 32 --no-b-adapt --no-i-adapt --qp-init 1 --max-bitrate 160000 --vbr-quality 21 --aq --cuda-schedule auto --output-buf 128 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --mv-precision q-pel --chromaloc 2 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) --crop 0,276,0,276 -i "C:\Temp\Ant-Man and the Wasp\Ant-Man and the Wasp (2018).[UHD.HDR].h265" -o "C:\Temp\Ant-Man and the Wasp\Ant-Man and the Wasp (2018).[UHD.HDR]_new_out.h265"

NVEncC (x64) 4.20 (r886) by rigaya, Oct 13 2018 11:20:30 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (17763)
CPU            Intel Core i7-3930K @ 3.20GHz [TB: 4.07GHz] (6C/12T)
GPU            #0: GeForce GTX 1080 (2560 cores, 1835 MHz)[416.34]
NVENC / CUDA   NVENC API 8.1, CUDA **10.0**, schedule mode: auto
Input Buffers  CUDA, 41 frames
Input Info     avcuvid: H.265/HEVC, 3840x2160, 24000/1001 fps
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main10 @ Level auto
3840x1608p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        160000 kbps (Max: 160000 kbps)
Target Quality 21.00
Initial QP     I:1  P:1  B:1
VBV buf size   auto
Lookahead      on, 32 frames
GOP length     240 frames
B frames       0 frames
Ref frames     5 frames, LTR: off
AQ             on
CU max / min   auto / auto
Others         mv:Q-pel
encoded 169979 frames, 83.52 fps, 22078.86 kbps, 18659.71 MB
encode time 0:33:55, CPU: 2.4, GPU: 7.8, VE: 50.2, GPUClock: 2037MHz, VEClock: 1822MHz
frame type IDR    709
frame type I      709,  total size    168.80 MB
frame type P   169270,  total size  18490.91 MB
**[NULL @ 0000025708e60140] missing picture in access unit**

**Comment by devil40xxx** [comment]
Hello drSHLEFF ，i use your command strings and get no error.
Have your update your  graphics driver ? Nvenc 4.xx need 390.77 or later.

**Comment by drSHLEFF** [comment]
Yes
![default](https://user-images.githubusercontent.com/11748220/47632934-31475500-db5d-11e8-90d7-ae68cfff1744.png)

**Comment by devil40xxx** [comment]
sorry  i am confuse....
Cause i check my diver it's someting like "23.21.13.9077"...2018/1/23 Microsoft Windows Hardware Compatibility Publisher etc etc

**Comment by drSHLEFF** [comment]
This error does not always appear. Prior to this, two films were encoded without errors, but the ant-man with the wasp caused an error.

**Comment by devil40xxx** [comment]
btw , would  you please give me some advice with these  :

when use
 
"d:\nvenc\NVEncC64.exe  -c hevc --output-depth 10 --vbrhq 4000 --max-bitrate 5000 --qp-init 21:26:31 --lookahead 32 --gop-len auto -b 0 --aq --mv-precision q-pel --chromaloc 2 --colormatrix bt2020nc --colorprim bt2020  --transfer smpte2084 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,50) --max-cll 992,282 --audio-copy --sub-copy --chapter-copy  -i "xxx.mkv" -o "yyy.mkv"

i got a encoded MKV file with same tracks but when opens in potplayer the video sucks (about ten second ,may be corrupt ) till get well.

if only use  -i "xxx.mkv" -o "yyy.hevc" , then will got all good video.
But you had to mux it again.

Am I wrong in the command strings above ?

**Comment by drSHLEFF** [comment]
I think you can't decode and encode mkv. First, need to demuxed the h265 (hevc) track from mkv, encode this h265 (hevc), and than mux a new mkv. In any case, I am doing just that))

**Comment by devil40xxx** [comment]
thx , i get your point.

I tesed a bit more and found the werid thing is the problem only occurs in  "--output-depth 10" ，in 8 bit mod it runs well.
And if it can't copy the tracks ，then why those commands exists @rigaya

**Comment by rigaya** [comment]
> Error "[NULL @ 0000025708e60140] missing picture in access unit"

It seems to be an error in [hevc parser of libavcodec](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/hevc_parser.c#L242).

> Error when encoding to mkv fromat with HEVC 10bit depth

mkv to mkv is supported, as you have tested in 8bit depth. I'm not able to find out what is wrong when muxing to mkv, as it is fine even with 10bit encoding when you mux to mp4 in the same code.

**Comment by hydra3333** [comment]
Eek, will you lodge a bug report over at https://trac.ffmpeg.org/ ?

**Comment by drSHLEFF** [comment]
Next time I see this error again...

**Comment by rigaya** [comment]
Might be fixed with NVEnc 6.01, improving handling of HEVC input.
