### ISSUE TITLE
New Movie lenght is shorter after recode

### ISSUE THREAD

**Issue by darkpuridee** [rigaya/NVEnc#87]
Ive always the same issues, and updates today to Version 20, but still the same.

as exampe, i recoded a video with a lenght of 2 hours 24min and 32 sec.

the recoded file is now 2 hours 19 mins 11 sec.

but i got this with every other vids

by batfile looks like

@echo off
echo Enter Bitrate
set /p bitrate=
for /f "tokens=1,2 delims=_" %%a in ("%~nx1") do (
set BEFORE_UNDERSCORE=%%a
set AFTER_UNDERSCORE=%%b
) 
"C:\Users\Syntax\Desktop\Ablage\NVEnc_4.16\NVEncC\x64\NVEncC64.exe" -i %1 --chapter-copy -c hevc --level 4.1 --profile main10 --cbr %bitrate% --audio-copy -o "D:\Conv\%BEFORE_UNDERSCORE%\%~nx1"

maybe i have some command strings for nvenCC wrong?

**Comment by rigaya** [comment]
Please check if framerate is estimated correct in NVEncC compared to the input file, if estimated wrong the movie length might differ. If so, please set the correct framerate by --fps.

If input file is VFR, please consider adding --avsync vfr, as NVEncC assumes input as CFR by default.
