### ISSUE TITLE
Key-on-chapter issue

### ISSUE THREAD

**Issue by fzold** [rigaya/NVEnc#92]
input and output file is mkv.

**--chapter-copy** --key-on-chapter 
should set IDR frame on chapter position copied from input file. Very important but does NOT WORK.
ffmpeg can do it with
-force_key_frames chapters -forced-idr 1

--chapter chapters.txt --key-on-chapter
sets IDR frames but does NOT MUX the chapter points.

The only version that properly works is
--chapter-copy --keyfile iframes.txt
But we have to generate the keyframes in a separate file (iframes.txt).

------
Dell XPS 15 9560 - Win 10 Pro 1709, i7-7700HQ,, GTX 1050, nvenc API 8.1 CUDA 10.0

**Comment by rigaya** [comment]
Thanks for reporting, now should be fixed with [NVEnc 4.27](https://github.com/rigaya/NVEnc/releases/tag/4.27).

**Comment by fzold** [comment]
Thanks, it works now.
Greetings from Germany.
