### ISSUE TITLE
strange --master-display output value

### ISSUE THREAD

**Issue by devil40xxx** [rigaya/NVEnc#93]
The source file Mastering display luminance is "min 0.0001cd/m2 ,max10000cd/m2 "

if use  "--master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(100000000,1)" to encode I get the result "min 0.0000cd/m2   max 10000/m2"in output file with mediainfo ;

if use "--master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(100000000,10)"

the result is "min 0.0010cd/m2 - max 10000/m2";

 i use the wrong method or there is  somthing mess in ""--master-display"?

**Comment by rigaya** [comment]
Thanks for reporting, should be fixed with [NVEnc 4.29](https://github.com/rigaya/NVEnc/releases/tag/4.29).

**Comment by devil40xxx** [comment]
Thanks for your reply rigaya ，and merry Xmas :)
--
