### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by darkpuridee** [rigaya/NVEnc#94]
Is it possible to have a Queue? i wanna start encoding my files and with not sit next to my pc and start any file for new

Sorry for my bad english

**Comment by Last-Order** [comment]
Are you mean something like monitoring a folder and encode files newly added?

I think a script or even crontab is more suitable for this situation.

**Comment by darkpuridee** [comment]
I mean that i can encode all files in a folder, or all selected.

Actually i have start every files encoding manually and have sit at the pc the whole time.

**Comment by rigaya** [comment]
Controlling jobs is not core feature for NVEncC, and I also think other method can be tested like scripts and others.
