### ISSUE TITLE
How to convert multiple files?

### ISSUE THREAD

**Issue by RapFan89** [rigaya/NVEnc#96]
Hi there,
i have a folder with 4k videos, i want to convert them to FHD, with audio and using my nvidia GPU ( GeForce GTX 1050 Ti with Max-Q Design) . The videos were recorded with the same camera and here are the specs:
` Input Info     avcuvid: H.264/AVC, 3840x2160, 30000/1001 fps`

i've tried something similar to `NVEncC64.exe -i "C:\FOLDER\*.MP4" --output-res 1920x1080 --audio-copy  -o "C:\FOLDER\FHD\video-fhd.mp4"` But had no luck, Can someone help me?

**Comment by rigaya** [comment]
You may save below as "convert.bat" and modify TARGET_DIR and NVENCC_PATH. By running the bat file, all *.mp4 files will be converted.

```bat
set TARGET_DIR=F:\temp
set NVENCC_PATH=NVEncC64.exe
for /f "usebackq tokens=*" %%I in (`dir /s /b "%TARGET_DIR%\*.mp4"`) do "%NVENCC_PATH%" --output-res 1920x1080 --audio-copy -i "%%~I" -o "%%~dpnI.converted.mp4"
```

**Comment by rigaya** [comment]
I'll close this issue as it has be resolved. Please reopen if you have any more related issues.
