### ISSUE TITLE
Is it possible to make a VFW/Directshow filter/encoder for Rigaya NVENC?

### ISSUE THREAD

**Issue by Truth1234** [rigaya/NVEnc#98]
Hello Rigaya!

Is it technically possible to make a VFW/Directshow filter/encoder for Rigaya NVENC?

As you know, many third party free video recorder apps and video transcoder apps still use this classic VFW/Directshow system.
Therefore it would be a good and useful idea to implement Rigaya NVENC in the vfw/Directshow platform.

Thank you for your reply!

**Comment by NoLimits2018** [comment]
Any idea?

**Comment by NoLimits2018** [comment]
> 
> 
> It'll be completely different interface from current encoder/transcoder, I'm not focusing on it now.

Hi!
Yes, it is different interface, but the the effect of such encoder would be enormous among the users.

**Comment by rigaya** [comment]
I'm sorry, but I have no plan for this now.
