### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by kostiam** [rigaya/NVEnc#99]
Trying to build NVEnc, but not successful.
Everything from Build.en is made, errors comes from NVEnc/NVEncCore/rgy_caption.h line 68 - "cannot open source Caption.h" and etc...
      
Where should i get the file?

**Comment by rigaya** [comment]
Please clone [Caption2Ass_PCR](https://github.com/maki-rxrz/Caption2Ass_PCR), and set environment variable "CAPTION2ASS_SRC" to "{cloned path}\src".

**Comment by kostiam** [comment]
Thanks.
I did it!
Will try to experiment with lookahead option, wanna try 60 and SSIM changes..

**Comment by kostiam** [comment]
It is only possible to enc with lookahead 55 option (1070Ti) with 720p60 video (HEVC). There is no minimum significant difference on SSIM between coded video with lookahead32 and lookahead55 options on 16Mbps(sometimes SSIM may change to 0,001..0.01%), but significant if to compare with lookahead8 (up to 1% in my case)
So, why lookahead 128 is not possible?

PS, Thank you for YOUR VERY PROJECT!!!
